### ISSUE TITLE
Crash during Google authorization on macOS

### ISSUE THREAD

**Issue by aozaki-kuro** [floccusaddon/floccus#1001]
### Describe the bug
The browser crashed immediately when trying to authorize Google Account on macOS with Edge.

### To Reproduce
1. Go to 'New Account' - 'Google Sync'
2. Click on 'LOGIN WITH GOOGLE'
3. The browser crashed

### Expected behavior
Complete the authorization in a new tab / window.

### Screenshots
N/A

### Desktop
(please complete the following information)
Macbook Air 2020 (M1)
 - OS: macOS Monterey 12.0.1
 - Browser: Microsoft Edge
 - Browser Version: 96.0.1054.34 (arm64)
 - Floccus version: 4.8.3
 - Floccus sync method: Google Drive

### Server
N/A

### Debug log

- [ ] Debug log provided

The browser crashed without provided an error or log.

### Additional context
N/A

**Comment by marcelklehr** [comment]
See #919
