### ISSUE TITLE
Sync the extension settings

### ISSUE THREAD

**Issue by stokito** [floccusaddon/floccus#1003]
I have PC and laptop and Firefox completely syncing it's settings but I have to configure the WebDAV on both of them.
I looks like the Floccus must sync it's own settings with Firefox Profile
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

**Comment by marcelklehr** [comment]
This is intentional as floccus accounts are configured per browser, not per Firefox account. For easier transfer of accounts from one machine to another, you can export and import your settings as a JSON file.
