### ISSUE TITLE
Open password protected credential with biometrics

### ISSUE THREAD

**Issue by BirdInFire** [floccusaddon/floccus#1004]
### Is your feature request related to a problem? Please describe.
It's pretty anoying to open up the secured credential with password.

### Describe the solution you'd like
Use the Windows hello / Touch ID / Yubikey / other passwordless, to open the locked floccus.

### Describe alternatives you've considered
Generate a tray app (or work with lofloccus who generate a local webdav)), to actually securise credential within the browser without requiring to enter password each time.

**Comment by marcelklehr** [comment]
Thank you for this feature request. It is my belief that it should be fairly rare for a user to require a password to secure the credentials stored in floccus, as the threat model in this case would include the attacker having being on / having full access to your machine. If this is your threat model, I understand that typing the passphrase every time you open the browser is tiresome. While passwordless auth would be cool, the flavor floccus would need is currently not supported widely enough in the browser landscape. Additionally, the ration between *development time* and *users benefited* for this feature would be too large for my taste at the moment.
