### ISSUE TITLE
Trigger a warning in localhost webdav

### ISSUE THREAD

**Issue by BirdInFire** [floccusaddon/floccus#1005]
### Is your feature request related to a problem? Please describe.
Actually when i use a localhost webdav to sync my bookmark in my folder of my sync provider all go without warning and this is risky for security because if one of my synced browser is breached by a malware, he can modify my bookmark to try to steal more information (phishing).

### Describe the solution you'd like
When Floccus detect "http://127.0.0.1 or http://localhost" trigger a warning and recommend to set an Encryption password (to mitigate the risk of interception / malware modification).

### Additional context
I ask this since the solution (xbel encryption) already exist in the extension it's just recommend to set it to those who use lofloccus or any other local unsecured webdav server.

**Comment by marcelklehr** [comment]
Are you concerned about the HTTP (no encryption) or about the localhost? Http with TLS on localhost shouldn't be too much of a problem, I think, as the attacker would need to be on the machine already to intercept that traffic -- by that time they can usually already manipulate your browser bookmarks. HTTP in general however, is a security problem indeed, I agree.

**Comment by BirdInFire** [comment]
> Are you concerned about the HTTP (no encryption) or about the localhost? Http with TLS on localhost shouldn't be too much of a problem, I think, as the attacker would need to be on the machine already to intercept that traffic -- by that time they can usually already manipulate your browser bookmarks. HTTP in general however, is a security problem indeed, I agree.

No actually i propose to recomment to a user who use a http for localhost or webdav, to use the built in encryption password to protect their bookmark even if the connection hitself isn't secure.

**Comment by marcelklehr** [comment]
I think if the browser is breached, the user has greater worries than their bookmarks being messed with. I will add a warning for http-only connections, though.

**Comment by BirdInFire** [comment]
> I think if the browser is breached, the user has greater worries than their bookmarks being messed with. I will add a warning for http-only connections, though.

true but many user who does not understand how it work will blindly follow tuto, and in the worst case will use an http connection with a nas, and if even worse they open it to internet it's a call to have everything intercepted.
The warning is more to tell them that even if it's work it's not secure, so if they want to use it outside they will search how to secure it.
