### ISSUE TITLE
Initial sync via webdav works, subsequent syncs fail

### ISSUE THREAD

**Issue by OnkelTom-76** [floccusaddon/floccus#1012]
### Describe the bug
I am trying to sync to my WEB.DE smartdrive. Generally available under 'https://webdav.smartdrive.web.de'
Credentials and path are okay.

Problem: With the initial sync, the bookmark file gets created. I can see and access it via e.g. a file-manager or the online surface of the provider WEB.DE. But subsequent syncs fail with E017 error. So the file on the webdav share does not get updated. In the trash bin, I can find a renamed ".lock" file, but the bookmark file itself does not get updated.

### Expected behavior
Would expect subsequent syncs (updates) to work as the initial sync (creation of bookmark file)

### Desktop
Floccus version: 4.8.6
Chrome browser: Version 96.0.4664.110 (Offizieller Build) (64-Bit)
Windows version: 10 Pro 19043.1415

### Server
WEB.DE specific - don't know details

### Additional context
The same floccus version 4.8.6 under Linux Mint 20.2 on a 64 bit machine produces the same behaviour.
Whereas version 4.7.0 of floccus works flawlessly.

Hope, the bot does not close this one as well...

Any help / support would be appreciated. Thank you.

**Comment by marcelklehr** [comment]
> Whereas version 4.7.0 of floccus works flawlessly.

huh. that's curious.

**Comment by OnkelTom-76** [comment]
> > Whereas version 4.7.0 of floccus works flawlessly.
> 
> huh. that's curious.

I did not manage to get it to work after 4.7.0. Neither under Windows 10 (latest Chrome version) nor under Linux Mint 20.3 (latest Chromium). Although even backing up account and re-use this backup, so I cannot mis-type anything. It works until 4.7.0 . But all newer versions end with E017, as far as I remember.

**Comment by marcelklehr** [comment]
Between v4.7 & v4.8 I changed some HTTP-request related stuff all around the code base in order to add Android support. I'll recheck those changes.

**Comment by marcelklehr** [comment]
It could be that you're not getting the correct error message. I've identified some problematic code, could you try enabling redirects in your floccus account settings to verify this?

**Comment by OnkelTom-76** [comment]
> It could be that you're not getting the correct error message. I've identified some problematic code, could you try enabling redirects in your floccus account settings to verify this?

"redirects"? I cannot follow. Where is this setting. Maybe the German phrase? Wo finde ich das?

**Comment by OnkelTom-76** [comment]
> It could be that you're not getting the correct error message. I've identified some problematic code, could you try enabling redirects in your floccus account settings to verify this?

I just played around with 4.7.0, 4.8.7 and 4.9.0. 4.7.0 is great. Everything fine. With 4.8.7 and 4.9.0 it sometimes workes with the 4th or 5th press of the button "jetzt synchronisieren". Even waiting 10, 15, 20, 30 seconds does no change. It sometimes works, sometimes not...

**Comment by marcelklehr** [comment]
> "redirects"? I cannot follow. Where is this setting.

Open Floccus panel -> Expand your account -> click on options -> scroll down to "Dangerous actions" -> Check "Allow redirects in Server URL" (it's likely not translated yet)

**Comment by OnkelTom-76** [comment]
> > "redirects"? I cannot follow. Where is this setting.
> 
> Open Floccus panel -> Expand your account -> click on options -> scroll down to "Dangerous actions" -> Check "Allow redirects in Server URL" (it's likely not translated yet)

Found it. It was not in 4.7.0, right. In 4.9.0, now enabled it. Same as before. Works 1 time, sometimes twice. Then error E017, again. Third or fourth try now work. Same as before enabling redirects.

**Comment by marcelklehr** [comment]
Would you be amenable to try out a build with my latest changes to test if they fix your issues?

**Comment by OnkelTom-76** [comment]
> Would you be amenable to try out a build with my latest changes to test if they fix your issues?

I will back up my sync file and will be happy to assist ;)

**Comment by marcelklehr** [comment]
Here you go: https://cloud.marcelklehr.de/s/fBzKz4s2TrAS396

You should be able to install the crx by dragging it onto `chrome://extensions` (not sure if that only works on linux, though).
Otherwise,

1. Unzip the zip file
2. Go to  `chrome://extensions`
3. Enable "Developer mode" (top left, I believe)
4. Load the extension by pointing Chrome to the unzipped directory

**Comment by OnkelTom-76** [comment]
I took the ZIP file and unpacked the 4.10-alpha.1. Added to Chrome, imported backup of account and started.
It is stuck at "synchronization in progress".

**Comment by OnkelTom-76** [comment]
Will be `away from my desk` for some time, now...

**Comment by marcelklehr** [comment]
Ah, I seem to have forgotten a change. :/
I've updated the builds at the above URL. Also, make sure to remove the .lock file associated with your bookmarks file in your WebDAV share.

**Comment by marcelklehr** [comment]
@OnkelTom-76 Can you try again with the new builds at the above URL?

**Comment by OnkelTom-76** [comment]
> @OnkelTom-76 Can you try again with the new builds at the above URL?

Added a new bookmarked and synced. Worked without any error message. The XBEL file contains the new bookmark. So, it seems to be working. VERY, VERY good!!! Thank you! Will have an eye on it and give feedback the next days, maybe on the weekend! Have a nice evening and again THANK YOU!

**Comment by OnkelTom-76** [comment]
Now done 9...10 syncs, adding and deleting some bookmarks. Everything fine. Good work! Appreciate your support!

**Comment by marcelklehr** [comment]
Cool! :tada: I'm glad it works again :)

> Good work! Appreciate your support!

You were also a very cooperative bug reporter, so thank you, too :)
