### ISSUE TITLE
Firefox Addon Causing PHP Errors On Nextcloud

### ISSUE THREAD

**Issue by Prog1563** [floccusaddon/floccus#1013]
### Describe the bug

I am going to start with this: I am uncertain if this is a Nextcloud issue or if this is a Floccus issue. I have only seen the behavior with Floccus hence the post here, if it needs to go to Nextcloud instead, please let me know :)

When syncing with Nextcloud, the plugin causes an error to be thrown.
`[PHP] Error: session_regenerate_id(): Session ID cannot be regenerated when there is no active session at /var/www/nextcloud/lib/private/Session/Internal.php#136`

### To Reproduce
1. Set up Flocccus with an app password from Nextcloud
2. Trigger a sync or wait for an automatic sync.

### Expected behavior
No error thrown.

### Desktop
(please complete the following information)
 - OS: Linux Mint 20.2
 - Browser: Firefox
 - Browser Version: 95.0.1
 - Floccus version: 4.8.7
 - Floccus sync method: Nextcloud

### Server
(please complete the following information)
 - OS: Debian 11
 - Nextcloud version: 23.0.0
 - Bookmarks app version: 10.0.3

### Debug log
I cannot find any button that says "debug log" in the plugin.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
> if it needs to go to Nextcloud instead, please let me know

Confirmed it's most likely a problem with the Bookmarks app

**Comment by Prog1563** [comment]
Alright, thanks!
I'll open an issue their way.
