### ISSUE TITLE
Latest release on Google Play store still pending review

### ISSUE THREAD

**Issue by ashutoshsaboo** [floccusaddon/floccus#1020]
Saw the recent release - v4.9 here - https://github.com/floccusaddon/floccus/releases/tag/v4.9.0, was excited to try google auth in the app but unfortunately latest release in Play store seems to be 4.8.7 (which was the previous release before v4.9 on github). Has it intentionally not been released to play store yet or maybe if  I haven't received it yet due to some phased rollout by Play Store? @marcelklehr

**Comment by ashutoshsaboo** [comment]
@marcelklehr could you please check this^?

**Comment by marcelklehr** [comment]
Google play is still reviewing the new release, which is taking longer than expected. I don't know when they will give the go, but I expect it within the next week.

**Comment by ashutoshsaboo** [comment]
@marcelklehr still no update on play store looks like. Did they reject it or something, if you received any update from them?

**Comment by marcelklehr** [comment]
@ashutoshsaboo Yep, they're taking their time :/ I also check their dashboard everyday, but no news other than "In review".

If you don't want to wait for Google, you can install [the latest release from the IzzyOnDroid F-Droid repo](https://apt.izzysoft.de/fdroid/index/apk/org.handmadeideas.floccus). Inclusion in f-droid will be done soon, too.

**Comment by ashutoshsaboo** [comment]
I see, is it possible if you could try emailing Google Play store's support to check with them on the app's status and if they can review it (atleast if they wanna reject, they should inform but from your message it looks like they haven't even reviewed it yet) @marcelklehr ? 8-9 days of wait from Google in reviewing an app for go-ahead sounds too long tbh.

**Comment by marcelklehr** [comment]
It's published now :)

**Comment by ashutoshsaboo** [comment]
Superb, works like a charm. Thank you! :)
