### ISSUE TITLE
Do not allow placeholder bob@example.com to actually become an active account

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1023]
### Is your feature request related to a problem? Please describe.
bob@example.com becomes a real Floccus account for the user, sometimes in multiple instances for the new extension installations

### Describe the solution you'd like
Do not actually allow the example instance to become active.  If it must be automatically created, do not allow it to actually activate.  Thank you for considering.

**Comment by marcelklehr** [comment]
Hi @sunjam  :wave: 

How does this happen? I only get a real bob@example account when setting out to create a new account without changing the defaults.

**Comment by sunjam** [comment]
Start adding a new account without completing the task and bob autofills into your client device.  This happens to me basically every time I need to reinstall floccus.

**Comment by PSeQXh** [comment]
> Start adding a new account without completing the task and bob autofills into your client device

Same here, started but didn't complete the task, on Chromium on alpine 3.15 with Floccus extension v4.13.0. It could be that one needs to actively click on the 'floccus button in the extension bar' again to trigger some syncing. At least for me, when I clicked on that button, Floccus created an (reasonable) error log:
> 2022-04-16T02:07:28.115Z Starting sync process for account bob@example.org
> 2022-04-16T02:07:28.381Z Syncing failed with E019: HTTP status 404. Failed POST request. Check your server configuration and log.

**Comment by marcelklehr** [comment]
Revamped the account setup process which fixes this issue.
