### ISSUE TITLE
Use Firefox Sync for non-bookmark related data in parallel

### ISSUE THREAD

**Issue by simonh1005** [floccusaddon/floccus#1028]
Hi all,
I am aware that according to the [FAQ](https://floccus.org/faq#i-am-currently-using-a-different-tool-to-sync-my-browser-data-can-i-use-this-with-floccus), using another tool to sync bookmarks in parallel with floccus is discouraged. At the same time, Firefox Sync (the native solution of Firefox) allows to [choose, what kind of data to sync](https://support.mozilla.org/en-US/kb/how-do-i-choose-what-information-sync-firefox).
Now, I'm asking myself, if it would be a problem to enable FF sync as long as I exclude the bookmarks from beeing sync. Like this, it would be possible to p.e. use floccus for cross-browser bookmark syncing and at the same time sync the browser history and addresses between mobile and desktop FF.
Did anyone test this already? How big is the risk of causing some data inconsistencies when trying?

**Comment by simonh1005** [comment]
Hi @marcelklehr,
is there any documentation about how to open an issue that is correctly following the template? I would love to follow any template, if it helps you organizing your backlog, but I could not find any hints/docs

**Comment by marcelklehr** [comment]
I've had this question a few times so far, but nobody came back with the answer after trying it out. So, my advice is: Make a backup and try it yourself -- and ideally come back here to report your experience :)

**Comment by simonh1005** [comment]
Thanks for the very fast answer!
Is floccus actually having a backup-functionality, or are you referring to a Firefox export of the bookmarks?

**Comment by simonh1005** [comment]
OK, just did a backup using firefox and also by copying the floccus bookmarks-file and activated FF-sync for 
- History
- Settings
- Addons
At least until now, after doing a triggering a manual sync in both tools, it seems, that they indeed do not influence each other. So for now, I would answer my own question with "**yes, it seems to be working**". In case that I observe some side-effects in the next days, I would re-open and update this issue.

**Comment by marcelklehr** [comment]
Cool! Side effects would most likely be duplicates, fyi
