### ISSUE TITLE
[feature request] Support buku `bookmarks.db`

### ISSUE THREAD

**Issue by GreenLunar** [floccusaddon/floccus#1033]
We want to sync with buku `bookmarks.db`.

### Is your feature request related to a problem? Please describe.
It would be nice to add support to export results to a buku `bookmarks.db` database file.

### Describe the solution you'd like
Export to `bookmarks.db` database file which buku users can import from.
`$ buku --import storage/shared/bookmarks.db`

### Describe alternatives you've considered
Make buku to support XBEL https://github.com/jarun/buku/issues/569

### Additional context
Ping @tomoakley

**Comment by marcelklehr** [comment]
Can buku import HTML files?

**Comment by GreenLunar** [comment]
Yes

**Comment by marcelklehr** [comment]
Then it might be easier to replace this issue with #616

**Comment by GreenLunar** [comment]
I think adding XBEL support (import/export) to buku is the best solution.

Closing.
