### ISSUE TITLE
[feature request] Connect using SSH to a custom path

### ISSUE THREAD

**Issue by GreenLunar** [floccusaddon/floccus#1034]
### Is your feature request related to a problem? Please describe.
Ability to connect using SSH.

### Describe the solution you'd like
SSH option with a user-defined path.

### Describe alternatives you've considered
SSH or [SSHFS](https://github.com/libfuse/sshfs) or [SSHFS-WIN](https://github.com/billziss-gh/sshfs-win)  and Rsync

**Comment by marcelklehr** [comment]
This would be nice indeed. Sadly, webextensions only have access to HTTP.
