### ISSUE TITLE
Sync error after updating to 4.10.0 (Android)

### ISSUE THREAD

**Issue by gitmaker032** [floccusaddon/floccus#1036]
### Describe the bug
After upgrading app to version 4.10.0 an error to connect to the server (XBEL/WebDAV) began to appear. If you roll back to version 4.9.0, functionality is restored and the error disappears. The error affects only Android, in the browser extension everything works fine. The connection settings are the same in all cases. Tried both updating and completely reinstalling the app.

### Expected behavior
There are no sync errors. 

### Screenshots
![image](https://user-images.githubusercontent.com/67278783/153053259-1630db5c-c659-4af6-9089-6dee9bdbc614.png)

### Android 
- Version: 11 (MIUI 12.5.7)
- Floccus version: 4.10.0
- Floccus sync method: XBEL/WebDAV

### Server
 - OS: Ubuntu 20.04.3
 - Nginx version: 1.18.0
 - https (Let's Encrypt)

### Debug log
2022-02-08T17:59:40.705Z Starting sync process for account user@mysite.com
2022-02-08T17:59:40.728Z onSyncStart: begin
2022-02-08T17:59:40.729Z https://mysite.com/dav/bookmarks.xbel.lock
2022-02-08T17:59:40.807Z Error Caught
2022-02-08T17:59:40.808Z [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
2022-02-08T17:59:40.814Z Syncing failed with E017: Network error: Check your network connection and your account details
2022-02-08T17:59:40.829Z onSyncFail
2022-02-08T17:59:40.902Z Error Caught
2022-02-08T17:59:40.902Z [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]

**Comment by marcelklehr** [comment]
> [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]

@gitmaker032 Can you check if this line contains useful information when not anonymizing the debug log?

**Comment by gitmaker032** [comment]
> > [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
> 
> @gitmaker032 Can you check if this line contains useful information when not anonymizing the debug log?

This is another bug (I can create a new issue if necessary) in version 4.10.0. The checkbox "Anonymize private data" does not save the state. After clicking on the "Save" button (settings), the checkbox returns to the active position. Consequently, it is not possible to get the extended log.

**Comment by marcelklehr** [comment]
> This is another bug (I can create a new issue if necessary) in version 4.10.0. The checkbox "Anonymize private data" does not save the state. After clicking on the "Save" button (settings), the checkbox returns to the active position. Consequently, it is not possible to get the extended log.

Yes, please. I cannot seem to reproduce this off-hand.

**Comment by marcelklehr** [comment]
Confirmed and fix is in the works.

**Comment by gitmaker032** [comment]
Problem solved in version 4.10.1 . Thanks for the quick fix.
