### ISSUE TITLE
The "Anonymize private data" checkbox does not save the state and is always active (Android, 4.10.0)

### ISSUE THREAD

**Issue by gitmaker032** [floccusaddon/floccus#1037]
### Describe the bug
The checkbox "Anonymize private data" is active by default and if you try to uncheck and save the settings, the checkbox remains active. Completely reinstalling the app does not solve the problem.

### To Reproduce
1. Go to Settings in an existing or new account.
2. Go to the "Download debug Logs" section, uncheck the box and save the settings.
3. Go back to the settings and recheck the state of the checkbox.

### Expected behavior
The checkbox keeps the inactive state.

### Screenshots (GIFs)
[View the GIF](https://i.imgur.com/JTrLfhB.gif)

### Android
- Version: 11 (MIUI 12.5.7)
- Floccus version: 4.10.0

**Comment by marcelklehr** [comment]
From what I can see in the GIF, this seems to be the intended behavior: Always default to anonymized logs. The question for me is, does it still anonymize the logs when disabling the checkbox and tapping on the download button?

**Comment by gitmaker032** [comment]
> From what I can see in the GIF, this seems to be the intended behavior: Always default to anonymized logs. The question for me is, does it still anonymize the logs when disabling the checkbox and tapping on the download button?

I thought that in order for the logging settings to apply, they need to be saved first :) Which is consistent with the logic of the other fields in the settings section. Yes, the logs look a bit different if you download them immediately after unchecking the box. However, in my [case](https://github.com/floccusaddon/floccus/issues/1036), no additional information on the error was added, which confused me.

**Comment by marcelklehr** [comment]
Mh, I see. Maybe two buttons or a dropdown button would be better then, what do you think?

**Comment by marcelklehr** [comment]
![image](https://user-images.githubusercontent.com/986878/153186745-19d8789c-0780-4287-8465-fe5ec345e563.png)
