### ISSUE TITLE
Autofill "Title" field when adding a bookmark based on the page title (Android)

### ISSUE THREAD

**Issue by gitmaker032** [floccusaddon/floccus#1039]
### Is your feature request related to a problem? Please describe.
User has to enter bookmark title manually in android app. Title field is empty by default and is not filled automatically. This is inconvenient and inconsistent with the logic of adding a bookmark in browsers where the title is auto-filled.

![image](https://user-images.githubusercontent.com/67278783/153210351-290a823d-849c-4509-b0d3-3b112d0be47b.png)

### Describe the solution you'd like
Implement autofill for "Title" field based on the page title:

- If valid url is passed through android share feature — try to autofill immediately after opening the app.
- If the bookmark is added manually in the app — try to autofill after entering valid url.
- If url of bookmark was changed when adding — try to autofill the title field again. 
- While trying to get page title, the title field is unavailable for editing.
- If editing a previously saved bookmark — autofill for the title field is disabled.

### Describe alternatives you've considered
Not required. 

### Additional context
Not required.

**Comment by marcelklehr** [comment]
Fixed in v4.10.x
