### ISSUE TITLE
Android: Dark theme doesn't work on all devices

### ISSUE THREAD

**Issue by Elbullazul** [floccusaddon/floccus#1041]
### Is your feature request related to a problem? Please describe.
The app always uses a light theme, even when the dark mode toggle is on, with no possibility to manually set a dark theme

### Describe the solution you'd like
The app should have a dark theme, so it doesn't look out of place on a system with dark mode on

### Describe alternatives you've considered
I tried using the dev tools' "Override dark mode" setting, but the app keeps using the white theme

### Additional context
Device info:
Pixel 6 Pro with Android 12
App Version is 4.10.1 (2022-02-09)
Downloaded from IzzyOnDroid

**Comment by marcelklehr** [comment]
ref https://github.com/ionic-team/capacitor/issues/4677

**Comment by Elbullazul** [comment]
I'm on a Pixel 6 Pro, App Version 4.10.1 (2022-02-09)

**Comment by shom13** [comment]
I can confirm, dark mode doesnt work with android app

**Comment by butaminas** [comment]
For me, it is always dark mode even though it is set to light mode. Only not working on android.
Tested on Redmi Note 8 Pro / MIUI 12.5.6 / Android 11.

P.S. This was already noted in another related issue - a temporary fix is to use [this](https://github.com/robingenz/capacitor-android-dark-mode-support).

**Comment by Elbullazul** [comment]
Version 4.11 seems to have fixed this for me

**Comment by shom13** [comment]
Yes, after an update its always on dark mode.

**Comment by marcelklehr** [comment]
Great! Thanks for the feedback :)
