### ISSUE TITLE
bookmark syncs move all separators towards the end of the folder

### ISSUE THREAD

**Issue by gf-mse** [floccusaddon/floccus#1042]
Hi, Floccus is almost certainly the best non-cloud software for bookmark synchronization, but until recently it just ignore separators and that was fine. But after a recent updates it takes them away from every folder and puts them at the end, like this:

http://wikisend.com/download/360804/bookmark-separators.png

I wonder if it is possible to return to the previous behavior where the separators were essentially ignored during a sync.

Kind regards,

**Comment by mnalis** [comment]
(Duplicate of #1043)
