### ISSUE TITLE
bookmark syncs move all separators towards the end of the folder

### ISSUE THREAD

**Issue by gf-mse** [floccusaddon/floccus#1043]
### Describe the bug
Hi, Floccus is almost certainly the best non-cloud software for bookmark synchronization, but until recently it just ignore separators and that was fine. But after a recent updates it takes them away from every folder and puts them at the end, like this:

http://wikisend.com/download/360804/bookmark-separators.png

I wonder if it is possible to return to the previous behavior where the separators were essentially ignored during a sync.

### To Reproduce
1. create a bookmark folder, put it under floccus sync
2. add a bookmark there
3. add a separator
4. repeat steps 2-3 N times, N > 1
5. wait for a sync
6. Observe that floccus moved all the separators to the end of the folder, as is shown on the screenshot.

### Expected behavior
Floccus does not change the order of the separators of the sync source

### Screenshots

http://wikisend.com/download/360804/bookmark-separators.png

### Desktop
(please complete the following information)

 - OS: Ubuntu 18.04
 - Browser: FF 90.0.2 (64-bit)
 - Floccus version: [e.g. 4.10.0]
 - Floccus sync method: webdav

### Server
(please complete the following information)
 - OS: see above
 - Nextcloud version: -
 - Bookmarks app version: ?

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

 - can not find one. bottom right corner says "secure your credentials".

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

**Comment by unalignedcoder** [comment]
Same problem here. 

![image](https://user-images.githubusercontent.com/16850566/158333995-7d6109c6-4570-4b48-b6aa-119ca5253ecc.png)

(Also, floccus is duplicating folders and their content over and over. Had to stop the thing.)

**Comment by marcelklehr** [comment]
Fixed.

> Also, floccus is duplicating folders and their content over and over. 

Please open a new issue <3
