### ISSUE TITLE
Map o description of encryption process for a webclient..

### ISSUE THREAD

**Issue by gesu92** [floccusaddon/floccus#1050]
### Is your feature request related to a problem? Please describe.
Just a question for knowledgement, I love this plugin (and now app for android), I just want to play with the file in webdav servers, with the only purpose of get more compatibility in desktop browsers, I need info about the encryption process of the xbel file, I just want to do something like a online xbel reader with the support of Floccus encryption, this will help to have something like a bookmark of the webapp in any desktop browser that have all the bookmarks of the floccus sync app, in minor terms it's like a webclient for Floccus, or just a xbel file editor with the Floccus encryption support.

### Describe the solution you'd like
Just a map o description of the encryption process or where have that information.

### Describe alternatives you've considered
I don't known if there are another xbel file editor, but it's necessary the encryption support for work with Floccus.

### Additional context
Nothing more, just thanks for this program, really useful, thanks so much.
PD=sorry bad english..

**Comment by marcelklehr** [comment]
Hey,

this is the entire crypto implementation: https://github.com/floccusaddon/floccus/blob/develop/src/lib/Crypto.ts

**Comment by gesu92** [comment]
when have something, I will put here, thanks again
