### ISSUE TITLE
E020: Could not parse server response.

### ISSUE THREAD

**Issue by 0cwa** [floccusaddon/floccus#1052]
### Describe the bug
Receive Error: `E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data `

It might be a result of charset issues, I have a lot of bookmarks, but I already ran the emoji troubleshooting.
The strange characters I have besides emojis (which are displaying fine in my nextcloud folder) are: · ® and •

I'm pretty sure this is linked to #992 ?

It seems like the bookmarks still upload?  But I'm not sure b/c I'm also using the Android app and they may have uploaded from there...

### To Reproduce
Sync ( 1000 bookmarks, maybe some odd characters exist )

### Expected behavior
No error

### Desktop
 - OS: Linux 
 - Browser Firefox
 - Browser Version 97.0
 - Floccus version: 4.10.1
 - Floccus sync method: Nextcloud Folder

### Server
 - OS: Debian 11 Yunohost
 - Nextcloud version: 23.0.0
 - Bookmarks app version: 10.0.3

### Debug log
Uploaded to: https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw
Name: floccus-4.10.1-2022-02-26.log
- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Thanks! I'll fix this.

**Comment by marcelklehr** [comment]
Should be fixed in the latest version of the bookmarks app (v10.1.0)
