### ISSUE TITLE
Incorporate htmlToXBel

### ISSUE THREAD

**Issue by GreenLunar** [floccusaddon/floccus#1055]
### Is your feature request related to a problem? Please describe.
Some web browsers still use HTML filetype to manage bookmarks.  See #616

### Describe the solution you'd like
Add a tool to convert HTML to XBEL.

Why?
1. An addon may be a solution, but only for temporary time since we are subjected to the whims of others.  See [example from the past](https://web.archive.org/web/20170425220517/https://www.andyhalford.com/).
1.1. Andy Halford's addons were using the XBEL format too and were helpful to [migrate to XBEL supportied web browsers](https://ubuntuforums.org/archive/index.php/t-1230791.html).
2. An addon must be browser specific, which would require more work.

### Describe alternatives you've considered
Package [htmlToXBel](https://github.com/Arora/arora/tree/a2d19752759bfb183d983ee3a9d726a4b09375a9/tools/htmlToXBel) of Aurora project as an optional utility software for floccus.  Mentioned at https://github.com/floccusaddon/floccus/issues/616#issuecomment-1053198133 and #1054

**Comment by marcelklehr** [comment]
Floccus can technically already convert between XBEL and HTML. Why do you need conversion to XBEL?

**Comment by GreenLunar** [comment]
To facilitate portability with other bookmarking software

**Comment by marcelklehr** [comment]
I guess this is no longer necessary with https://github.com/floccusaddon/floccus/pull/1180 being merged
