### ISSUE TITLE
Google Drive sync reporting successful but not creating bookmarks.xbel file when sync folder is empty

### ISSUE THREAD

**Issue by Cakehole** [floccusaddon/floccus#1056]
### Describe the bug
Floccus not creating bookmarks.xbel file when initially configured and sync'd but reporting successful sync activity

### To Reproduce
1. Downloaded Floccus from Chrome Webstore and installed per directions on Floccus website
2. Successfully connect Google Drive, restrict sync to Bookmarks Bar folder and set encryption password
3. Run initial sync and Floccus reports success
4. Check Google Drive and bookmarks.xbel NOT created

### Expected behavior
At initial sync, bookmarks.xbel file should be created and stored in Google Drive root folder

### Screenshots
- None

### Desktop
 - OS: [macOS Monterey 12.3]
 - Browser [Chrome]
 - Browser Version [98.0.4758.109]
 - Floccus version: [4.10.1]
 - Floccus sync method: [Push, also tried Normal]

### Server
 - Google Drive Business Basic account

### Debug log
- [floccus-4.10.1-2022-02-28.log](https://github.com/floccusaddon/floccus/files/8149884/floccus-4.10.1-2022-02-28.log)

### Additional context
- Have also tried with macOS v11 and Windows 11 both with latest applicable version of Chrome and Edge - None working

**Comment by marcelklehr** [comment]
The folder you selected to be synced is empty. In this case, floccus doesn't do anything. Add a bookmark to your bookmarks bar and you'll see the file being created.
