### ISSUE TITLE
stop showing the passphrase in clear plain text

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1060]
### Describe the feature you'd like to request

Everytime I check my extension settings or the Android app, my cherish and very secret passphrase appears to me in plain, not encrypted, text.

Its always a choc when I see it like this non hidden.

### Describe the solution you'd like

You should force *asterisque* caracter, like this nobody is able to read it over my shoulder.

### Describe alternatives you've considered

You could also decide to completely hide it.
I mean we have to choose it to encrypt the backup but we don't need to see it everyday.
So when we set up the backup we could write this passphrase and then it doesnt appear anymore.

If we lose it, we lose it

**Comment by marcelklehr** [comment]
This appears to be a bug. Passwords should be hidden by default, but there should be a button allowing to view the password. Can you open a bug report instead?
