### ISSUE TITLE
Firefox Tab syncing syncs to every open window.

### ISSUE THREAD

**Issue by InAUGral** [floccusaddon/floccus#1061]
### Which version of floccus are you using?

4.10.1

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using?

Firefox 97 on Pop OS (Ubuntu based)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.1.0

### Which version of Nextcloud? (if relevant)

22.2.3

### Describe the Bug

With Tab syncing enabled it keeps syncing all tabs to every Firefox window that is open e.g. I have 3 Windows open and it keeps syncing all tabs from my main Firefox window to the other two windowed instances. It seems unintended but may be an intentional feature?

### Expected Behavior

Presumably to sync all tabs to the main Firefox window instead of every single window, if this is not possible I suggest the option to allow this option be selected in the settings.

### To Reproduce

Setting up via Nextcloud bookmarks plugin and logging in. Allowing sync to take place using Tab syncing setting. Syn strategy merge local and remote.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
This should be fixed in the latest version. Can you confirm?

**Comment by InAUGral** [comment]
Sorry for the delay in testing but it would seem this issue is fixed now.
