### ISSUE TITLE
Passphrase appearing in plain text

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1062]
### Which version of floccus are you using?

4.10.1

### Sync method

{"label"=>"Google Drive"}

### Which browser are you using?

FF 97.0.2, Chrome 99.0.4844.51, Mobile Floccus app

### Describe the Bug

When I go in Floccus settings (either in the chrome extension, the firefox extension or the mobile app), my passphrase appears in plain unencrypted text.

### Expected Behavior

You said in another topic that it wasnt Normal and that it was suppose to appear first in ********** and only if we click in the "Eye icon" change to plain text.

Thats the contrary happening for me, in every Floccus version, in desktop browser or in mobile app, the pasphrase always appears first in plain texte and only if I click the "Eye icon" change to *******

### To Reproduce

To reproduce you just have to go to Floccus settings, where the passphrase is store.

I'd be surprised if I am the only one experiencing that, since its happening in every platform and from the start I am using Floccus (one month ago)

**Comment by marcelklehr** [comment]
Touché. My bad, I skipped over your sync method and tried to replicate with WebDAV, but with Google Drive I can indeed replicate the bug. It's fixed now. Stay tuned for the next release and thanks for reporting! :blue_heart:
