### ISSUE TITLE
Improve wording around sync strategies

### ISSUE THREAD

**Issue by marcelklehr** [floccusaddon/floccus#1066]
### Describe the feature you'd like to request

Some of the terminology can be confusing for novice computer users.  Terms like "Push" and "Pull" can come across too technical.

### Describe the solution you'd like

I think it would be much better to replace as follows:
A) Instead of "Push Sync" replace with "Upload - Overwrite Nextcloud data" 
B) Instead of "Pull Sync" replace with "Download - Overwrite Local data" 
C) Instead of "Normal Sync" replace with "Merge - Merge Local and Nextcloud data"
D) Instead of "Push Sync Once" replace with "Upload Once"  (overwrite Nextcloud data with local data)
E) Instead of "Pull Sync Once" replace with "Download Once" (overwrite Local data with Nexcloud data) 

### Describe alternatives you've considered

N/A

**Comment by pinpontitit** [comment]
I agree. I never understood those push and pull terms before your post lol
