### ISSUE TITLE
Folders or filenames that contain a "/" symbol will cause these folders to be continuously created

### ISSUE THREAD

**Issue by Tek220308** [floccusaddon/floccus#1067]
### Which version of floccus are you using?

v4.10.1

### Sync method

{"label"=>"WebDAV"}

### Which browser are you using?

Chrome Firefox

### What kind of WebDAV server are you using? (if relevant)

synology webdav

### Describe the Bug

There is a folder called "c/c++" in my bookmarks, and there are some link files in it. After multiple synchronizations, there are problems such as hanging, high CPU usage, and multiple folders with the same name. The programmer's intuition tells me that "/" is probably the root cause. It is normal after changing the "c/c++" folder to "c_cxx".
A similar problem occurs if the linked file also has a "/" symbol.

### Expected Behavior

Normal synchronization of folders or files containing the "/" symbol

### To Reproduce

Create a folder with a "/" symbol in its name, put some link files in it, or create a link file with a "/"

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> Create a folder with a "/" symbol in its name, put some link files in it, or create a link file with a "/"

I cannot replicate this. Sorry.

**Comment by Tek220308** [comment]
Sorry, there may be other reasons. I can't find a way to reproduce for the time being. The phenomenon is that after continuous automatic synchronization, the xbel file of webdav is getting bigger and bigger, and there are more and more file entries.



在 2022年3月9日，04:46，Marcel Klehr ***@***.***> 写道：

﻿

Create a folder with a "/" symbol in its name, put some link files in it, or create a link file with a "/"

I cannot replicate this. Sorry.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffloccusaddon%2Ffloccus%2Fissues%2F1067%23issuecomment-1062192145&data=04%7C01%7C%7C54836eccfa0343466e5308da0144a657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823691608049519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XqaUmREpzZtXId5S4qftXUESXUtBfQ05N5CGytSELhM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYECZZYAEHSPJX5CJQERCQLU664ANANCNFSM5QGWL4QQ&data=04%7C01%7C%7C54836eccfa0343466e5308da0144a657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823691608049519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3XLgv6XogtppqSj5Mfe53NAfJ5a7OJjlbIxac1%2B3Btc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C54836eccfa0343466e5308da0144a657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823691608049519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7Vq7sB0yYknfi%2FkshTt4ED5mCs0JaUAZDbxSQqswld4%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C54836eccfa0343466e5308da0144a657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823691608049519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kHN8N%2BwpI70xees30QuBoTT5mCGH3eoBMYz2CVfZakk%3D&reserved=0>.

**Comment by marcelklehr** [comment]
It's possible that this is due to cancelled sync runs when closing the browser window while floccus is syncing.
