### ISSUE TITLE
Cleaner status indication in the toolbar

### ISSUE THREAD

**Issue by brjhaverkamp** [floccusaddon/floccus#1072]
### Describe the feature you'd like to request

Currently in the toolbar there is an overlay with an green X, blue <> or error character on top of the floccus logo.
This looks quite rough and primitive and not very inline with most of the other add-ons

### Describe the solution you'd like

I propose to make the status indication more like the Nextcloud desktop app. Here
have the icon change to red with a warning sign in it when some thing is wrong
and with a progress circle when a sync in progress.

### Describe alternatives you've considered

The alternative is to learn to live with these visual status notification:-)

**Comment by marcelklehr** [comment]
Great idea! Thanks :)
