### ISSUE TITLE
Cannot add webdav account manually, default account created instead

### ISSUE THREAD

**Issue by cracket** [floccusaddon/floccus#1073]
### Which version of floccus are you using?

4.11.0.1

### Sync method

{"label"=>"WebDAV"}

### Which browser are you using?

firefox 97.0.2 32 bit armhf

### Describe the Bug

User cannot create webdav account manually, instead default webdav account is created, and as a workaround it can be edited to proper configuration

### Expected Behavior

If firefox/web browser is too slow to process click, first click on "Add account" should block events until page with editing details is ready
Do not fire multiple "add account" event until account is saved or updated
When creating default bob@example.com account - it should have "auto-sync" set to off by default
Do not allow to create more than 1 default webdav accounts

### To Reproduce

Steps to reproduce: 
- use latests components (floccus 4.11,  firefox 97, ubuntu 20 on armhf) on preferably slow machine
- remove all configured floccus accounts
- restart ff 
- I have clicked "+ NEW ACCOUNT" in top right icon pull down menu (it was empty due to no accounts configured)
- configuration page was shown: moz-extension://xxx-xxxx-xxxx-xxxx/dist/html/options.html#/new ( How do you want to sync? )
- I have selected "XBEL file in WebDav"
- clicked Add account, there was nothing happened
- so I clicked 4 more times on "add account", and UI still did nothing, and remained on page "how do you want to sync?"
- then I have moved to about:debugging (about:devtools-toolbox?id=floccus%40handmadeideas.org&type=extension) and tried to read some fancy floccus console logs 
- floccus started to synchronize 4 times the default built in account:
2022-03-11T21:43:09.100Z Starting sync process for account bob@example.org
- huge cpu utilization started due to multiple accounts being synced (although not the one I wanted)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank you for reporting this issue!

> so I clicked 4 more times on "add account", and UI still did nothing, and remained on page "how do you want to sync?"

Can you right click on the page when this happens, select 'Inspect' and then, in the newly opened dev-tools window go to the console tab to check for JavaScript errors?

**Comment by cracket** [comment]
There are no relevant errors in js console of  moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/html/options.html#/new page.

```
Error: Cannot find module './pl.json'
    r moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/js/options.js:2
    a moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/js/options.js:2
    m moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/js/options.js:2
options.js:2:1313657
Error: Cannot find module './pl.json'
    r moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/js/options.js:2
    a moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/js/options.js:2
    m moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/js/options.js:2
options.js:2:1313922
Error: Cannot find module './en_US.json'
    r moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/js/options.js:2
    a moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/js/options.js:2
    m moz-extension://6f77eca5-e455-4fd3-b517-6453fa9f6978/dist/js/options.js:2
options.js:2:1313657
[Vuetify] [UPGRADE] 'v-content' is deprecated, use 'v-main' instead.

found in

---> <VMain>
       <VApp>
         <App> at src/ui/App.vue
           <Root>

```
I suspect this can be just a huge delay due to bookmarks lockup ( see my other comment in [https://github.com/floccusaddon/floccus/issues/973#issuecomment-1065727558](https://github.com/floccusaddon/floccus/issues/973#issuecomment-1065727558) ) but I need to prove it somehow. 

How floccus should behave if some of the firefox storage is locked for more than 50 seconds (slow hardware and huge sqlite DBs in ff)?

**Comment by marcelklehr** [comment]
Could indeed be that it just takes veeery long :/ I'll consider adding a loading indicator.

**Comment by soil8rino** [comment]
Same behaviour here on Linux Mint
Kernel: 5.4.0-100-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: MATE 1.26.0 
           wm: marco dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 

and

fierfox 97.0.1 (64 bit) 

This is what I get in the dev-tools window

Error: Cannot find module './it_IT.json'
    r moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    n moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    m moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
options.js:2:1301190
Error: Cannot find module './it.json'
    r moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    n moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    m moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
options.js:2:1301455
Error: Cannot find module './it.json'
    r moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    n moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    m moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
options.js:2:1301190
Error: Cannot find module './it.json'
    r moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    n moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    m moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
options.js:2:1301455
Error: Cannot find module './en_US.json'
    r moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    n moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    m moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
options.js:2:1301190
[Vuetify] [UPGRADE] 'v-content' is deprecated, use 'v-main' instead.

found in

---> <VMain>
       <VApp>
         <App> at src/ui/App.vue
           <Root> options.js:2:1676781
TypeError: t is null
    s moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    p moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    p moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    o moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
options.js:2:1422933
TypeError: r is null
    u moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    p moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    p moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    o moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
options.js:2:1422933
TypeError: r is null
    u moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    p moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    p moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    o moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
options.js:2:1422933
TypeError: r is null
    u moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    p moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    p moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
    o moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/dist/js/options.js:2
options.js:2:1422933
Errore mapping di origine: Error: NetworkError when attempting to fetch resource.
URL risorsa: moz-extension://2307e850-0184-42c0-ad14-5b7d0c940d16/lib/materialdesignicons.min.css
URL mapping di origine: materialdesignicons.css.map

**Comment by sunjam** [comment]
I just removed bob@example.com four times from my Floccus browser extension on Firefox this morning.  Then, while attempting to add a new account... bob@example.com was added again.

**Comment by marcelklehr** [comment]
I've updated the account creation workflow in v4.14.0, please let me know if this is still an issue with the new workflow.

**Comment by soil8rino** [comment]
I removed floccus then I reinstalled it immediately after.
I do not know if this is what you expect from me to do.
Anyway I didn't notice any problem and my configuration was still there up and running

**Comment by marcelklehr** [comment]
@soil8rino This issue is about account creation, so if there are still excessive useless accounts created upon clicking NEW ACCOUNT, let me know. I'm closing this for now.
