### ISSUE TITLE
Allow smaller sync rates

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1078]
### Describe the feature you'd like to request

Hi
Why the smallest sync rate is 5 minutes ?

Is it technically possible to have an almost instantaneous syncing (same as in note taking apps for example Google keep or Standard Notes).

Because sometimes I create new bookmarks on my computer, for example, and 1 min after I close my browser and go out for work.
And on my way to work, I go on Floccus android, and I discover, sadly, that my browsers bookmarks didnt have time to sync.

So now what I do is that, before closing my browser and computer, I always go in Floccus to click on "Sync Now" by fear of not having my new bookmarks on smartphone.

Such situation could be avoided with instantaneous, or almost instantaneous sync (like 0.25 seconds or 1 second or 5 seconds).

Thanks

### Describe the solution you'd like

None

### Describe alternatives you've considered

None

**Comment by marcelklehr** [comment]
> Such situation could be avoided with instantaneous, or almost instantaneous sync (like 0.25 seconds or 1 second or 5 seconds).

Currently, floccus waits 1 min after the user makes a change in their bookmarks and then syncs. I suppose this could be reduced. IMHO it should be a bit more than 5s. Maybe 10s or 20s.
