### ISSUE TITLE
Automatic lock override should not happen

### ISSUE THREAD

**Issue by raslop** [floccusaddon/floccus#1089]
### Which version of floccus are you using?

4.12.0

### Sync method

{"label"=>"WebDAV"}

### Which browser are you using?

Firefox 98.0.1

### What kind of WebDAV server are you using? (if relevant)

Doesn't matter.

### Describe the Bug

I have seen 4a5e6de29, which reduces the lock-timeout to 15 minutes, and I have my doubts if this is really wise.

I have devices A and B and ~2.5k bookmarks. When doing some major re-organization on device A, i.e. move say delete ~200 bookmarks and move ~200 bookmarks to different folders, I have seen that some the device B takes up to 25 minutes for incorporating these changes. I works, but takes especially more than 15 minutes.
Fearing that another sync run on device A may harm something I disabled synchronization on A manually and waited until B was finished.

Question: What does the 15 minutes lock-timeout mean exactly? Is it overridden after this time? If yes, I don't think such overrides should happen automatically, but only manually (as suggested with #1068).

### Expected Behavior

No automatic lock-override at any time.

### To Reproduce

None.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by mnalis** [comment]
one thing to keep in mind (if applicable in this specific case) is that different machines that might be syncing bookmarks might not be NTP-synchronized, e.g. their clocks might differ.

**Comment by marcelklehr** [comment]
> different machines that might be syncing bookmarks might not be NTP-synchronized

Damn. Yeah, that's a problem.

**Comment by raslop** [comment]
> > different machines that might be syncing bookmarks might not be NTP-synchronized
> 
> Damn. Yeah, that's a problem.
> 
> There's no good way around this, though, I believe, except somehow asking the server what time it is. @mnalis What do you think? I suppose it's a fair requirement for a sync program to expect accurate time on the involved machines.

I also believe that with the help of the server it should be possible for a client B to determine the age of a lock on the server created by client A, even if the clocks are not synchronized, at least with an error margin of several seconds. Let's assume client A is currently synchronizing and regularly refreshes the lock on the server S. Client B checks the lock on the server and can then compare the following four timestamps:
- (a) The timestamp of the lock message from A taken from A's local clock. This is directly available as part of the lock/lockfile.
- (b) The last modification time of the lock/lockfile from the server S, taken from S's local clock. At least for WebDAV this should be available via PROPFIND or maybe even via the `Last-Modified` HTTP header (which seems to be optional). I also don't know HTTP response headers are available in floccus.
- (c) The current local time on B, taken from B's local clock.
- (d) The current local time on S, taken from the `Date` HTTP header of the response from S.

This is not thought to the end, but maybe a start. At least it should be possible to determine if the clocks are sufficiently synchronized.

I don't know about the google drive backend, but for WebDAV and maybe even for Nextcloud based accounts this could be possible.

I also tend to say that sufficiently synchronized clocks are required for synchronization.

**Comment by marcelklehr** [comment]
Indeed, it would be best to utilize the server time for this. I didn't know the Date header was mandatory for 2xx - 4xx responses, that's useful!

**Comment by marcelklehr** [comment]
We're using the Last-Modified header now which seems to work well. The Date header is not used so far, but I feel like that's fine.
