### ISSUE TITLE
"Failed to map parentId: 6341" sending Chrome bookmarks bar folder contents

### ISSUE THREAD

**Issue by srd424** [floccusaddon/floccus#1090]
### Which version of floccus are you using?

4.12.0

### Sync method

{"label"=>"WebDAV"}

### Which browser are you using?

99.0.4844.74

### What kind of WebDAV server are you using? (if relevant)

https://github.com/hacdias/webdav v4.1.1

### Describe the Bug

"Failed to map parentId: 6341" when trying to sync with the webdav server, even after setting to overwrite and deleting the old file on the webdav server.

### Expected Behavior

Bookmarks should sync without errors

### To Reproduce

Debug log has been uploaded to https://cloud.marcelklehr.de/s/... - hope it helps! Can try to export the bookmarks from the browser somehow as well if that will help, let me know.

### Debug log provided

- [X] I have provided a debug log file

**Comment by srd424** [comment]
Interestingly, I've just switched this account back to "merge" instead of "overwrite cloud with local" and it's happy now (I'm sure it wasn't originally.) Not sure what happened..

**Comment by rigrig** [comment]
Just had the same issue in Firefox 98.0.2 (64-bit): "Failed to map parentId: 7", [debug log](https://tubul.net/s/public/download?path=%2F&files=floccus-4.12.0-2022-03-24.log)

Synching with Nextcloud 23.0.3, Bookmarks app 10.1.0

Not sure when this broke, but it had synced my last bookmark, created 2 days ago on this PC.
1. It was set to "Merge local & cloud", retrying multiple times resulted in the same error
2. Switched to "Download & overwrite local" -> same error
3. Switched to "Upload & overwrite cloud" -> this fixed it
4. Switched back to "Merge local & cloud" -> working fine now

**Comment by marcelklehr** [comment]
Thank you for providing these logs! I was able to extract a test case out of them and fix this bug.
