### ISSUE TITLE
Floccus mobile repo? Tag?

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1093]
### Describe the feature you'd like to request

Floccus mobile appears to be different from the browser extension.

### Describe the solution you'd like

Would it be helpful to add some sort of tag or should it have it's own repo?

### Describe alternatives you've considered

Curious on what you'd prefer.  I'll just add [mobile] to issues... let me know what you think.

**Comment by marcelklehr** [comment]
Good idea. The repo is the same, because a large part of the code is shared between addon and android app. here you go: https://github.com/floccusaddon/floccus/labels/android
