### ISSUE TITLE
[Android] app name is confusing

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1094]
### Describe the feature you'd like to request

App name in the Izzy repo is currently `org.handmadeideas.floccus`

### Describe the solution you'd like

`Floccus Mobile` or `Floccus for Android` would make more sense.

### Describe alternatives you've considered

Hope this is helpful.  Once installed, the app shows up as `floccus`

**Comment by marcelklehr** [comment]
The official long name is "floccus bookmark sync", not sure why IzzyOnDroid displays the app ID.

**Comment by marcelklehr** [comment]
@IzzySoft Any idea what I have to do to change the listing?

**Comment by marcelklehr** [comment]
nvm, fixed. :see_no_evil:

**Comment by IzzySoft** [comment]
To play on an old joke: "app name, package name – sounds all the same to me" :speak_no_evil: :dash:
