### ISSUE TITLE
[Android] F-Droid Store listing

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1096]
### Describe the feature you'd like to request

Currently the app is available from a third party repo or the Floccus website download page, but it would be nice to add it to the main F-Droid archives eventually.
- #1095

### Describe the solution you'd like

Make app available from F-Droid proper.

### Describe alternatives you've considered

Having the third party repo is great for those needing a release faster, but addition to standard F-Droid will increase adoption and visibility.

Installations instructions already available from https://floccus.org/download

**Comment by marcelklehr** [comment]
Merge request was merged :tada: 

Floccus should be visible in an F-Droid app near you pretty soon :)

**Comment by sunjam** [comment]
Awesome, it'll be exciting when it arrives at https://search.f-droid.org/?q=floccus&lang=en

**Comment by marcelklehr** [comment]
Here we go: https://f-droid.org/en/packages/org.handmadeideas.floccus/

**Comment by pinpontitit** [comment]
> Here we go: https://f-droid.org/en/packages/org.handmadeideas.floccus/

Just a little thing to say:
do you think the logo of floccus in F-Droid could be improved ?

It's pixelated 
and slightly too big also: it seems it will make the dark square around to explode.

Also, Is it possible to round the corners to make it more stylish, as for example the **Gitnext** app icon.
This one:
![Screenshot_20220531-024627_F-Droid~2.jpg](https://user-images.githubusercontent.com/100489443/171072346-2568eb20-bef5-4860-a66c-497bbb0835df.jpg)

The floccus icon I can see on my phone:
![Screenshot_20220531-024355_F-Droid~2.jpg](https://user-images.githubusercontent.com/100489443/171072367-0967c379-9a7b-4dc6-9bdd-8d0707d44430.jpg)

I'm sorry I don't know how to use properly gimp or paint, nor create a SVG.
But someone in the community is maybe more confortable with that ?

**Comment by marcelklehr** [comment]
@pinpontitit Mh, I'm not sure why that is. The file that should be used looks much better: https://github.com/floccusaddon/floccus/blob/develop/fastlane/metadata/android/en-US/images/icon.png

**Comment by sunjam** [comment]
Are svg images supported?  I also noticed the pixelation.

**Comment by IzzySoft** [comment]
@marcelklehr as it seems you don't receive notfications from GitLab: Do you still uphold https://gitlab.com/IzzyOnDroid/repo/-/issues/216 now that Floccus is available at F-Droid – or can that issue be closed, too?

**Comment by marcelklehr** [comment]
Ah, sorry for the frustration. Not sure why I don't get notifications
from gitlab :/
I'd love floccus to still be on IzzyOnDroid as some people are not
comfortable with the fact that f-droid builds their own apks.

**Comment by IzzySoft** [comment]
> Not sure why I don't get notifications from gitlab :/

That happens from time to time – e.g. when they could not deliver a few messages in a row, they then mark the address as "unreachable". You then need to ask GitLab stuff to make it "unstuck".

> I'd love floccus to still be on IzzyOnDroid as some people are not comfortable with the fact that f-droid builds their own apks.

Thanks – it will then show up again with the next sync today at around 8 o'clock (7 pm UTC).
