### ISSUE TITLE
[Android] No version number or "About" section of app

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1099]
### Describe the feature you'd like to request

I cannot find a version number or links to this github or the website from within the app itself while attempting to fill out a bug report.  Just filing as a _nice to have_
- #1098 

### Describe the solution you'd like

Include some info within the app about current version, link to the website, link to the github.  You could also link to the download page, play store and f-droid.

### Describe alternatives you've considered

Find the app listing in the F-droid store to get more info.

**Comment by marcelklehr** [comment]
There is now an about section starting with v4.13.1

**Comment by marcelklehr** [comment]
@allcontributors Please add @sunjam to the list of contributors for ideas and testing

**Comment by marcelklehr** [comment]
@sunjam You will now be listed in the about page as a contributor :heart:
