### ISSUE TITLE
[Android] loginFlow SSO Failed to fetch

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1100]
### Which version of floccus are you using?

Android

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using?

Android

### Which version of Nextcloud Bookmarks are you using? (if relevant)

unknown

### Which version of Nextcloud? (if relevant)

23.0.3

### Describe the Bug

Unable to login from SSO.  With or without username filed in, app just returns `Failed to fetch`

### Expected Behavior

I was assuming I would be able to login from the [Nextcloud Android app loginFlow](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html), since I have it running on the same device.

### To Reproduce

1. Install Nextcloud on Android and login
2. Install floccus on Android
3. Add account via SSO loginFlow
4. Grant access from Nextcloud Android app

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Fixed with v4.13.0
