### ISSUE TITLE
[Android] Forbid bob@example.com from being added

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1101]
### Describe the feature you'd like to request

If no action is taken bob@example.com will be added to a user's account if they do not fill out the `Add Account` fields fast enough.  There must be a way to display that filler text without actually populating the fields literally.

### Describe the solution you'd like

Display that text without populating the field intended for user input.

### Describe alternatives you've considered

Thank you for considering.  It is minor, but also frustrating to have to continually remove bob@example.com from user accounts.

**Comment by marcelklehr** [comment]
see #1023
