### ISSUE TITLE
[Android] When no accounts present, do not continuously refresh

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1102]
### Describe the feature you'd like to request

When no accounts are present the app is continuously refreshing.

### Describe the solution you'd like

Ability to prevent the app from refreshing when no accounts have been added.
- #1101 

### Describe alternatives you've considered

Force quite the app on Android.

**Comment by marcelklehr** [comment]
> the app is continuously refreshing

I cannot reproduce this. By refreshing I assume you mean loading? When I delete all my accounts the app goes to the account setup screen for me.
