### ISSUE TITLE
backup plugins and other firefox configurations

### ISSUE THREAD

**Issue by pinkworld123** [floccusaddon/floccus#1103]
### Describe the feature you'd like to request

Hello, It would be very good when with bookmarks also backup plugins and other firefox configurations. Thanks.

### Describe the solution you'd like

backup plugins and other firefox configurations. 

### Describe alternatives you've considered

backup plugins and other firefox configurations

**Comment by marcelklehr** [comment]
This is out of scope for this project at this time. Thank you for your feedback nonetheless and happy syncing :hearts:
