### ISSUE TITLE
Support keyword search sync across browsers and profiles

### ISSUE THREAD

**Issue by timkgh** [floccusaddon/floccus#1104]
### Describe the feature you'd like to request

Support keyword search sync across browsers and profiles, e.g. 
`g` -> `https://www.google.com/search?q=%s`

### Describe the solution you'd like

Synchronize keyword searches across all supported browsers, together with the bookmarks.

Should also work across profiles in the same browser.

### Describe alternatives you've considered

Nothing great out there, seems natural for floccus to support it.

**Comment by marcelklehr** [comment]
I'm sorry. This data is not available to addons in firefox, which makes this infeasible.
