### ISSUE TITLE
Add Tab Sync Support for Sidekick Browser

### ISSUE THREAD

**Issue by blacklightpy** [floccusaddon/floccus#1105]
### Describe the feature you'd like to request

Right now Tab Sync doesn't work for Sidekick Browser, because I think it stores session data in a different format than Chrome, with multiple sessions.

### Describe the solution you'd like

Implement Tab Sync for Sidekick Browser.

### Describe alternatives you've considered

Sidekick is working on their own sync since Google shut down the sync API, but still, it can then only sync with Sidekick. For cross-browser syncing I still need Floccus.

**Comment by marcelklehr** [comment]
Sorry, I will not implement custom APIs from niche browsers for now.
