### ISSUE TITLE
number of minutes since last sync on toolbar icon

### ISSUE THREAD

**Issue by lazymonkey2** [floccusaddon/floccus#1106]
### Describe the feature you'd like to request

is it possibile to put the number of minutes since the last sync on the toolbar icon?
the number should be reset after a sync occurs automatically.

### Describe the solution you'd like

 put the number of minutes since the last sync on the toolbar icon.
if I don't find a bookmark that I have added on other device I can understand if I need to sync again by just looking at the floccus icon in the toolbar.

### Describe alternatives you've considered

an alternative could be to put the date and time of last synchronization in the tooltip of the toolbar icon.
but the minutes from last sync is better for me.

**Comment by marcelklehr** [comment]
I think the tooltip option would be better, as simply the number of minutes would be confusing without context, I think. If you need this in order to be sure that a sync has happened recently, then I'd rather make the icon red on the condition that a sync hasn't happened since X time. What do you think?

**Comment by 424344** [comment]
yes, I want to know if it was synced recently, so turning red the icon could be enough.
I think the feature should be optional, and the user can specify the number of minutes in the settings.
thank you.

**Comment by 424344** [comment]
other idea: is it's possible to detect when a new bookmarks is added, or an existing bookmark is modified? or moved in a different folder?
is it's possible then you could make red the icon when there was a change in the bookmarks and the sync is still not being done.

**Comment by marcelklehr** [comment]
I think conveying synced state via icon coloring is bound to be problematic. I am closing this in favor of #1416 which suggests to add a notification when a sync was done
