### ISSUE TITLE
Syncing failed with E034

### ISSUE THREAD

**Issue by SteveKeller** [floccusaddon/floccus#1109]
### Which version of floccus are you using?

4.12.0

### Sync method

{"label"=>"WebDAV"}

### Which browser are you using?

Chromium 96.0.4664.45

### Which version of Nextcloud? (if relevant)

22.2.3

### Describe the Bug

Some strange thing happen to me. From one day to the next, webdav sync of the bookmark file is not working anymore.

Log Message:
Starting sync process for account user@mynextcloud.net
2022-04-01T13:36:07.697Z onSyncStart: begin
2022-04-01T13:36:07.697Z https://mynextcloud.net/remote.php/dav/files/user/bookmarks/bookmarks.xbel.lock
2022-04-01T13:36:08.477Z https://mynextcloud.net/remote.php/dav/files/user/bookmarks/bookmarks.xbel.lock
2022-04-01T13:36:10.014Z Syncing failed with E034: Bookmarks file is unreadable. Did you forget to set an encryption passphrase?
2022-04-01T13:36:10.016Z onSyncFail

I am pretty sure that I did not set any passphrase on the bookmark file or for my credentials.
Any idea how this can happen? If not I will just uninstall and install floccus again and try to force sync from my browser.

Kind Regard
Steve

### Expected Behavior

Working normally

### To Reproduce

No idea

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Were you able to resolve this? When this error happens it's good to have a look inside the file in question to check what's wrong. This error is triggered when the file [doesn't look like xml](https://github.com/floccusaddon/floccus/blob/1e51d8f5bfb209e96b53fd2f5ab92410f2ca76a4/src/lib/adapters/WebDav.js#L192-L193).

**Comment by SteveKeller** [comment]
Floccus was working correct. It was a Nextcloud problem.

Somehow when Floccus tried to sync the bookmark file, it was empty. Same behaviour when I downloaded the file directly with the browser. But Nextcloud showed that it should have a file size of some kb.
Solution: Delete old bookmark file and sync again

Sorry for my late answer.

Kind Regard
Steve
