### ISSUE TITLE
[Android] Sorting bookmarks

### ISSUE THREAD

**Issue by tiptruck** [floccusaddon/floccus#1114]
### Describe the feature you'd like to request

The ability to sort bookmarks alphabetically. 

### Describe the solution you'd like

An option on main screen to choose sorting order. Eg. Date added, Alphabetical, frequent bookmarks, etc

### Describe alternatives you've considered

None considered

**Comment by Eyion** [comment]
On The Windows platform, I created A backup of bookmarks in Browser A, but failed to keep the original file sorting after the synchronization in browser B on the same platform. Then I synchronized bookmarks on android phone, but the file sorting did not follow my original backup. I want it to remember the sort I did when I originally backed it up, hopefully later versions will fix this, thank you!

**Comment by marcelklehr** [comment]
Hello @Eyion 
Thank you for your feedback! This issue is not about keeping the manually set order across syncs, but about exposing a way to sort bookmarks in a different order on demand in the Android app. Your issue is probably the same as #1110

**Comment by pinpontitit** [comment]
> ### Describe the feature you'd like to request
> 
> The ability to sort bookmarks alphabetically. 
> 
> ### Describe the solution you'd like
> 
> An option on main screen to choose sorting order. Eg. Date added, Alphabetical, frequent bookmarks, etc
> 
> ### Describe alternatives you've considered
> 
> None considered

I think this issue can be closed if you want, this feature has been implemented in the latest Android version.

**Comment by tiptruck** [comment]
Thank you.  The new feature works like a charm.  Closing
