### ISSUE TITLE
Sync doesnt work since new version 4.13

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1116]
### Which version of floccus are you using?

4.13

### Sync method

{"label"=>"Google Drive"}

### Which browser are you using?

Firefox 99

### Describe the Bug

Bookmarks Sync stopped working after the 4.13 Floccus update.
Now, the "cloud icon" in the extension toolbar is always red, and if I click manually on "Sync Now" button, nothing happens, as if the button wasn't responsive.

If I go to settings I noticed that my passphrase is encrypted, so the bug may be coming from a Credential problem. Floccus doesnt recognizee its been unlocked by credentials, I think.

And if I close my browser and open it again, normally, it locks Floccus and I have to put my credentials. Now its always unlocked but still with my passphrase encrypted.

If I click on Secure your credentials, I cant set up new credentials anymore.

**Comment by mariohommel** [comment]
I have the same issue here, Firefox 99 and Floccus 4.13.

**Comment by pinpontitit** [comment]
Is someone able to answer this question ?

Since syncing stopped working (4 days), I made many changes to my bookmarks (adding and editing, and classifying), both on desktop extension and Android app.

When the syncing issue will be solved, which classification will take the lead on the other.

Will my Android app bookmarks overwrite my desktop bookmarks ?
Will desktop bookmarks overwrite Android App ?
Will they merge ?

And the problem is, if they merge. that means that all the bookmarks I deleted after classifying on my desktop will be kept because I havent deleted them on Android ?

Thanks

**Comment by pizzadude** [comment]
just downgrade floccus for now

**Comment by pinpontitit** [comment]
> just downgrade floccus for now

I didnt think that was possible LOL
Thanks mate.
So if I am right I have to use the .xpi release for firefox.

**Comment by marcelklehr** [comment]
Sorry, for the inconvenience. I'll try and fix this soon.
