### ISSUE TITLE
[Android] After user grants access over SSO, automatically "Save"

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1122]
### Describe the feature you'd like to request

After granting access to a new account over SSO, the user must click the "Save" button on the top right.
Please making this save automatic as opposed to manual when granting access over SSO.

If the Save button is not click the user will instead become bob@example.com

Thanks!

### Describe the solution you'd like

Automatically save the SSO account.

### Describe alternatives you've considered

You must click the "Save" button after granting SSO access, which is counterintuitive.  Thanks!

**Comment by marcelklehr** [comment]
Thank you for raising this issue. I think implementing #1023 will fix this as well, hence I'm closing for now.

**Comment by sunjam** [comment]
Possibly.  The only confusion with it is after completing SSO login Nextcloud says:

`Access Granted.  You may now close this Window.`

but Floccus is still waiting for you to click the `Save` button, which is easy to miss and can be browsed away from by clicking anywhere else.

**Comment by marcelklehr** [comment]
Agreed. It's problematic that the window doesn't close automatically, once the authorization is done.

A different browser implementation may help with this: https://ionicframework.com/docs/native/in-app-browser

**Comment by marcelklehr** [comment]
Fixed by https://github.com/floccusaddon/floccus/commit/e68009010e89d4153fc3c916758c51053aed02ce

Window closes automatically now.
