### ISSUE TITLE
Use Globe icon instead of Star icon for individual bookmarks

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1123]
### Describe the feature you'd like to request
Just a papercut issue.

:star:  www.example.com

Is displayed for URL's.  There will be confusion because stars are used in all other Nextcloud apps to ["Favorite" an item](https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webgui.html?highlight=favorite).

### Describe the solution you'd like

Use the :earth_africa: icon, as you've done in Bookmarks, to let the user know they can click it to visit that URL.

### Describe alternatives you've considered

none, just was surprised to find the star icon did not mean save to favorites or save offline.  Thanks!

**Comment by marcelklehr** [comment]
mh, by now the bookmarks app on nextcloud also uses the star icon to signify a bookmark. Will ask the design team for feedback. Closing for now.
