### ISSUE TITLE
[Android] Black Floccus splash screen

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1124]
### Describe the feature you'd like to request

Papercut feature request.
A black splash screen when starting Floccus for Android.  I'm not sure of whether phone users use light themes... might be just me, but everything on my phone is dark mode.
- My nextcloud is also Dark Theme, which Nextcloud mobile apps usually match in color scheme.

Minor papercut, but that white splash screen is strong contrast to the otherwise dark themed app.
- Perhaps this can respect theme settings of the user's Nextcloud to be light or dark theme.

### Describe the solution you'd like

Show black splash screen on Floccus for Android if you are on dark theme Nextcloud.

### Describe alternatives you've considered

:dark_sunglasses: using the app as-is  :white_check_mark:

**Comment by marcelklehr** [comment]
With the upgrade to capacitor v4 we get splashscreens that are adjusted to dark mode :tada:
