### ISSUE TITLE
Android app struggles to open

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1125]
### Which version of floccus are you using?

Samsung Galaxy A21 (fully up to date)

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using?

Android

### Which version of Nextcloud Bookmarks are you using? (if relevant)

curent stable

### Which version of Nextcloud? (if relevant)

v23.0.2

### What kind of WebDAV server are you using? (if relevant)

not relevant

### Describe the Bug

Android app is seizing up when you browse back to it.

Stuck at splash screen... just straight white with no floccus icon for ~15 seconds.
or, Stuck at black screen with blue C shape for ~15 seconds
No icons visible.  They re-appear after 10 - 15 seconds.
No top bar visible (hamburger menu, search, settings icon) for 30 - 45 seconds.
App crashes.
`E027: Sync was Interrupted` notification appears after re-opening.

### Expected Behavior

Hope the above is clear.  I'll try to get screenshots and add them here.  Let me know on if there is a way to send you logs from Android.  It is possible my phone has not finished synchronizing over the last couple hours, but I am connected to 1000mb fiber internet.

### To Reproduce

Signed on with Loginflow SSO and sync account of 2000 bookmarks.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> when you browse back to it.

What does this mean exactly?

**Comment by sunjam** [comment]
You already have Floccus for Android app open.  You browse to some other app using the ||| button or the O button on the bottom of the phone UI (Android navigation) and then go back to Floccus.

**Comment by sunjam** [comment]
![Screenshot_20220420-102439_floccus bookmark sync](https://user-images.githubusercontent.com/1787238/164297747-ef72ad92-3431-4f2e-a67c-5cd62b467e13.jpg)
![Screenshot_20220420-102413_floccus bookmark sync](https://user-images.githubusercontent.com/1787238/164297777-0d76721e-6d32-413b-bb99-97320c1d0054.jpg)
![Screenshot_20220420-100404_floccus bookmark sync](https://user-images.githubusercontent.com/1787238/164297845-9fa1b8a7-8c37-47de-a428-11286ff62f0b.jpg)
![Screenshot_20220420-100841_floccus bookmark sync](https://user-images.githubusercontent.com/1787238/164297894-c5fd4095-9fe0-4f65-8605-bbe90d72df2f.jpg)

**Comment by marcelklehr** [comment]
:tada: Thanks for the feedback and the follow up :)
