### ISSUE TITLE
Submit bug reports from Android app 

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1127]
### Describe the feature you'd like to request

Request is for the ability to submit bug reports or logs from the app to the dev.
- Logs
- Screenshots as attachments
- send wherever makes the most sense.

### Describe the solution you'd like

No idea on the best way to do this, but I'd love to be able to send logs and screenshots.

### Describe alternatives you've considered

Manually create issues and ask the dev questions.  :laughing:

**Comment by marcelklehr** [comment]
Duplicate of #1098
