### ISSUE TITLE
[Android] Menus and buttons unresponsive if sync is in progress

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1129]
### Which version of floccus are you using?

4.13.1

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using?

Android

### Which version of Nextcloud? (if relevant)

v23.0.2

### What kind of WebDAV server are you using? (if relevant)

none

### Describe the Bug

If sync is in progress the menus and buttons are impossible to use.

### Expected Behavior

Android app buttons and menus will still be functional if a sync is in progress

### To Reproduce

Navigate around the app.  All menus and buttons will seize up if syncing.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by pinpontitit** [comment]
I just tried and for me it works.
When I click on the sync icon (or if I pull down the page, sync starts, a blue line appears, which I suppose indicates its syncing. 
And during the sync, I can click on a bookmark (which will open on my browser), or click on a folder, or click the "settings" icon.
I am using Floccus 4.13.1 also.

**Comment by marcelklehr** [comment]
I can also not reproduce this

**Comment by marcelklehr** [comment]
This might be much better in the last few releases, as I've cleaned up some functions that would cause performance hiccups. @sunjam can you confirm?

**Comment by sunjam** [comment]
@marcelklehr the buttons are still unresponsive during sync, but initial sync now took less than two seconds with 3k bookmarks on Android (new device).  A major improvement!

I tried a manual sync and was able to re-create the unresponsive buttons during the second or so the sync runs.  Perhaps someone else with an Android phone can test this.

**Comment by sunjam** [comment]
Realized I wasn't on latest Floccus 5.2.6 for Android. Under it the buttons do respond during sync!

Closing since buttons are responding during sync.

**Comment by marcelklehr** [comment]
Yay! I'm happy to have solved this :) Thanks for the feedback!
