### ISSUE TITLE
Already saved password can be readable or visible

### ISSUE THREAD

**Issue by shuricksumy** [floccusaddon/floccus#1135]
### Which version of floccus are you using?

4.13.1

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using?

Chrome, Firefox

### Describe the Bug

Hi,
I think it's a bit not secure to have the possibility to see the password which was already filed out. 

![image](https://user-images.githubusercontent.com/12009686/164616891-862f5de8-acee-4a2e-8293-f0cb301c2750.png)

### Expected Behavior

Only new password which is printing can be visible.
Already saved password should be always hidden by ****

### To Reproduce

1. Setup browser extension
2. Fill up settings
3. Save
4. Open edit or review these settings
5. Press "eye" icon near password field

Actual result: Already saved password is visible
Expected result:  Already saved password should be always hidden

### Debug log provided

- [ ] I have provided a debug log file

**Comment by pinpontitit** [comment]
I agree with you but this is not a bug. Its on purpose from the developer.
You can read our conversation on this other topic:

**Comment by marcelklehr** [comment]
I consulted the nextcloud design team and they confirmed, it's advisable not to allow this. Thanks for your feedback :)
