### ISSUE TITLE
Android: bug with the new feature "Allow network usage"

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1137]
### Which version of floccus are you using?

Android 4.13.1

### Sync method

{"label"=>"Google Drive"}

### Describe the Bug

There's a new feature in Floccus Android:
"Mobile settings:Allow network usage"

If I understand right, the purpose of it is to get online all the Favicons of the bookmarks.

To enable it, I have to check the checkbox below.
The problem is:
I check it, and after click on "Save" to save the settings. But after exiting the settings, if I come back to settings, the chzckbox is unchecked/uncrossed. As if my decision to enable this setting wasnt saved.

And of course there's still no Favicon loaded.

### Expected Behavior

The checkbox should stay checked even after exiting the settings or the app,
and favicon should work.

### To Reproduce

..

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Nice catch! Thank you for the feedback. This fix will ship with the next release
