### ISSUE TITLE
Make Nextcloud 2FA Login Compatible

### ISSUE THREAD

**Issue by AxelJust** [floccusaddon/floccus#1140]
### Describe the feature you'd like to request

Unfortunatly I couldn't log in to my Nextcloud instance due To my 2FA Setup

### Describe the solution you'd like

A Loging by redirecting to the NC instance would propably bring Compatibility to all Login Setups

### Describe alternatives you've considered

.

**Comment by marcelklehr** [comment]
This is possible since some time:

![Untitled](https://user-images.githubusercontent.com/986878/165536022-ca90d8e8-be6c-457f-bfe5-eb8943393fd0.png)
