### ISSUE TITLE
Android: top bar disappearing

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1150]
### Which version of floccus are you using?

4.13.1

### Sync method

{"label"=>"Google Drive"}

### Which browser are you using?

Android app

### Describe the Bug

It happened two times today.

It happens exactly like this:

I am on the floccus app, and while I am on the app, I decide I am tired of using my phone and decide to lock my phone by clicking the button on the side of the phone. So the screen turns off and I put my phone on my pocket.

If after some time, I decide to take my phone and unlock it, the first thing appearing is the Floccus app, of course, because thats the thing on which I was before locking the phone.

I noticed that Floccus starts syncing automatically, but whatever, I don't need Floccus right now, I just unlocked the phone to do something else.
So i click on the "show running apps" button. (You know, on android, there's this main toolbar all down the screen (=the Android Navigation Bar:    **< O |||**   )
with the "Return" Button at the left (**<**), the "Go to main screen where all the apps icons are" Button at the center (**O**) , and at the right the "Show me which apps are currently running" (  **|||** ). So I click on this last one. I see an animation of Floccus app being downsized.

And during the animation I can see the top toolbar of the Floccus bar (the toolbar that shows the search bar, the sync icon, and the settings icon) disappearing and being replaced by black background.

If i go back to the app, the black background is still there, and the buttons are still missing.

I have to close definitely the app and reopen it to see those buttons reappear.

Pictures:
![Screenshot_20220502-033653_One UI Home](https://user-images.githubusercontent.com/100489443/166175130-2736acfc-36e9-4489-a76c-8a8fcbcbf3f9.jpg)
![Screenshot_20220502-033656_floccus bookmark sync](https://user-images.githubusercontent.com/100489443/166175131-48cebf1f-310e-4c8c-af12-7d509d5dc4a6.jpg)

### Expected Behavior

..

### To Reproduce

..

### Debug log provided

- [ ] I have provided a debug log file

**Comment by pinpontitit** [comment]
More details:
It happened again today. No need to lock the phone ans so on. 
I made a test on purpose: just by going to Floccus App, swipe down and the most rapidly possible click on the "Opened app button" as I explained on my previous message.
It disappeared again. The bar being disappeared, the button that were in the bar(settings and sync for example) are no longer clickable of course.

I tried doing it more times and it doesnt do that anymore and just works normally. So I don't know exactly the good steps to reproduce. I just know it does it enough to be noticed but not always.

**Comment by marcelklehr** [comment]
I think I've fixed this. Can you try running the latest develop branch? (I hope it works for you)

**Comment by marcelklehr** [comment]
Is this still happening in the latest version?

**Comment by pinpontitit** [comment]
For now, it doesnt seem to happen in the latest version. 
I'll continue trying to induce it on purpose just to be sure, but for now it seems solved.
