### ISSUE TITLE
bookmarks deleted from new folders

### ISSUE THREAD

**Issue by m4rtini2** [floccusaddon/floccus#1151]
### Which version of floccus are you using?

4.13.1

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using?

firefox 99.0.1

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.3.1

### Which version of Nextcloud? (if relevant)

23.0.4

### Describe the Bug

Reordered bookmarks from the bookmark bar to other newly created folders in the bookmark menu are gone after other browsers are used. Sync fails with "Failed to map parentId: <varying ids>" message
On the server everything is fine. The bookmarks are still in the correct folders.

### Expected Behavior

The reordered bookmarks stay where they were placed. According to the sync profile. The bookmark bar has a copy of the bookmarks that were moved beacause the "send to server" profile from another browser syncs them to this place again.

### To Reproduce

1. Create bookmarks in the bookmark bar on browser 1. Put some of them in folders.
1.1. Create a "send to server" profile on browser 1. 
1.2 Sync bookmarks . 
1.3 Close browser 1.
2. Create a "merge local & cloud" profile on browser 2. 
2.1. Sync the bookmarks. 
2.2 Create new folders and subfolders in the bookmark menu. Sort the bookmarks from the bookmark bar to the created folders.
2.3 Sync the bookmarks
2.4 Close browser 2
3. Use browser 1
3.1 Sync the bookmarks
3.2 Close browser 1
4. Open browser 2
4.1 Open bookmarks and find the folders created in 2.2 empty

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
I've tried to reproduce this, but couldn't find behavior that wasn't expected by me. Note that "send to server" is called "Upload & overwrite cloud" in english, which does pretty much what it says: It overrides any changes you have made on the server with that of the current browser. Having one browser on "merge" strategy and one on "upload" is unlikely to be desirable. What are you hoping to achieve?

The translation possibly needs a revision. Is this german?

**Comment by m4rtini2** [comment]
Yes, this extension is in german language and i was not aware of the "overwrite cloud" part. 
Anyway, this behaviour seems still inconsitent as floccus only deleted the bookmarks from the folders and not the folders themself on the "merge" browser. 
The bookmark structure on the server was a mix of the created folders filled with bookmarks from "merged" browser and "stil unsorted" bookmarks in the bookmark bar from the "Upload & overwrite cloud" browser. This was exactly what i wanted.

My intent is to slowly cleanup my bookmarks from different browsers and so i expected the "Upload & overwrite cloud" browser to act as a master and push the changes immediately to the "merge" browsers. I also expected the "merge" browsers to push the changes to the server where i would review them, and integrate them into the "Upload & overwrite cloud" browser by hand. As it could not know about them. But i did not expect them to get deleted on the "merge" browsers. I understand that this would in my case temporaly create duplicates but they would get deleted eventualy.
"Immer vom Server kommende Änderungen verwerfen und lokale Änderungen hochladen" for me does not imply deletion of the bookmarks that are not on the local browser. 
But if it is the correct behaviour then i am sorry for causing trouble by writing this issue.

**Comment by marcelklehr** [comment]
> "Immer vom Server kommende Änderungen verwerfen und lokale Änderungen hochladen" for me does not imply deletion of the bookmarks that are not on the local browser.

It is supposed to imply that :/ The wording for this is very unfortunate and hard to get right. Maybe it could be replaced with

"Revert changes *from other browsers* and upload local changes"

?

**Comment by m4rtini2** [comment]
I agree, it is hard to find the right short description. But as you already have comment fields i suggest to put one under every option and precisly describe what it does. Maybe like:
O Immer vom Server kommende Änderungen verwerfen und lokale Änderungen hochladen
    _Lokale Lesezeichen werden zum Server kopiert. Änderungen durch anderen Quellen werden dabei überschrieben. Lokal nicht  
    vorhandene Lesezeichen und Ordner werden gelöscht!_

But with this behaviour it is, as you mentioned, not possible to use different options on different browsers.
If the "Upload & overwrite cloud" option would only upload and overwrite, but not delete the changes from "merge" option they could coexist and would even have a use case. Mine, described above ;) But this is of course for you to decide if it is possible and desired.

**Comment by marcelklehr** [comment]
I think for your use-case the merge strategy on all browsers should be fine. It is not a blind merge, after all, but more of an intelligent merge.

**Comment by m4rtini2** [comment]
Thank you. I will use the merge option then.
This issue can be closed.
