### ISSUE TITLE
Firefox 100: Cannot reconnect to Google account

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1153]
### Which version of floccus are you using?

4.13.1

### Sync method

{"label"=>"Google Drive"}

### Which browser are you using?

Firefox 100.0

### Describe the Bug

Hi
I removed my account, and created a new one.
I cannot connect it to my Google account anymore.

It says:
E031: Could not authenticate with Google Drive. Please connect floccus with your google account again.

I tried many times, also with firefox 99.0.1.

It was working fine before, but just because I removed the account and created a new one, it wont work anymore.

I tried also deleting the old authorization for floccus on my google account, before trying to connect the new floccus account. That didnt work.

Thanks

### Expected Behavior

..

### To Reproduce

Click on "Remove account".
Then create a new account.
Choose Google storage
Put your email, and password.
Click on "I authorize allizom.com to see and make changes on my google drive files"
The pop-up disappears as if it was all good.

But when going on the floccus extension the error code above appears in red.
And the cloud icon stays red.

### Debug log provided

- [x] I have provided a debug log file
[floccus-4.13.1-2022-05-04.log](https://github.com/floccusaddon/floccus/files/8622124/floccus-4.13.1-2022-05-04.log)

**Comment by marcelklehr** [comment]
Can you inspect the network requests sent to google servers on the settings page? There should be some more detailed errors there.

**Comment by pinpontitit** [comment]
You mean the Settings of Floccus ?

In the settings, under **"Server details"**, its as if I wasnt connected to my Google account: 
-there is still the "Login with Google" button, 
-and its written: "Connect your Google account to store the bookmark sync file in your Google Drive."

If I click the Login button, it asks me to reproduce the same steps described before:
-a pop-up from google opens
-choose the google account you want to use
-but then says "**Allizom.org** wants a new access to your google account. Allizom already have some rights. Click here to see the **1** services that Allizom already have rights on." etc....
-I click on "Proceed"
-Pop-up disappears and I am still not connected.
-And in settings there's still the "Login with google" button

Could the problem be on Google side ?
But why is Google saying that "Allizom" already have rights if the problem comes from google ?

And last thing, is it normal that in Chrome, it says:
"**Floccus** wants to connect to your Google Account"
and in Firefox its: **Allizom** ?

**Comment by pinpontitit** [comment]
I found this this in the "Debug add-ons" section, if it helps:

POST https://oauth2.googleapis.com/token
Status: 400 Bad Request

Error: E031: Could not authenticate with Google Drive. Please connect floccus with your google account again.
background-script.js:2:189146

I can send you more screenshots in private if needed.

**Comment by pinpontitit** [comment]
Ok so I have some news.
Login to my google account still doesnt work.

So I decided to try a different way: by exporting floccus extension from chrome and importing it to Firefox.

I didn't remember that I already tried it in the past, and that it didnt work, thats why I had tried to do it the old way: by login to my google account, writing my bookmark file name and passphrase, etc.. (which doesnt work as I explained in my previous posts)

So as I said, importing account to floccus dont work in firefox :
when i click on import, a popup showing my computer files appear, i select the floccus_export.json file, click "OK", the popup showing my files disappear, and then nothing happens. 
Still no account shown in floccus.

So I start doing random things. And I decided to go to "about:addons" in firefox. From there I went to the floccus extension. Then in "options", where it show exactly the same thing as in the floccus extension.
And in there, I could import my account file without problem !

So to sum up: Importing an account from the regular, floccus extension icon in the top bar doesnt work.
But importing an account from the "options" menu of the floccus extennsion, in "about:addons", works.

Strange, right ?
In librewolf it didnt work also, but I was thinking the culprit was "librewolf" that has some tweaks for privacy, and maybe broke the normal behavior of extensions.
But in Firefox 100, it also didnt work, while I didnt do anything. Firefox 100 browser was just installed, no config changed at all, its brand new.
Maybe it comes from Windows but i doubt it.

So thats all good for me I don't need to login anymore, so I don't know if you wish to close this issue, if you could reproduce it or not, but in my case I coulndt figure if its the floccus extension, my browser config, or firefox in general.

Still there's this new issue with the impossible "import" without going to about:addons.

**Comment by marcelklehr** [comment]
I can reproduce this with fx 100. I've contacted mozilla to sort this out, will perhaps file a bug on their bugzilla if this is confirmed to be a bug in Firefox. Oof.

**Comment by marcelklehr** [comment]
While in contact with mozilla QA I tried to reproduce this again and I cannot reproduce it anymore. Can you try it again as well?

**Comment by pinpontitit** [comment]
Yes! I tried with Firefox 100.0.2, with Firefox 98.0.1, with Librewolf, it works in all of them.
It seems that clicking on login opens a different kind of popup, I mean its not a popup anymore, but a tab, and it works.
Nice work mate
