### ISSUE TITLE
Nextcloud Bookmarks equals titles of bookmarks with the same URL

### ISSUE THREAD

**Issue by m4rtini2** [floccusaddon/floccus#1154]
### Which version of floccus are you using?

4.13.1

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using?

firefox 99.0.1

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.3.1

### Which version of Nextcloud? (if relevant)

23.0.4

### Describe the Bug

Some bookmarks from the bookmark bar _without_ a title, that also exist in a subfolder _with_ a title, get the url as title after a "merge" synchronisation. This happens on all clients. (I can not tell if this is a bug in floccus or the bookmark app in nexctcloud.)
Take a look at 1,2 and 3 as an example. If you delete the title from the modified bookmarks on the server the ones in the subfolder get also the title removed and replaced with the url after synchronisation. 

synchronised as "Upload & overwrite cloud"
![bookmark bar 2](https://user-images.githubusercontent.com/51192661/166735851-cbde1422-4f9e-4947-a958-f164907843b5.jpg)

after sync profile changed to "merge"
![bookmark bar after sync 2](https://user-images.githubusercontent.com/51192661/166737613-3a746347-60aa-4f55-8695-287b3fc10b3c.jpg)

on the server
![nextcloud bookmarks 2](https://user-images.githubusercontent.com/51192661/166735961-e9b94835-e4e6-4378-bac1-26fe6cd19ec8.jpg)

### Expected Behavior

Unmodified titles, urls, tags and notes of the bookmarks on all sync methods. In the correct order and in the correct place (according to the sync method).

### To Reproduce

1.1 change sync to "Upload & overwrite cloud" 
1.2 create some bookmarks in the bookmark bar and delete the titles
1.3 create a subfolder in the bookmark bar and recreate the bookmarks from 1.2, _do not_ delete the titles
1.4 synchronise
1.5 change sync to "Merge" and wait for synchronisation to finish
1.6 find some / all of your new bookmarks modified
1.7 delete the titles from the bookmarks in the bookmark bar on the server by clicking the three dots and editing the title
1.8 synchronise
1.9 find the modified bookmarks in the bookmark bar _without_ titles as intended and the same ones in the subfolder with titles _replaced_ by url as not intended

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Part of this behavior is "as intended" as the same URL can only have one title in the Bookmarks app. URL as title shouldn't happen anymore, but I'll investigate that.

**Comment by m4rtini2** [comment]
Thank you for looking into this.
So my problem that i can not have bookmarks with diferent titles for the same url is a result of the design of the bookmark app for nextcloud. If i would have 10 bookmarks with different titles and the same url in various folders the bookmark app would change the tilte of all 10 of them? Which title would it choose? As Firefox allows this behaviour, i think the bookmark app should allow it too.  
Should i post a bug report in the bookmark app repository or aks for this function as an enhancement? Or would this be to complicated to implement?

Is there a way to modify the url slightly so i land on the same url but the bookmark app will recognise it as a unique entity? I remember modifing the urls of youtube links to play videos without adds but can not find that info anymore.

**Comment by marcelklehr** [comment]
> the bookmark app would change the tilte of all 10 of them? Which title would it choose?

The Bookmarks app deduplicates your bookmarks automatically. As far as the app is concerned you have one bookmark in 10 folders. The last time a title is written to that bookmark, that's the title it has -- in all 10 folders.

> Is there a way to modify the url slightly so i land on the same url but the bookmark app will recognise it as a unique entity?

Yes, you can usually add `#anythingyouwant` to the end of any URL to have it point to the same location while technically being a different URL (unless the original URL already contains a #fragment part).

**Comment by m4rtini2** [comment]
Adding `#anythingyouwant` to the url may need some tweaking on some sites but is a good workaround and is working for me. The titles on the nextcloud server are empty now, as intended, but filling in the notes makes them distinguishable. Thank you very much for your support.
The issue can be closed.
