### ISSUE TITLE
Cannot connect to Nextcloud

### ISSUE THREAD

**Issue by thanasistrisp** [floccusaddon/floccus#1156]
### Which version of floccus are you using?

4.13.1

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using?

Brave V1.38.111 with chromium 101.0.4951.54

### What kind of WebDAV server are you using? (if relevant)

https://shared02.opsone-cloud.ch/

### Describe the Bug

I do not know if this server provides support for bookmark sync but in Nextcloud site the option other providers is grayed out (even when changing ip...). Which server do you suggest me to use?

### Expected Behavior

To be able to connect

### To Reproduce

![image](https://user-images.githubusercontent.com/79643637/167025603-2ce84c47-8ab8-4ec3-a8a7-bf203dd0c9fa.png)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @thanasistrisp 

Unfortunately the nextcloud.com website is being renovated and apparently this feature doesn't work yet. (cc @jospoortvliet )

Also, you should make sure the provider you chose has the Bookmarks app installed (there should be a star icon in the top bar giving access to the bookmarks app.) If you can't find the bookmarks app in the web interface, you cannot sync via the Nextcloud Bookmarks option.
