### ISSUE TITLE
Failed to decrypt file when moved to another folder

### ISSUE THREAD

**Issue by mneiger** [floccusaddon/floccus#1159]
### Which version of floccus are you using?

4.13.1

### Sync method

{"label"=>"WebDAV"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

Opera 86.0.4363.50 / FIrefox 100.0

### Which version of Nextcloud? (if relevant)

 v23.0.3

### What kind of WebDAV server are you using? (if relevant)

Nextcloud v23.0.3

### Describe the Bug

if I move the bookmark xbel file to another folder and adjust the floccus configuration accordingly, then it refuses to sync again and reports:

> E030: Failed to decrypt bookmarks file. The passphrase may be wrong or the file may be corrupted

[floccus-4.13.1-2022-05-11.log](https://github.com/floccusaddon/floccus/files/8672254/floccus-4.13.1-2022-05-11.log)

resetting to old location works 

### Expected Behavior

it should accept to the new file location and continue syncing

### To Reproduce

stop auto-sync
connect to nextcloud (webdav) server
move the xbel file to another location
wait some time (just in case)
edit floccus options and adjust "bookmarks file path" accordingly
save the options
ask floccus to "sync now"

### Debug log provided

- [X] I have provided a debug log file

**Comment by mneiger** [comment]
Still in 4.14.0

**Comment by mneiger** [comment]
Still here in 4.15.0

**Comment by mneiger** [comment]
and still here in 4.16.0 :-(

**Comment by mneiger** [comment]
Still here in 4.17.0 and nextcloud 23.0.4

**Comment by mneiger** [comment]
And still here in 4.17.1 and nextcloud 24.0.4 :-(

**Comment by marcelklehr** [comment]
Hey @mneiger Thank you for reporting this. I can confirm this is an issue. It's currently by design, but I can understand that this is frustrating. That said, Google Drive is not a high priority for me atm, so it will take some time until I get to this.

**Comment by mneiger** [comment]
Hi @marcelklehr , thanks for the confirmation. I feared it was something like the path being embedded in the encrypting code. It really means I will have to handle my migration another way.
However, I'm not using google drive but webdav on Nextcloud which is a more "native" platform to Floccus.

**Comment by mneiger** [comment]
Hi @marcelklehr , 
I finally migrated my bookmark data by recreating the xbel file. 
I'm still ready to help testing if there's ever a fix. However, if this is webdav specific, I wonder whether this is not in the end to be considered a duplicate of  #1263 .

Thanks.

**Comment by marcelklehr** [comment]
I'm starting to migrate the encryption now to move away from using the path as a salt. Once this change has propagated to all clients, I can roll out the actual change, in about a month.
