### ISSUE TITLE
New account does not automatically save after completing LoginFlow SSO

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1160]
### Which version of floccus are you using?
Firefox browser extension

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

latest

### Which version of Nextcloud Bookmarks are you using? (if relevant)

latest

### Which version of Nextcloud? (if relevant)

latest

### What kind of WebDAV server are you using? (if relevant)

Please auto-save after completing LoginFlow.  It makes no sense to grant access via LoginFlow and then make the user have to manually click the "Save" button.  If they do not click this button the entire process silently fails to be recorded by Floccus. The user actually ends up with bob@example.com user instead.

Thank you for considering!

### Describe the Bug

Save button must be manually clicked by the user or the entire loginflow SSO process with complete, but Floccus will silently fail to record the settings, which will instead be recorded as bob@example.com

### Expected Behavior

Once loginflow sso access is granted the account settings should be automatically saved.

### To Reproduce

Create a new account.
Loginflow SSO
Grant access
Do not click the save button.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
This is fixed in latest code but not released yet.
