### ISSUE TITLE
Remove bob@example.com values from fields in Floccus

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1161]
### Which version of floccus are you using?

latest

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

latest

### Which version of Nextcloud Bookmarks are you using? (if relevant)

latest

### Which version of Nextcloud? (if relevant)

latest

### What kind of WebDAV server are you using? (if relevant)

Please remove the values bob@example.com
Instead, just fail the entire account creation process or force the person to edit their entry as opposed to creating a fake account for the user.

Thank you for considering!

### Describe the Bug

bob@example.com is not a real account, but is being treated as real entires

### Expected Behavior

bob@example.com might be visible to explain what a user must enter, but please do not actually treat this as literal text entries in the fields.
Users should be required to properly fill out those fields just as I'm being required to fill out this field right now in reporting this issue

### To Reproduce

1. Create an account.
2. Type anything you want
3. Don't press the save button
4. bob@example.com

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank you for the feedback! This is fixed in latest code, just not released yet
