### ISSUE TITLE
Setting passphrase does not encrypt bookmarks

### ISSUE THREAD

**Issue by Seirade** [floccusaddon/floccus#1164]
### Which version of floccus are you using?

4.14.0

### Sync method

{"label"=>"WebDAV"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

Firefox 100

### What kind of WebDAV server are you using? (if relevant)

LoFloccus v1.2.3 (https://github.com/TCB13/LoFloccus)

### Describe the Bug

Securing account credentials and setting the passphrase does nothing to encrypt the bookmarks. The resulting XBEL can be opened in a text editor and read plainly.

Possibly relevant: I'm using Firefox with the History privacy setting of "Never remember history", which is equivalent to having private/incognito mode on by default. I'm not sure if this prevents the browser session from temporarily storing the passphrase, but the extension seems to only prompt me for it once and is able to sync normally, just without encryption.

Other observance: Testing with an older browser, [Firefox Portable 64](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%2064.0/) with the same settings, I noticed that the bookmarks are also kept in the extension's storage (`Data/profile/browser-extension-data/floccus@handmadeideas.org/storage.js`) without encryption. I'm not too familiar with how extensions work, but this would seem to suggest that when the extension loads the bookmarks into its storage from the file, that it also does not encrypt them. This can be problematic with non-portable (regular) installations leaving unencrypted data behind on devices when the browser is uninstalled. I could not reproduce this part with my regular installation of Firefox 100, though I may have been looking for the `storage.js` file in the wrong location.

### Expected Behavior

The XBEL file where bookmarks are kept should contain unreadable encrypted data, and anywhere else they are kept, such as extension storage (`storage.js`).

### To Reproduce

From a fresh installation of Floccus:
1) Create a new account
1) Choose the "XBEL file in WebDAV share" option for syncing
1) Choose the Bookmarks file path and Local folder
1) Use default settings for syncing (15 minute interval, Merge local and cloud changes, Yes include this account's folder in other accounts)
1) Next, secure credentials by setting a passphrase
1) Open Floccus and start a sync

When syncing is done, open the XBEL file in a text editor and you should be able to see the bookmarks in plaintext.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
I cannot replicate this off-hand. It seems likely to me that you only followed the account setup flow (which currently doesn't ask for an encryption passphrase) and didn't fill in the passphrase in the settings afterwards. Could this be the case? A way to improve this situation would definitely be to ask for an encryption passphrase during the account setup.

**Comment by Seirade** [comment]
I did later set the passphrase in the account options, but it made no difference, even after forcing a new sync (using the "Upload & Overwrite Once" option). Restarting the browser did ask me to enter the passphrase before a sync could begin, so I assumed that it was set, but the bookmarks still weren't being encrypted.

I tried again just now, but this time I also changed the XBEL path, and that seems to have worked. It seems like setting the passphrase doesn't work unless it creates a new XBEL. I tested this with the old path, and that appears to be the case. The bookmarks are not encrypted unless you delete the existing XBEL. This makes it difficult to encrypt the bookmarks by default, since during account setup, there is no option to set the passphrase first, but also the bookmarks are synced immediately after creating the account. Overwriting cloud changes does not encrypt them.

Also: If at a later stage you do not wish to encrypt them, there doesn't seem to be a way to remove the passphrase from the account settings. Would you just save with a blank field? That seems dangerous, as the field is blank by default, so the user may accidentally remove their passphrase if that's how it's done.

Overall, it seems like the functionality is there and it works, but there are many ways that the user could accidentally be leaving their bookmarks unencrypted. Some UX improvements would be very appreciated :)

**Comment by octigha** [comment]
The problem I'm having is that my bookmarks are always encrypted, even if I haven't set a password. I set a simple password once after installation and cancelled it.
