### ISSUE TITLE
Passphrase not showing anymore

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1165]
### Which version of floccus are you using?

4.14.0

### Sync method

{"label"=>"Google Drive"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

Firefox 100

### Describe the Bug

Hi,
I don't know if its a bug or a new feature so I'm verifying with yous.

I updated floccus extension in Firefox browser, now I have Floccus 4.14
And in the settings I don't see the passphrase anymore.
I mean the passphrase box is empty.

So I thinked, maybe with the update there was some kind of bug that erased the passphrase.
So I entered it again, and clicked on Save.
But when i quit the settings and then go back there its again empty. As if "Save" button didnt work.

I went on Chrome, where I still have older Floccus 4.13, and the passphrase is still there.

And I tried something:
I added a bookmark in Chrome (where the passphrase appears with Floccus 4.13),  and then click on "Sync".
Then I went in firefox (where the passphrase wont save as I explained, with floccus 4.14) and clicked on " Sync", to see if the bookmark I added in Chrome would appear.
And it still works, the bookmark appeared in Firefox.

So even if the passphrase seems to not be saved, floccus in Firefox is still able to read the XBEL file and fetch the new bookmark.

I also tried downloading the XBEL file before and after syncing with firefox, and its still encrypted.

### Expected Behavior

In older version, the passphrase was always saved and could be shown by clicking in the Eye icon.
I guess, if the Passphrase "box" is still here in Settings, that the passphrase should still appear inside.

### To Reproduce

Install Floccus 4.14 in firefox 100.
Check that the passprase has disappeared in the settings.
Put the old passphrase.
Click on Save.
Quit settings.
Enter settings again.
The passphrase has disappeared again.

Do a sync beteween older floccus version and the new one (where it seems no passphrase is set)
See that the sync is still working fine.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Yep, that's the result of the fix for #1135

**Comment by pinpontitit** [comment]
Ohh I see..

I misunderstood your comment in this [thread](https://github.com/floccusaddon/floccus/issues/1135#issuecomment-1113975414).
I was thinking that you were saying that the nextcloud design team said that it's advisable to always let the password readable as it was before.
(My english is bad)

So I wasnt expecting a change on this matter.

Thats great !

However, now the fact that the "Passphrase" box is still appearing, while we are not supposed to enter it again, because it's been saved, is misleading.
In my opinion, this box should disappear and be replaced by a button where we can read something like "Click here to modify passphrase" or "click here to reconsider the use of a passphrase".

Or, the first time we set a passphrase, the passphrase box should disappear, and a line should appear stating:
"A passphrase has been set, which makes your XBEL bookmarks file encrypted. If you do not wish your bookmark file to be encrypted anymore, or if you want to use a different passphrase, please consider creating a new file/choose a new path".

It depends on the possibility to change the passphrase. I've never tried to change the passphrase in one browser and check what it did in another browser, so I don't know what would happen.

I imagine that the most common UX (as seen in all type of accounts on the web), is the famous option "Change my passphrase":
Old passphrase: 
New passphrase: 
Repeat new passphrase:

But I don't know if it works the same way in Floccus.

**Comment by akwala** [comment]
> Yep, that's the result of the fix for #1135 Suggestions on how to improve the UX are always welcome :)

I agree with @pinpontitit that it is misleading to see an empty password field when secured credentials are decrypted. The UI needs to provide a clear way to change/remove credentials.
