### ISSUE TITLE
Local import/export

### ISSUE THREAD

**Issue by kotjarka** [floccusaddon/floccus#1166]
### Describe the feature you'd like to request

Mobile browsers, ie. Firefox stores bookmarks in simple sqlite DB (https://gist.github.com/dogancelik/b82c6eac880eb58acd2b). 
If device is rooted, it shouldnt be hard to import / export bookmarks from app to this DB, to further use in browser. What do you think about idea, of course feature avilable only to more experinced users with root..

### Describe the solution you'd like

Sync with local browser DB

### Describe alternatives you've considered

n/a

**Comment by marcelklehr** [comment]
I think this is already covered by #1083 which would also allow import export on non-rooted devices, albeit via the longer route of using an exported HTML file
