### ISSUE TITLE
lower precison for % numbers in error messages

### ISSUE THREAD

**Issue by m4rtini2** [floccusaddon/floccus#1167]
### Describe the feature you'd like to request

This is not about a real feature request but more a cosmetic enhancement with a low priority. 
After the addon got updated i got a failsafe error with a very precise percent number of bookmarks that would get deleted. Like 50.0147815138971%

### Describe the solution you'd like

A integer number might be sufficient to signal the severity of the problem.

### Describe alternatives you've considered

Leave it as it is. It does no harm. This would be just cosmetic.

**Comment by marcelklehr** [comment]
Good point, I had the same thought once, but forgot about it.

**Comment by marcelklehr** [comment]
@pinpontitit This may be a good first issue to tackle if you're up for it :)
