### ISSUE TITLE
bookmark syncs move all separators towards the end of the folder

### ISSUE THREAD

**Issue by raslop** [floccusaddon/floccus#1170]
### Which version of floccus are you using?

4.14.0

### Sync method

{"label"=>"WebDAV"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

Firefox 100.0.1

### What kind of WebDAV server are you using? (if relevant)

home-brewed server

### Describe the Bug

After the automatic upgrade to 4.14.0 this week I noticed that similar to #1043 all bookmark separators were moved to the end of the folder again. It worked fine the last couple of weeks, but 4.14.0 seems to break it again, somehow.

### Expected Behavior

Bookmark separators stay, were they are.

### To Reproduce

Don't know.
The provided anonymized debug log is from the last sync, but maybe the "move to end end" happened in an earlier sync already.

### Debug log provided

- [X] I have provided a debug log file

**Comment by raslop** [comment]
2022-05-19T20:10:40.530Z Starting sync process for account user@domain
2022-05-19T20:10:40.542Z onSyncStart: begin
2022-05-19T20:10:40.552Z onSyncStart: completed
2022-05-19T20:10:40.555Z Using "merge slave" strategy (no cache available)
2022-05-19T20:10:41.050Z { localDiff: 
   [ { type: 'REORDER',
       payload: 
        + #qdWNbSkQsRRDundefined parentId: G4C0ZLWaX_Q7, hash: undefined
        - #cY3R6M79oLnu[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: qdWNbSkQsRRD
        - #TAmVKfMBM8lk[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: qdWNbSkQsRRD
        - #RerEOADPgLcd[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: qdWNbSkQsRRD
        - #TZcncfDkgUS2[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: qdWNbSkQsRRD,
       order: [62a6da8735c18e2d66fe5de3dc5440252a1da49e3cbaa7c1d2d5068ad73ffba0] } ],
  serverDiff: 
   [ { type: 'REORDER',
       payload: 
        + #1undefined parentId: 0, hash: undefined
        - #53[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: 1
        - #54[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: 1
        - #55[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: 1
        - #56[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: 1,
       order: [62a6da8735c18e2d66fe5de3dc5440252a1da49e3cbaa7c1d2d5068ad73ffba0] } ] }
2022-05-19T20:10:41.052Z { localTreeRoot: 
     + #G4C0ZLWaX_Q7[eb045d78d273107348b0300c01d29b7552d622abbc6faf81b3ec55359aa9950c] parentId: undefined, hash: undefined
       + #qdWNbSkQsRRDundefined parentId: G4C0ZLWaX_Q7, hash: undefined
         - #cY3R6M79oLnu[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: qdWNbSkQsRRD
         - #TAmVKfMBM8lk[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: qdWNbSkQsRRD
         - #RerEOADPgLcd[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: qdWNbSkQsRRD
         - #TZcncfDkgUS2[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: qdWNbSkQsRRD,
  serverTreeRoot: 
     + #0[4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2] parentId: undefined, hash: undefined
       + #1undefined parentId: 0, hash: undefined
         - #53[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: 1
         - #54[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: 1
         - #55[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: 1
         - #56[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: 1,
  cacheTreeRoot: 
     + #G4C0ZLWaX_Q7[eb045d78d273107348b0300c01d29b7552d622abbc6faf81b3ec55359aa9950c] parentId: undefined, hash: undefined
       + #qdWNbSkQsRRDundefined parentId: G4C0ZLWaX_Q7, hash: undefined
         - #cY3R6M79oLnu[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: qdWNbSkQsRRD
         - #TAmVKfMBM8lk[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: qdWNbSkQsRRD
         - #RerEOADPgLcd[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: qdWNbSkQsRRD
         - #TZcncfDkgUS2[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: qdWNbSkQsRRD }
2022-05-19T20:10:41.053Z { revertPlan: 
   [ { type: 'REORDER',
       payload: 
        + #qdWNbSkQsRRDundefined parentId: G4C0ZLWaX_Q7, hash: undefined
        - #cY3R6M79oLnu[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: qdWNbSkQsRRD
        - #TAmVKfMBM8lk[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: qdWNbSkQsRRD
        - #RerEOADPgLcd[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: qdWNbSkQsRRD
        - #TZcncfDkgUS2[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: qdWNbSkQsRRD,
       order: [62a6da8735c18e2d66fe5de3dc5440252a1da49e3cbaa7c1d2d5068ad73ffba0] } ] }
2022-05-19T20:10:41.053Z Checking failsafe: 0/4=0
2022-05-19T20:10:41.054Z { revertOrderings: 
   [ { type: 'REORDER',
       payload: 
        + #qdWNbSkQsRRDundefined parentId: G4C0ZLWaX_Q7, hash: undefined
        - #53[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: 1
        - #54[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: 1
        - #55[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: 1
        - #56[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: 1,
       order: [62a6da8735c18e2d66fe5de3dc5440252a1da49e3cbaa7c1d2d5068ad73ffba0],
       oldItem: 
        + #1undefined parentId: 0, hash: undefined
        - #53[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: 1
        - #54[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: 1
        - #55[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: 1
        - #56[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: 1,
       oldOrder: [62a6da8735c18e2d66fe5de3dc5440252a1da49e3cbaa7c1d2d5068ad73ffba0] } ] }
2022-05-19T20:10:41.054Z { reorderings: 
   [ { type: 'REORDER',
       payload: 
        + #qdWNbSkQsRRDundefined parentId: G4C0ZLWaX_Q7, hash: undefined
        - #53[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: 1
        - #54[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: 1
        - #55[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: 1
        - #56[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: 1,
       order: [62a6da8735c18e2d66fe5de3dc5440252a1da49e3cbaa7c1d2d5068ad73ffba0],
       oldItem: 
        + #1undefined parentId: 0, hash: undefined
        - #53[f7e26f7122bd990bb0112d17b9fe6179b3555d739c99cc2f05252f1163c75bac](b621cba8e74d22ceb585b4d96ca1b6461e72d3f358d1affe3fb16919ccd6894a) parentId: 1
        - #54[f167853b936f439b173ab76df0fdfdac3c75c6c303be31b2d617d58862c0cafd](a37de75fec38d7553cecb4c547f70c501732495590b333b439695668a6273c72) parentId: 1
        - #55[caf7d37cdfb4ecd1ba0d6db9b910878c82498cf7b80250fd2bea18ed3f684772](f6f7567692cd9e9d5c8cc53a446c5719541b314a9d28a17fbfce334bc1e39790) parentId: 1
        - #56[51305ed54a6411f009afe66fc56ce8b7e1dbfd5beb07cce3ef353dc2723be0ea](add312a79412103418c7154f7dcee15796d009071ba183fe27ccd76361a829b9) parentId: 1,
       oldOrder: [62a6da8735c18e2d66fe5de3dc5440252a1da49e3cbaa7c1d2d5068ad73ffba0] } ] }
2022-05-19T20:10:41.055Z (local)ORDERFOLDER { id: 'qdWNbSkQsRRD',
  order: 
   [ { type: 'bookmark', id: 'cY3R6M79oLnu' },
     { type: 'bookmark', id: 'TAmVKfMBM8lk' },
     { type: 'bookmark', id: 'RerEOADPgLcd' },
     { type: 'bookmark', id: 'TZcncfDkgUS2' } ] }
2022-05-19T20:10:41.624Z onSyncComplete
2022-05-19T20:10:41.628Z No changes to the server version necessary
2022-05-19T20:10:41.633Z Successfully ended sync process for account user@domain

**Comment by marcelklehr** [comment]
I cannot reproduce this with Firefox 100 at the moment. It might work if you let floccus add the separators upstream once, since floccus supports syncing separators now.

**Comment by raslop** [comment]
Well, it seems that this was a one time event after the upgrade from floccus 4.13 to 4.14.
After reorganizing the separators in some folders, the correct position was synced again to other devices.
So I spent some time again to restore the position of more separators, which were also correctly synced again.
I agree to close this issue and hope that such glitches don't occur with future updates, as re-positioning the separators takes a lot of time.
