### ISSUE TITLE
Passive De-stabilization Bug Encountered

### ISSUE THREAD

**Issue by dawilan** [floccusaddon/floccus#1171]
### Which version of floccus are you using?

v4.14.0

### Sync method

{"label"=>"WebDAV"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

multiple - included lower down

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.3.1

### Which version of Nextcloud? (if relevant)

23.0.4

### What kind of WebDAV server are you using? (if relevant)

Nextcloud

### Describe the Bug

I was syncing between 2 browsers on the same machine:

- Vivaldi Browser 5.2.2623.48 (Stable channel) (x86_64) 
- Brave Browser 1.38.119 Chromium 101.04961.67 (x86_64)

**Symptoms:**
1. Both Browsers are running far more load than normal.
2. NextCloud server itself is running PHP FPM processes in excess of normal limits.
3. I observe little happening on the browsers to justify load - start troubleshooting.  Load is far better with Floccus disabled.
4. I drill into the bookmarks.xbel file and see duplicate entries for the entire body of bookmarks.  Looks like a sync merge gone awry.  When I say duplicate merges - I counted no less than 25,000 repeats of the same JSON objects all nested together.  Each time it was looping it was also pushing down so the local browsers had super inflated bookmarks data as well.

### Expected Behavior

Just clean operation and sound merged data to sync across.

### To Reproduce

Unfortunately I have no idea.  I started fresh and cleaned up everything.  We will see if this replicates. If it does I know exactly the versions and sync settings.

I more or less wanted to pass this upstream to you so that you could be aware of what was going on.

I absolutely love Floccus.  Excellent work!

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
I'm not sure why this happens, but it could be a case of misconfiguration, can you check whether the folders you set up for sync are correct?
