### ISSUE TITLE
UX improvements: Account creation and settings

### ISSUE THREAD

**Issue by Seirade** [floccusaddon/floccus#1172]
### Describe the feature you'd like to request

Some things are missing from the account creation/setup phase. Below are some suggestions to make things a little more consistent. None of the suggestions are crucial, but they would help improve the first-time user experience, rather than having to learn some of the quirks.

### Describe the solution you'd like

- [x] **1) Account creation: Ability to set a passphrase for the account in order to encrypt the bookmarks XBEL**
Without this, after the account is created, the initial sync won't encrypt the bookmarks file since the passphrase has to be set as an extra step.

- [x] **2) Account creation: Ability to set auto-sync setting**
Similar to the first suggestion, this would be mainly to prevent an initial sync to mess something up, like not encrypting the bookmarks.

- [ ] **3) Account creation/settings: Set an account name?**
Not sure if desired, but it might be useful to allow the user to give a name to an account in order to distinguish them from one another. Otherwise, the default names set are kind of vague ("Root folder", "Other Bookmarks", etc).

- [x] **4) Account settings: Removing passphrase**
There's currently no way to remove a passphrase from an account in order to save the bookmarks as an unencrypted XBEL file. At the moment, you just get the following error:
`E034: Bookmarks file is unreadable. Did you forget to set an encryption passphrase? `

Leaving the passphrase box blank and clicking Save does not remove it, since the bookmarks continue to be encrypted, and there is also no indicator anywhere that a passphrase is set. It would be nice if this could be set up in a similar way to the "Secure your credentials" panel.

- [ ] **5) Account settings: Confirm passphrase**
A second input box would be useful in order to not accidentally set a wrong passphrase. Again, similar to the "Secure your credentials" panel.

### Describe alternatives you've considered

N/A

**Comment by pinpontitit** [comment]
I agree with all of that.

Setting the file path for the XBEL file and setting a passphrase should be done directly when creating an account.

Also allowing to set an account name could be useful if we have multiple accounts and even if there's only one it would definetly look less techy/geeky than the actual name "Google drive/root folder".

I agree with the last points, "removing passphrase" and a "confirm passphrase" box.

**Comment by marcelklehr** [comment]
Thank you both for your feedback and suggestions! I've already fixed the easiest bits.

I'm not convinced account names are necessary. IMHO the combination of username@server, account type and synced folder should be unique and is still more informative than an arbitrary account name that the user might forget what it stands for.

PS: @all-contributors Add @Seirade as a contributor for ideas, feedback and bug hunting. :hearts:

**Comment by marcelklehr** [comment]
I've just redesigned the passphrase option:

![Peek 2022-07-04 13-27](https://user-images.githubusercontent.com/986878/177145734-e6955f9d-8b8b-49f4-ac6e-3b0e647d5435.gif)

**Comment by pinpontitit** [comment]
> I've just redesigned the passphrase option:
> 
> ![Peek 2022-07-04 13-27](https://user-images.githubusercontent.com/986878/177145734-e6955f9d-8b8b-49f4-ac6e-3b0e647d5435.gif)
> 

But if you click on "Change" the old password is readable ?
Because if thats the case, thats a stepbackward.

It wasnt readable anymore which was good IMHO

**Comment by marcelklehr** [comment]
Ah, right, I forgot about that. Thanks for the heads up!

**Comment by marcelklehr** [comment]
I'll close this since everything I deem important has been implemented, and "Set an account name?" has its own issue by now #1205
