### ISSUE TITLE
Failsafe for uploading to the cloud (before sync)

### ISSUE THREAD

**Issue by Seirade** [floccusaddon/floccus#1173]
### Describe the feature you'd like to request

Currently, there's some intentional behavior which could cause users to accidentally wipe their bookmarks XBEL file. The steps to reproduce are (using Firefox):
- Populate Browser A with a bunch of bookmarks and Browser B with none
- Export a JSON backup of B's bookmarks
- Sync bookmarks from Browser A to Browser B with the "Merge local and cloud changes" option
- Use the restore option on Browser B to roll back the sync
- Sync Browser B. Since the restoration mimicked deleting a bunch of bookmarks, the XBEL was wiped clean

The above is the most obvious example, but this could also apply to a situation where Browser B also has entirely different bookmarks. In this case, the XBEL would not be empty, so the user might not suspect anything happened.

### Describe the solution you'd like

Similar to the Failsafe option (which only applies to local changes), a check should be done before syncing to the cloud. If more than X% of bookmarks were changed/deleted, it should prompt the user if they would like to continue.

Also, it would be nice if the Failsafe options could let the user set their own % (or also a fixed number), just to add more customization.

### Describe alternatives you've considered

N/A

**Comment by pinpontitit** [comment]
I agree with the custom Failsafe percentage (50% seems totally random).

For the first issue you spoke about: unintentional removal of bookmarks, I don't totally understand your steps to reproduce.

You say:

> Use the restore option on Browser B to roll back the sync

I don't understand what is the restore option ? 
Is it importing an account from the JSON backup we exported earlier ?
In that case the solution could be a "script" who checks before importing an account if the same account already exists, and abort if true.
It would maybe need to give unique ID's to each account.

I am not sure.

Or maybe you meant the "Trigger from scratch" option ?

**Comment by Seirade** [comment]
By "restore" option, I mean the browser's own built-in one. In Firefox, it would be in the `Bookmarks Library > Import and Backup > Restore`

**Comment by marcelklehr** [comment]
Theoretically the other browsers should catch this with the failsafe when downloading the changes from the server, no?

**Comment by Seirade** [comment]
Yeah, that's a good point. I suppose the user could "Upload & overwrite cloud" from Browser A to fix things, so I'll consider that part a non-issue. I still think it would be useful to allow the user to set a custom % or amount for the Failsafe option.

**Comment by marcelklehr** [comment]
I'm not keen on introducing new settings. 50% was just a number I pulled out of my head, if you can think of a better default, I'm happy to change it.

**Comment by Seirade** [comment]
Not a new setting (unless you mean the custom amount), just a change into a variable % rather than a fixed 50%. If it's a no change, feel free to close this

**Comment by marcelklehr** [comment]
@Seirade How much would you set it to?

**Comment by Seirade** [comment]
If you're leaving this as a static value, 50% is fine for the average user. I'll close this for now.
