### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1174]
### Describe the feature you'd like to request

I've ran into many design problems that I want to share with you in order to improve the user experience.

I'm sorry to not open a bug or feature issue for each one of them but there's so many things I had in mind...

- [x] 1) About NewAcoount.vue
In Firefox, when you click on  "+ New account", a pop-up appears next to the floccus extension icon.
In this pop-up, you can see "1", "2", "3", 4", "5", in the stepper.

In Chrome when you click on "+ New account", its different: a new tab opens.
In this tab you can see next to the numbers, the dscription of the step.
So it's written "1 Sync method", "2 Sync server", etc..

But the v-card used is too narrow. 
So instead of having in a row all the steps written, there's a wrapping, and the step 4 and 5 are placed in a row under.
And this row under overlaps the big Title of the current step "How do you want to synchronize ?"

This happen maybe because I am using Floccus in french. I guess that in English its fitting just well.

- [x] 2)  I encounter many wrapping problems (with the text inside the buttons) with the french translation.

I'm trying to avoid those wrapping by reducing the more I can the length of the french translation. (There's more to do, i'll change some in the days to come)
However that not always possible. For example:

"Sync" can only be translated by "Synchroniser" in french. We don't use abbreviation for that.
I could use the beginning of the word with a dot to express that there's more coming but that doesnt look good I think (for example "Sync.".
"Sync now" = "Synchroniser maintenant"
"Now" can only be translated "maintenant". So i could remove "now" and just let "Synchroniser". But even "Synchroniser" is longer than "Sync now"
"Merge" = "Fusionner"
"Auto-Sync" = Synchronisation automatique. "Auto-synchronisation" doesnt mean anything in french. "Auto-sync" even less.
"Once" = "une fois"
"Allow Network Usage =  "autoriser l'utilisation d'internet" or "autoriser la connexion à internet"
"Failsafe = Mesure de sécurité
"Download anonymized logs" = "Télécharger journaux anonymisés" and in beautiful french "Télécharger des journaux anonymisés"
etc...

So some of those buttons are always going after the screen (Android) or the popup border (for firefox) or the v-card component( for Chrome, or are being wrapped in the line under.

So I am thinking of many solutions:

-for specifically the NewAccount-vue problem, we could just erase those step titles and just let the numbers, as in firefox. The step titles arent so necessary.

-for the rest of the extension we could avoid to use the same string for the setting title and the button.
 For example in the "Secure your Credential" popup (SetKey.vue), the big main title is "Define a passphrase for Floccus".
And in the button under there's again written "Define a passphrase for Floccus"
We already know the consequences that hitting the button will have. Maybe we could just replace that by "Confirm"

And there are many other case with double text in title and button:
Trigger sync from scratch
Allow network usage
Download logs
Erase the account (but thats a security measure to have it twice)

It's quite repetitive. We could delete the title and let the text inside the button, or let the title and change the text in the button instead with something as "OK" (preferable I think for the reasons above)

-another solution could be to widden the v-card to fit the text inside (however that would only fix the problem for browsers and not Android).
But I don't know if its possible to widden this component, I think it has a limit, right ?

- [ ] 2) Now that the encryption passphrase is no longer readable, we have to find a new use for the "Secure your credentials" (or delete it but lets take advantage of it now that its here)
It should be called by a new name as:
"Protect your account" or "Lock Floccus"

And we should explain better inside what's the meaning for it, because that's a problem I encountered when I first met Floccus:
I had some difficulties to understand why there was a passphrase in settings, then another passphrase in credentials.
And when it was written errors or other things like "Remember your passphrase" "Are you sure you set a passphrase"
I was always thinking twice : which passphrase ?

So we could explain better in the Set-Key page the puprose of this second passphrase: 
"This passphrase (maybe a different word than passphrase to avoid confusion with the encryption passphrase) has for purpose to protect your floccus settings and sync process. Without entering it at each restart you cannot change the settings, delete an account, and if you or someone removes all your bookmarks, this deletion wont be synced. "

- [x] 3) The encryption passphrase box should disappear when a passphrase has been entered. Now its misleading to still have this empty box while there's actually a passphrase set.

- [x] 4) Logs: I think "Anonymized" is not explained enough. It should be explained that Anonymized means that the title and links of your bookmarks will be replaced by random caracters.

- [x] 5) In android when you click on the upper left button (the one with three horizontal lines), a screen slide from the left.
This screen is so narrow that the text inside is not readable, we can only see the beginning of each sentence:

-Floccus
-Synchronisation priv...
-Google drive: floccu...
-Importer/exporter un....

Thanks

### Describe the solution you'd like

..

### Describe alternatives you've considered

..

**Comment by Seirade** [comment]
> And we should explain better inside what's the meaning for it, because that's a problem I encountered when I first met Floccus

I had similar problems, and I was going to open another issue for this, but I can't think of a better way to handle it.

The "Secure your credentials" (aka, lock Floccus) is for globally unlocking access to all of the accounts, even ones that are encrypted with a passphrase. Unfortunately, this means that if you don't secure the credentials, it's possible to steal passphrases to all of the accounts by exporting them, since the passphrase is included in the JSON file.

My original idea was to require typing the passphrase for the account *before* allowing access to change settings/exporting. However, there are some settings that are accessible in the main panel (the auto-sync toggle, and sync behaviors). This means that if someone wanted to be malicious, they could delete all bookmarks then click on "Upload and Overwrite". In order for this idea to work, ALL settings would have to be hidden, but then it would be tedious to have to unlock every account on browser start, especially if there are multiple. I don't think this is a bad idea though, as it would be similar to how you would unlock a database in a password manager. The Floccus account would be like a password database, so if you have multiple, you would obviously need to unlock them all individually before being able to use them. The difference is that you can only sync one local folder per-account, so maybe that should change to allow multiple folders (if that's possible)?

**Comment by marcelklehr** [comment]
Great suggestions: I'll work on these one step at a time!

For now I've managed to make the sync strategies selector in the popup panel more accessible:

![Screenshot from 2022-05-21 20-39-51](https://user-images.githubusercontent.com/986878/169665149-c5b77ffe-0164-48a5-a376-4dc4571d4213.png)

**Comment by marcelklehr** [comment]
@all-contributors Add @pinpontitit as a contributor for ideas, feedback and bug hunting :hearts:

**Comment by marcelklehr** [comment]
> for the rest of the extension we could avoid to use the same string for the setting title and the button.

I agree that the button texts could sometimes be shortened. However, it's good practice for accessibility to have a verb and a noun as a button text, so I'm not sure I want to shorten things like "Download Anonymized logs".

**Comment by marcelklehr** [comment]
I've changed the logs download buttons to "Full logs" and "Redacted logs" now
