### ISSUE TITLE
Automatic backups

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1177]
### Describe the feature you'd like to request

Hi
I use to regularly backup my bookmarks because I have "Auto-Sync" enabled and I am affraid that, maybe by mistake or because of a bug, my bookmarks in a platform (for example in Chrome) get deleted and it auto-sync this deletion with other platforms (Firefox or Android).

I know that by enabling the "Failsafe" I am quite safe from mistakes, but it still could delete less than 50%.

To backup my bookmarks I always go in the current browser settings and save it somewhere.
I have to do it manually.
That's a pity that browsers don't offer to automatically backup bookmarks in the local folder of our choice (they only allow online sync)

Why not adding an option to save Automatic backups in the folder of our choice ?

For example I am using Google Drive. I already have the XBEL file in the root folder of Gdrive, but this file gets updated regularly when I add or remove bookmarks.
There could be a setting in Floccus which says:

- Check here to enable Automatic Backups
- Choose the interval between backups (the same component than the one used for "synchronisation interval" but with days)
- Choose the folder path for your backups
- Check here if you want to each time overwrite your previous backup, or let unchecked if you prefer to always create a new backup file in this format : "floccus_bookmarks_backup_**/**/2022.xbel"

I noticed that for now there's still not possibility to export the bookmarks in anything other than xbel (for example json, csv, html, etc).
EDIT: In floccus settings there's the export account feature which creates a .json
But maybe a file in .json or else would be better than .xbel for browsers compatibility ?
I don't know.

{EDIT: My bad: In floccus settings there's the export account feature which creates a .json. But it doesn't contain the bookmarks. If such a feature came to appear we would need to clean up a little bit because it would be difficult for frist-time-users to understand all those files needed:
-xbel syncing file
-.json account export
-.log files
-.foo backup}

Just throwing this idea, but tell me if other persons would be interested or if it would be too much of "niche" feature.

Thanks

### Describe the solution you'd like

..

### Describe alternatives you've considered

..

**Comment by marcelklehr** [comment]
> I know that by enabling the "Failsafe" I am quite safe from mistakes, but it still could delete less than 50%

The 50% rule is kind of arbitrary, I'm open to changing it to something better if you have arguments for a specific number.

So far my stance has been that backups are outside of the scope for floccus and should be handled by server-side software, as is done in the Bookmarks App.
