### ISSUE TITLE
Add back button to account setup process

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1182]
### Describe the feature you'd like to request

Hi

I could use a "Go back" button in "newAccount.vue" process.
For example in step 1, I choose Google, so it takes me to step 2.
But then I regret and would prefer use Nextcloud.
To come back to step 1 there's no "Go back" button (I don't know how you would say in english)

I always have to close the tab and open a new newAccount.vue page.

If you are already at step 4 and want to come back to step 3, its such a pain in the ass to close the tab and start everything from scratch than just clicking Go back button.

Thanks

### Describe the solution you'd like

..

### Describe alternatives you've considered

..

**Comment by marcelklehr** [comment]
Meta comment: Please open one issue per proposal so it's easier to keep track of what is being proposed.
