### ISSUE TITLE
Syncing failed with JSON.parse: expected ':'

### ISSUE THREAD

**Issue by houdini69** [floccusaddon/floccus#1184]
### Which version of floccus are you using?

4.14.0

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

LibreWolf 

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.3.1

### Which version of Nextcloud? (if relevant)

24.0.1

### Describe the Bug

Floccus sends a parse error after syncing:
2022-05-29T13:25:46.800Z Starting sync process for account xxxxx@xxxxx.xxxx.xxx
2022-05-29T13:25:49.400Z Syncing failed with JSON.parse: expected ':' after property name in object at line 1 column 96502 of the JSON data

### Expected Behavior

synchro without error

### To Reproduce

Start web browser. Floccus icon shows error after syncing.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @houdini69 

Please make sure you got the version information for Nextcloud Bookmarks correct. There is no version 100.0.2-1

**Comment by houdini69** [comment]
Sorry about that! Corrected.

**Comment by marcelklehr** [comment]
Ok, this seems to be a problem with the response from the server. Can you check the nextcloud log for errors?

**Comment by houdini69** [comment]
Nothing wrong in nextcloud log.
In my web server nginx I got:
192.168.1.75 - - [29/May/2022:19:01:23 +0200] "GET /nextcloud/apps/logreader/poll?lastReqId=eCuujthFXprdOlY2fr5p HTTP/2.0" 200 22 "-" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.1.75 - xxxxxxxxx [29/May/2022:19:01:24 +0200] "GET /nextcloud/ocs/v2.php/apps/user_status/api/v1/user_status?format=json HTTP/1.1" 200 151 "-" "Mozilla/5.0 (Macintosh) mirall/3.5.0git (build 10063) (Nextcloud, osx-19.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
192.168.1.75 - xxxxxxxxx [29/May/2022:19:01:24 +0200] "POST /nextcloud/index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 200 40 "-" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.1.75 - xxxxxxxxx [29/May/2022:19:01:24 +0200] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.5.0git (build 10063) (Nextcloud, osx-19.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"

**Comment by marcelklehr** [comment]
Is this the nextcloud log or the Apache log?

**Comment by houdini69** [comment]
It's the nginx log.

In the nextcloud log there's nothing wrong. I'm going to reinstall Bookmarks app in netcloud as I could'nt connect to nextlcoud in Nextcloud Bookmark Manager client app too:
"there was an error retrieving:
https://xxxxxxxxx.xxxx.xxx/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1

TypeError: Cannot read property &#39;find&#39; of null"

**Comment by houdini69** [comment]
Reinstalling Bookmarks app in Nextcloud doesn't solve this issue. 

I noticed that synchro works on Android with the Bookmarks Android app after removing the bookmarks in this app.

**Comment by marcelklehr** [comment]
Can you post the returned content of `xxxxxxxxx.xxxx.xxx/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1](https://xxxxxxxxx.xxxx.xxx/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1` with sensitive content redacted?

**Comment by houdini69** [comment]
I could'nt access the returned content of https://xxxxxxxxx.xxxx.xxx/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1. It's forbidden by rules by my nginx configuration.

**Comment by marcelklehr** [comment]
Then floccus will have a hard time syncing with your server.

**Comment by houdini69** [comment]
Floccus was working nicely previously before Nextcloud update to version 24. Note that Bookmarks Android app still works.

**Comment by marcelklehr** [comment]
> But unfortunately floccus is still not working.

What is the error message? Are there other routes that are blocked by your nginx config? If you are maintaining a white list, the URLs that are part of the Bookmarks API are listed here: https://nextcloud-bookmarks.readthedocs.io/en/latest/index.html

**Comment by houdini69** [comment]
The error message is always the parse error indicated in my first message. 

Rules set in my nginx config are only by IP addresses. Otherwise the nginx configuration for nextcloud is the recommended one.

**Comment by marcelklehr** [comment]
Mh, then we need to dig a bit deeper:

#### Firefox
* Go to `about:debugging`
* go to "This firefox"
* click on `Inspect` button next to floccus entry
* go to the network tab in the inspector
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests

**Comment by houdini69** [comment]
Syncing failed with JSON.parse: expected ':' after property name in object at line 1 column 96502 of the JSON data [background-script.js:2:210323](moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js)
2022-06-03T16:03:50.300Z Syncing failed with JSON.parse: expected ':' after property name in object at line 1 column 96502 of the JSON data [background-script.js:2:14224](moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js)
2022-06-03T16:04:47.800Z Starting sync process for account houdini@monplaisir.ddns.net [background-script.js:2:14224](moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js)
SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 96502 of the JSON data
    getEntry moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    getCache moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    v moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    i moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    i moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    s moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    promise callback*c moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    s moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    promise callback*c moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    s moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    promise callback*c moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    s moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    promise callback*c moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    i moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    i moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    sync moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    syncAccount moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    scheduleSync moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    add moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    _tryToStartAnother moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    add moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    add moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    scheduleSync moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    checkSync moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2
    controller moz-extension://38c9843e-c185-491f-9164-2427d0896a79/dist/js/background-script.js:2

**Comment by marcelklehr** [comment]
> I've set my web server to allow access with your curl command and I got all bookmarks in a string

Can you check whether what you get from the curl command is valid json (e.g. using https://duckduckgo.com/?q=validate+json)?

**Comment by houdini69** [comment]
I got "JSON is valid!"

**Comment by marcelklehr** [comment]
Can you go into the *network tab* in the inspector window and trigger a new sync to check the request the returns invalid json?

**Comment by marcelklehr** [comment]
> getCache

Aaah! I just saw this. It seems like your cache is corrupt. Can you try uninstalling the extension and reinstalling?

**Comment by houdini69** [comment]
You're right! Reinstalling floccus fixed this issue.
