### ISSUE TITLE
Android : Alphabetical Sorting case sensitive

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1189]
### Which version of floccus are you using?

4.15

### Sync method

{"label"=>"Google Drive"}

### Describe the Bug

I just tried to sort alphabetically on Android and there's a problem.

It sort first all the Uppercase letters and then all the Lowercase.

I think users are expecting the alphabetical sorting to be case insensitive.

For example what is happening now when sorting alphabetical:
```
-Alakazam
-Doubidouwawa
-Zorro
-beach
-doubidoua

```
What should happen:
```
-Alakazam
-beach
-doubidoua
-Doubidouwawa
-Zorro
```

### Expected Behavior

..

### To Reproduce

..

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Agreed! The relevant part of the code is here: https://github.com/floccusaddon/floccus/blob/develop/src/ui/views/native/Tree.vue#L332 if you'd like to take it up (I think a simple .toLowerCase() would be enough) :hearts: .
