### ISSUE TITLE
Account creation fails with SSO and 2FA/TOTP

### ISSUE THREAD

**Issue by chriswells0** [floccusaddon/floccus#1192]
### Which version of floccus are you using?

4.14.0

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

Android 12

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.3.1

### Which version of Nextcloud? (if relevant)

24.0.1

### Describe the Bug

When adding a Nextcloud account, the SSO login flow opens and allows you to enter your credentials. The browser is closed after a successful login. However, with 2FA/TOTP enabled, there isn't enough time to select the 2nd factor before the window is closed. The account is unable to log in at that point.

### Expected Behavior

Select a 2nd factor for authentication to complete the login flow.

### To Reproduce

Simply enable 2FA in Nextcloud and attempt to add the account to Floccus on Android.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by chriswells0** [comment]
I should add that I have both Nextcloud Notifications and TOTP enabled as the 2FA options. I tried disabling TOTP so there would be only 1 option, which prevents the "choose your 2nd factor" screen from appearing. Then I was able to receive the notification in the Nextcloud app, but it was too late as Floccus had already closed the window and moved on.

**Comment by marcelklehr** [comment]
Confirmed. That's a weird one, cause it only moves on if nextcloud gives the go.
