### ISSUE TITLE
Brave: mobile and "other" bookmarks not synced

### ISSUE THREAD

**Issue by lazymonkey2** [floccusaddon/floccus#1193]
### Which version of floccus are you using?

4.15.0

### Sync method

{"label"=>"Google Drive"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

brave 102, firefox 101

### Describe the Bug

mobile bookmarks are not synchronized.
also "other bookmarks" are not synchronized.

only the bookmarks from the toolbar are synchronized.

### Expected Behavior

all bookmarks must be synchronized.

### To Reproduce

add some bookmark to mobile and to "other bookmarks" folder.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
The bookmarks are likely in Google Drive, if you've selected the root folder, but cannot be synced to brave, because it doesn't have Other bookmarks and mobile bookmarks folders. The solution is to create two more accounts in Brave that sync those folders to a different location (and disable access for the topmost account). Let me know if this is unclear.

**Comment by 424344** [comment]
thanks, I'll try using more accounts.
but why did you say that brave doesn't have mobile and Other bookmarks? I'm using them! :-)

**Comment by 424344** [comment]
yes, Brave bookmarks are similar to other chromium browsers. 
Chrome has mobile and Other bookmarks (and I think Edge too).
But on desktop they are showed only if there are bookmarks saved into those folders (at least for mobile, but I believe it works the same for Other bookmarks too).
If on your phone you add a mobile bookmark then it will appear on desktop in the "mobile" folder.
"Other" bookmarks  I think it is always there, I can see it in brave://bookmarks (or chrome://bookmarks or edge://favorites).
I believe on chrome these special folders are root folders, similar to the toolbar root folder.

**Comment by 424344** [comment]
related issue: in chrome I changed the options to sync from "bookmarks bar" to "root".
then I wanted to go back to sync only the bookmarks in the toolbar, so I switched back the option to "bookmarks bar".
now I get this error when I sync (push up);
Failed to map parentId: 1

here is the log file:
[redacted-floccus-4.15.0-2022-06-08.log](https://github.com/floccusaddon/floccus/files/8862344/redacted-floccus-4.15.0-2022-06-08.log)

**Comment by marcelklehr** [comment]
You can try a push sync to push your current state to the server.

**Comment by 424344** [comment]
I have already tried a push up, and got same error.

**Comment by marcelklehr** [comment]
Does it help to trigger a sync from scratch in the settings?

**Comment by 424344** [comment]
I have deleted the old bookmarks.xbel on gdrive, and did again a Push up. 
Now it works.
