### ISSUE TITLE
"cannot read properties of undefined (reading 'id')" Kiwi browser android

### ISSUE THREAD

**Issue by Adel-Chaker** [floccusaddon/floccus#1199]
### Which version of floccus are you using?

4.15.0

### Sync method

{"label"=>"Google Drive"}

### Which browser are you using? In case you are using the Android App, specify the Android version please.

Kiwi browser (Android)

### Describe the Bug

Sync failed with "Cannot read properties of undefined (reading 'id')" message.

### Expected Behavior

Sync

### To Reproduce

- Install floccus on chrome (Windows)
- Conf the profil and connect to drive
- Export profil, and send it to phone
- Install kiwi browser (v: 101.0.4951.40)
- Install floccus extension
- Import profil 
- Launch sync (Merge or download)

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @Adel-Chaker 

Sorry for the delay. Is this still happening? Can you check whether everything looks ok in the account settings?

**Comment by dafzor** [comment]
Getting the same error when attempting sync Firefox to Edge.

Firefox: 105.0.2 (64-bit)
Edge: 106.0.1370.37 (Official build) (64-bit)
floccus: 4.17.1

```
2022-10-08T14:01:20.664Z Starting sync process for account Google Drive: bookmarks.xbel
2022-10-08T14:01:20.666Z onSyncStart: begin
2022-10-08T14:01:22.729Z onSyncStart: completed
2022-10-08T14:01:22.730Z Using "merge default" strategy (no cache available)
2022-10-08T14:01:22.731Z Syncing failed with Cannot read properties of undefined (reading 'id')
2022-10-08T14:01:22.732Z onSyncFail
```
