### ISSUE TITLE
[iOS] Self-signed certificates not working

### ISSUE THREAD

**Issue by cmalvi** [floccusaddon/floccus#1201]
### Which version of floccus are you using?

Lastest from App Store

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Describe the Bug

After install the app, just launched, then selected the NextCloud Bookmarks option and insert the url of my Nextcloud instance, as already did it for the browser extension on my computers. The app keep loading without going further in the setup wizard

### Expected Behavior

Proceed in the setup

### To Reproduce

Already wrote in the description part

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello!

Which iOS version is this and what device?

**Comment by cmalvi** [comment]
iPhone SE 2020 with iOS 15.5

**Comment by marcelklehr** [comment]
Do you use 2 factor authentication?

**Comment by cmalvi** [comment]
Yes, but I can't even use app's password because floccus doesn't accept the address

**Comment by marcelklehr** [comment]
So it stalls after the first button press directly after entering the URL?

Floccus tests the URL as follows: `POST {nextcloudURL}/index.php/login/v2` can you try that with curl, perhaps?

**Comment by cmalvi** [comment]
It rejects the url saying is wrong, so I can’t proceed to authentication

**Comment by cmalvi** [comment]
Result of curl:

“ Please enter content (application/x-www-form-encoded) to be POSTed”

and after wait for input

**Comment by marcelklehr** [comment]
You can POST an empty message in curl

**Comment by marcelklehr** [comment]
> It rejects the url saying is wrong

Do you mind sending me the URL in private, e.g. email (see my github profile) so I can check why it might be seen as invalid?

**Comment by cmalvi** [comment]
> You can POST an empty message in curl

Still it keep waiting for input even after input

**Comment by marcelklehr** [comment]
maybe ctrl+D

**Comment by cmalvi** [comment]
> > It rejects the url saying is wrong
> 
> 
> 
> Do you mind sending me the URL in private, e.g. email (see my github profile) so I can check why it might be seen as invalid?

No sorry, it's my private instance.

It works with all the following OS/ software with no problem:

- Gnome
- Joplin
- Floccus browser extension (Firefox)
- macOS
- Windows

And many others.

I made it to not share with anyone

**Comment by marcelklehr** [comment]
> No sorry, it's my private instance.

ok, I understand.

Are you using a self-signed certificate?

**Comment by cmalvi** [comment]
> maybe ctrl+D

Here the result:

LWP will support https if the LWP::Protocol::https module is installed


So the app use a different method from other app and browser extension to handle https?

**Comment by cmalvi** [comment]
> > No sorry, it's my private instance.
> 
> 
> 
> ok, I understand.
> 
> 
> 
> Are you using a self-signed certificate?

Yes.

The only software where I've had problem due to this is macOS which accept only certificates with specific criteria, even with self-signed
With other software no specific problem about certificate

**Comment by marcelklehr** [comment]
> LWP will support https if the LWP::Protocol::https module is installed
> So the app use a different method from other app and browser extension to handle https?

This is a message from your server, it has nothing to do with floccus.

So, either your https setup is broken, as curl cannot seem to connect either, or floccus cannot handle self-signed certificates on iOS (which I haven't tested yet, but is not unlikely, it also doesn't work on Android).

**Comment by marcelklehr** [comment]
I'm closing this as 'won't fix' as self-signed certificates are an avoidable IMO and out of scope of floccus.
