### ISSUE TITLE
Cancel sync button doesn't work

### ISSUE THREAD

**Issue by InfamousUser** [floccusaddon/floccus#1203]
### Which version of floccus are you using?

4.15.0

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 102.0.5005.115

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.4.0

### Which version of Nextcloud? (if relevant)

24.0.1

### Describe the Bug

Pressing the "Cancel sync" button does nothing to cancel the sync.

### Expected Behavior

Pressing the "Cancel sync" button cancels the sync.

### To Reproduce

1. Make an account in Floccus.
2. Let it start syncing.
3. Decide not to let it continue syncing.
4. Depress the "Cancel sync" button.
5. Observe Floccus syncing nicely.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by InfamousUser** [comment]
Still doesn't work or mostly doesn't work. It worked at least once after a long delay.

**Comment by marcelklehr** [comment]
It is somewhat delayed due to the way it works. If the sync run is very fast it may trigger too late, but from my tests, if the sync runs for a longer time, it works fine.
