### ISSUE TITLE
Account renaming option (mainly for floccus apk)

### ISSUE THREAD

**Issue by Virgus** [floccusaddon/floccus#1205]
### Describe the feature you'd like to request

I've configured several accounts on the Android app.
While those related to google drive have clear names (Google Drive: name_of_the_file.xbel) those related to WebDav storage have names which are not readable enough. In my case I have "UserLogin@WebDavHost...". I cannot read further so I have to try each account to indentify each file. Even by turning the smartphone in landscape mode the account-name field is still not readable.
Thanks for this wonderful tool.

### Describe the solution you'd like

Add a GUI custom name field for account names.

### Describe alternatives you've considered

-

**Comment by marcelklehr** [comment]
Duplicate of #1294
