### ISSUE TITLE
[Android] Syncs indefinitly for large folders

### ISSUE THREAD

**Issue by Haze-sh** [floccusaddon/floccus#1208]
### Which version of floccus are you using?

4.15.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 4.15.0 Samsung A52s

### What kind of WebDAV server are you using? (if relevant)

Nginx

### Describe the Bug

The sync goes for days and never ends with the android version though I sync smoothly with the browser addon the same bookmarks file on my self-hosted webdav server.

### Expected Behavior

Sync is done as expected.

### To Reproduce

Use floccus android app with bookmarks folder +10000 bookmarks

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
This should be fixed with v4.16.0, please try it once it's available and report back :hearts:

**Comment by Haze-sh** [comment]
Unfortunately the problem didn't solve by v4.16.0

**Comment by marcelklehr** [comment]
I cannot replicate this with simply adding >10000 bookmarks over XBEL on WebDAV.

Do you have a lock file on your webdav share? Ie. if you bookmarks file is bookmarks.xbel, do you have a bookmarks.xbel.lock file in the same directory? It could also be a certificate issue: self-signed certs do not currently work on most android phones with floccus. Have you tried removing and recreating the account on android and see if that helps? Also, can you try to set up a new account with just a few bookmarks and try to sync that via your self-hosted server to check whether it's the number of bookmarks? (In the same theory: Does the progress bar change at all on android, during the time it says it's syncing?)

**Comment by Haze-sh** [comment]
Yes there is a lock file on my WebDav share. I don't think it is a certificate problem because I have another file with another account on the same WebDav and it works flawlessly. I tried removing and adding the account several times without a problem. I also tried less bookmarks and it works well. Actually the progress bar doesn't change with the case of many bookmarks.

**Comment by marcelklehr** [comment]
If the lock file is there and no other computer is currently syncing, you may try removing the lock file manually

**Comment by Haze-sh** [comment]
@marcelklehr I waited till every computer stops syncing and the lock file isn't there anymore. Nothing changes.

**Comment by Haze-sh** [comment]
The problem was being the XBEL file doesn't have a folder structure at all. Not just a big folder but there was no folder. This works well inside the browser already working folder structure but doesn't for the android app.
