### ISSUE TITLE
[IOS] Mediaplayback stops when opening Floccus

### ISSUE THREAD

**Issue by getwet** [floccusaddon/floccus#1210]
Hi,

I was wondering Spotify or VLC stops playing when I open Floccus on iOS.

Cheers and have a nice weekend

**Comment by marcelklehr** [comment]
Mh, this is curious. I have not idea why this happens.

**Comment by idunno101** [comment]
I also experienced this issue so I did some searching and I think I found the cause.

[This post](https://forum.ionicframework.com/t/background-sound-music-are-cancelled-after-opening-app-ios/229473) on the Ionic Forum hinted that the background-mode cordova plugin might be the cause.

There's a similar issue for the original plugin at https://github.com/katzer/cordova-plugin-background-mode/issues/481

In that issue they figured out that [this line](https://github.com/EinfachHans/cordova-plugin-advanced-background-mode/blob/d2df19303f66677e8d1bfbc873f5986c635b557a/src/ios/APPBackgroundMode.m#L176) needed to be added to _APPBackgroundMode.m_
```
withOptions:AVAudioSessionCategoryOptionMixWithOthers
```

So I guess a different fork of the background-mode plugin should be used. Or you could remove the plugin if you think it's not needed (like the person on the forum did).

**Comment by getwet** [comment]
> Hi,
> 
> I was wondering Spotify or VLC stops playing when I open Floccus on iOS.
> 
> Cheers and have a nice weekend

Now fixed with Floccus 5.0.2. 

Great work 👍
Many thanks.
