### ISSUE TITLE
Open tabs nextcloud sync creates extra folder when storing bookmarks

### ISSUE THREAD

**Issue by advait404** [floccusaddon/floccus#1214]
I am using nextcloud bookmarks to save my open tabs from kiwi and firefox. In both cases, I have specified the server folder as /firefox laptop and /kiwi browser respectively.

Everything works great, except that in nextcloud the bookmarks for the tabs are stored inside /firefox laptop/ /ABC.com

There is a blank folder generated inside the server specified folder, which is kinda annoying as it requires more clicks to navigate.

**Comment by marcelklehr** [comment]
Hey @advait404 

This is due to the fact that tabs can be in different windows. Every window gets its own folder. In the next release, these folders will be appropriately named to avoid confusion.

**Comment by advait404** [comment]
I see, thank you for the quick feedback.
