### ISSUE TITLE
Floccus doesn't fetch and sync Safaris bookmarks on iPhone

### ISSUE THREAD

**Issue by verlen64** [floccusaddon/floccus#1216]
### Which version of floccus are you using?

v4.16.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iOS 15.5

### What kind of WebDAV server are you using? (if relevant)

WebDAV Server on Synology NAS

### Describe the Bug

Floccus shows all bookmarks that come from my desktop Computer in its proprietary Bookmark list and syncs them to Safari, so I am able to open them in Safari. Safari even shows the synced bookmarks in the same list as bookmarks I collected with my iPhone. But none of the latter appear in Floccus' proprietary list and or are synced to bookmarks.xbel, although I chose merging as sync strategy.

### Expected Behavior

Floccus should sync all bookmarks that I collected with Safari 

### To Reproduce

1 Installation
2 Sync 

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @verlen64 

> and syncs them to Safari

I am not aware of possible syncing with safari at the moment. The floccus iOS app is not intended to sync your iOS Safari bookmarks. You can only open links in Safari but not sync with safari. This is a limitation from Apple. The only things I can offer as a way to mitigate is bookmarks import into the iOS app from your browser and sharing links from your browser to floccus. But other than that nothing more seems possible.

**Comment by joshuabeny1999** [comment]
Why there is such limitation? Safari on iOS supports since iOS15 extensions?

**Comment by marcelklehr** [comment]
The relevant problem is web extension compatibility, especially bookmarks API compatibility: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks#browser_compatibility

It may be possible to integrate with Safari today, but it's more work than would be necessary if Safari supported the same APIs other browsers support, which I hope will be soon.
