### ISSUE TITLE
Sync with file or directory. 

### ISSUE THREAD

**Issue by dot-bob** [floccusaddon/floccus#1217]
### Describe the feature you'd like to request

It would be useful to have the option to sync bookmarks with a file like a sqlite database, or a directory.  This way bookmarks could be placed on typical file server , NAS,  or cloud service like Onedrive or Dropbox.

The directory option could help for cloud services that are slow to detect changes and resolve conflicts.

**Comment by marcelklehr** [comment]
Hi @dot-bob 

As web extensions are not allowed to write to the file system, the only way currently is via [LoFloccus](https://github.com/TCB13/LoFloccus/)
