### ISSUE TITLE
iOS won't sync

### ISSUE THREAD

**Issue by radiochild577** [floccusaddon/floccus#1218]
### Which version of floccus are you using?

latest/4.16.0

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iPhone 11 Pro on iOS 15.5

### Which version of Nextcloud Bookmarks are you using? (if relevant)

v10.5.1

### Which version of Nextcloud? (if relevant)

v24

### Describe the Bug

floccus iOS app will not sync my bookmarks. Works fine from any other OS/browser, just not the iOS app. The first version of iOS app would sync, but revert updates fail to sync. 

I've tried removing the account and re-adding, deleting and downloading the app again to start from scratch, but nothing will get the app to sync from my iPhone. The iOS app logs are completely empty when I try to inspect for clues, and the only info I get as to what prevented the sync from occurring is "E017: Network error: Check your network connection and your account details".

### Expected Behavior

To download my existing bookmarks on the initial sync, but it falls every time

### To Reproduce

Download iOS app, login to server and sync

### Debug log provided

- [ ] I have provided a debug log file

**Comment by radiochild577** [comment]
Still can't use floccus on iOS due to this issue. All I the only one?

**Comment by basement-cacophonist** [comment]
You're not the only one. Same issue for me. iPhone 13 Pro on the latest OS. Trying to use WebDAV with the same credentials that work perfectly on desktop Firefox and it never syncs. Log is completely empty.

**Comment by momor10** [comment]
i have the same problem, but i am using a self hosted nextcloud (truenas).  I can sync with the browser addons. But the ios app will give me an E017 and empty logs.

**Comment by basement-cacophonist** [comment]
> i have the same problem, but i am using a self hosted nextcloud (truenas). I can sync with the browser addons. But the ios app will give me an E017 and empty logs.

I'm not sure what changed for me, but after I posted about the issue, the iOS app synced all my bookmarks from the WebDAV server successfully the next day.

**Comment by RyanVerhey** [comment]
I am still having this issue, on iPadOS, with Nextcloud Bookmarks.

**Comment by marcelklehr** [comment]
I've just managed to install MacOS and run a simulator, I'm happy to say that in the current development version sync seems to be working :tada:

**Comment by jrnovak** [comment]
I am having the same issue.  Has there been any resolution?

**Comment by momor10** [comment]
i had this issue using the nextcloud app on truenas scale from the truecharts repository. I now switched to proxmox and am using nextcloud in a docker enviroment and ios is syncing without any issues.
