### ISSUE TITLE
iOS - Cannot Login to Google Drive

### ISSUE THREAD

**Issue by pinpontitit** [floccusaddon/floccus#1220]
### Which version of floccus are you using?

4.16

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

MacOS 12.4

### Describe the Bug

I tried running the iOS floccus app on my Macbook to check how it looks.

I downloaded Floccus on the apple store.

On the first screen the app asks to choose the way I want to sync my bookmarks
I choose to sync with Google Drive.

On the second screen that shows the option: Connect to Google Drive, I clicked on the blue button "Login with Google Drive".

And nothing happens. It's as if the button event wasn't returning anything.

I also tried, after downloading the github repo, running "gulp", etc, to build the app with Xcode.
The build worked.
I went through the same process described above.

And on the same screen (2) of the new account process, when I click on the Login with Google button, again nothing happens.

But Xcode console give me those errors each time I click on the button:
```
⚡️  To Native ->  OAuth2Client authenticate 111063102
ERROR MESSAGE:  {"errorMessage":"ERR_PARAM_NO_APP_ID","message":"ERR_PARAM_NO_APP_ID"}
⚡️  [error] - {"errorMessage":"ERR_PARAM_NO_APP_ID","message":"ERR_PARAM_NO_APP_ID"}
⚡️  [error] - [Vue warn]: Error in v-on handler (Promise/async): "Error: ERR_PARAM_NO_APP_ID"

found in

---> <VBtn>
       <VStepperContent>
         <VStepper>
           <VCard>
             <NewAccount> at src/ui/views/NewAccount.vue
               <VApp>
                 <NativeApp> at src/ui/NativeApp.vue
                   <Root>
⚡️  [error] - {"errorMessage":"ERR_PARAM_NO_APP_ID"}
```

The fact that it happens when I build myself but also with the apple store app makes me think its a bug on the iOS app.

But, as I cannot try on an Iphone, I wanted to know if it happens to someone else who uses an Iphone.

If you try creating an account with Google, does it work for you ?
@radiochild577
@getwet

Thanks

### Expected Behavior

When clicking on the button, it should open the google login page on my browser, as it does with the Android app.

### To Reproduce

Steps given above.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by getwet** [comment]
Sorry, I had no Bookmarks on Google Drive.

**Comment by radiochild577** [comment]
I sync with Nextcloud, big Google drive

**Comment by pinpontitit** [comment]
Thanks for the answers.
 Even if you don't use Google Drive, could you try just in Floccus clicking in the button Login with Google Drive (in the "Add an account" process), just to see if the button works for you ?

**Comment by radiochild577** [comment]
Just tried and the button did not work for me

**Comment by pinpontitit** [comment]
thanks :-)

**Comment by getwet** [comment]
I tired to login with Google Drive but it won't progress after klick "login with Google". It does nothing. I have to restart the app to come back to my bookmarks.

**Comment by marcelklehr** [comment]
I can confirm Google OAuth does not work yet on iOS.
