### ISSUE TITLE
[Android] Unwanted connections to Google auto fill service

### ISSUE THREAD

**Issue by rndhaz** [floccusaddon/floccus#1223]
### Which version of floccus are you using?

4.16

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 4.16

### Describe the Bug

When the app is started, it opens unwanted connections to `content-autofill.googleapis.com` on my phone. As you suspected in https://github.com/floccusaddon/floccus/discussions/962#discussioncomment-3222279 it really seems related to the Webview component that is used in the app.

A quick web search for that domain showed, that there are few similar reports for other apps. E.g. here https://www.kuketz-blog.de/lineageos-webview-bug-ungewollte-verbindungen-zu-content-autofill-googleapis-com/
However the phone, where this issue is observed, is a Samsung Galaxy S9+ with Android 10. Not rooted or modded in any way.

### Expected Behavior

Do not open unwanted and unneeded connections to Google services. Especially when option 'allow network usage" (for favicons, etc.) is not set.

### To Reproduce

Just start the app.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> Not rooted or modded in any way.

In that case floccus uses the system webview which seems to connect to google by default. I am not able to fix that.
