### ISSUE TITLE
[Android] Nextcloud login on Android skips 2FA prompt

### ISSUE THREAD

**Issue by beune** [floccusaddon/floccus#1230]
### Which version of floccus are you using?

4.16.0

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

4.16.0, Motorola g8 power

### Which version of Nextcloud Bookmarks are you using? (if relevant)

11.0.1

### Which version of Nextcloud? (if relevant)

24.0.3

### Describe the Bug

When trying to login to Nextcloud through the android app, after entering username and password, the 2FA prompt briefly shows up but the app moves on to finalizing the setup process. Therefore, the account is not properly authenticated and cannot sync.

### Expected Behavior

Being able to enter a Nextcloud 2FA code to successfully authenticate the user to the app

### To Reproduce

Login to nextcloud through the android app.

Enter server URL

Enter credentials and log in

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @beune 
thank you for your feedback! This issue [has been reported](https://github.com/floccusaddon/floccus/issues/1192) before and the good news is, it's already fixed in the code. All that's needed is a new release of the android app and you should be able to login with floccus without any hurdles :)

**Comment by beune** [comment]
Can you confirm the version in which this is fixed? I downloaded the latest version from F-Droid, but there is where the issue occurred.

**Comment by marcelklehr** [comment]
Sorry, I wasn't clear. The fix is not released yet.

**Comment by marcelklehr** [comment]
Update: Fix is released in [v4.17.0](https://github.com/floccusaddon/floccus/releases/tag/v4.17.0)
