### ISSUE TITLE
Support sharing from browsers using system webview

### ISSUE THREAD

**Issue by zhihang-yi** [floccusaddon/floccus#1233]
### Describe the feature you'd like to request

As you know, there are some browser do not have their own kernel, such as `Via` or `Xbrowser` and so on. They rely on the `Android System WebView` provided by the system to render web pages. 

Now, when sharing web pages with `floccus` through these browsers, the link obtained by floccus **is empty**.

### Describe the solution you'd like

I hope you adapt such non kernel browsers so that they can share web pages to floccus normally. Thank you!

### Describe alternatives you've considered

Periodically export HTML files and then import floccus

**Comment by Jan69** [comment]
I would say that the title is very confusing, perhaps better worded as "support sharing from browsers using system webview" or something?

**Comment by zhihang-yi** [comment]
> I would say that the title is very confusing, perhaps better worded as "support sharing from browsers using system webview" or something?

I think you are right. I've revised it！Thank you for your prompt.

**Comment by uGeek** [comment]
It happens with many applications, the same Android Firefox.

 The only browser that works fine for me is Chrome. 

I use different RSS (Feedme) readers and when I share with floccus this error also happens. The title of the article appears on the link line first and on the same line the https link. 

Perhaps a simple solution would be that when sharing, it would only leave the phrase https in the link line and the rest of the text would be passed to the title.

**Comment by marcelklehr** [comment]
> The title of the article appears on the link line first and on the same line the https link.

Can you share an example or make a screenshot?

**Comment by zhihang-yi** [comment]
> > The title of the article appears on the link line first and on the same line the https link.
> 
> Can you share an example or make a screenshot?

![Screenshot_2022-08-14-19-53-11-632_android.jpg](https://user-images.githubusercontent.com/84566015/184535635-8613e3b5-01e5-41e6-831f-d427e30bf154.jpg)
-  This is a page and I click the Share.

![IMG_20220814_195354.jpg](https://user-images.githubusercontent.com/84566015/184535666-d2522707-ffa4-481c-89e5-4ad565a30a1d.jpg)
-  The title is right, but the link is empty.

**Comment by marcelklehr** [comment]
Thank you. And the title field then also contains the URL?

**Comment by zhihang-yi** [comment]
> Thank you. And the title field then also contains the URL?

 Well... no. Just to have the title itself.
`GitHub: Where the world builds software · GitHub`

**Comment by uGeek** [comment]
https://tlgur.com/d/GVq9bpw8

https://tlgur.com/d/8DlP5bl8


I get the title first followed by the url, in the link line.


Whether in the Link or Title line, ideally floccus will filter the url that contains https or http and place it in the link line. The text that remains to the Title line

**Comment by uGeek** [comment]
> > > The title of the article appears on the link line first and on the same line the https link.
> > 
> > 
> > Can you share an example or make a screenshot?
> 
> ![Screenshot_2022-08-14-19-53-11-632_android.jpg](https://user-images.githubusercontent.com/84566015/184535635-8613e3b5-01e5-41e6-831f-d427e30bf154.jpg)
> 
> * This is a page and I click the Share.
> 
> ![IMG_20220814_195354.jpg](https://user-images.githubusercontent.com/84566015/184535666-d2522707-ffa4-481c-89e5-4ad565a30a1d.jpg)
> 
> * The title is right, but the link is empty.

scroll to the end of the line, because I get the title first followed by the link

**Comment by zhihang-yi** [comment]
> > > > The title of the article appears on the link line first and on the same line the https link.
> > > 
> > > 
> > > Can you share an example or make a screenshot?
> > 
> > 
> > ![Screenshot_2022-08-14-19-53-11-632_android.jpg](https://user-images.githubusercontent.com/84566015/184535635-8613e3b5-01e5-41e6-831f-d427e30bf154.jpg)
> > 
> > * This is a page and I click the Share.
> > 
> > ![IMG_20220814_195354.jpg](https://user-images.githubusercontent.com/84566015/184535666-d2522707-ffa4-481c-89e5-4ad565a30a1d.jpg)
> > 
> > * The title is right, but the link is empty.
> 
> scroll to the end of the line, because I get the title first followed by the link

![image](https://user-images.githubusercontent.com/84566015/184540346-e097e849-de57-4727-ae16-8e8a8a16cfe8.png)

**Comment by marcelklehr** [comment]
Man, android is so messed up sometimes. I'll come up with a fix, thank you for your feedback!
