### ISSUE TITLE
extension for mobile devices (especially firefox for android, but also a little bit better UI overall, on small screens)

### ISSUE THREAD

**Issue by Jan69** [floccusaddon/floccus#1235]
### Describe the feature you'd like to request

make the browser extension work on firefox for android, and enhance working on patched chrome, like kiwi browser (mostly UI rework, addon works perfectly with kiwi)

### Describe the solution you'd like

ability to use the browser extensions on mobile firefox (and chrome forks with extension support)

it's possible to test the extension using https://support.mozilla.org/en-US/kb/extended-add-support to install, and [about:debugging](about:debugging) to debug, with caveat that only published extensions on the addons store can be tested (possibly will change, and once the extention does work without errors, I bet it would get approved for the "works on android" section just fine).
so far I tried, and there's a bit of warnings in firefox's about:debugging, although it doesn't look too terribly bad, mostly just unexpected values...
adding google or nextcloud doesn't work simply because the addon settings has to be closed, to return to browser tabs (but it does open one in background, just by the time you reach it you've closed the set-up page, nullifying progress, if there's a way to set a persistant data, like a cookie, to save the current auth attempt, and resume later when returning from auth flow, it should work fine, I think?)
adding webdav just doesn't do anything after hitting the "add" button, neither does importing an account... (no change in UI, probably errors out)
as I'm not really a developer, I've no idea how tall of an order this is, but I would ***very* much** like to be able to use it on firefox, and from what I can see, mobile firefox *should* have most of the same APIs available, so I think it would be doable?

### Describe alternatives you've considered

using the plain normal app, which works decently enough, but doesn't sync mobile bookmarks, hence only half-useful...
would be really nice to be able to two-way sync bookmarks on mobile also, not having to rely on sharing to add links (especially since it's not perfect, e.g. #1233), and opening up a separate app to view links (because bookmarks would autocomplete, saving time)

**Comment by marcelklehr** [comment]
I understand the desire to have floccus run natively inside a browser. Unfortunately firefox for android does not support the necessary APIs for floccus to work. See #3
