### ISSUE TITLE
Sync on bookmark creation on Android app

### ISSUE THREAD

**Issue by plantroon** [floccusaddon/floccus#1238]
### Describe the feature you'd like to request

While I don't fully understand how often Floccus app syncs to the server, the other similar app Nextcloud Bookmarks syncs immediately on bookmark's creation. I prefer Floccus mainly for its folder support.

### Describe the solution you'd like

When bookmark is created, through share menu or otherwise, sync with the server immediately.

### Describe alternatives you've considered

Opening the app manually and syncing.

**Comment by marcelklehr** [comment]
Should be solved in the next release.
