### ISSUE TITLE
iOS: open floccus stops and blocks spotify music

### ISSUE THREAD

**Issue by Ansichtsritter** [floccusaddon/floccus#1239]
### Which version of floccus are you using?

4.17.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

 Ios: 15.6.1, 13 mini, firefox klar 103

### What kind of WebDAV server are you using? (if relevant)

Hetzner Storage Box

### Describe the Bug

As son as i open floccus, my music in Spotify stops, and can only started again if i close floccus. No browser or other app open at this time.

### Expected Behavior

I just want to listen my music while using floccus :)

### To Reproduce

Just use Spotify as normal and open floccus - i use Spotify in offline mode with downloaded music.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Should be fixed in the latest version.
