### ISSUE TITLE
ios status bar broken

### ISSUE THREAD

**Issue by hellojaccc** [floccusaddon/floccus#1241]
### Which version of floccus are you using?

4.17

### Sync method

Nextcloud Bookmarks

### Describe the Bug

![BC6D53DB-F430-4FF3-871A-7834B0860C69](https://user-images.githubusercontent.com/71537512/187075591-9797db0c-25fa-4143-b1ae-a8573bc655c4.png)

Status bar is white and can be scrolled down

### Expected Behavior

It should respect theme and cant be scrolled

### To Reproduce

Enable dark theme, portrait, iphone se2020 ios 15.5

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Should be fixed in the latest release.
