### ISSUE TITLE
E017: Network error: Check your network connection

### ISSUE THREAD

**Issue by protonandelectron** [floccusaddon/floccus#1248]
### Which version of floccus are you using?

4.17.0

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Andoird 10

### Describe the Bug

E017: Network error: Check your network connection...

constantly showing this message,
even after loging in and loging out
and clearing the app data didn't work either.

### Expected Behavior

should be able to show all the bookmarks but just showing error.

### To Reproduce

just opened the app and its there (the error).

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
This should be fixed in v4.17.1 which will be available via play and f-droid store soon

**Comment by zero77** [comment]
It looks like f-droid is now up to date but, the play store isn't.

**Comment by marcelklehr** [comment]
Yes, Google Play is being difficult atm, sadly...
