### ISSUE TITLE
Updating addon during sync leaves lock file in place

### ISSUE THREAD

**Issue by SlaveOfCats** [floccusaddon/floccus#1249]
### Which version of floccus are you using?

4.17.0, 4.17.1

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 101.0.1

### Which version of Nextcloud? (if relevant)

23.0.8

### What kind of WebDAV server are you using? (if relevant)

Nextcloud as a WebDAV server

### Describe the Bug

I started Firefox and manually checked for Add-on updates. There was a new version of floccus, so I clicked the Update button, but failed to notice that floccus was syncing my bookmarks at the same time. Afterward, the sync itself seemed fine, but the lock file was not deleted from the WebDAV server. When I opened one of my other Firefox installations, it started but never completed syncing.

In the end, I closed all instances of Firefox, manually deleted the lock file, and then restarted Firefox instances. All instances of Firefox were able to sync.

### Expected Behavior

When updating the add-on during a sync, I'd expect one of the following:

- delaying the update until after the sync is complete (maybe with a warning to the user)
- aborting the sync (including deleting the lock file) and restarting after the update

### To Reproduce

I can't reproduce this myself due to the dependence on having a new update to the add-on.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Yeah, interrupting sync runs often leaves a remnant lock file. In case of an update it may indeed possible to gracefully abort the sync run.

**Comment by SlaveOfCats** [comment]
Just to add a similar case that recently happened: I shut down Firefox while floccus was syncing and the lockfile was left behind. I deleted the lockfile when I noticed it (the next time I started FF), and all was well after that.

**Comment by marcelklehr** [comment]
Floccus should recover and ignore the lock file after a certain time, but avoiding remnant lock files altogether is near to impossible.
