### ISSUE TITLE
Can not log in to my nextcloud instance

### ISSUE THREAD

**Issue by akallabeth** [floccusaddon/floccus#1250]
### Which version of floccus are you using?

4.17.1 (F-Droid)

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

grapheneos (android 13) pro

### Which version of Nextcloud? (if relevant)

23.0.8.1

### Describe the Bug

When trying to log in to the nextcloud instance, the password is not accepted.

* Certificate is a valid Lets encrypt cert
* I use a custom `App-Password` which works fine (texted with other services by copy/paste)

### Expected Behavior

Credentials accepted, floccus working on my device

### To Reproduce

1. connect to nextcloud instance 
2. enter credentials (use a `App-Password` generated for the specific app)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Floccus uses Nextcloud's login flow which allows you to use your normal password and 2factor authentication when authenticating for floccus access. Can you try your normal credentials?

**Comment by akallabeth** [comment]
@marcelklehr sorry for the dealy,
also did not work.

Works for the nextcloud client and browser on the same device though.

FYI: Got 2FA set up with a yubikey or OTP tokens as second factor

**Comment by akallabeth** [comment]
Also of interest: Floccus from my firefox on debian (laptop) syncs to the same instance/account without any issues.

**Comment by b-m-f** [comment]
Hitting the same issue.

Logs from instance:
```
Exception: OC\Core\Service\LoginFlowV2Service::flowDoneWithAppPassword(): Argument #3 ($loginName) must be of type string, null given, called in /var/www/html/core/Controller/ClientFlowLoginV2Controller.php on line 227 in file '/var/www/html/core/Service/LoginFlowV2Service.php' line 189
```

**Comment by marcelklehr** [comment]
Sorry for the delay.

> also did not work.

@akallabeth What happened?

> Logs from instance:

@b-m-f That error looks like a server side issue. Logging in with login flow shouldn't trigger an exception.

**Comment by akallabeth** [comment]
@marcelklehr the credentials did not log me in, the page refreshed promted again

**Comment by marcelklehr** [comment]
> the credentials did not log me in, the page refreshed promted again

Sometimes you need to log in twice. Nextcloud has a bug regarding that

**Comment by akallabeth** [comment]
@marcelklehr does not work. did fix that by downgrading to an older version though (`v4.15.0`)

**Comment by akallabeth** [comment]
Nice catch indeed, but that does not resolve this issue (it also does not work with normal passwords except with the older version mentioned, where I can log in perfectly)

**Comment by mottech20** [comment]
@akallabeth I couldn't wait for the new release, so I just went and [edited](https://github.com/nextcloud/server/issues/33187#issuecomment-1179584560) the `ClientFlowLoginV2Controller.php` on my docker container. I was able to login with app password afterwards. Quiet easy if you have access to the instance.

**Comment by mottech20** [comment]
@marcelklehr Tangential but if the login could utilize Android's built-in accounts similar to what the Notes and Talk app do (using accounts registered from the main NC app), it would be ideal.

**Comment by ingelumer** [comment]
@mottech20 many thanks for your hint to edit the file directly in Docker. 
It brought me a step further, but actually to the next login issue.
For anyone running into same trouble where Nexrcloud authentication was not succeeding this might help you.

I found that using the Floccus app the login process referred to a http login page, so removed https.
When using the Chrome extension my login did not succeed after Zugriff gewähren.
This fix was solving the issue, run following command in your nextcloud docker instance: 
`docker exec -it -u www-data NAME_NEXTCLOUD_CONTAINER bash -c './occ config:system:set overwriteprotocol --value="https"'`
Source: https://help.nextcloud.com/t/zugriff-gewaehren-laedt-ohne-ende/46622/7

**Comment by marcelklehr** [comment]
> @marcelklehr Tangential but if the login could utilize Android's built-in accounts similar to what the Notes and Talk app do (using accounts registered from the main NC app), it would be ideal.

This is sadly not possible due to incompatible technologies used :/

**Comment by marcelklehr** [comment]
Closing this as a nextcloud setup issue.
