### ISSUE TITLE
WebDAV Syncing stuck

### ISSUE THREAD

**Issue by lschricke** [floccusaddon/floccus#1252]
### Which version of floccus are you using?

4.17.1

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 104.0.2 (64-bit)

### What kind of WebDAV server are you using? (if relevant)

The box.com webdav server

### Describe the Bug

Hello! 
First of all, I find this tool very useful, so many thanks to the authors!

The bug I'm experiencing is that the Syncing for my two folders seems to be stuck. It stays in "Syncing" mode until I cancel it. 

Here is the log file: 
```
2022-09-09T08:52:04.229Z Starting sync process for account xxxxxxxxxxxx@dav.box.com
2022-09-09T08:52:04.254Z onSyncStart: begin
2022-09-09T08:52:04.254Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:06.111Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:08.273Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:10.732Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:13.414Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:16.579Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:20.450Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:25.179Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:30.768Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:37.591Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:45.823Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:52:55.898Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:53:08.369Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:53:23.774Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:53:43.173Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:54:06.769Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:54:36.106Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:55:12.402Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:55:57.831Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:56:54.186Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:58:04.604Z https://dav.box.com/dav/my-bookmarks.xbel.lock
2022-09-09T08:58:58.493Z Syncing failed with E027: Sync process was interrupted
2022-09-09T08:58:58.497Z onSyncFail

```

### Expected Behavior

The syncing process finishes after some time.

### To Reproduce

Not sure if this issue is easily reproducible. Is it related to Firefox? To webdav and box.com service? To Floccus itself? To the lock file maybe?

Any help is appreciated.

Thanks and have good day!

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @lschricke 

Sorry for the delay. I'm busy with work nowadays, but thank you for taking the time to give feedback.
It appears that a recent sync run did not finish and left a remnant lock file. You may simply delete `my-bookmarks.xbel.lock` in your box.com files and sync should work again. Also see the last faq: https://floccus.org/faq/

**Comment by lschricke** [comment]
Hello @marcelklehr, thanks for your reply 👍. I did remove the lock files. Hopefully this will work fine! 
Cheers!

**Comment by lschricke** [comment]
Hello, it did not really work I think. In fact the lock files get re-created afterwards but are never deleted from the box.com account. Is this normal?

Thanks

**Comment by lschricke** [comment]
Hi @marcelklehr , 
In case it helps, here is a screenshot of the problematic lock file in the box.com account:

<img width="898" alt="Screenshot 2022-09-29 at 10 38 41" src="https://user-images.githubusercontent.com/3723626/192983688-fbe5824b-97ee-483f-bfbb-e58d0cacc2d9.png">

Do you have an idea of what might causing the issue here?

Cheers!
Lucas

**Comment by marcelklehr** [comment]
I don't seem to be able to reproduce this. In my experiments floccus continues with sync if the lock file is older than 15minutes :/

**Comment by marcelklehr** [comment]
Can you query the lock file using curl and check the headers maybe? Would be interesting to see if Last-Modified actually shows the correct value.

**Comment by jdelker** [comment]
Hey folks,

I'm also affected by this problem, but I suspect a different cause.
My Scenario: Floccus 4.17.1 with 2 "Nextcloud-Bookmarks Sync" shares on different folders.
Despite some early adopter bugs ;), this setup has operated fine for the last months/years.

Now, for quite some time, I also experience this "lock" on multiple devices (all Firefox).
From my recent observations I encounter this situation regularly (if not always?), when the particular Windows or Mac host is woke from hibernation, I notice that Floccus shows a current sync operation, but without anything happening.
In fact, it stays in that state basically **permanently**. How long this state persisted can be seen on the "Last synchronized" message, which not seldom shows "x days ago" - with a sync interval of 1h!

Since this situation does not recover automatically as I would conclude from your FAQ message about stale locks and the 30min lock override, I assume that this is not related to a lock file present on the server.

**Comment by jdelker** [comment]
I figured, that disabling/enabling the floccus extension does recover the problem!
Sync starts directly after that and completes successfully after roughly 1min.

**Comment by jdelker** [comment]
@marcelklehr: I see this is still tagged as "waiting for more information". Is there anything I can provide for this to continue?
If you believe, that I described a totally different scenario - for the same problem observation - let me know, and I open a new issue for that.

**Comment by jdelker** [comment]
Just an idea:
May it be possible that Floccus is just trapped within a WebDAV request, that - for what ever reason - did not receive a response and is now basically waiting forever due to a missing timeout? 
What logs or stack-dumps could I gather, to find out what Floccus is waiting for?

**Comment by marcelklehr** [comment]
> If you believe, that I described a totally different scenario

This would be the case, as WebDAV and Nextcloud Bookmarks have to different locking mechanisms.

**Comment by marcelklehr** [comment]
ping @lschricke

**Comment by jdelker** [comment]
FYI: I've created a new issue for the Nextcloud Bookmarks sync, due to it's possible different nature.
However, I still see a strong similarity. 
Despite my previous assumption, that this is more a "locked-client" thing, rather than a central lock-file issue, I have now evidence, that this is indeed related to a central locking problem on the server.

**Comment by marcelklehr** [comment]
When floccus appears to be hanging/stuck can you do the following to provide client-side logs while sync is running.

#### Firefox
* Go to `about:debugging`
* click on `debug` button next to floccus entry
* trigger a sync by clicking on `sync now` for the account of your choice.
* go back to the inspector window and copy the logs after waiting for the sync to finish

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* trigger a sync by clicking on `sync now` for the account of your choice
* go back to the inspector window and copy the logs after waiting for the sync to finish
