### ISSUE TITLE
Cant sign in because Google Authorization error

### ISSUE THREAD

**Issue by onehex** [floccusaddon/floccus#1253]
### Which version of floccus are you using?

4.17.1

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chromium

### Describe the Bug

Google Authorization error below
----
Authorisation Error
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
[Learn more](https://developers.google.com/identity/protocols/oauth2/policies#secure-response-handling)
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: https://fnaicdffflnofjppbagibeoednhnbjhg.ch40m1umapp.qjz9zk/

### Expected Behavior

should be able to sign in.

### To Reproduce

when trying to sign in with google drive.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
That's a weird redirect URI. Which version of chromium are you using?

**Comment by marcelklehr** [comment]
If you're using ungoogle chromium, see https://github.com/ungoogled-software/ungoogled-chromium/issues/1437

**Comment by protonandelectron** [comment]
Thanks I got it.
here's a workaround I found, don't know if you know it already.

you can just import the data and it will work in ungoggled chrome.
