### ISSUE TITLE
Issue 1237 is not fixed - at least not for me

### ISSUE THREAD

**Issue by thembuck** [floccusaddon/floccus#1254]
### Which version of floccus are you using?

4.17.1

### Sync method

Google Drive

### Describe the Bug

After selecting the account I get logged in and __google search__ opens. From there I can't get back to floccus app in a connected state.

4.17.1 form f- droid didn't change that behavior.

4.17.0  worked well on a different device (android 8) with a different google account. 

### Expected Behavior

Possibility to select the/a bookmark file on Google drive to sync.

### To Reproduce

...

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Let's continue in the original issue.
