### ISSUE TITLE
Android app does not start on LineageOS 13 (marshmallow 6.0.1)

### ISSUE THREAD

**Issue by cracket** [floccusaddon/floccus#1259]
### Which version of floccus are you using?

floccus-build-v4.17.1.apk 

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

6.0.1

### Describe the Bug

Did I miss something important for apk to run on Android?
I would expect some UI to show up after installation. 
I would expect some Android logs or errors in logcat 
minSdkVersion allows to install on Android 5.0 

any doc how to install/debug apk correctly?

### Expected Behavior

UI similar to shown in pictures of #861 

### To Reproduce

Install floccus-build-v4.17.1.apk from github releases (no kiwi browser installed)
Open application 
White screen with centered floccus logo shows up. 
Nothing else happens 

Lineage OS is without gms and google play. 

### Debug log provided

- [ ] I have provided a debug log file

**Comment by anirov** [comment]
Samsung, Android 8.0 too analog problem (v.4.17.0 & v.4.17.1)
version 4.16.0 work Ok.

**Comment by cracket** [comment]
Is there any hint or screenshot what should be visible after starting the app?
I'd like to clarify expected results, but I have no idea what should happend there.

**Comment by marcelklehr** [comment]
> version 4.16.0 work Ok.

huh, that's interesting. I'll investigate which change might have caused this

> Is there any hint or screenshot what should be visible after starting the app?

When starting the app for the first time you should see a splash screen with the floccus logo and afterwards a form allowing you to create a new account.

**Comment by degreeofcertainty** [comment]
Magisk/settings/configure deny list/add floccus

**Comment by marcelklehr** [comment]
> Magisk/settings/configure deny list/add floccus

What does this mean?

**Comment by marcelklehr** [comment]
Can you try this again with the latest version, please?
