### ISSUE TITLE
More human WebDAV configuration support

### ISSUE THREAD

**Issue by khinsen** [floccusaddon/floccus#1263]
### Describe the feature you'd like to request

WebDAV is an eternal source of frustration, and floccus is no exception. My first attempt to use floccus has been a failure so far because of "Could not connect to server: 500", with no explanation and no support for debugging, for a WebDAV account that works fine with several other clients. I'd love to get help from floccus to explore and fix the issue.

### Describe the solution you'd like

1) Better documentation. The user guide says "The URL should end with a slash" right after quoting an example that doesn't end with a slash. In the next sentence, it refers to a list of URLs, none of which end with a slash.
2) More lenient configuration. floccus could add a slash by itself if the URL doesn't have one. Or do the opposite, if that's what it takes.
3) Debugging aids:
  - Explanation of error messages
  - Suggestions of what's worth trying
  - As a last resort: show the JavaScript code that floccus uses to connect, to enable experiments in a JS console for those who know a bit of JS.

### Describe alternatives you've considered

Give up and use some other tool than floccus (sorry for the flippant reply, but since this is a required field, I had to come up with something).

**Comment by marcelklehr** [comment]
Thank you for your feedback. You've done exactly the right thing by coming here with your problem.

500 in this case means HTTP Status 500, so your HTTP server responds to a PROPFIND on the webdav URL you entered with a 500. I recommend checking your server log. The error message in this case is indeed a bit glib. I'll extend it to be more useful.

**Comment by khinsen** [comment]
Thanks for your reply, and for improving the error message!

Unfortunately, "check the server log" is a solution only for the server administrator. Not my case - I am a "mere" user on an owncloud instance run by my employer.

That said, knowing that the operation is PROFIND is potentially useful for debugging, so that should be in the floccus error message. But for me, PROPFIND works just fine when done with `curl`:
```
$ curl -X PROPFIND  -u <user>:<pass> <my-url>
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 07 Oct 2022 11:34:47 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype><d:quota-used-bytes>8646280100</d:quota-used-bytes><d:quota-available-bytes>98727902300</d:quota-available-bytes><d:getetag>&quot;63400ed77a413&quot;</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/webdav/Sync/</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 07 Oct 2022 06:49:18 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype><d:quota-used-bytes>3206412378</d:quota-used-bytes><d:quota-available-bytes>98727902300</d:quota-available-bytes><d:getetag>&quot;633fcbeeea349&quot;</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/webdav/floccus/</d:href><d:propstat><d:prop><d:getlastmodified>Thu, 06 Oct 2022 07:11:35 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype><d:quota-used-bytes>0</d:quota-used-bytes><d:quota-available-bytes>98727902300</d:quota-available-bytes><d:getetag>&quot;633e7fa776bf5&quot;</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/webdav/git-annex/</d:href><d:propstat><d:prop><d:getlastmodified>Tue, 05 Apr 2022 12:10:11 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype><d:quota-used-bytes>25176960</d:quota-used-bytes><d:quota-available-bytes>98727902300</d:quota-available-bytes><d:getetag>&quot;624c3239f3b89&quot;</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/webdav/zotero/</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 07 Oct 2022 11:34:47 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype><d:quota-used-bytes>5414690762</d:quota-used-bytes><d:quota-available-bytes>98727902300</d:quota-available-bytes><d:getetag>&quot;63400ed77a413&quot;</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>

So I guess it takes something more specific to get the error response.
```

**Comment by marcelklehr** [comment]
> But for me, PROPFIND works just fine when done with curl

Interesting! What is the status code here?

**Comment by marcelklehr** [comment]
Aah, in case you're using owncloud, I believe they have a bug where they cannot process `Origin: null`

**Comment by marcelklehr** [comment]
I should put that in the FAQ

**Comment by khinsen** [comment]
Status is '200 OK'.

If that's an owncloud issue, there is probably little I can do about this, other than look for another WebDAV server.

But I think it would be useful to have that piece of JS code somewhere in the documentation, to help others debug their WebDAV issues.

**Comment by khinsen** [comment]
Another test: my WebDAV server works fine with floccus on Android. Support for the hypothesis that it's owncloud not getting along well with Web extensions.
