### ISSUE TITLE
Floccus not synchronizing JavaScript bookmarklets to Brave

### ISSUE THREAD

**Issue by rogermccoy** [floccusaddon/floccus#1266]
### Which version of floccus are you using?

4.17.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave for Windows

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.1.0

### Which version of Nextcloud? (if relevant)

21.0.0

### Describe the Bug

I'm synchronizing numerous bookmarks between Chrome and Firefox using Floccus. When I tried synching to Brave, most bookmarks loaded, but JavaScript bookmarklets are all missing. (They have not been deleted elsewhere.)

I've since done a push in Chrome and a pull in Brave, but they still aren't showing up. 

### Expected Behavior

All bookmarks, including JavaScript bookmarklets, should synchronize.

### To Reproduce

Add JavaScript bookmarklets to synchronized bookmarks on Chrome/Firefox.
Sync using Floccus.
Sync to Brave. Other bookmarks are present; JavaScript bookmarklets are missing.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> Sync method Nextcloud Bookmarks
> JavaScript bookmarklets are missing.

Nextcloud Bookmarks does not currently support JavaScript bookmarks that's why they are not synced. As a workaround you may use webdav or Google Drive sync which support JavaScript bookmarks.
