### ISSUE TITLE
Login with Google account not working 

### ISSUE THREAD

**Issue by Else00** [floccusaddon/floccus#1267]
### Which version of floccus are you using?

4.17.1

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Version 106.0.5249.91 (Official Build, ungoogled-chromium) (64-bit)

### Describe the Bug

When I press the "LOGIN WITH GOOGLE" button I get this error.
By doing this from the iOS app, the Google account login worked.

![Screenshot 2022-10-13 085609](https://user-images.githubusercontent.com/48489849/195526252-ca10aa1f-61d0-4a8b-b798-2dfcbded5090.png)

### Expected Behavior

I would expect a working login like iOS

### To Reproduce

Install the floccus extension on ungoogled-chromium and try to login with the Google account

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @Else00 

This is a known issue with ungoogled-chromium. As a workaround you can import a floccus account from a different browser where Google Drive is setup already.
