### ISSUE TITLE
foccus for Android: Display full folder path

### ISSUE THREAD

**Issue by WebworkrNet** [floccusaddon/floccus#1268]
### Describe the feature you'd like to request

At the moment, the folders/subfolders in which a bookmark or folder is stored are not displayed.

### Describe the solution you'd like

Displaying the full folder path could help.

Who will benefit from it?
Anyone who has amassed numerous bookmarks and organized them in a folder structure.

### Describe alternatives you've considered

-

**Comment by dylandea** [comment]
You mean some breadcrumb at the top of the screen to indicate where we currently are ?
I also think it could be useful !

**Comment by WebworkrNet** [comment]
> You mean some breadcrumb at the top of the screen to indicate where we currently are ?
> I also think it could be useful !
> 
> EDIT: and maybe also when you edit a bookmark and you click on the folder selection menu, it could open directly all the tree until the current folder

Exactly 🙂

**Comment by WebworkrNet** [comment]
Do I have to do anything else as a user to see the breadcrumbs in the Floccus app (for Android)? Thanks

**Comment by dylandea** [comment]
It is working for me.
When I open the app, I click on a folder, and after entering this folder, the breadcrumb appears at the top.
Silly question but have you tried updating the app ?
