### ISSUE TITLE
[floccus for Android] Menu: Folder selection

### ISSUE THREAD

**Issue by WebworkrNet** [floccusaddon/floccus#1269]
### Which version of floccus are you using?

4.17.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Phone App, Samsung Galaxy A13 5G (SM-A136B/DSN), Android 12

### Describe the Bug

The "Folder selection" menu is not sorted alphabetically.

Instead, in my example, the last folder created is also shown last in the sequence.

### Expected Behavior

Regardless of any previous sorting, I would expect this menu to be basically alphabetical.

### To Reproduce

1. Alphabetical sorting is selected. 
2. A new folder is created. 

It will probably behave similarly with a bookmark, but I have not checked this. 

### Debug log provided

- [ ] I have provided a debug log file

**Comment by WebworkrNet** [comment]
![Screenshot_20221014-214012_floccus bookmark sync.jpg](https://user-images.githubusercontent.com/43509007/195933067-2ac01da1-b794-4e36-bd04-0682eca77cc4.jpg)

![Screenshot_20221014-213751_floccus bookmark sync.jpg](https://user-images.githubusercontent.com/43509007/195933084-4b4d70a7-8f27-4863-bc9f-38d3d36f6792.jpg)

**Comment by WebworkrNet** [comment]
Maybe related to #1251.

**Comment by WebworkrNet** [comment]
It looks as if the order of the folders corresponds to the time they were created. The last folder created is displayed last in the directory tree.

**Comment by dylandea** [comment]
Your solution would be that the folders on the "Folder slection" menu should be sorted the same way than the home screen ones ?
For example, if choosen "alphabetical", they should be alphabetical, if choosen by "Link", they should also be sorted by Link, etc ?

**Comment by frudolph77** [comment]
There is a workaround available, when you also use floccus for chrome. 
Sort the bookmarks alphabetical in bookmark manager of chrome and sync. 

But having the alphabetical sorting directly in the android app would be great.
