### ISSUE TITLE
iOS integrate with Safari via Extension

### ISSUE THREAD

**Issue by joshuabeny1999** [floccusaddon/floccus#1270]
### Describe the feature you'd like to request

Safari on iOS supports since iOS 15 Browser extensions. So it should be possible to integrate the Safari iOS Bookmarks with the app. 

### Describe the solution you'd like

Integration as Safari Extension

### Describe alternatives you've considered

There is none alternative.

**Comment by marcelklehr** [comment]
Please see #23
