### ISSUE TITLE
floccus not working with Huawei P8 Lite 2017

### ISSUE THREAD

**Issue by NHA-GH** [floccusaddon/floccus#1274]
### Which version of floccus are you using?

4.17.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave 1.20.208

### Which version of Nextcloud? (if relevant)

23.0.5

### Describe the Bug

when launching floccus for Android on smartphone Huawei P8 Lite 2017 (PRA-LX1), I have a blank screen and nothing happens. The app seems to freeze.
I only have the solution to force close it.
On a Huawei tablet T5 with the same Android 8 version, it works perfectly.

Can you help please ?

### Expected Behavior

the app should display the configuration steps to input the server name, login and password

### To Reproduce

- install floccus Android from GG play store
- launch it

### Debug log provided

- [ ] I have provided a debug log file

**Comment by NHA-GH** [comment]
Hello and thanks anirov !
I have found the 4.16 version on F-Droid : it seems to work ! Thanks really !

It's incredible that the 4.17 update version don't work at all on my Android 8 Huawei smartphone. 
And that same version works on my Huawei tablet with Android 8 too...

**Comment by marcelklehr** [comment]
This is a weird one. I'm going to enable logging in production with the next release so you we can debug this better.

**Comment by marcelklehr** [comment]
Can you try with the latest version, and if there are still problems, check the logs which should now be enabled?

**Comment by NHA-GH** [comment]
Hello, thanks for your help.
I have downloaded the last version 3.24 and I encounter the same problem.
I have a totally blank page when launching floccus on the Huawei P8 lite 2017 (PRA-LX1).
Nothing happens then, the only thing I can do is to quit the app.

Where can I find the logs please ?
Thanks. Best regards

**Comment by marcelklehr** [comment]
> 3.24

This is not the last version.

**Comment by NHA-GH** [comment]
Sorry... 
I have tried 4.19.1 version of floccus...
3.24 is the version number of nextcloud that I have updated yesterday too !

**Comment by marcelklehr** [comment]
> 3.24 is the version number of nextcloud

(Also rather unlikely...)

**Comment by NHA-GH** [comment]
I don't understand... 3.24.1 is the last version of nextcloud/Android see https://github.com/nextcloud/android

**Comment by NHA-GH** [comment]
can you tell me how to look at the logs please ?

**Comment by marcelklehr** [comment]
> nextcloud/Android

Ah, that makes sense, sorry.

> Where can I find the logs please ?

That would be the android logs. There's many ways to get them. You can try with adb: `adb logcat` if that doesn't work, google will help.

**Comment by NHA-GH** [comment]
Thanks, I will search how to look at the logs.
Best regards
