### ISSUE TITLE
iOS Safari Share / Sent to

### ISSUE THREAD

**Issue by jcarnat** [floccusaddon/floccus#1276]
### Describe the feature you'd like to request

Hi,

It would be great if an URL could be sent to Floccus using the Safari Share button.

### Describe the solution you'd like

Browse a web site using iOS Safari. Hit the « Share » button. Select Floccus. Enter a description and save. The bookmark is now saved.

### Describe alternatives you've considered

As for now, I have to use the « Share » button to « Copy URL ». Switch to Floccus. Click the « Add » favorite. Paste URL and enter details.

**Comment by SteffenAuer** [comment]
I agree, this would be great to have and really one of the main uses cases for me as well.
As it's already in `To Do` I assume there are plans to implement this, so I just wanted to give a quick and (not so) dirty workaround solution that makes this a little easier until it is added to the app itself:

Use the `Shortcuts` app on iOS (I would share the shortcut file directly but Apple won't let me w/out being signed into iCloud.. which I am not and don't want to).

1. Add `Copy to Clipboard` action. Tap on `Content` and select `Shortcut Input`. Then click on `Any` and only enable `URLs`. Tap on `Nowhere` and enable `Show in Share Sheet`.
2. Add `Open App` action and select `floccus` from the list.
3. Now give the shortcut a name and a nice icon
4. And voilà, you can now select the shortcut from the share menu in any browser and it'll open Floccus with the url from the website in the clipboard.
5. You can also re-arrange the items in the share sheet so this appears more at the top where it's quicker to reach.

<img src="https://user-images.githubusercontent.com/60623116/204521402-265ec972-f107-4bc1-822e-975efa83f2ef.jpg" width=250/> <img src="https://user-images.githubusercontent.com/60623116/204521391-019cdbc6-5e2e-4b3e-9021-e6726be5b946.jpg" width=250/> <img src="https://user-images.githubusercontent.com/60623116/204521378-2a6cc7ed-eba7-4029-89bf-4bffbe61a210.jpg" width=250/> 

Hope this helps someone.
