### ISSUE TITLE
Android App : Folders name aren't being updated on the android app, if they were changed on the browser.

### ISSUE THREAD

**Issue by dylandea** [floccusaddon/floccus#1281]
### Which version of floccus are you using?

4.17.1

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Samsung S10, Android 12

### Describe the Bug

While investigating for another issue, I noticed that my folders on the Android app have different names, than the same folders on my desktop browsers.

It seems that they keep their old names, while I had renamed them on the browser.

So I think that folder's name aren't updating correctly on the Android App..
I tested if the same thing happened with the bookmarks, but no, their names are correctly updated.

### Expected Behavior

When I rename a folder on browser, when syncing and merging on mobile it should rename the folder also.

### To Reproduce

Rename a folder in Firefox for example.
Sync with "Merge" behavior.
Go to the Android app, and sync with Merge behavior.
The folder keeps its old name.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Confirmed.
