### ISSUE TITLE
[Android] Add option to set focus to search field automatically when app opens

### ISSUE THREAD

**Issue by heapifyman** [floccusaddon/floccus#1282]
### Describe the feature you'd like to request

It would be nice to have an option that automatically sets the focus to the search field in the app-bar when I open the app on Android.

I usually open the app and then "search" for the bookmark I want to open in the browser by typing in a few characters.

The proposed option would spare me the extra tap to set focus in the search field.

### Describe the solution you'd like

The option could be added to the "Mobile settings" section. It could be named "Autofocus search field", for example:

* [x] set focus to search field when app is opened

### Describe alternatives you've considered

n/a

**Comment by marcelklehr** [comment]
I don't think this is worth having, sorry.
