### ISSUE TITLE
Instructions in "Setting up a dev environment" are not working

### ISSUE THREAD

**Issue by heapifyman** [floccusaddon/floccus#1284]
### Which version of floccus are you using?

4.17.1

### Sync method

Nextcloud Bookmarks

### Describe the Bug

Following the instructions in [Setting up a dev environment](https://github.com/floccusaddon/floccus#setting-up-a-dev-environment) results in an error when running `gulp`:

```
gulp: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
[1]    111467 IOT instruction (core dumped)  gulp
```

It appears to be this issue: https://github.com/laverdet/node-fibers/issues/451

Apparently, fibers is not compatible with node v16 or higher. See also https://github.com/laverdet/node-fibers#readme

### Expected Behavior

Running `gulp` should succeed.

### To Reproduce

1. Follow the instructions in [Setting up a dev environment](https://github.com/floccusaddon/floccus#setting-up-a-dev-environment)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by dylandea** [comment]
Yes I already spoke about that with the dev.
He asked me if I could rewrite the doc, but I always report.
I'll do it soon.

Could you try something and tell me if it works ?

Try using Node 14.17.0.

For more info check this [discussion](https://github.com/floccusaddon/floccus/discussions/1178).

If you get it to work, tell me also if using Node 14.17 was enough, or if you had to do something else that you read in the discussion I provided above (or something else you found online).

It would help me for writing the new steps on the README.md.
