### ISSUE TITLE
Nextcloud Syncing stuck

### ISSUE THREAD

**Issue by jdelker** [floccusaddon/floccus#1290]
### Which version of floccus are you using?

4.17.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox (different versions; different platforms (Mac & Windows))

### Which version of Nextcloud Bookmarks are you using? (if relevant)

11.0.4 (and earlier)

### Which version of Nextcloud? (if relevant)

25.0.1 (and earlier)

### Describe the Bug

This case is a variant of #1252, but with Nextcloud-Bookmarks being the sync endpoint.

From [my post in #1252](https://github.com/floccusaddon/floccus/issues/1252#issuecomment-1283740820):

> Now, for quite some time, I also experience this "lock" on multiple devices (all Firefox).
> From my recent observations I encounter this situation regularly (if not always?), when the particular Windows or Mac host is woke from hibernation, I notice that Floccus shows a current sync operation, but without anything happening.
> In fact, it stays in that state basically permanently. How long this state persisted can be seen on the others share "Last synchronized" message, which not seldom shows "x days ago" - with a configured sync interval of 1h!
> 
> Since this situation does not recover automatically as I would conclude from your FAQ message about stale locks and the 30min lock override, I assume that this is not related to a lock file present on the server.

### Expected Behavior

No sync deadlock.

### To Reproduce

I'm not sure how the initial deadlock happens.
As it appears, one of the participating floccus clients eventually sets a lock, but doesn't clear that afterwards.

One thing that can be reproduced quite easily is the dysfunction of the automatic lock-removal (after 30min):
- create a manual lock on the particular bookmark folder by setting a current timestamp via SQL:
  `UPDATE bookmarks_root_folders SET locked_time = NOW() WHERE bookmarks_root_folders.user_id = 'myusername'`
- after this no syncing is performed anymore (All HTTP requests for `POST /index.php/apps/bookmarks/public/rest/v2/lock` are returned with code 423).
- This state remains stable for hours. No client tries to break the lock with a `DELETE` request.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by jdelker** [comment]
For clarification: 
In #1252, I assumed that the issue may be related to the local foccus-client being somehow "stuck", rather than a problem with some central locking on the server. According to my latest observations, that doesn't hold true.

I monitored the HTTP-Requests on the Nextcloud-Server for requests to `/index.php/apps/bookmarks/public/rest/v2/lock`. When floccus is stuck, all requests result in code 423, which seems to indicate an active lock. And it stays this way for hours/days, if no action is taken.
When I disable/enable the floccus extension in the browser (Firefox). The lock is cleared after some minutes (successful DELETE request with code 200 is seen in the logs).

So, I would conclude that there are two problems:
1. lock recovery is not working correctly
2. floccus somehow get's into a situation, where a lock is set, but not cleared.

The combination of both results in a permanent stuck floccus client.

**Comment by marcelklehr** [comment]
> This state remains stable for hours.

I cannot reproduce this with my tests. After 30 minutes Nextcloud Bookmarks should unlock the lock automatically. If the lock persists beyond 30 minutes, it's because a client sync is still running. While syncing floccus writes the lock every two minutes to make sure it doesn't expire. So, your original intuition is probably correct: The problem is a sync client getting stuck in sync and sending a lock request every two minutes.

**Comment by marcelklehr** [comment]
Can you provide a log from when floccus is stuck after hibernation, so I can see what was the last executed action?

**Comment by jdelker** [comment]
Hi Marcel,
thanks for your response.

I monitored this in the past days to get a better understanding about what's happening here.
This are my findings (and please correct me anywhere, when this may not be plausible):
- Unlocking of the shared resource (here Nextcloud Bookmarks) can happen in two ways. Either the client performs an **explicit** unlock (DELETE on lock resource), or the server performs an **implicit** unlock, once it receives a (POST) lock request from the client and the active lock is older than 30min.
- From what I can see in the access.log on the Nextcloud server, the above seems generally functional. Every other half hour a lock request is returned with a "200", indicating an successful lock override.
- My previous statement ("_state remains stable for hours_") probably results from the fact, that the particular client is unable to fetch a free lock and thus remains in a blocked state for very long.
- While locked, I occasionally monitored the lock-timestamp written to NC's DB table. I could not see any 2-minute-increments, as indicated in your last post, but only found a static timestamp, which seems to be renewed every 30min.
- My assumption about hibernation is probably invalid, or at least not causal for the effect.

Given all of the above, it looks like the client(s) get(s) stuck while syncing, or take far too long for it (which it shouldn't, with the reasonable amount of bookmarks). The lock is then implicitly broken with the first lock attempt after 30min and the circle starts again.
Right now, there is too much noise in the logs, showing implicit and explicit locking actions for various floccus profiles.
My next step is to simplify that setup as much as possible and then gather the requested client logs.
If you have any other ideas from the above, let me know.

**Comment by marcelklehr** [comment]
> Right now, there is too much noise in the logs, showing implicit and explicit locking actions for various floccus profiles.

There should only ever be one account actively syncing, I think.

> I could not see any 2-minute-increments

Ah, with Nextcloud Bookmarks that's to be expected as the lock holds for 30mins if no DELETE comes in. So, floccus may try every 2mins but only after 30mins will it come through to relock, which might be cause for trouble, but that's probably unrelated and for a different ticket.

>  it looks like the client(s) get(s) stuck while syncing, or take far too long for it

Can you still look into the debug console when you experience a stuck sync? It would be really interesting what it's doing when it's stuck, as I currently cannot replicate this.

**Comment by jdelker** [comment]
Again, I've monitored this for several days now.
For **active** floccus clients, the general locking mechanism seems to work ok.
From monitoring the HTTP requests on the NC server, I can see clients request a lock (POST), sync and release it afterwards (DELETE). Any other client trying to sync at the same time, is unable to receive the lock (code 423) and retries after some wait. Even if a client didn't release the lock (due to shutdown, hibernation, whatever), the lock is auto-expiring after 30min and the next request is successful again.
So from that perspective, I would conclude that there is no locking issue involved here.

However, I still see stalled floccus clients, that show the "sync in progress" icon, but effectively doing nothing - for days!
I conclude this from the fact, that
- the NC server does not show any HTTP request from the client
- the next sync profile in the floccus popup shows a "Last synchronized" date, with "2 weeks ago".

I currently have a Browser in this state (Firefox on macos), so I tried to dump the logs from floccus.
To my surprise, the log ended with `2022-12-01T22:56:26.776Z Successfully ended sync process for account xxx@some.where`, which obviously just shows the last successful sync "2 weeks ago".
I assume, this log in of no use here.

@marcelklehr: Do you have any advise how to get more logging or find what makes floccus stall? Unfortunately, I've no way of reproducing this state deliberately, as floccus seems to work ok for a while after disabling/enabling the module again.

**Comment by jdelker** [comment]
Bot, please don't close ;)

**Comment by silopolis** [comment]
Looks like I'm having the same issue on a fresh NextCloud 27+ and Floccus in Firefox installed, all up to date.

```
curl 'https://******.org/nc/index.php/apps/bookmarks/public/rest/v2/lock' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0' -H 'Accept: */*' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Authorization: Basic c2ls****lsTw==' -H 'Origin: moz-extension://c0574878-ded3-4b7a-9ce7-49411a7d046e' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Content-Length: 0' -H 'TE: trailers'
{"status":"error","data":"Resource is already locked"}
```

**Comment by wonx** [comment]
I'm having the same issue here.

**Comment by marcelklehr** [comment]
As a quick workaround you can get syncing working again by issuing the following:

```
curl 'https://******.org/nc/index.php/apps/bookmarks/public/rest/v2/lock' -X DELETE ...
```

**Comment by marcelklehr** [comment]
Please also give your floccus version, this should be fixed in v5.0.5

**Comment by wonx** [comment]
Thank you. I figured out a workaround. When cancelling the sync two or three times it actually went a delete lock petition and the sync would retry. 

However, I believe the issue appears when I try to sync too many changes at the same time (e.g. deleting 100 bookmarks), and at some point the sync process times out. After trying a bunch of times it finally finishes. For some reason, it appears to affect Firefox more often than Chrome. 

I will try the new version. Let me know if you want me to run more tests.

**Comment by jdelker** [comment]
I consider this issue resolved.
Revisiting this with 5.0.10 does not show the problem anymore.
