### ISSUE TITLE
Allow changing name of accounts/profiles

### ISSUE THREAD

**Issue by infinity0** [floccusaddon/floccus#1294]
### Which version of floccus are you using?

4.17.1

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 12

### What kind of WebDAV server are you using? (if relevant)

N/A

### Describe the Bug

I am using multiple accounts with the same account details (user@host) but a different bookmark file. The Android UI only lists the user@host part of the account on the LHS sidebar, so all accounts look identical even though they are not.

Furthermore, this is the only UI to switch between accounts, so there is no way to disambiguate except by trial-and-error, and memorising the order of accounts.

### Expected Behavior

The browser UI includes the bookmark filename when displaying the list of accounts. The Android UI should do the same.

### To Reproduce

As described above.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by ojde** [comment]
It would be nice to be able to give a name to an account (user@host is fine as a default, though)

**Comment by G-Huber** [comment]
Would love to see this too. In the browser addon as well.

My usecase looks like this:

I'd like to access my bookmarks and tabs from all my devices (using FF exclusively), but don't want the currently opened tabs synced. So I put tabs of every device into one file and sync each of these to a separate bookmark folder on all the other devices.
Also bookmarks in the toolbar at home differ from those at work. Sadly FF bookmark management isn't as flexible as it used to be - the toolbar is a hardcoded folder, thus I can't just sync those as part of the bookmark-menu and select what to show in the toolbar locally.

As Floccus profiles only sync one folder hierarchy each I do have a lot of profiles (One for the bookmark-menu, one each for the toolbars - either private or work - and one for the tabs of every device. Currently totaling 7 profiles.)

While with the addon it's halfway clear what's what, to distinguish the two different toolbars I need to look at which file the profile syncs to. On Android though I've got a list of 7 identical user@server entries which gets quite confusing.

Happy to hear this is already being worked on :)

**Comment by marcelklehr** [comment]
Will ship with the next release
