### ISSUE TITLE
Refresh is triggered to easily and quickly

### ISSUE THREAD

**Issue by godfuture** [floccusaddon/floccus#1297]
### Which version of floccus are you using?

4.17.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 12 on Fairphone 3+ Witz lineageOS 19.1

### Which version of Nextcloud Bookmarks are you using? (if relevant)

currently latest

### Which version of Nextcloud? (if relevant)

24.0.7

### What kind of WebDAV server are you using? (if relevant)

Nextcloud 24 with booksmarks app.

### Describe the Bug

Scrolling up triggers the sync too easy. Mostly I hit the refresh even though I just wanted to scroll up.

### Expected Behavior

The UI should less sensitive to pull down when scrolling. The user should have a good control when to refresh and when not while scrolling the screen. Therefore it needs a certain area of tolerance where the user has to "overscroll" to make the refresh trigger.

### To Reproduce

Connect to server
Wait for first sync
Scroll till bottom
Try to scroll till top without triggering refresh

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
I tend to agree. It would be a nice feature, but implemented like this it's not cool

**Comment by godfuture** [comment]
> I tend to agree. It would be a nice feature, but implemented like this it's not cool

Exactly. Also for users with extend bookmark db size, the sync takes longer. In my case for internal LAN it only syncs with 2 MBits. Dont know why, but somehow there is a bottleneck. If I accidently hit refresh, I always have to wait for sync to finish.

Thanks for your quick help here.
