### ISSUE TITLE
Improve error message when creating a bookmark fails

### ISSUE THREAD

**Issue by Beres-Berlin** [floccusaddon/floccus#1300]
### Which version of floccus are you using?

4.17.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox Linux 78.15.0esr (64-Bit)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.5.1

### Which version of Nextcloud? (if relevant)

23.0.11

### Describe the Bug

The floccus Addon can't sync the local bookmarks with the Nextcloud server anymore. I don't know when this started, unfortunately. The nextcloud bookmarkd App is installed, of cource.

The following error message is displayed:

"E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data "

### Expected Behavior

The floccus Addon in Firefox should be able to synchronize the bookmarks.

### To Reproduce

Have a nextcloud server with the bookmarks app installed and active. Have bookmarks. Install floccus addon. Create nextcloud account in floccus. Try to synchronize.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank you for your feedback! In this case the error stems from a bookmark with a very long URL (if you scroll down in the log file you'll see the offending bookmark).

I'll try to improve the error message for this kind of error.

**Comment by Beres-Berlin** [comment]
Hi!

thanks a lot for your quick reply! Indeed, this particular bookmark (for anyone wondering: so something I drew on textpaint.net) broke the synchronization. But I'm not totally sure it was the length of the URL or the "second favicon" in the website's title. Anyhow, after deleting the long URL and the favicon the synchronization works again like a charm.
