### ISSUE TITLE
Floccus does not sync - E 17 and E20 messages, with several browsers

### ISSUE THREAD

**Issue by nolens** [floccusaddon/floccus#1305]
### Which version of floccus are you using?

4.17.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave, latest version (based on Chromium)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

11.04

### Which version of Nextcloud? (if relevant)

24.0.8

### Describe the Bug

When trying to sync, an "E17" Error messages is showing for each bookmark that us supposed to sync. 

Bookmark entries in Nextcloud bookmarks app do not show properly (folder names have synced, but bookmarks "inside" are showing like "ghost entries". Cannot be read, selected or deleted.

Steps tried to solve the problem:
- emptying all nextcloud database tables for bookmarks app has not helped
- manually delete bookmark entries in nextcloud does not work ( see above)
- Un-installing and re-installing the Chrome extension did not help
- deleting and re-establish account in floccus account several times - has not helped, either

The same thing happens in latest Firefox. 

if you need the logfile, please tell me where and how to upload. It contains sensitive data. 

### Expected Behavior

Bookmarks should upload / sync with Nextcloud bookmarks app 

### To Reproduce

normal standard procedure: 

- install bookmark extension in Brave
- setup account
- use sync buttom, "autosync" switched on

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
E017 Network error can happen if you have certificate problems with your server. E20 can happen when the server experiences an error.

> Bookmark entries in Nextcloud bookmarks app do not show properly (folder names have synced, but bookmarks "inside" are showing like "ghost entries"

Make sure your MySQL version is compatible with Nextcloud Bookmarks

**Comment by nolens** [comment]
> certificate problems with your server.

The various SSL check tools all say that the certificate is getting a A+ rating - so it seems to be okay. 
Also, other syncs (calendar, files, etc.) work flawlessly. 

> MySQL version is compatible

My managed hosting is using 5.7.40 . 

This seems to be the culprit?

**Comment by nolens** [comment]
After upgrading to MySQL 8.0x both problems are gone. 

Thanks @marcelklehr !!
