### ISSUE TITLE
Failed to map parentId

### ISSUE THREAD

**Issue by NeilJared** [floccusaddon/floccus#1306]
### Which version of floccus are you using?

4.17.1

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

 Android app, Poco X3 Pro running Miui 13.0.4 and Android 12 SKQ1.211006.001

### What kind of WebDAV server are you using? (if relevant)

Synology NAS official version, latest, currently is 2.4.4-10122. NAS is running DSM 7.1.1-42962 Update 3. I think Floccus stopped working since I updated to latest DSM OS, but was mandatory due to issues patched then

### Describe the Bug

My android app shows

Failed to map parentId: 170

And does not sync

### Expected Behavior

Should sync since nobody has modified anything in my system, but DSM version to latest

### To Reproduce

When press sync

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Mh, I don't seem to be able to suss out why this would happen. Is this still an issue with the latest version?

**Comment by NeilJared** [comment]
It is now working G, updated DSM to the latest "update 4" and works smooth again. I really do not why or the reason, but it works again

**Comment by marcelklehr** [comment]
Mh, then lets call it a fluke and close this :) If you run into any other problems, you know where to go :)

**Comment by marcelklehr** [comment]
Since this error keeps popping up, we're now discussing more strategies over here: https://github.com/floccusaddon/floccus/issues/2096
