### ISSUE TITLE
The Android app crashes

### ISSUE THREAD

**Issue by kalekad** [floccusaddon/floccus#1308]
### Which version of floccus are you using?

v4.18.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Samsung, LineageOS 19.1(Android 12L)

### Describe the Bug

application crashes when selecting a bookmark

### Expected Behavior

-

### To Reproduce

-

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> The application crashes when I select a bookmark, but the menu appears in which browser I want to open the bookmark, I select the browser and the bookmark is loaded.

**Comment by marcelklehr** [comment]
> When I reopen an already opened application in the background, I don't go back to the folder where I was, but the application loads the base folder.

I cannot reproduce this. For me it works.

**Comment by marcelklehr** [comment]
> In the browser, I share a bookmark to the app, the bookmark save menu appears, I don't save the bookmark, but I click the arrow in the top left corner, go back to the browser and back to Floccus, and the previously rejected bookmark shows up for saving.

I can only reproduce this when not tapping the back button in the save menu but switching to the browser directly and then resharing to floccus. I don't believe this can be fixed, though.

**Comment by technopagan** [comment]
+1'ing the crashing on Lineageos 19.1 + WebDav:

During account setup, the app constantly resets itself when losing focus (e.g. when I look up my WebDav password) so that I had to write everything down beforehand and do the account setup without changing app focus. 

After the WebDav account was finally set up, I tried importing an HTML bookmarks file. This also makes the app crash immediately.

**Comment by KevinCFechtel** [comment]
I experienced also the same behavior with resetting the app when loosing focus.
Also i can repeatly crash the app by adding a Bookmark with empty Link to the root folder.
The only way to get the app back working is to delete all data (which means i need to readd the account which is a paine with the resetting when losing focus bug).
I am using a Samsung Galaxy S20 FE with Android 13 patchlevel December 2022

**Comment by marcelklehr** [comment]
The only thing I can reproduce is the broken state after adding a bookmark without a link. I can fix that.

The crashing / resetting may be due to capacitor v4. Hopefully they have a fix for that

**Comment by marcelklehr** [comment]
Could you may try to get the log after a crash, if you have a bit of android experience?

**Comment by KevinCFechtel** [comment]
I will try to get the logs with logcat tomorrow.

**Comment by KevinCFechtel** [comment]
So, here are two log files. 
One with the crash after inserting an empty link (with starting the app in the broken state).
One with resetting the application when loosing focus.
Hope this helps.
[floccus_empty_link.log](https://github.com/floccusaddon/floccus/files/10371325/floccus_empty_link.log)
[floccus_loosing_focus.log](https://github.com/floccusaddon/floccus/files/10371326/floccus_loosing_focus.log)
