### ISSUE TITLE
Firefox dark theme

### ISSUE THREAD

**Issue by kalekad** [floccusaddon/floccus#1309]
### Which version of floccus are you using?

v4.18.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Tor Browser 12.0.1(Firefox 102.6esr)

### Describe the Bug

Floccus is light with a dark browser theme.

### Expected Behavior

Browser dark - Floccus dark
-switch - follow system, light, dark

### To Reproduce

-

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Floccus follows the browser UI as far as I understand. If you only set the website mode to dark and leave the browser UI bright, floccus will be bright.

**Comment by marcelklehr** [comment]
I can not reproduce this then. Maybe it's a problem with TOR browser. Have you tried with normal firefox?

**Comment by marcelklehr** [comment]
> Would it be possible to add a toggle- follow system, light, dark?

No, I'm sorry. I'm trying to limit the amount of options I add to the app
