### ISSUE TITLE
It can't select folder in floccus extension on iceraven

### ISSUE THREAD

**Issue by nolnolnolnol** [floccusaddon/floccus#1318]
### Which version of floccus are you using?

v4.18.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iceraven browser(1.19.0)    gecko  kernel version：108.0

### What kind of WebDAV server are you using? (if relevant)

webdav：
https://aki.teracloud.jp/dav/

### Describe the Bug

![IMG_20230110_222500](https://user-images.githubusercontent.com/27913929/211581781-395cfb15-4dd1-4c39-8a44-269cb6351f60.jpg)
In this step，it dosen't display any related bookmark folder of browser（include default folder and created folder）

### Expected Behavior

I hope it could display the default/created bookmark folder.

### To Reproduce

Please refer to the following screenshots
![Screenshot_2023-01-10-22-21-00-833_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/27913929/211584008-7c2744cc-3632-4c09-9477-4b0e1e04131b.jpg)
![IMG_20230110_225259](https://user-images.githubusercontent.com/27913929/211584086-efcb236f-f595-40e5-83c4-d00763c84ca0.jpg)
![Screenshot_2023-01-10-22-50-41-214_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/27913929/211584173-8778dae9-bde1-464b-bab9-e68571571824.jpg)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
mmh, I can't reproduce this with my Firefox, what's iceraven?

**Comment by nolnolnolnol** [comment]
sorry，I didn't add the title correctly
here is the link of  iceraven browser：
https://github.com/fork-maintainers/iceraven-browser/releases

thanks

**Comment by marcelklehr** [comment]
Thank you.

So, to cite the repo:

> The ability to attempt to install a much longer list of add-ons than Mozilla's Fenix version of Firefox accepts. Currently the browser queries [this AMO collection](https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/) Most of them will not work, because they depend on code that Mozilla is still working on writing in android-components, but you may attempt to install them. If you don't see an add-on you want, you can [request it](https://github.com/fork-maintainers/iceraven-browser/issues/new).

So, let's look if mozilla has implemented the bookmarks API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks#browser_compatibility

It has not. Thus it can't be used. Thus this is not a bug in floccus.
