### ISSUE TITLE
Failed to map parentId: 1097 Last synchronized: 1 day ago

### ISSUE THREAD

**Issue by dylantrevor87** [floccusaddon/floccus#1319]
### Which version of floccus are you using?

4.18

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

EDGE Version 108.0.1462.76 (Official build) (64-bit)

### Describe the Bug

I just clicked "push up" and it failed.
![floccus error](https://user-images.githubusercontent.com/103875977/211584088-2c3cbaab-e3f1-414a-8a56-0ab3e5a937cd.png)

Yesterday it synced correctly, but after last sync I had changed many bookmarks (like moved and deleted).
After these changes floccus is not working.

### Expected Behavior

complete the sync without errors.

### To Reproduce

Attached is redacted log.

[redacted-floccus-4.18.0-2023-01-10.log](https://github.com/floccusaddon/floccus/files/10383777/redacted-floccus-4.18.0-2023-01-10.log)

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank you for providing a debug log! This will hopefully be gone with the next release today

**Comment by dylantrevor87** [comment]
thanks!
