### ISSUE TITLE
Android app keeps crashing. Cannot complete setup process

### ISSUE THREAD

**Issue by legolasdimir** [floccusaddon/floccus#1322]
### Which version of floccus are you using?

4.18.0

### Sync method

Google Drive

### Describe the Bug

When attempting to set up Floccus on my android phone
(Android 13 
galaxy s22 plus
one ui 5.0)
 using Google drive, the app keeps crashing on different screens, it will not let me pick an import file. Sometimes it crashes when clicking the import button or when choosing a file or clicking login with google or any number of other random screens. Basically its intermittent and sometimes actions that would crash it don't. 

### Expected Behavior

The app does not crash and allows me to set up sync smoothly.

### To Reproduce

Download the app and try to open it and log in with google or import accounts. I am not able to test the other sync options as I do not have a next cloud instance or a webdav server

### Debug log provided

- [x] I have provided a debug log file

**Comment by legolasdimir** [comment]
uploaded a debug file. looking at f droid for a stable version

**Comment by legolasdimir** [comment]
the app works if i download version 4.17.1 from f-droid

**Comment by marcelklehr** [comment]
see #1308 Release is coming soon
