### ISSUE TITLE
Can not load Chinese

### ISSUE THREAD

**Issue by vate34** [floccusaddon/floccus#1325]
### Which version of floccus are you using?

4.18.1

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

 macOS and Windows 108.0.5359.125（Official Build, ungoogled-chromium） (arm64); Windows google chrome 108 shows the same error

### What kind of WebDAV server are you using? (if relevant)

self host

### Describe the Bug

can't load Chinese language ,show en locales for default, and throw errors in conlose:
```js
options.js:2 Error: Cannot find module '../../../dist/_locales/zh_CN.json'
    at n (options.js:2:2268214)
    at options.js:2:1822411
```
<img width="577" alt="image" src="https://user-images.githubusercontent.com/17670639/212797943-b876a341-648b-4383-bb54-bf64a0bc9941.png">

### Expected Behavior

Show Chinese Characters in user interface

### To Reproduce

open the extension in Chromium with Simple Chinese, all interface shows English Language by default which is expect for Chinese. And it shows warn message about "can't load zh_CN.json" if I press F12 for detail.
By the way, It shows Chinese correctly in Microsoft Edge which is in my pc.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by cng10001** [comment]
我在想会不会是浏览器内核太新了

**Comment by marcelklehr** [comment]
Fixed now.
