### ISSUE TITLE
"Failed to create the following bookmark on the server: [object Object]"

### ISSUE THREAD

**Issue by unficyp** [floccusaddon/floccus#1327]
### Which version of floccus are you using?

4.18.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chromium Version 109.0.5414.74 (Offizieller Build) Arch Linux (64-Bit)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.5.1

### Which version of Nextcloud? (if relevant)

Nextcloud Hub II (23.0.12)

### Describe the Bug

Syncing (merge) works except for one Entry:
https://www.youtube.com/watch?v=G75F6newMv8&ab_channel=Gronkh

error part of the logfile:
`     { type: 'REORDER',
       payload: 
        + #403[C++/QT] parentId: 1, hash: 0c5aca1276a5aa9715e869e2d2ba23a405f45d0ca8b74bbd5aebad86bce5c40a
        - #404[qtforum.de - Foren-Übersicht](https://www.qtforum.de/) parentId: 403
        - #405[Qt Centre Forum](https://www.qtcentre.org/forum.php) parentId: 403
        - #481[Modernes C++](https://www.modernescpp.com/) parentId: 403
        - #483[C++ (Cpp) Code Examples - HotExamples](https://cpp.hotexamples.com/) parentId: 403,
       order: [Object] } ] }
2023-01-20T10:36:07.604Z Checking failsafe: 0/387=0
2023-01-20T10:36:07.604Z (nextcloud-folders)CREATE     - #undefined[NIEMAND glaubt einem Kinderschläger! 🌳 MINECRAFT LiTW #401 - YouTube](https://www.youtube.com/watch?v=G75F6newMv8&ab_channel=Gronkh) parentId: 255
2023-01-20T10:36:08.291Z Syncing failed with E035: Failed to create the following bookmark on the server: [object Object]`

already tried to change the name,location or some parts of the url of the bookmark -> same error
uploaded log: floccus-4.18.1-2023-01-20.log

### Expected Behavior

No error

### To Reproduce

add the book mark to a folder in the bookmark bar, open floccus, press Sync now button.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
The problem is likely the emoji. You should also check the Nextcloud log for errors

**Comment by unficyp** [comment]
also thought that the emoji is the culprit  soi changed the name of the bookmark to "test" - but that does not solve the problem - guess thats not enough ?

nextcloud log shows:
`      "Exception":"OC\\DB\\Exceptions\\DbalException",
      "Message":"An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\x8C\\xB3 M...' for column `nextcloud`.`oc_bookmarks`.`description` at row 1",
      "Code":1366,`

**Comment by marcelklehr** [comment]
That error still points to the emoji. Is this without the emoji?

**Comment by unficyp** [comment]
This one is:
`        - #488[test](https://www.youtube.com/watch?v=G75F6newMv8&ab_channel=Gronkh) parentId: 1,
       order: [Object] } ] }
2023-01-20T12:07:47.418Z Checking failsafe: 0/388=0
2023-01-20T12:07:47.418Z (nextcloud-folders)CREATE     - #undefined[test](https://www.youtube.com/watch?v=G75F6newMv8&ab_channel=Gronkh) parentId: 249
2023-01-20T12:07:48.213Z Syncing failed with E035: Failed to create the following bookmark on the server: [object Object]`

strange: i went throuh the bookmaks logfile:

`         {
            "file":"/var/www/nextcloud/apps/bookmarks/lib/Service/BookmarkService.php",
            "line":151,
            "function":"_addBookmark",
            "class":"OCA\\Bookmarks\\Service\\BookmarkService",
            "type":"->",
            "args":[
               "gweber",
               "https://www.youtube.com/watch?v=G75F6newMv8&ab_channel=Gronkh",
               "test",
               **"🌳 MINECRAFT LITW: http://grnk.yt/litw🌳 ALLE LPs & Co: http://gronkh.video 🌳 NEUE RL-SKINS: http://gronkh.shop·············································...",**
               null,
               [
                  249
               ]
            ]
         },
         
         {
            "file":"/var/www/nextcloud/lib/private/DB/Connection.php",
            "line":270,
            "function":"executeStatement",
            "class":"Doctrine\\DBAL\\Connection",
            "type":"->",
            "args":[
                "INSERT INTO `oc_bookmarks` (`url`, `title`, `description`, `user_id`, `added`, `lastmodified`, `last_preview`, `clickcount`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)",
                [
                    "https://www.youtube.com/watch?v=G75F6newMv8&ab_channel=Gronkh",
                    "test",
                    **"🌳 MINECRAFT LITW: http://grnk.yt/litw🌳 ALLE LPs & Co: http://gronkh.video 🌳 NEUE RL-SKINS: http://gronkh.shop·············································...",**
                    "gweber",
                    1674216468,
                    "And 3 more entries, set log level to debug to see all entries"
                ],
                [
                    2,
                    2,
                    2,
                    2,
                    1,
                    "And 3 more entries, set log level to debug to see all entries"
                ]
            ]
        },`

where is this link coming from ? don't have that in other bookmarks

**Comment by marcelklehr** [comment]
The app is probably auto-populating the description from the URL you give it

**Comment by marcelklehr** [comment]
In any case, you should change your mysql collation: https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by unficyp** [comment]
closing. installed nc nexthub 25.x on a new server -> works now
