### ISSUE TITLE
Work Manager and/or JobScheduler to run periodic syncs instead of being constantly in the background

### ISSUE THREAD

**Issue by matejdro** [floccusaddon/floccus#1331]
### Which version of floccus are you using?

4.18

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 13, Pixel 7 Pro

### Which version of Nextcloud Bookmarks are you using? (if relevant)

12.0.0

### Which version of Nextcloud? (if relevant)

25.0.3

### Describe the Bug

After opening Floccus, this notification pops up and remains active, seemingly indefinitely:

![image](https://user-images.githubusercontent.com/507922/214608632-0017022c-f8a0-48b0-9423-07047ef6811d.png)

### Expected Behavior

Floccus should use Work Manager and/or JobScheduler to run periodic syncs instead of being constantly in the background. That would get rid of the notification.

### To Reproduce

1. Open the app
2. Sync at least once
3. Go back to home screen
4. Observe notifications.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
The next release will remove background mode.
