### ISSUE TITLE
Obtain title when the link is shared from YouTube/Spotify/YT Music

### ISSUE THREAD

**Issue by ChuZhenMok** [floccusaddon/floccus#1332]
### Describe the feature you'd like to request

Currently, when sharing a link from YouTube to floccus to save as a bookmark, the Title will be saved as "YouTube" as default.
Is it possible to obtain the title when pasting the link?
Thank you for the amazing app.

### Describe the solution you'd like

Is it possible to obtain the title when pasting the link?

### Describe alternatives you've considered

Maybe the title can be obtained after saving the bookmark also can.

**Comment by marcelklehr** [comment]
When the sharing app supplies a title, that is used. If not, we fetch it. Seems like in your case YouTube sets the title to "YouTube". So, nothing we can do. Sorry.

**Comment by mortee** [comment]
I mean, are customized solutions to getting the page title for certain enormously popular websites absolutely off the table? I find this issue with specifically Youtube really annoying too, and I'd love to have it solved somehow.

**Comment by marcelklehr** [comment]
> I mean, are customized solutions to getting the page title for certain enormously popular websites absolutely off the table?

Mmmh, I guess we can introduce an exception for Youtube

**Comment by mortee** [comment]
Wow, that would be awesome! I'm sure there's some quite primitive API that can provide the video title, given its ID.

**Comment by marcelklehr** [comment]
We can just make it use the fallback title fetcher which is used when no title is passed

**Comment by mortee** [comment]
I don't follow. Isn't the issue here that the "fallback title fetcher", which is invoked when no title is passed along the shared URI, only returns "YouTube" for YT links, because (I'm assuming) that's what the initial HTML response contains for the URI?

**Comment by marcelklehr** [comment]
My assessment [here](https://github.com/floccusaddon/floccus/issues/1332#issuecomment-1556128968) was that the YouTube app sends a title, but only sets it to "YouTube", so since the title is set, floccus assumes it's good and the fallback doesn't kick in.

**Comment by marcelklehr** [comment]
Just tested: The title tag in youtube's initial response contains the full video title as expected

**Comment by mortee** [comment]
Weird. When I share from my YT app into a text note, then the full video title is there, too. Where and how might this be diverted to the fixed "YouTube" string?

**Comment by GambaJo** [comment]
I have the same issue. I don't think, this is a general problem of the suplying app, because it works with the "original" bookmarks app for Nextcloud.
For example, when I visit a youtube page in my Android browser an click on "share" and choose the nextcloud bookmarks app, this app have the whole title of the youtube video and not only "Youtube".

I also tried this with sharing a link from NewPipe. Nextcloud bookmark app get the whole title, floccus only "Youtube".

**Comment by marcelklehr** [comment]
I found the issue. The user agent was to blame for the wrong title. With a neutral UA the title is obtained correctly :tada:
