### ISSUE TITLE
Can't sync on Brave or Firefox (Windows)

### ISSUE THREAD

**Issue by Onailimissam** [floccusaddon/floccus#1341]
### Which version of floccus are you using?

4.18.1

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave 1.48.167

### Describe the Bug

I simply can't sync with Brave, nor with Firefox. I deleted my account and created a new one. I connect to Google Drive without problems and set up a passphrase. Then the sync fails with error:

> E034: Bookmarks file is unreadable. Did you forget to set an encryption passphrase? Last synchronized: 0 seconds ago

even though there's no Bookmarks file in my Drive.

Here is the debug log:

> 2023-02-20T17:58:28.149Z Starting sync process for account Google Drive: bookmarks.xbel
> 2023-02-20T17:58:28.155Z onSyncStart: begin
> 2023-02-20T17:58:30.214Z Syncing failed with E034: Bookmarks file is unreadable. Did you forget to set an encryption passphrase?
> 2023-02-20T17:58:30.216Z onSyncFail

If I do not set up a passphrase, I get instead:

> E034: Bookmarks file is unreadable. Did you forget to set an encryption passphrase? Last synchronized: 0 seconds ago

with debug log:

> 2023-02-20T18:14:04.699Z Starting sync process for account Google Drive: bookmarks.xbel
> 2023-02-20T18:14:04.709Z onSyncStart: begin
> 2023-02-20T18:14:06.513Z Syncing failed with E034: Bookmarks file is unreadable. Did you forget to set an encryption passphrase?
> 2023-02-20T18:14:06.514Z onSyncFail

Note: it was working fine before the last update...

Also, on Firefox, connecting to my Google Account fails (without any explanation).

### Expected Behavior

It should sync. It was working fine until recently.

### To Reproduce

Just create a new account as decribed above.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
I cannot reproduce this. To fix this, you can try to remove the bookmarks file on GDrive and start a push sync in brave.
