### ISSUE TITLE
[Andoid] Remember sort order & sort folders first

### ISSUE THREAD

**Issue by DerSaxxe** [floccusaddon/floccus#1346]
### Which version of floccus are you using?

v4.18.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 11, Mi 9T and 9T Pro

### Which version of Nextcloud Bookmarks are you using? (if relevant)

v12.0.0

### Which version of Nextcloud? (if relevant)

v25.0.4

### Describe the Bug

1. App always starts with custom sort order even if select alphabetical and restart the app
2. In alphabetical order folders are within the bookmarks

### Expected Behavior

1. App should start with the last selected sort order
2. Folders should be at the top in alphabetical order like in Nextcloud bookmarks

### To Reproduce

First problem: Select alphapetical order and restart app
Second problem: Add a bookmark "A" and "C" and one folder "B", select alphabetical order

### Debug log provided

- [ ] I have provided a debug log file

**Comment by frudolph77** [comment]
I would suggest an other enhancement: add the possibility for **ascending**  sort order
