### ISSUE TITLE
Failed to map parentId: 95

### ISSUE THREAD

**Issue by Brodieman** [floccusaddon/floccus#1351]
### Which version of floccus are you using?

4.18.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 110.0.5481.178

### Which version of Nextcloud Bookmarks are you using? (if relevant)

11.0.4

### Which version of Nextcloud? (if relevant)

23.0.0

### Describe the Bug

Testing out Floccus.  Have the extension installed on Chrome and Vivaldi.  Extension is working on Vivaldi but Chrome will not sync or pull bookmarks down with error "Failed to map parentId: 95"

Log: 
[floccus-4.18.1-2023-03-09.log](https://github.com/floccusaddon/floccus/files/10935886/--redacted--)

### Expected Behavior

The bookmarks will sync

### To Reproduce

I try any form of a sync and I get this

### Debug log provided

- [X] I have provided a debug log file

**Comment by Brodieman** [comment]
You can close this.  I never tried to upload only merge or pull down.  I did an upload and it worked and seems to sync now

**Comment by Brodieman** [comment]
I did an upload and it worked, then the sync worked.  Now it's back to the error again

**Comment by Brodieman** [comment]
Now the parentId is 188

**Comment by marcelklehr** [comment]
@Brodieman The log file you uploaded contains all your bookmarks in plain text. I've removed the link for now for the benefit of your privacy.

**Comment by Brodieman** [comment]
Thank you

**Comment by marcelklehr** [comment]
Since this error keeps popping up, we're now discussing more strategies over here: https://github.com/floccusaddon/floccus/issues/2096
