### ISSUE TITLE
Support being a 'Share' target on iOS

### ISSUE THREAD

**Issue by slondr** [floccusaddon/floccus#1360]
### Describe the feature you'd like to request

Ability to share a link (website) into floccus using iOS's native share functionality.

Floccus iOS appears in the list of apps to share a link with, but when you select floccus and hit share, it just opens the app and does nothing with the link sent to it.

### Describe the solution you'd like

nextbookmark (a more full-featured, but unmaintained/dead Nextcloud Bookmarks client for iOS) handles shared links by inserting them directly as a bookmark into the default folder. That behavior would be awesome, but even just opening the new bookmark dialog with the shared link would be great.

### Describe alternatives you've considered

- Copying and pasting the link manually
- Switching back to nextbookmark

**Comment by marcelklehr** [comment]
Mh, that should work in v4.19

Can you try closing the app manually and then sharing to it? Maybe there's a bug there

**Comment by slondr** [comment]
The app being closed or open doesn't seem to change anything, I still just end up on the main bookmark list with no bookmark added either way

**Comment by marcelklehr** [comment]
mmh. I'll have to retest this then.

On an iPad I just randomly could get a hold of it wasn't even in the list of apps to share a link with. :/

**Comment by leftshine** [comment]
same bug with iOS 16.1

**Comment by raimerik** [comment]
Interestingly, 'share with' works almost reliably with Safari (~90%), but extremely unreliably (~5%) with Firefox (Standard+Klar versions)!
How come?
(iOS 16.4.1 / floccus 4.19)

**Comment by getwet** [comment]
Same to me. No problems with Safari, but no "save" dialog on Firefox. 
iOS version 16.4.1
Floccus version 4.19

**Comment by alexanderswerdlow** [comment]
Sharing from iOS in Safari seems to work for me (just downloaded, only tried a couple times, on iOS 17 Beta).

However, the desired solution (immediately saving a link to a default folder) originally requested would make things a lot more usable. The primary reason I chose foccus is the native browser integration so I don't need to think about opening a second app. It would be great it if this was an option (perhaps an iOS action) that doesn't require opening the floccus app and simply adds the link to a folder (e.g., just like "Add to reading list" works in Safari)

**Comment by MinamiHasaki** [comment]
iOS version 16.1 20B82)
Floccus version 4.19.0

I'm missing a "Share" or "Send To" option completely in Safari and Chrome.

**Comment by marcelklehr** [comment]
This should be fixed in the next release.

**Comment by getwet** [comment]
> I've got no problems with Safari, but no "save" dialog on Firefox. 
> iOS version 16.4.1(a)
> Floccus version 4.19
> Firefox version 112.2
> Firefox Klar version 112.0

With Floccus Version 5.02 now works on Firefox Standard and klar.

Great work. 👍
Many thanks
