### ISSUE TITLE
Suggestion : control to set syncing priority

### ISSUE THREAD

**Issue by DeirdreYoung** [floccusaddon/floccus#1369]
### Describe the feature you'd like to request

I'd love a way to set priority of syncing high or low. Right now I am guessing that if the dialog is open, priority is high.

### Describe the solution you'd like

A high-low control.

### Describe alternatives you've considered

A high-low control.

**Comment by marcelklehr** [comment]
Hello.

So what would the priority influence?

**Comment by DeirdreYoung** [comment]
Never mind - I tried to sync a very large number of bookmarks in Firefox and Floccus just wouldn't stop. I ended up making just one shared folder - to my little Nextcloud server, I'm proud to say! - and it works great.
