### ISSUE TITLE
Add a way to sync database offline

### ISSUE THREAD

**Issue by not-programmer98** [floccusaddon/floccus#1370]
### Describe the feature you'd like to request

I hope you add a way for syncing bookmarks offline using for example syncthing without any cloud option 

### Describe the solution you'd like

Local database and let the user sync it with the way he likes

### Describe alternatives you've considered

KeePass a famous password manager have that feature and I'm using syncthing to sync it's database

**Comment by marcelklehr** [comment]
Floccus itself sadly cannot access the file system from the browser, but you can use LoFloccus to sync to a file on your computer
