### ISSUE TITLE
Bookmarks containing bookmarklet code are not getting stored

### ISSUE THREAD

**Issue by godfuture** [floccusaddon/floccus#1371]
### Which version of floccus are you using?

4.19.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 111.0.1

### Which version of Nextcloud Bookmarks are you using? (if relevant)

12.1.0

### Which version of Nextcloud? (if relevant)

25.0.4

### Describe the Bug

In Nextcloud community I found a nice way to add a bookmarks to server directly. There is one bookmark that has code like:
`javascript:(function(){var a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('https://nextcloud.braendlin.dedyn.io/apps/bookmarks/bookmarklet?url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.screenX||a.screenLeft)+10)+',top='+((a.screenY||a.screenTop)+10)+',height=650px,width=550px,resizable=1,alwaysRaised=1');a.setTimeout(function(){d.focus()},300);})();`

When you press this bookmark, a dialog appears to enter a bookmark. These bookmarks are not getting synced by floccus. I have other bookmarks of such kind for other platforms.

### Expected Behavior

These bookmarks are getting synced like any other "normal" URI based bookmarks.

### To Reproduce

1. Add a bookmark with the following address to browser (name it as you wish): `javascript:(function(){var a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('https://nextcloud.braendlin.dedyn.io/apps/bookmarks/bookmarklet?url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.screenX||a.screenLeft)+10)+',top='+((a.screenY||a.screenTop)+10)+',height=650px,width=550px,resizable=1,alwaysRaised=1');a.setTimeout(function(){d.focus()},300);})();`
2. Run the floccus sync.
3. Check if the bookmark exists on server.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
This is a javascript bookmark. Nextcloud Bookmarks only supports http bookmarks at the moment.
