### ISSUE TITLE
Cannot install on Opera

### ISSUE THREAD

**Issue by aith85** [floccusaddon/floccus#1372]
### Which version of floccus are you using?

latest

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Opera 97.0.4719.63 win64

### Describe the Bug

Chrome Floccus extension is not installing on Opera browser (win64), giving a "cannot decompress the extension" error.

### Expected Behavior

As far as I understand, I should be able to install Floccus chrome extension on Opera, just like I did with other chrome extensions.
However, it keeps giving me an error after downloading.
"Cannot decompress the extension"

https://chrome.google.com/webstore/detail/floccus-bookmarks-sync/fnaicdffflnofjppbagibeoednhnbjhg
https://imgur.com/a/QhSJ8IL

I'm getting this error since several months so it's not this one Opera version but at least 6 months, maybe 1y.

### To Reproduce

Open Opera browser (win64), go to floccus chrome extension page, try to install.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> "cannot decompress the extension"

Well, then we have to remove opera support on the website I suppose. If opera uses the chrome webstore but cannot install floccus from the chrome webstore, that's a bug in opera.
