### ISSUE TITLE
floccus stops auto-sync after some time on Chromium, FF and Android app keep working

### ISSUE THREAD

**Issue by spi43984** [floccusaddon/floccus#1378]
### Which version of floccus are you using?

4.19.1 on Linux Ubuntu 20.04 and 22.04

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chromium 112.0.5615.165, Firefox 112.0.1

### Which version of Nextcloud Bookmarks are you using? (if relevant)

12.1.0

### Which version of Nextcloud? (if relevant)

25.0.4

### Describe the Bug

Firefox is configured to sync bookmarks with Nextcloud Bookmarks with the help of floccus. Android floccus app is also configured to sync the same.

Floccus is also installed on Chromium to sync these bookmarks. As the folders for bookmarks and the bookmarks bar differ in Firefox and Chromium, in Chromium two sync jobs were configured - one for the bookmarks bar and a 2nd one for the general bookmarks (with different server/local folders). Both profiles had their own Nextcloud token for authentication. Syncing works.

But after some time floccus in Chromium stops syncing and is complaining about network issues. Network works and floccus as Android app and in Firefox also still work, so can't be a network issue, maybe a temporary issue after waking up notebook from suspend mode.

To narrow that down one sync job (for the bookmark bar) was removed to just go with a sync of the general bookmarks. But still after some time the auto-sync stops working in Chromium and complains about network issues.

The log just doesn't show anything, only the last successful sync but nothing further.

### Expected Behavior

auto-sync keeps working in Chromium

### To Reproduce

set up auto-sync in Chromium with a dedicated server/local folder (not default)
keep syncing every 30 minutes

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Network issues are pretty self-explanatory. I'm not sure how I can help you with this. If it works with Firefox and the same configuration, then it may be a browser issue and nothing I can do in floccus to fix this.

**Comment by spi43984** [comment]
Well, there are no network issues at that time. It could be browser related and that's exactly what I am saying. As floccus is a browser add-on I thought you might be interested to hear that. I can dig into that if you point me into the right direction - as said the plain log files show nothing, floccus just stops working and the icon in the tool bar is crossed out.

**Comment by marcelklehr** [comment]
You can try going into about:extensions, enable developer mode and inspect the floccus background page.

**Comment by spi43984** [comment]
> You can try going into about:extensions, enable developer mode and inspect the floccus background page.

Will do. Are there extensions floccus might have an issue with? Like Tab Suspender (https://chrome.google.com/webstore/detail/tab-suspender/fiabciakcmgepblmdkmemdbbkilneeeh)?

**Comment by spi43984** [comment]
Ok, I got the error again. In floccus background page I see net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED errors. That happened after Chromium crashed and I restarted Chromium.

The nextcloud server accepts client certificates, but for nextcloud none are needed. Floccus on Firefox works without any issues after Firefox being restarted. Only on Chromium floccus stops syncing.

**Comment by spi43984** [comment]
Added a AutoSelectCertificateForUrls managed policy for Chromium - haven't seen any client cert errors yet...
