### ISSUE TITLE
Allow syncing to the file system

### ISSUE THREAD

**Issue by martin-braun** [floccusaddon/floccus#1384]
### Describe the feature you'd like to request

I use Syncthing and I love it, because it removes the necessity to host my files in a cloud and with more than one device I can't lose my data in an unfortunate event, so long my devices are not in the same place. Additionally, if I need more access to my files, I still can choose to host Syncthing on a server in the future without any change on my clients. I love it, I don't want to use any other cloud storage.

### Describe the solution you'd like

Allow the apps to sync bookmarks to the file system. For desktop there could be daemon that does this, since extensions can't access the file system. Or maybe it was possible to interact with Syncthing itself, but it would open other file cloud sync services if floccus could read/write to the local file system. It could organize the bookmarks as files in the same way like it is portrait in the bookmark manager (1 file = 1 bookmark), this would make things fail-proof towards collisions. If there are conflicts between two bookmarks, the sync software itself will handle the conflict by its own policy, i.e. Syncthing will make a copy of the older file with a different name.

### Describe alternatives you've considered

I was looking for a light-weight WebDAV cloud service for self-hosting and comes with good encryption. I think nextCloud is too overkill for something like that. Maybe there are better ways to achieve what I want?

**Comment by marcelklehr** [comment]
See https://github.com/TCB13/LoFloccus/

**Comment by martin-braun** [comment]
@marcelklehr Thank you, that should solve it. 👍
