### ISSUE TITLE
Exception after importing synchronized HTML directly into the browser

### ISSUE THREAD

**Issue by sun2ot** [floccusaddon/floccus#1385]
### Describe the feature you'd like to request

My bookmark structure contains multiple layers of folders. When I chose `HTML` as the synchronization format, everything was fine. Any browser with Floccus installed can synchronize normally and the directory hierarchy is correct.

But if I download the `HTML` file from `WebDAV` locally and import it into the browser as a file, the directory hierarchy of the bookmark will be lost. **_All bookmarks are in the root directory. No any folder._**

I'm not sure if this is a bug or a feature. Hope to your reply. Thank you.

### Describe the solution you'd like

- Down load the HTML file from WebDAV
- Import the file to browsers
- The bookmarks' structure is correct. With root folders and sub folders.

### Describe alternatives you've considered

Manually export bookmarks file from one browsers and import to another.

**Comment by marcelklehr** [comment]
> import it into the browser as a file

Which browsers have you tried?

**Comment by sun2ot** [comment]
> Which browsers have you tried?

The Android mobile browser such as `Kiwi`, and Windows borwser such `Chrome`.

**Comment by marcelklehr** [comment]
Mh, I can confirm this. The problem is that there's not really a standard for this at all, it seems.

**Comment by marcelklehr** [comment]
fixed with https://github.com/floccusaddon/floccus/pull/1396
