### ISSUE TITLE
Please add an option to update upon opening the browser.

### ISSUE THREAD

**Issue by dasu88** [floccusaddon/floccus#1392]
### Describe the feature you'd like to request

Please add an option to update upon opening the browser.

### Describe the solution you'd like

There is a high chance that I made changes to my bookmarks during the update but closed the browser before it finished updating. If the update can be executed upon the first opening, without waiting for its scheduled execution, it will ensure consistency.

### Describe alternatives you've considered

Manually execute.

**Comment by marcelklehr** [comment]
Good idea. Previously I disabled this because it could cause dataloss, but now we have a better way to prevent dataloss anyway.
