### ISSUE TITLE
Encryption not active when set up during account creation

### ISSUE THREAD

**Issue by eljoest** [floccusaddon/floccus#1398]
### Which version of floccus are you using?

4.19.1 (F-Droid)

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 11 (OnePlus)

### Describe the Bug

After the initial setup of the account including an encryption password, I discovered that the file saved to Google Drive was not encrypted.

The configured password was exported (in plain text) when I chose to export the account settings just before checking the upload file.

Afterwards I discovered that the "Passphrase" section in the settings showed an add button. After adding the password again through this button, the uploaded file is encrypted.

### Expected Behavior

Encryption configured during account setup is active at once.

### To Reproduce

* On a fresh install
* create a new account with Google Drive sync
* leave all settings at their defaults
* enter an encryption password
* complete the account creation
* add some bookmarks
* export the settings to confirm the encryption password is present
* force sync
* check google drive file

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Confirmed also for browser usage.
