### ISSUE TITLE
iOS App not available.

### ISSUE THREAD

**Issue by saiworksandbox** [floccusaddon/floccus#1402]
### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Floccus iOS

### Describe the Bug

It looks like the app is no longer available on the iOS app store. https://apps.apple.com/us/app/floccus/id1626998357 this is the download link on the website. If i search for the app on the app store it does not exist.
I have tried the link with a bunch of regions/countries by changing the "us" part to "in", "de" etc. The webpage just says connecting...

### Expected Behavior

It would be great if the app was made available again 👍 hopefully available in India too 🙏 and thank you for this great app 🤝

### To Reproduce

Open this link from any region https://apps.apple.com/us/app/floccus/id1626998357

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
I can confirm. I have opted to not pay the $100 fee for another year of app store availability since third-party app stores are said to be around the corner.

**Comment by Tewelus** [comment]
Is there a recommendation of an alternativ App Store? I never heard about that, searching gave me some names, but where is floccus to find? I don’t want to install all this stuff and then my device break. I would pay for the app if it is listed in the official store, I think other people agree. Thank you for your work so far.

**Comment by marcelklehr** [comment]
Thank you for weighing in @Tewelus. I think making it a paid app is a good way forward. Especially since the iOS version is not that popular yet and alternative app stores do not seem as around the corner as I thought :D
So far ~100 people have installed it on iOS so I've set the price to $0.99. It should be back online now. Have fun syncing :blue_heart:

**Comment by Tewelus** [comment]
Thank you very much. Hope everything will work with the purchase. It told me, the update is for free, because I already have a previous version. Is that intentional? Better you check that 😉 Otherwise give me your PayPal, I appreciate your work very much.
