### ISSUE TITLE
E019 when trying to sync with Radicale WebDAV server

### ISSUE THREAD

**Issue by tom709** [floccusaddon/floccus#1405]
### Which version of floccus are you using?

4.19.1

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 115.0.3 on Linux

### What kind of WebDAV server are you using? (if relevant)

Radicale 3.1.8

### Describe the Bug

When trying to sync with Radicale WebDAV, I get this error: "E019: HTTP status 400. Failed PUT request. Check your server configuration and log. Last synchronized: 0 seconds ago".

Log:
2023-07-28T07:12:16.841Z Starting sync process for account test@192.168.2.2
2023-07-28T07:12:16.878Z onSyncStart: begin
2023-07-28T07:12:16.878Z http://192.168.2.2:5232/test/bookmarks.xbel.lock
2023-07-28T07:12:16.955Z http://192.168.2.2:5232/test/bookmarks.xbel.lock
2023-07-28T07:12:17.019Z Syncing failed with E019: HTTP status 400. Failed PUT request. Check your server configuration and log.
2023-07-28T07:12:17.029Z onSyncFail

Radicale log:
Jul 28 09:05:45 host env[4869]: [2023-07-28 09:05:45 +0200] [4869/Thread-45442] [WARNING] Bad PUT request on '/test/bookmarks.xbel.lock': At line 1: Failed to parse line: <html><body>I am a lock file</body></html>

### Expected Behavior

should sync

### To Reproduce

Install Radicale:
python3 -m pip install --upgrade radicale
useradd --system --user-group --home-dir / --shell /sbin/nologin radicale
mkdir -p /var/lib/radicale/collections
chown -R radicale:radicale /var/lib/radicale/collections

Start Radicale:
python3 -m radicale --hosts 0.0.0.0:5232

Browse to and create user: http://localhost:5232/

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
radicale is a CalDAV (calendar) and CardDAV (contacts) server not a simple webdav server. It is trying to parse the things that floccus uploads and fails of course, because bookmarks are not calendar entries.
