### ISSUE TITLE
Android App, WebDav, wrong account is used

### ISSUE THREAD

**Issue by thofrey** [floccusaddon/floccus#1407]
### Which version of floccus are you using?

4.19.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Ecosia 8.0.0

### Which version of Nextcloud? (if relevant)

V25.0.9

### What kind of WebDAV server are you using? (if relevant)

Nextcloud, I think no special setup

### Describe the Bug

Sync dies not respect the account data, creating or synching bookmark.xbel.

1. Create account for "User1"
2. Path e.g /Floccus/bookmark-user1.xbel
3. Create a bookmark in App
4. sync
5. File created as expected in folder
6. so far so good

1. Create second account "User2"
2. Path e.g /Floccus/bookmark-user2.xbel
3. Create a bookmark in App
4. sync

Unexpectected:
File /Floccus/bookmark-user2.xbel created in folder-structure of user1.

### Expected Behavior

File /Floccus/bookmark-user2.xbel created in folder-structure of user2

### To Reproduce

I reproduced the steps above with new and empty folders in Nextcloud for both users. On my device I uninstalled und installed Floccus. Everything clean.

Tested only for Webdav, not tested for NC-Bookmarks. Tested only for xbel.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello, I'm sorry for the delay. Can you reproduce this also with a more mainstream browser like Chrome or Firefox?
