### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by edueocara27** [floccusaddon/floccus#1410]
### Which version of floccus are you using?

v4.19.1

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Microsoft Edge (Windows 11) 116.0.1938.69 and Kiwi Browser (Android 11) 116.0.5845.72

### Describe the Bug

I'm trying to use floccus to synchronize Edge (PC) bookmarks with Kiwi Browser (Android) but I'm not succeeding.

Basically I enable sync on Edge using Google Drive. An .xbel file is generated in Google Drive. However, when I go to Kiwi Browser and try to import this .xbel file from Google Drive, an error message appears saying ''Unexpected token 'v', ''<?xml vers'' ... is not valid JSON''

When I use the android app, it's even worse because the app doesn't even allow me to select the .xbel file to import. In fact, I started to think that I'm doing something wrong in trying to sync bookmarks instead of being a bug.

### Expected Behavior

Floccus on Kiwi Browser to import Edge bookmarks when clicking on the .xbel file

### To Reproduce

Edge (PC): Click on floccus extension button -> set sync bookmarks using Google Drive -> Sync bookmarks in the created .xbel file

Kiwi Browser (Android): Click on floccus extension button -> click on 'Import accounts' button -> select the .xbel file.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @edueocara27 
So the xbel files is not supposed to be imported via the import function.
Floccus has XBEL files which are stored on Google Drive and floccus will automatically read and write from those files if you have it set up in your browser.
Floccus also has json files which you can use to export and import floccus *accounts*. Ie. you can go to one device where you set up a lot of accounts in floccus, press export, get a json file, then go to a different device and import the json file: plop, you will have all those accounts in that other floccus device as well.
I hope this clears things up :)
