### ISSUE TITLE
unable to sync bookmarks (Could not update - Invalid bookmark)

### ISSUE THREAD

**Issue by mm1ke** [floccusaddon/floccus#1411]
### Which version of floccus are you using?

4.19.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 102.15.0, Firefox 117, Chrome latest

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.0

### Which version of Nextcloud? (if relevant)

27.0.2

### Describe the Bug

Hi,

For some weeks now i'm unable to sync bookmarks via floccus to nextcloud on multiple computers. I've cleared a couple of times now the bookmarks on both nextcloud (basically cleared the db) and local clients, restored the bookmarks and tried to resync.
Initially i can sync from the client to nextcloud, but as soon as i try to pull/merge, syncing fails.
Only bookmark folders are being sync, the bookmark itself are not.

I've uploaded a redacted debug log from today: floccus-4.19.1-2023-09-13.log

### Expected Behavior

Syncing should work as expected

### To Reproduce

Any change to the bookmarks, which would trigger a resync, reproduces this issue. Right now syncing doesn't work at all.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @mm1ke 
I'm sorry for the delay. I think this may be a bug in the bookmarks app. Have you tried updating it?

**Comment by mm1ke** [comment]
Hello @marcelklehr 
Just updated the bookmarks app in nextcloud (didn't realize there was an update available).
Syncing works again now. Thank you.
