### ISSUE TITLE
Sync on local change doesn't work

### ISSUE THREAD

**Issue by BloodyIron** [floccusaddon/floccus#1417]
### Describe the feature you'd like to request

5 minute background sync is generally fine to sync downloads of bookmarks. But when I'm adding/deleting bookmarks I really don't want to have to manually trigger sync each time, or even risk shutting my computer down before the next timed sync and losing that sync consistency.

I would like a setting where in addition to timed syncs, if the client detects a local bookmark change (add/delete/move/etc) that does not meant the "Destructive threshold" (50% default I think?) that it automatically and immediately syncs those changes (after waiting say... 5 seconds or something like that). And if each time it triggers any future notification stuff, I'm okay with that.

Namely I work with a high productivity pace, and 5 minutes timed periodic sync isn't sufficient for me in certain regards (but sometimes it is).

Anyways, if we could get something like this, that would be super awesome. Thanks! :)

### Describe the solution you'd like

Already described. Why is this even required?

### Describe alternatives you've considered

Currently I just manually trigger the sync after any change that I make, as generally any change I make I need (even moving folders for bookmarks).

**Comment by marcelklehr** [comment]
> detects a local bookmark change (add/delete/move/etc) that does not meant the "Destructive threshold" (50% default I think?) that it automatically and immediately syncs those changes (after waiting say... 5 seconds or something like that)

This is already implemented. It should sync 7 seconds after a bookmark was changed. If that doesn't work atm, then it's a bug.

**Comment by BloodyIron** [comment]
@marcelklehr I will aspire to test that at some point, thanks!

**Comment by BloodyIron** [comment]
Yeah the 7 second thing is not happening for me. I've given it over a minute after adding a bookmark and it still has not sync'd. v4.19.1

The way I can "tell" is the plugin reports time since sync'd, shows 10 minutes.... wait... then 11 minutes.... 12 minutes... which if that's accurate tells me it did not auto sync immediately-ish ;)

**Comment by gvegidy** [comment]
Just to add a datapoint:

for me the auto-sync 7 seconds after a local change works fine. Firefox 120.0.1 on Fedora Linux x86_64, Floccus 5.0.0.

I consider this auto-sync a good idea, thanks for implementing it.

**Comment by marcelklehr** [comment]
@gvegidy Yes, it was fixed with v5.0.0, thanks for the feedback!

**Comment by BloodyIron** [comment]
@marcelklehr when does the update hit the Chrome Plugin ecosystem? I don't think my "browser" sees it yet... or something like that 🤔

**Comment by marcelklehr** [comment]
Yes, chrome webstore is still reviewing the release

**Comment by BloodyIron** [comment]
@marcelklehr don't yet see the update on the Chrome Store. Am I doing something wrong, or?

**Comment by marcelklehr** [comment]
@BloodyIron No, I've paused the release on chrome until the most problematic issues have been resolved with v5 that transpired after releasing on firefox

**Comment by BloodyIron** [comment]
@marcelklehr is there a particular version milestone I should watch for in the skies? As in, a version you're roughly aiming to have such things "solved" in? I can appreciate it's not so easy of a thing to define sometimes, but if you have a such a target "version" in your mind already, I'd like to know so I can watch quietly while I look forward to all this stuff rolling out. :)

Also, thanks for the insights into what's going on! Isn't it such a bother when you release a bunch of work only to have to roll it back? :P It happens!

**Comment by marcelklehr** [comment]
@BloodyIron The issues i was referring to have been resolved now. I've submitted v5.0.6 for review on chrome web store and will try to gradually roll out the release for chrome to avoid bombing all users at once, in case there's new trouble...

**Comment by marcelklehr** [comment]
Staged rollout of v5.0.6 on chrome web store has just started

**Comment by BloodyIron** [comment]
@marcelklehr yay thanks! And also thanks for your hard work and all the work of others too! \o/ Seriously, this plugin really is fabulous for my workflow :)

**Comment by BloodyIron** [comment]
@marcelklehr I'm new to the auto-updating aspect of Chrome plugins. From a UX perspective, should I "expect" that Chrome's Plugin ecosystem will auto-update itself, or should I be manually checking to "apply update" (or equivalent) kind of thing?

Not trying to pressure you to go faster here, more trying to set my reasonable expectations of what to watch for. :) Thanks again!

**Comment by marcelklehr** [comment]
Yes, v5.x will reach you at some point, I'm currently at 5% rollout :)

**Comment by BloodyIron** [comment]
@marcelklehr I think you misunderstand. Does the Chrome plugin ecosystem auto-update plugins when an update rolls out? I haven't bothered in the past to ever check.

**Comment by marcelklehr** [comment]
> Does the Chrome plugin ecosystem auto-update plugins when an update rolls out?

Yes, once you install a plugin, chrome will keep it up to date.
