### ISSUE TITLE
No bookmarks in the bookmark folder after force upload

### ISSUE THREAD

**Issue by AlertWarn** [floccusaddon/floccus#1418]
### Which version of floccus are you using?

4.19.1

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 117.0.5938.152

### Describe the Bug

I can see the file in my google drive. However, the bookmark folder in Chrome where they are supposed to show is empty.
![2023-10-16 08_39_24-Bookmarks](https://github.com/floccusaddon/floccus/assets/106180115/5d0ba0aa-788e-4d18-ac81-94feea9ed8c0)
![2023-10-16 08_40_11-My Drive - Google Drive](https://github.com/floccusaddon/floccus/assets/106180115/e97484f0-b4f8-4e75-82c1-a268fa150e5b)

### Expected Behavior

I expected to see the bookmarks in the new folder.

### To Reproduce

Am I doing something incorrectly? 

https://github.com/floccusaddon/floccus/assets/106180115/66a7447d-7aca-4f20-a79a-d6fe039b5420

[floccus-4.19.1-2023-10-16.log](https://github.com/floccusaddon/floccus/files/12917395/floccus-4.19.1-2023-10-16.log)

### Debug log provided

- [X] I have provided a debug log file

**Comment by wazula** [comment]
Same problem with WebDav. The browser can write files, but downloading or merging is not possible. The debug log shows that everything is fine. It looks like the one already available

**Comment by marcelklehr** [comment]
It appears there are no bookmarks in your xbel file on GDrive either so floccus just syncs nothing to nothing.

**Comment by marcelklehr** [comment]
> after force upload

If you force upload with an empty set of bookmarks in your current browser, the server version will look like the browser version: empty.

**Comment by wazula** [comment]
Solved problem on WebDav with on IIS. In IIS Manager it's nessesary to define MIME Type, I had to add .xbel as extention an is a  text/plain Type to make it accesable.

**Comment by wazula** [comment]
> Same problem with WebDav. The browser can write files, but downloading or merging is not possible. The debug log shows that everything is fine. It looks like the one already available. Flocus 4.18.1 with Firefox 118.0.2 and MS Edge 118.0.2088.46

Solved problem on WebDav with on IIS. In IIS Manager it's nessesary to define MIME Type, I had to add .xbel as extention an is a text/plain Type to make it accesable.
