### ISSUE TITLE
GNOME Web support

### ISSUE THREAD

**Issue by julianfairfax** [floccusaddon/floccus#1421]
### Describe the feature you'd like to request

GNOME Web has extensions support in development. Currently, floccus doesn't work properly with it.

### Describe the solution you'd like

It would be nice if floccus were supported on GNOME Web.

### Describe alternatives you've considered

Not using floccus on GNOME Web?

**Comment by marcelklehr** [comment]
Hello @julianfairfax 
Thank you for your request. Unfortunately, it is GNOME web that currently does not support floccus, or rather, the webextensions bookmarks API (which, you will notice, is missing from [this list](https://gitlab.gnome.org/GNOME/epiphany/-/blob/master/src/webextension/README.md#webextension-javascript-apis)). Until then, floccus cannot work for (hopefully) obvious reasons.
