### ISSUE TITLE
Sync of private tabs

### ISSUE THREAD

**Issue by Mrothyr** [floccusaddon/floccus#1425]
### Which version of floccus are you using?

4.19.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Kiwi Browser (Android)

### Describe the Bug

I sync the open tabs. Floccus sync the nirmal tabs AND the private tabs - and open the private tabs then in the normal view. The extension is NOT activated for private tabs.

### Expected Behavior

Private tabs shouln't be synced.

### To Reproduce

Open some private tabs, sync open tabs. Wait for sync.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @Mrothyr 

> The extension is NOT activated for private tabs.

This does not affect access to tabs, only access to tab contents.

I will investigate if it is possible to find out which tabs are private.
