### ISSUE TITLE
Initial setup doesn't save encryption passphrase

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [floccusaddon/floccus#1427]
### Which version of floccus are you using?

4.19.1

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chromium 119.0.6045.123

### Describe the Bug

I just have installed the floccus browser extension, logged in into Google Drive, set the password (64 symbols) and bookmarks have been synced.
Then I opened the created file and found this there:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xbel PUBLIC "+//IDN python.org//DTD XML Bookmark Exchange Language 1.0//EN//XML" "http://pyxml.sourceforge.net/topics/dtds/xbel.dtd">
<xbel version="1.0">
<!--- highestId :3: for Floccus bookmark sync browser extension -->
<folder id="1"><title>Bookmarks Bar</title></folder>
<folder id="2"><title>Other Bookmarks</title><bookmark href="https://github.com/floccusaddon/floccus" id="3"><title>GitHub - floccusaddon/floccus: :cloud: Sync your bookmarks privately across browsers and devices</title></bookmark></folder>
</xbel>
```

You can see my one test bookmark in plain text...

### Expected Behavior

Encrypted file.

### To Reproduce

Install the floccus browser extension, log in into a Google Drive, set custom name for the bookmarks file and set a password.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @CaliforniaMountainSnake 
Thank you for reporting this. It appears to be known already. See #1398 .
Hence I am closing this as a duplicate.
