### ISSUE TITLE
Synchronisation using SFTP

### ISSUE THREAD

**Issue by ArthurMitchell42** [floccusaddon/floccus#1428]
### Describe the feature you'd like to request

While WebDAV is commonly available has it been considered to use SFTP over SSH please?
While SFTP might be a little slower it is a lot more secure.
Regs,
Arthur

### Describe the solution you'd like

By adding an SFTP sync option on the setup it would require 
- a server address
- path to file with file name
- a user name
- a password for decrypting the key
- a box to paste the private key

### Describe alternatives you've considered

I currently use WebDAV. Unfortunately my only strong language is Python so I don’t feel able to have a go at this myself.

**Comment by marcelklehr** [comment]
hello @ArthurMitchell42 
Sadly web extensions are not allowed to open tcp sockets, so this is not possible. I will have to close this request due to this.

**Comment by ArthurMitchell42** [comment]
Ok, thank you for looking at this.
