### ISSUE TITLE
https://domain name:port doesn't work

### ISSUE THREAD

**Issue by bzmshang** [floccusaddon/floccus#1432]
### Describe the feature you'd like to request

I want to synchronize bookmarks to my Synology, so I want one that supports https://domain name:port, but currently it seems that it cannot be used if it has a port.

### Describe the solution you'd like

/

### Describe alternatives you've considered

/

**Comment by marcelklehr** [comment]
I cannot reproduce this. It should work with a port in the server URL both for Nextcloud Bookmarks and WebDAV sync.

**Comment by marcelklehr** [comment]
> After this period of testing, it is found that as long as the local web port is inconsistent with the port forwarded out, it can be used, in addition, it is also found that the path is written according to the prompt, and the synchronization will report an error, I do not know where the setting is wrong

I'm sorry, I don't understand you. Can you give as simple as possible instructions on how to reproduce this?

for example, I did the following:

1. setup a nextcloud server, listening at localhost:8080
2. create a floccus webdav profile with  https://localhost:8080/remote.php/webdav/ as server url
3. enter necessary credentials
4. sync
5. outcome: success

**Comment by marcelklehr** [comment]
Does the folder `a` exist? Floccus doesn't create folders for you

**Comment by marcelklehr** [comment]
Also, does accessing the webdav share work with other clients?
