### ISSUE TITLE
Lost all bookmark names after automatic upgrade to 5.0.0

### ISSUE THREAD

**Issue by benjaoming** [floccusaddon/floccus#1450]
Hi :wave: 

Thanks for the great project, this is really one of the best extensions and most necessary extensions for Firefox :heart: 

### Which version of floccus are you using?

5.0.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 120.0.1

### What kind of WebDAV server are you using? (if relevant)

Nexcloud 25.0.0

### Describe the Bug

I have been using Floccus for a few months. My browser was running and when Floccus upgraded today, I lost all my bookmarks titles. Both folder names and bookmark names.

![image](https://github.com/floccusaddon/floccus/assets/374612/c6961a24-b764-4fdc-bf07-c4d81f655f95)

### Expected Behavior

Labels/titles are still there after upgrading.

### To Reproduce

Just upgrade? Or maybe this is only on Webdav?

### Debug log provided

- [ ] I have provided a debug log file

**Comment by benjaoming** [comment]
Hi! I have issues using the provided link to upload a debug log: https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

**Comment by matthewadie** [comment]
I can confirm this happening to me as well with the following setup:

- Windows 11
- Firefox 120.0.1
- Floccus updated on Dec 9 2022

Matthew


> Hi 👋
> 
> Thanks for the great project, this is really one of the best extensions and most necessary extensions for Firefox ❤️
> ### Which version of floccus are you using?
> 
> 5.0.0
> ### Sync method
> 
> WebDAV
> ### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.
> 
> Firefox 120.0.1
> ### Which version of Nextcloud Bookmarks are you using? (if relevant)
> 
> _No response_
> ### Which version of Nextcloud? (if relevant)
> 
> _No response_
> ### What kind of WebDAV server are you using? (if relevant)
> 
> Nexcloud 25.0.0
> ### Describe the Bug
> 
> I have been using Floccus for a few months. My browser was running and when Floccus upgraded today, I lost all my bookmarks titles. Both folder names and bookmark names.
> 
> ![image](https://private-user-images.githubusercontent.com/374612/289275492-c6961a24-b764-4fdc-bf07-c4d81f655f95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzA2MzAsIm5iZiI6MTcwMjEzMDMzMCwicGF0aCI6Ii8zNzQ2MTIvMjg5Mjc1NDkyLWM2OTYxYTI0LWI3NjQtNGZkYy1iZjA3LWM0ZDgxZjY1NWY5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxMzU4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTlkNGFkNmZlZDE1MWVkMmQwYjg2NThlMmUzNTJlZTkwYTQ4NzQ5NDAyMDliZTIxYzEzYTFkZGM1ZjdlODc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kuRx_HjkpFTrV5at1VtUNdUVJRSnrap1SCqCrzhO3iU)
> ### Expected Behavior
> 
> Labels/titles are still there after upgrading.
> ### To Reproduce
> 
> Just upgrade? Or maybe this is only on Webdav?
> ### Debug log provided
> 
>     * [ ]  I have provided a debug log file

**Comment by benjaoming** [comment]
Looking at the .xbel file stored via WebDav, it seems that all the titles are still there - phew :cold_sweat: 

But the titles and names are still not showing. I tried to restore an older version and pull it, no changes.

**Comment by matthewadie** [comment]
All of my other floccus installs are running version 4.19.1, I've blocked floccus from updating, and they are all  still operating normally.

For the floccus 5.0  firefox install with the problem I removed the profile and tried to import a previously exported version of the profile.  However, it will no longer allow me to do this.  I get the following error:

permissions.request may only be called from user input .

Matthew

**Comment by matthewadie** [comment]
I removed floccus 5.0 and installed the previous 4.19.1 version from firefox add-ons.  I can now import the profile without any problems, and my bookmarks sync normally.

Matthew

**Comment by marcelklehr** [comment]
I can reproduce this. A fix is in the works.

**Comment by marcelklehr** [comment]
A new version is available now for firefox, v5.0.1 which fixes the XBEL parser

**Comment by matthewadie** [comment]
Thank you very much!  I can confirm that the fix works. 

And thank you for the project, it's very useful, I use it across browsers, operating systems, and devices...

**Comment by benjaoming** [comment]
Thanks for the quick fix! :pray: I can confirm, too, that it works! I disabled Failsafe, pulled down bookmarks and enabled Failsafe afterwards.
