### ISSUE TITLE
Error when syncing in a bookmark with all-numeric title

### ISSUE THREAD

**Issue by gvegidy** [floccusaddon/floccus#1452]
### Which version of floccus are you using?

5.0.1

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 120.0.1 on Fedora Linux x86_64

### What kind of WebDAV server are you using? (if relevant)

Apache httpd

### Describe the Bug

When syncing in (not out) a bookmark with a all-numeric title I get an error. It looks like a type mismatch.

This is what I have in the xbel file on the server:
```
   <bookmark href="http://test.example.com/" id="1338">
      <title>12345</title>
    </bookmark>
```

This is what I get when floccus tries to sync:
```
Could not update - #UWaXW_MJka3O[12345](http://test.example.com/) parentId: ncsIvj_cAQeO: Type error for parameter changes (Error processing title: Expected string instead of 12345) for bookmarks.update.
```

This bookmark didn't create issues with floccus v4.19.1

### Expected Behavior

Syncs without issue, title is kept as entered 

### To Reproduce

```
   <bookmark href="http://test.example.com/" id="1338">
      <title>12345</title>
    </bookmark>
```

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Confirmed and fixed.

**Comment by gvegidy** [comment]
wow, that was fast. Thank you.

**Comment by marcelklehr** [comment]
heh, trying to mitigate toothing pains from the v5 launch as fast as possible...
