### ISSUE TITLE
All bookmarks and folders have empty names

### ISSUE THREAD

**Issue by alinanorakari** [floccusaddon/floccus#1453]
### Which version of floccus are you using?

5.0.1

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 120.0.1

### What kind of WebDAV server are you using? (if relevant)

Nextcloud 27.1.4

### Describe the Bug

After an automatic update to floccus 5.x all my bookmarks and bookmark folders, while still there, have lost their names and I am forced to manually name all of them again.

### Expected Behavior

No metadata gets lost

### To Reproduce

I guess just let Firefox automatically update floccus from an earlier version to 5.x

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @alinanorakari 
This was an unfortunate bug in the XBEL parser that has since been fixed. If you have other floccus clients that are still on v4.x you can force push to your server from there and force pull on firefox after updating to v5.0.1+

**Comment by marcelklehr** [comment]
see #1450

**Comment by alinanorakari** [comment]
Thank you. My desktop hadn't updated yet and I was able to recover its version of the bookmarks
