### ISSUE TITLE
v5.0.0 killed all bookmark titles

### ISSUE THREAD

**Issue by Fmstrat** [floccusaddon/floccus#1454]
### Which version of floccus are you using?

5.0.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

120.0.1 (64-bit)

### What kind of WebDAV server are you using? (if relevant)

Standard nextcloud webdav

### Describe the Bug

Auto-updated to 5.0.0. All bookmarks now have no title, across everything. 

### Expected Behavior

Titles to not be deleted from bookmarks.

### To Reproduce

All bookmark titles work in the previous version, update, and now bookmarks are a mess of "no title" folders and links. Happy to provide any logs that may be debug this, but I'm seeing iterations on the release right now so I'm guessing v5 just slipped out too early. If they're still helpful, let me know and I'll post them.

I tried clearing out Floccus and creating a new profile, but when I try to point it to the root folder and force a download, it now fails:
- Use original working XBEL file
- Add new Webdav account (no passphrase)
- Use Root Folder in Firefox
- Turn off auto-sync
- Set up to undo local changes and only download (to be safe)
- Force sync down (down arrow)
- It syncs for about 2 seconds but does nothing

This could likely be a new bug in and of itself. Also, the auto-sync is turned off in the wizard, but it's showing 15 minutes in the account settings. Seems there may be a few issues with the latest release and it wasn't ready for prime time.

I can get this bug to reproduce by using a new folder:
- Use original working XBEL file
- Add new Webdav account (no passphrase)
- Use "Other Bookmarks" folder in Firefox
- Turn off auto-sync
- Set up to undo local changes and only download (to be safe)
- Force sync down (down arrow)
- It syncs to Other Bookmarks with no titles

### Debug log provided

- [ ] I have provided a debug log file

**Comment by Fmstrat** [comment]
5.0.2 seems to have solved this, with a ton of deleting, recreating, disabling safety, etc. Bit of a nightmare for me today, but hopefully it's a clean fix for most and there's not a flood coming your way ;)

**Comment by ibressler** [comment]
Same here with 5.0.0, its with Firefox 120.0.1 (64-bit) after auto update all titles of folders and urls gone, only the urls itself remain. What info will be helpful?

**Comment by Fmstrat** [comment]
@ibressler If you force FF to update add-ons: https://support.mozilla.org/en-US/kb/how-update-add-ons

You might have better luck than me and a normal sync will solve it after the 5.0.2 update.

**Comment by kolinger** [comment]
Just update to 5.0.2 or wait until 5.0.2 is available. This is already fixed by 5.0.1 [here](https://github.com/floccusaddon/floccus/commit/4fff4c0c88ce1baaea68ead8562abad88bdcdcfe).

**Comment by ibressler** [comment]
Thanks a lot! Had to restore the bookmarks file on the server with an older version and setting  floccus to discard local changes and pull only from the server (once) that restored the titles. Now, 2-way sync works fine again. :+1:
