### ISSUE TITLE
Decryption stopped working, unable to sync

### ISSUE THREAD

**Issue by Seirade** [floccusaddon/floccus#1457]
### Which version of floccus are you using?

5.0.2

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 115.5.0esr (64-bit)

### What kind of WebDAV server are you using? (if relevant)

LoFloccus v1.2.3 (https://github.com/TCB13/LoFloccus)

### Describe the Bug

After the recent update, I noticed Floccus hasn't been syncing for the past 2 days. Error is:
```
E030: Failed to decrypt bookmarks file. The passphrase may be wrong or the file may be corrupted.
```
Floccus also keeps trying to sync, despite the Auto-sync option being disabled. I tried retyping the Password in the Server Details, Pulling down once, and restarting the browser, but it's unable to decrypt. On a different machine, same browser version, Floccus v4.19.1 still works, so it must have been the v5.0 update that broke.

### Expected Behavior

Floccus should be able to decrypt the bookmarks file in order to write to it properly.

### To Reproduce

On Firefox 115.5.0esr (64-bit), upgrade from Floccus v4.19.1 to v5.0.2. Decryption should suddenly not work.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @Seirade 

Can you check the file in question to see if it's actually encrypted? In v4.x there was a bug that would prevent the file from actually getting encrypted, so floccus might be trying to decrypt a plain text flie now

**Comment by Seirade** [comment]
The file is still encrypted. I never had any issues with it in v4.x. I also have two other browsers that don't auto-update extensions, and Floccus still works fine there. One is on v4.17.1 and the other's on v4.19.1. I'm hesitant on updating those until it's working properly again.

**Comment by tom709** [comment]
Same problem here. I am running Floccus against a Webdav backed by NGinx with an encrypted xbel file. After upgrade to 5.0.2 the sync does not work any more. The xbel file is not updated and even the Floccus log is still from the last time I synced with Floccus 4.19.1. I tried downgrading to 4.19.1 but even with the old version, now the sync does not work any more.

**Comment by Seirade** [comment]
I didn't try downgrading, but I did just now and can also confirm that it did not fix it. Another weird observation that I forgot to mention earlier was that it doesn't ask you for credentials when starting up the browser. They seemed to not be set so I tried setting them up again with "Secure your credentials", but no luck.

**Comment by marcelklehr** [comment]
Ahh, you've been using the "secure your credentials" feature? That was removed in v5. I suppose the code responsible for migrating has a bug. Short term workaround is to setup the profile from scratch.

**Comment by Seirade** [comment]
I tried exporting the account (profile) from v4.19.1 to make setting it up easier. I even removed the credentials before exporting, but got an error in v5.0.2 when importing it:
```
permissions.request may only be called from a user input handler
```
Setting it up completely from scratch did work, however. Everything seems to work, including syncs between different versions.

**Comment by Eyion** [comment]
Which version of floccus are you using?
5.0.2

Sync method
WebDAV

Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.
Android App

Describe the Bug
When I use the sync feature, I get error E017(Network error: Please check your network connection or account information), which ends up not completing the sync successfully.This problem did not occur when using version 4.19.1.

**Comment by tom709** [comment]
In my case the sync failed after upgrading from 4.19.1 to 5.0.2 even though the "secure your credentials" feature is not activated. I only posted here because I found that my XBEL file on the Webdav server does contain readable XML. After downgrading to 4.19.1, at first the sync seemed to take forever, but then, after an hours or so I noticed that it had actually succeeded. Very strange that.
