### ISSUE TITLE
Auto-sync toggle doesn't seem work on native/Android

### ISSUE THREAD

**Issue by kolinger** [floccusaddon/floccus#1465]
### Which version of floccus are you using?

develop

### Sync method

WebDAV

### Describe the Bug

New auto-sync enable toggle (in WebDAV profile `OptionsWebdav.vue`) doesn't seem to have effect. I can activate it (animation plays) it but it doesn't save, no console output is generated and I can see that my account is still `enabled: false`. If I `Save` and then go back to profile settings then auto-sync is disabled again.

My account is imported that's why it has `enabled: false`.

I tried to look how is enabled handled but I don't even understand how `enabled` could get into AccountStorage/Preferences let alone if something could be overriding `enabled` to false. This is very magic indeed.

### Expected Behavior

Auto-sync enable should persist.

### To Reproduce

Try to use auto-sync toggle on native/Android and see if it sticks.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thanks for filing the issue! :) I used the wrong event handler :D https://github.com/floccusaddon/floccus/commit/0aa47fed2e3210b848f571beb62e4ef78e7e206a

**Comment by kolinger** [comment]
Works but I see visual bug - Preferences/AccountStorage enabled gets true but if I return to profile settings then toggle shows off even if profile has enabled: true. If I toggle on then back off (to set false) then result is enabled: null. Something is off. Toggle sets value but doesn't read it back.

Do you see this visual bug as well?
