### ISSUE TITLE
Use Android WebView/Nextcloud App for login

### ISSUE THREAD

**Issue by SuperSandro2000** [floccusaddon/floccus#1467]
### Describe the feature you'd like to request

Right now the android app uses some browser component to login which is not a Android WebView so cookies etc. are not shared with Chrome. This means you need to log into nextcloud even if you are already logged into your browser or the nextdloud app. Other nextdcloud apps do not have this problem.

### Describe the solution you'd like

Login via Android WebView or nextcloud app.

### Describe alternatives you've considered

None

**Comment by marcelklehr** [comment]
Thank you for the feedback and weighing on this. I am aware of this, but it is due to the technological choices I made when building the app. It's unlikely to be fixable soon.
