### ISSUE TITLE
about updates

### ISSUE THREAD

**Issue by star2k** [floccusaddon/floccus#1473]
### Describe the feature you'd like to request

The 5.0 version has been released for many days, why hasn't it been updated in the Chrome Web Store?

### Describe the solution you'd like

The 5.0 version has been released for many days, why hasn't it been updated in the Chrome Web Store?

### Describe alternatives you've considered

The 5.0 version has been released for many days, why hasn't it been updated in the Chrome Web Store?

**Comment by marcelklehr** [comment]
Hello @star2k 
v5 has been kept back from chrome store because bugs have been reported after releasing to firefox. I intend to fix the most urgent bugs before publishing on Chrome Webstore.

**Comment by marcelklehr** [comment]
Staged rollout of v5.0.6 on chrome web store has just started
