### ISSUE TITLE
 E036: Missing permissions to access the sync server

### ISSUE THREAD

**Issue by DareDevil2000** [floccusaddon/floccus#1475]
### Which version of floccus are you using?

5.0.3

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

120.0.1 (64-bit)

### Describe the Bug

![fl](https://github.com/floccusaddon/floccus/assets/64276640/c1f4d216-d616-403d-ba57-031f31f29329)

### Expected Behavior

after importing a new profile the sync service keep kicking in and give this error every time
![fl](https://github.com/floccusaddon/floccus/assets/64276640/214a48a4-04a9-457e-bb80-4a6dd36564b1)
[floccus-5.0.3-2023-12-13-full.log](https://github.com/floccusaddon/floccus/files/13661327/floccus-5.0.3-2023-12-13-full.log)

### To Reproduce

several 

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank you for creating an issue! Did you update from an earlier floccus version or is this a new install?
