### ISSUE TITLE
After importing account I got blank screen on Iphone/Ipad

### ISSUE THREAD

**Issue by leobyrro** [floccusaddon/floccus#1476]
### Which version of floccus are you using?

5.0.2

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Safari

### Describe the Bug

The bookmarks weren't synced and the app seems not working well.

### Expected Behavior

After succesfully importing the account from Google Drive it should start sincying bookmarks as it did with the other browsers.

### To Reproduce

After importing the account from Google Drive I open Safari and noticed that the bookmarks weren't synced. I opened again Floccus app and clicked on "Google Drive: bookmarks.xbel" and the got a blank screen. After that every time I opened Floccus app i get that. I uninstalled and did everything again and still got the samen blank screen and the bookmarks weren't synced.

I did a video and posted on Youtube: https://youtu.be/Zdhka_JfV1w?si=0GjTe9kTk5UeO1ID

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @leobyrro 
So, the floccus iOS app is not able to sync your Safari bookmarks. It will only sync bookmarks into a bookmarks directory in the app itself.

**Comment by marcelklehr** [comment]
Your video doesn't show the blank screen after clicking on "Google Drive: bookmarks.xbel", I believe

**Comment by leobyrro** [comment]
Don't bother, I already deleted the app and got rembursed by Apple. So now I can't show the blank screen anymore.

**Comment by marcelklehr** [comment]
Sorry about the disappointment :)
