### ISSUE TITLE
Can't sync with Synology WebDAV from Firefox on MacOS

### ISSUE THREAD

**Issue by aliher1911** [floccusaddon/floccus#1478]
### Which version of floccus are you using?

v5.0.3

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox MacOS 120.0.1

### What kind of WebDAV server are you using? (if relevant)

Synology DSM5.2

### Describe the Bug

Can't add account to synchronize bookmarks. Getting
```
E036: Missing permissions to access the sync server Last synchronized: 2 days ago
```

Same setup works successfully with Firefox 119.0 under Arch Linux (on different machine) and under Chrome 120.0.6099.71 MacOS (on the same machine)
Account config was exported from Arch into json and imported both in Firefox and Chrome under mac os and fails in Firefox.

I also tried to recreate account by hand with the same results.
WebDAV uses custom rootCA and certificate signed by it. rootCA is added to keychain and firefox is set up to trust custom rootCA's so that it treats WebDAV connections as secure (no red lock in URL bar).

Debug logs are scarce (redacted user/host):
```
2023-12-13T18:25:09.993Z Starting sync process for account user@server
2023-12-13T18:25:09.995Z onSyncStart: begin
2023-12-13T18:25:09.996Z Syncing failed with E036: Missing permissions to access the sync server
2023-12-13T18:25:09.996Z onSyncFail
```

### Expected Behavior

Expecting sync to work :-)

### To Reproduce

Export working account for WebDAV from linux firefox, import into MacOS firefix, observe the failure.

Unfortunately I'm not sure which web server Synology NAS is using to provide webdav functionality to dive more details.

### Debug log provided

- [X] I have provided a debug log file

**Comment by aliher1911** [comment]
Looks like its a duplicate of #1458.

For posterity:
(right click on floccus icon) -> ManageExtension -> Permissions(tab) -> Access your data for all web sites

If this is a hard requirement now, maybe it needs to be highlighted somewhere?

**Comment by marcelklehr** [comment]
> If this is a hard requirement now, maybe it needs to be highlighted somewhere?

It shouldn't be, I'm looking into how to get rid of having to do this.

**Comment by aliher1911** [comment]
One thing I noticed that this permission is enabled on the previous installs that started on both earlier firefox and floccus versions, but is disabled in fresh installs. So existing users won't see it as a part of upgrade, but new users or users who reinstalled browers or have new user profiles will.

**Comment by marcelklehr** [comment]
Yes, I noticed the same thing. Thanks for the feedback! :)
