### ISSUE TITLE
Synchronisation with G Drive broken with v5.00 and later

### ISSUE THREAD

**Issue by lap75000** [floccusaddon/floccus#1479]
### Which version of floccus are you using?

5.03

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome & android

### Describe the Bug

EO17 (v5.00) or 31 (v5.03) errors from android app and Chrome add-on. Reversed to version 4.19 , everything ok.

### Expected Behavior

see bug description

### To Reproduce

I think any user using G Drive would encounter this bug?

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
It seems, there was a breaking change in our HTTP library
