### ISSUE TITLE
[v5] Permanent sync without any updates

### ISSUE THREAD

**Issue by tom709** [floccusaddon/floccus#1480]
[floccus-5.0.3-2023-12-15-redacted.log](https://github.com/floccusaddon/floccus/files/13683668/floccus-5.0.3-2023-12-15-redacted.log)
### Which version of floccus are you using?

5.0.3

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 120.0.1 on Linux

### What kind of WebDAV server are you using? (if relevant)

NGinx

### Describe the Bug

Floccus 5.0.3 still goes into permanent sync; only interrupted by showing "All good" for a second where it says "synced 2 hours ago"; and then starts syncing again.  Sync interval set to 15 min; Auto sync off; deleted all lock files on server while browser was closed; XBEL file is encrypted. Tried clearing cache; no change. Log was 65MB so I had to shorten it.

### Expected Behavior

should sync only every 15 min

### To Reproduce

unknown

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Could you please upload the full log here? https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

**Comment by tom709** [comment]
Uploaded floccus-5.0.3-2023-12-15-redacted2.log

**Comment by marcelklehr** [comment]
I think I know what is happening. Can you go to `about:debugging` -> "This firefox" -> "extensions" -> "floccus" and click "Inspect", then navigate to the `Console` tab. Then wait a while until floccus has finished syncing and shows the check mark symbol again. This should be a short-term "fix" to get it to work again, but I need to work on a long-term fix.

**Comment by tom709** [comment]
It does not stop syncing when I look at the console. I am attaching the result of "RMB->Save all messages to file" from the console.
[console-export-2023-12-16_19-22-25.txt](https://github.com/floccusaddon/floccus/files/13693546/console-export-2023-12-16_19-22-25.txt)

**Comment by tom709** [comment]
In my case, one Firefox syncs all its bookmarks while another instance syncs that into a sub-folder while not syncing the rest of its bookmarks. Maybe that makes a special case. Both are FF on Linux.

**Comment by j-lakeman** [comment]
Reproduced on Linux with same Firefox # as OP, but floccus version 5.0.4. Could not reproduce on macOS.
@marcelklehr's workaround worked for me.

**Comment by BeFreeNowHere** [comment]
I have the same problem: Endless syncing wihtout reason, even if autosync is disabled.
In addition to Firefox I have this in Ungoogled Chromium and in Waterfox G6.0.6 under Linux Mint 21.2
Can I safely return to version 4?

**Comment by marcelklehr** [comment]
v5.0.5 should fix this
