### ISSUE TITLE
impossible connection whith the last version of Floccus on Android

### ISSUE THREAD

**Issue by pbtoubol** [floccusaddon/floccus#1481]
Hello,
I have the same problem with the 5.0.3 version of Floccus with Bookmarks 13.1.2 version on Nextcloud v27.1.5
With the older versions I always have "E017: Network error: Check your network connection and you account details"

thank you for the help .

_Originally posted by @pbtoubol in https://github.com/floccusaddon/floccus/issues/1466#issuecomment-1858863493_

**Comment by marcelklehr** [comment]
Can you try:

1. Updating to v5.0.4 by going to about:addons and checking for updates
2. Recreating your sync profile

**Comment by marcelklehr** [comment]
Oh, so this is on android? The point of me telling you to open a new issue is so that you would fill out the full issue template :see_no_evil:

**Comment by marcelklehr** [comment]
Please open a new issue with all necessary information: https://github.com/floccusaddon/floccus/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

**Comment by pbtoubol** [comment]
Where can i download the v5.0.4 ?

**Comment by marcelklehr** [comment]
https://github.com/floccusaddon/floccus/releases/tag/v5.0.4
