### ISSUE TITLE
[native] 5.0.3 E017: Network error: Check your network connection and you account details

### ISSUE THREAD

**Issue by terba** [floccusaddon/floccus#1486]
### Which version of floccus are you using?

Android 5.0.3

### Sync method

Nextcloud Bookmarks

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

27.1.5

### Describe the Bug

Can not sync, I get "E017: Network error: Check your network connection and you account details" on the top of the main screen.
The logs are empty (redacted and full app logs contain only older entries).
No errors (or anything related) in Nextcloud server logs or proxy access and error logs.

### Expected Behavior

Syncing goes as it should.

### To Reproduce

Just start the app.

### Debug log provided

- [X] I have provided a debug log file

**Comment by Rorschach1010** [comment]
Same here but I had the same issue with the previous version. The Firefox add-on doesn't have this issue and is syncing without a problem. Only the android app isn't working.

**Comment by ip6li** [comment]
Chromium AddOn v4.19.1 is also not affected by that bug.

**Comment by ShinIce** [comment]
Problem still there in 5.0.4 from f-droid

**Comment by mathesst** [comment]
Also having the issue, still present with 5.0.4 release. Latest 27 nextcloud release, with latest bookmarks version.

**Comment by marcelklehr** [comment]
v5.0.5 is out now and should fix this

**Comment by mathesst** [comment]
Thanks for the update! For me it works again! Happy holydays!
