### ISSUE TITLE
Login at Nextcloud not possible - Exception error

### ISSUE THREAD

**Issue by webjunkietom** [floccusaddon/floccus#1489]
### Which version of floccus are you using?

5.0.4

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 121.0 on Android 13

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

27.1.5

### Describe the Bug

I defined an App token for the floccus App and tried to login. It doesn't work and the server log in nextcloud shows me an exception error:

Exception: OC\Core\Controller\ClientFlowLoginV2Controller::poll(): Argument #1 ($token) must be of type string, null given, called in /html/cloud/lib/private/AppFramework/Http/Dispatcher.php on line 230 in file '/html/cloud/core/Controller/ClientFlowLoginV2Controller.php' line 88

### Expected Behavior

The sync wizard for a new account stops at step 2 and I'm not able to go to step 3.

### To Reproduce

After filling in the URL to my nexcloud server and the credentials in the embedded nextcloud login screen (WebView?) I get the message that the login was successfull and the window could be closed. Afterwards the wizards stops at step 2 and nothing happens.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @webjunkietom 
v5.0.5 should fix this. Kindly try

1. Going to `about:addons`
2. Click on the cog button
3. Select `Check for updates`
4. Floccus should be updated and the problem should be gone.
