### ISSUE TITLE
Android E031 can't connect to Google

### ISSUE THREAD

**Issue by mvevitsis** [floccusaddon/floccus#1491]
### Which version of floccus are you using?

Android 5.0.3

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 12

### Describe the Bug

After authorizing with my Google account, the Android app has a message E031 asking me to authorize again. 

![Screenshot_20231221-112554_floccus bookmark sync.png](https://github.com/floccusaddon/floccus/assets/12841042/85affb1f-9f55-401d-9a62-3b94e8bec29c)

### Expected Behavior

Google login works correctly

### To Reproduce

1. Attempt to create or import a Google drive profile

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank you for providing feedback! I have good news for you :) This is fixed in v5.0.5
