### ISSUE TITLE
Floccus not working after updating nextcloud

### ISSUE THREAD

**Issue by barnycloud** [floccusaddon/floccus#1492]
### Which version of floccus are you using?

4.19.1

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 64bit, v. 120.0.6099.111 

### Which version of Nextcloud Bookmarks are you using? (if relevant)

12.1.0

### Which version of Nextcloud? (if relevant)

25.0.3

### What kind of WebDAV server are you using? (if relevant)

No

### Describe the Bug

After updating Nextcloud to a newer version, floccus didnot synchronize any more. Returning to version 25.0.3 floccus did work again (correctly synchronizing). What to do? May  I have a new try to update Nextcloud?

### Expected Behavior

Synchronizing after Nextcloud update

### To Reproduce

Floccus not synchronizing after Nextcloud update

### Debug log provided

- [X] I have provided a debug log file

**Comment by barnycloud** [comment]
I have now updated to version [Nextcloud Hub 3](25.0.13) and floccus seems to work without any problems in Chrome.
Unfortunately, I only have basic knowledge of the programming languages java, python, javascript and C (Arduino). I have no knowledge of php, so I probably can't contribute much to the code and can't help myself

**Comment by marcelklehr** [comment]
Which versions did you update to that didn't work?

**Comment by barnycloud** [comment]
Unfortunately, I did not notice the version number. It was a version following version 25.0.3. Anyway using versions 25.0.3 and 25.0.13 floccus does not show any problems.  
Merry christmas and a happy new year
