### ISSUE TITLE
Auto sync toggle does not stick

### ISSUE THREAD

**Issue by thatso** [floccusaddon/floccus#1493]
### Which version of floccus are you using?

5.0.5

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 13

### Describe the Bug

As already mentioned by @kolinger [here](https://github.com/floccusaddon/floccus/issues/1465#issuecomment-1853359616_): if I switch on auto sync in the options, confirm with `save`, leave options and enter them again, the auto sync switch is displayed as off.

### Expected Behavior

The switch state should display the real setting.

### To Reproduce

As stated in the bug description.

**Comment by marcelklehr** [comment]
Indeed, it's broken again :(

**Comment by kolinger** [comment]
It works! Vue is confusing tho... why this [isn't documented](https://vuetifyjs.com/en/api/v-switch/#links)? They just talking about some v-model value, no input-value...

**Comment by marcelklehr** [comment]
I'm not using vuetify v3 but [vuetify v2](https://v2.vuetifyjs.com/en/api/v-switch/#props) but yeah, the docs there aren't much more explicit either. Usually you will want to use v-model anyway, what I'm doing is a bit of a hack, because it's bad form to manipulate a components props from within.

**Comment by kolinger** [comment]
Thanks! Correct documentation explains a lot of my confusion of where you get these non-existing attributes from. Since previous fix 0aa47fed2e3210b848f571beb62e4ef78e7e206a with @change event isn't a thing in v3 also. The new Vue changed everything!

**Comment by marcelklehr** [comment]
@kolinger Also, note there's a difference between 'vue' and 'vuetify'  ;)
