### ISSUE TITLE
Auto-sync switch is turned off again

### ISSUE THREAD

**Issue by j-lakeman** [floccusaddon/floccus#1496]
### Which version of floccus are you using?

5.0.5

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android, Firefox Addon

### Describe the Bug

Auto-sync switch doesn't stay turned on

### Expected Behavior

Auto-sync switch should stay turned on

### To Reproduce

1. switch Auto-sync on
2. save
3. go back to settings
4. see reset switch

### Debug log provided

- [ ] I have provided a debug log file

**Comment by misterhsp** [comment]
What is the auto-sync option for anyway?

...

**Comment by marcelklehr** [comment]
Confirmed, fixed, release pending.

> What is the auto-sync option for anyway?

The auto-sync option allow enabling automatic sync in regular intervals.
