### ISSUE TITLE
Syncronisation with Nextcloud not work : Scheduled

### ISSUE THREAD

**Issue by oopen** [floccusaddon/floccus#1499]
### Which version of floccus are you using?

5.0.5

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 121.0 (64 bits) - Manharo Linux

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

28.0.1

### Describe the Bug

Synchronization never work.

Display :
```
Scheduled
This profile will be synced soon.
We're either waiting for other devices of yours, or other profiles on this device, to finish syncing.
```

Floccus logs :
```
2023-12-29T07:53:41.173Z Starting sync process for account jhon@nextcloud.mydomain.com
2023-12-29T07:53:41.483Z Resource is locked, trying again soon
```
![Capture d’écran du 2023-12-29 08-56-29](https://github.com/floccusaddon/floccus/assets/7348132/2b06047d-48e9-414d-94f0-5c4bffa55b18)

### Expected Behavior

Synchronization MUST work, after adding account.

### To Reproduce

Add Floccus extention to Firefox,
Add a nextcloud account, in floccus.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
hello!

Thank you for your feedback! This is a known issue that I'm working to fix as soon as possible. see #1495
