### ISSUE TITLE
automatically renaming new bookmark folders to "New folder"

### ISSUE THREAD

**Issue by cleancoda** [floccusaddon/floccus#1502]
### Which version of floccus are you using?

5.0.5

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

LibreWolf 121.0-1

### Which version of Nextcloud? (if relevant)

26.0.0

### Describe the Bug

whenever a new bookmarks folder is added from the same pop-up window of adding a new bookmark, and given a name via the browser pop-up, the extension somehow manages to rename the folder back to "New folder". I need to manually rename it back to what it was and manually resync to ensure it captures the changes.

note, all of my bookmarks are on the Bookmarks toolbar, and need to map **Bookmarks Toolbar/** to  **/Bookmarks Toolbar/**

### Expected Behavior

new bookmark folder names should be not renamed or changed automatically to "New folder"

### To Reproduce

1. using LibreWolf as browser, and Floccus logged in to Nextcloud instance. Configure to auto-sync and setup
2. add some bookmarks, then while adding a new bookmark, create a new folder on the same pop-up itself, give it a name, and save the bookmark inside the new folder you just created. wait for auto-sync to happen, check if bookmark folder name is same.

note: use bookmarks toolbar to save bookmarks and new folder on.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by cleancoda** [comment]
Thank you for your fantastic work, I just realized you released a new version 18 hours ago and that fixed another challenge I was having - the toggle auto-sync was turning off. works now! Thank you! Hope you can find the challenge with this odd behavior too! :)

**Comment by marcelklehr** [comment]
Mh, I can't seem to reproduce this.

**Comment by marcelklehr** [comment]
This is likely a LibreWolf issue, so I'm closing it for now. Sorry
