### ISSUE TITLE
"This profile will be synced soon"

### ISSUE THREAD

**Issue by AumCoin** [floccusaddon/floccus#1503]
### Which version of floccus are you using?

5.0.6

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

FF 121.0

### What kind of WebDAV server are you using? (if relevant)

Owncloud

### Describe the Bug

I see you recently fixed this bug supposedly, but it's not fixed for me.  I noticed my bookmarks weren't syncing.  FF had a little yellow arrow on the settings and when I clicked it it told me Floccus needed new permissions.  I clicked some "update" button.  Something updated.  Floccus continually works intermittently, running again every so many seconds.  I get the same error as others.  I see that I am on the latest version of Floccus.  The specific message is "This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing."

DEBUG LOG (FULL):
===========
2024-01-02T14:01:34.003Z Starting sync process for account admin@192.168.8.193
2024-01-02T14:01:34.141Z onSyncStart: begin
2024-01-02T14:01:34.143Z http://192.168.8.193:8081/remote.php/dav/files/admin/bookmarks.xbel.lock
2024-01-02T14:01:34.405Z Resource is locked, trying again soon

Should I just delete the .lock file here?

### Expected Behavior

I expect my device to sync.

### To Reproduce

no idea

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi!

Have you followed all steps from https://github.com/floccusaddon/floccus/issues/1495 ?

**Comment by suadiig** [comment]
Hi, I have the same issue with Floccus 5.0.6.  
I read issue #1495.  
I am using Nextcloud Bookmarks (not webDav) and Floccus for the first time.   The latest version of them all.
I am using only one client: Chrome Extension.
Error and Log are the same as those reported in this issue 1503.

I tried a second time after deleting all bookmarks from nextcloud app, and deleting floccus profile.
This second time I kept the floccus browser extension window opened all the time.   The progress bar seemed stuck at 5 or 10%  for maybe a minute, and then I briefely saw a green "All good" message, but a moment later it changed to "Scheduled: the profile will be synched soon...".
From the 7k+ bookmarks I have, just over 600 were synced the first time.  Over 300 the second time.

Regards.

**Comment by marcelklehr** [comment]
Hi @suadiig  

Thank you for taking the time to report this issue. This is indeed a new occurence, since you are using chrome. I have just released a patch that should make background sync work in chrome again (v5.0.9)

**Comment by marcelklehr** [comment]
@suadiig Would you be up for testing v5.0.9 directly without waiting for the chrome webstore rollout? You can download the zipped crx file [here](https://github.com/floccusaddon/floccus/files/13876819/fnaicdffflnofjppbagibeoednhnbjhg.zip). Then unzip, and drag and drop the file onto the `chrome://extensions` page to install it.
