### ISSUE TITLE
unclear permission

### ISSUE THREAD

**Issue by alpo** [floccusaddon/floccus#1504]
### Which version of floccus are you using?

5.0.5

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 115.6.0esr

### What kind of WebDAV server are you using? (if relevant)

Caddy

### Describe the Bug

The new permission "Access your data for all websites" is declared as optional, but without this permission the WebDAV sync does not work (E036: Missing permissions to access the sync server). 
![Screenshot_2024-01-02_16-53-54e](https://github.com/floccusaddon/floccus/assets/977573/38a5fbfb-5fc8-488e-abea-72cb168ca37d)

### Expected Behavior

The mandatory permission will be requested as mandatory. The new invasive permission will be clearly mentioned in a changelog/blog/whatever.

### To Reproduce

-

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi,
thank you for your feedback. Firefox forces me to have this optional, even though it's really not as you noticed. This is a won't fix sadly.

**Comment by SeanDS** [comment]
@marcelklehr Thanks for the great work on the addon! But please consider putting something in the changelog either on Firefox Addons or here on GitHub to explain exactly why this new permission is needed, even if it's something trivial. I am always suspicious of addons asking for new permissions and I so far could not find any explanation for why it's needed. I can guess it's due to the upgrade to Manifest v3, but I might also assume the addon has been hijacked and is being used for data mining - and not finding anything in the changelog I am still somewhat suspicious!

**Comment by marcelklehr** [comment]
> why this new permission is needed

The thing is, it's not a new permission. Floccus has always had this permission for the past years. The reason you get asked about it, is because it is now optional, for technical reasons. I can add something in the changelog :)

**Comment by CristianKerr** [comment]
Hi @marcelklehr, sorry I write it here, but I think its not worth a new issue. May I ask you why is this option needed? I was looking around and didn't find an explanation. I understand it has something to do with the Dav server sync? What is the particular feature that needs permission to see all sites data? Thank you

**Comment by marcelklehr** [comment]
In order for the extension to access your sync server it needs the permission for that. The permission for outward http requests to a certain domain is tied to general access to all website data for that domain, however. So, in order for floccus to access any sync server, it needs access to all website data for all domains.

**Comment by CristianKerr** [comment]
I see, thank you for the explanation. This sounds like is not very well implemented permission from Mozilla or whoever is responsible. No wonder almost any non-trivial extension needs to have it.

**Comment by marcelklehr** [comment]
> No wonder almost any non-trivial extension needs to have it.

Yeah, that's exactly the case :/

**Comment by jasonbrown1965** [comment]
> > No wonder almost any non-trivial extension needs to have it.
> 
> Yeah, that's exactly the case :/

Non-ironic laugh emoji from me, starting to think as a non-tech that global IT standards have been heroically defended for decades, but the creative chaos/destruction tsunami has exploded over from the economics classes into code? Just a little too much, too many times. Or I'm somehow misreading issue boards rife with lament about 'web' sites missing basic standards.

. . .
