### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [floccusaddon/floccus#1505]
### Describe the feature you'd like to request

GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

### Describe the solution you'd like

It would be nice if the app's code were moved to GitLab or Codeberg.

### Describe alternatives you've considered

None.

**Comment by marcelklehr** [comment]
Hi @julianfairfax 
Sorry for the late response. At this time I'm not inclined to move the repo even though I understand and partly share your concerns.
