### ISSUE TITLE
Freshly installed app stuck starting on up-to-date Graphene OS (Android 14)

### ISSUE THREAD

**Issue by j-lakeman** [floccusaddon/floccus#1507]
### Which version of floccus are you using?

5.0.6

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 14

### Describe the Bug

App seems to be stuck starting on first time opening.

### Expected Behavior

Shouldn't be stuck.

### To Reproduce

1. uninstalled the app
2. reinstalled it
3. open it
4. stuck on starting screen

### Debug log provided

- [ ] I have provided a debug log file

**Comment by mvevitsis** [comment]
Same. I updated to the latest version and the app no longer starts.

**Comment by Rorschach1010** [comment]
Same here. Android App on Android 14 and the server just nextcloud.
I also just updated the app and didn't newly install it.

**Comment by TheCakeIsNaOH** [comment]
Can confirm the same behavior on Android 13 for me. Update does not work, it also does not work after clearing data. 

A bisect seems to indicate that https://github.com/floccusaddon/floccus/commit/da5cc59e4aedfe0e821a94aae496edd79ebeb7bf is the problematic commit it, but I'm not sure why.

**Comment by misterhsp** [comment]
Can confirm the same behavior on Android 13/14

...

**Comment by marcelklehr** [comment]
Thank you for reporting! v5.0.7 will be available soon which fixes this.
