### ISSUE TITLE
E033: Redirect detected. 

### ISSUE THREAD

**Issue by eleaner** [floccusaddon/floccus#1511]
### Which version of floccus are you using?

5.0.7

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

firefox 121.0

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

Nextcloud AIO v7.9.0

### Describe the Bug

i created a profile and linked with the nextcloud account but I am receiving this error
![image](https://github.com/floccusaddon/floccus/assets/5169203/cb5301a0-1655-406b-93a2-de7626e7b7a0)
attaching log
[floccus-5.0.7-2024-01-05-full.log](https://github.com/floccusaddon/floccus/files/13841441/floccus-5.0.7-2024-01-05-full.log)

I don't do any redirects that I am aware of

I found the option to ignore redirects but it does not help
![image](https://github.com/floccusaddon/floccus/assets/5169203/fb2a2e5a-e104-49d9-a733-1c3cfbb69086)
and a second log
[floccus-5.0.7-2024-01-05-full(1).log](https://github.com/floccusaddon/floccus/files/13841466/floccus-5.0.7-2024-01-05-full.1.log)

### Expected Behavior

synchronisation

### To Reproduce

I am not sure, but i get the same error with brave

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @eleaner 
If you get a parse error, check the nextcloud log on your server

**Comment by eleaner** [comment]
I see, my nextcloud is behind authelia
I believe floccs might be trying to connect from unauthorised session and gets rejected

**Comment by marcelklehr** [comment]
mmmh, I've heard before that floccus doesn't seem to work well with authelia. I know very little about it, though. Do you know how floccus would need to behave to work with authelia?

**Comment by eleaner** [comment]
I know very little too but if the session is authorised everything should work
e.g. when I authorise floccus to work with nextcloud - it uses my current session and authelia naturally let it pass.
so synchronisation should do the same but it seems to be establishing a new session or connect from a different server

**Comment by marcelklehr** [comment]
>  it uses my current session

Mh. Floccus doesn't use sessions, though. You can try enabling "send client credentials" in the profile options, but out of the box, floccus only does basic auth.

**Comment by eleaner** [comment]
well, I am not sure if "session" is a good term
what I mean is when i login to nextcloud it goes through authelia first
I actually don't have them integrated so next I have to login to nextcloud
but authorisation is remembered in the browser somehow
so even if I log-off nextcloud and try to login again, authelia will let me through
it will also let me through through every service that sits behind her
so i would say - browser is authorised

somehow authorisation of plugin in nextcloud also gets through authelia without any issue - still because browser is authorised
but then synchronisation in the same browser must do something different

I doubt I can explain it more clearly

**Comment by marcelklehr** [comment]
From your explanation, it seems like authelia sets a cookie. Do you have other client software working with this setup? Like nextcloud desktop?

**Comment by eleaner** [comment]
not that I am aware of
but I guess it would not work that easily as it would have to first allow authelia login

**Comment by marcelklehr** [comment]
Have you tried the "send client credentials" in the profile options already? That might fix this, but other than that, I can not help you further.
