### ISSUE TITLE
iOS app: Cannot authenticate

### ISSUE THREAD

**Issue by boraozgen** [floccusaddon/floccus#1515]
### Which version of floccus are you using?

5.0.5

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iOS 17.1.2

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

27.1.5

### Describe the Bug

I can sync with browser extensions successfully. I installed the iOS app. When trying to log in with username and password, I get "Temporary error: Please try again.". This can have something to do with my reverse proxy setup, since I get bruteforce throttling warning after this error. However resetting bruteforce or adding the trusted proxy did not solve the issue. Alternatively I tried using the app token authentication. After entering the credentials, I receive the error "Access denied: CSRF check failed". I assume this is caused by the app since I never had received similar issues on web authentication or other apps.

### Expected Behavior

Log in on iOS app.

### To Reproduce

Log in on iOS app.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
I was able to reproduce this. Very strange

**Comment by boraozgen** [comment]
Thanks for the quick fix! It's working now. Cheers
