### ISSUE TITLE
Mobile app is not starting anymore on my phone (GrapheneOS)

### ISSUE THREAD

**Issue by MentalRedemption** [floccusaddon/floccus#1516]
### Which version of floccus are you using?

5.0.6

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 13 on Pixel4a

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

Nextcloud Hub 27.1.5.

### Describe the Bug

The Floccus app stucks in startup view, only showing  the startup logo and does not proceed further.
[Floccus_debug_log.txt](https://github.com/floccusaddon/floccus/files/13849872/Floccus_debug_log.txt)

### Expected Behavior

The application starts and showing me the bookmark tree.

### To Reproduce

Just click on the Floccus Icon to start the app.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank you for taking the time to file an issue! This is known and a new release is in the process of being published and should arrive as an update on your device soon :blue_heart:

**Comment by MentalRedemption** [comment]
Thanks alot,

I find your app one of the most useful!
Thanks for your afford!

M. Funk ***@***.***

-------- Original-Nachricht --------
Am 6. Jan. 2024, 16:51, schrieb Marcel Klehr :
