### ISSUE TITLE
Moving bookmarks.xbel to another Google Drive Account doesn't read the existing file and creates a new one instead

### ISSUE THREAD

**Issue by zavocc** [floccusaddon/floccus#1519]
### Which version of floccus are you using?

5.0.9

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 120.0.6099.217

### Which version of Nextcloud Bookmarks are you using? (if relevant)

N/A

### Which version of Nextcloud? (if relevant)

N/A

### What kind of WebDAV server are you using? (if relevant)

N/A

### Describe the Bug

I've been transferring my bookmarks.xbel file to another google drive account, if I logged in to the new browser profile from scratch with alternative google drive account and try to login with it with the floccus extension (without importing profiles). It just creates a new bookmarks.xbel file instead of reading the existing file in Google Drive.

### Expected Behavior

I would expect for it to pull my bookmarks from that file

### To Reproduce

1. On the browser profile with the bookmarks data with old google account where Floccus is currently syncing, download the existing bookmarks.xbel file
2. Create a new profile in Chrome or chromium derivatives
3. Login to the new or alternate google account and place the copied bookmarks.xbel to that alternative account in the same location as the old account
4. Login with Google in the Floccus setup page without importing profiles and configure where to sync as usual (e.g. in specific folder where bookmarks have been pulled and sync from there)
5. Run sync and observe google drive, you will see a new file is created instead rather than using existing ones

### Debug log provided

- [ ] I have provided a debug log file

**Comment by zavocc** [comment]
Workaround seems to be by just replacing the newly created bookmarks.xbel file with the old one, since Google might have given different scoped access to particular file which it couldn't read the old bookmarks.xbel file, i believe this wouldn't be the case for webdav or other storage provider without special file access

**Comment by marcelklehr** [comment]
Indeed, the Google Drive permissions floccus requests are to read only files that it created itself.
