### ISSUE TITLE
Kiwi Browser

### ISSUE THREAD

**Issue by DogancanYr** [floccusaddon/floccus#1530]
### Which version of floccus are you using?

5.0.9

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Kiwi Browser

### Describe the Bug

I imported the profile and the bookmarks are not imported .
[floccus-5.0.9-2024-01-27-full.log.txt](https://github.com/floccusaddon/floccus/files/14073745/floccus-5.0.9-2024-01-27-full.log.txt)

### Expected Behavior

.

### To Reproduce

..

### Debug log provided

- [X] I have provided a debug log file

**Comment by x3oo** [comment]
I have the same problem.
The bookmarks appear in the log file but the actual bookmarks dont change.
Maybe it's a bug with Kiwi Browser.

**Comment by x3oo** [comment]
I could narrow it down.
Syncing of root directory doesnt work. If you Sync to another directory it works.

**Comment by marcelklehr** [comment]
> 2024-01-27T14:10:37.885Z Syncing failed with Cannot read properties of undefined (reading 'id')

@x3oo Do you get the same error in the logs when trying to sync root directory?

**Comment by marcelklehr** [comment]
What does Kiwi's bookmarks tree look like nowadays? Does it have some default folders that you cannot delete like Bookmarks Toolbar etc.?

**Comment by x3oo** [comment]
> What does Kiwi's bookmarks tree look like nowadays? Does it have some default folders that you cannot delete like Bookmarks Toolbar etc.?

I just checked. 
In the root directory you can't delete the two directories: "mobile bookmarks" and "reading list"
You can create directories though.
When i was trying to set it up, "just downloading" didnt work either....

**Comment by marcelklehr** [comment]
Then you cannot sync the root folder and have to choose a folder one level deeper

**Comment by sjain882** [comment]
Not sure why this was closed, as it wasn't established that it was solely Kiwi's fault. Root directory sync did actually work for me on the first sync, but after that, it doesn't work. There may be more to this, however, as occasioanlly Bookmarks Bar syncs just fine, but Mobile Bookmarks & Reading List is entirely missing on my PC...
