### ISSUE TITLE
Always Scheduled

### ISSUE THREAD

**Issue by zyyjade** [floccusaddon/floccus#1538]
### Which version of floccus are you using?

5.0.8

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 122.0.1 64bit

### Describe the Bug

Every time I have been using it for a while, the "Scheduled" page always appears.

### Expected Behavior

Normal automatic synchronization.

### To Reproduce

[![pF3mHl6.png](https://s11.ax1x.com/2024/02/09/pF3mHl6.png)](https://imgse.com/i/pF3mHl6)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by superlinuxero** [comment]
Affected as well, with Nextcloud sync method

**Comment by superlinuxero** [comment]
In my case, I have 2 Firefox and 1 Chrome browsers installed in different computers and I haven't been able to sync any of them with my nextcloud instance in more than 5 days. All 3 browsers show the same error, and Nextcloud is updated to latest stable version and working correctly.

**Comment by marcelklehr** [comment]
Can you make sure you're on 5.0.**9**?

**Comment by superlinuxero** [comment]
![imagen](https://github.com/floccusaddon/floccus/assets/32478929/c0122976-3ddd-4f02-8f07-efcb2250c93e)

**Comment by superlinuxero** [comment]
Ok. Just now I could do a sync. This is what I did: I closed all browsers, restarted apache (where our office nextcloud instance is running), waited 45 minutes and opened one browser, synced correctly, then the second one which also synced just fine, and finally the third one. I've checked NextCloud logs just to see if there was something it could seem strange, but I couln't find anything related. Is there any "lock" file or similar I could check when syncing using Nextcloud backend? In any case I'll be following floccus behavior more closely and see how it behaves during the following days.

**Comment by marcelklehr** [comment]
> opened one browser, synced correctly, then the second one which also synced just fine, and finally the third one

Mh, very curious that this worked.

**Comment by ours1** [comment]
Hello
I have the same problem with 5.08 and firefox 122.0.1, one on windows and the other on kubuntu. With webdav in a nextcloud server from a provider.
I don't know if there is a link, but I've got as well a message from nextcloud saying "myFileBookmarkFloccus.html.lock is deleted from server (Sabre/DAV/Esception/Notfound)". This occur since a much longer time, but until now, didn't prevent from floccus working fine.
Hope this will help, if you need more info, please ask.

**Comment by marcelklehr** [comment]
For Nextcloud Bookmarks there's also a lock endpoint. It's at `https://yournextcloud.com/index.php/apps/bookmarks/public/rest/v2/lock` if you send a HTTP DELETE to that endpoint it will clear the lock, e.g.


```bash
curl -X DELET -u 'user:password' https://yournextcloud.com/index.php/apps/bookmarks/public/rest/v2/lock
```

**Comment by ours1** [comment]
Nexctloud Bookmarks is an app you can integrate within nextcloud by yourself ? I don't think I'm using it, unless it's mandatory and I didn't ever notice it.

**Comment by marcelklehr** [comment]
@ours1 Sorry, I was responding to @superlinuxero

**Comment by superlinuxero** [comment]
> For Nextcloud Bookmarks there's also a lock endpoint. It's at `https://yournextcloud.com/index.php/apps/bookmarks/public/rest/v2/lock` if you send a HTTP DELETE to that endpoint it will clear the lock, e.g.
> 
> ```shell
> curl -X DELET -u 'user:password' https://yournextcloud.com/index.php/apps/bookmarks/public/rest/v2/lock
> ```

Ok. I'm checking my syncs and for now they're working alright. If it fails again first thing I'll check is the lock

Thanks for your nice plug-in

**Comment by beyercj** [comment]
same here. Floccus version 5.0.9 on Firefox 115.7.0esr 64bit under Linux and Samsung Galaxy A12 under Android. The lock file is not deleted by Floccus. When I try to delete it manually I get the message "An item with the same name already exists" and cannot delete the lock file unless I rename it. After renaming and deleting the lock file, synchronisation works until I use the desktop and phone. The lockfile is not deleted by floccus after 20min as mentioned in FAQs. Log file is just says it tried to synchronise.

**Comment by marcelklehr** [comment]
Closing this in favor of #1548 to consolidate the two threads, since it's the same problem.
