### ISSUE TITLE
Configuration page does not "open"

### ISSUE THREAD

**Issue by DefCon-CC** [floccusaddon/floccus#1540]
### Which version of floccus are you using?

5.0.8

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 122.0.1 (64-Bit)

### What kind of WebDAV server are you using? (if relevant)

Owncloud (v10.13.1) Webdav 

### Describe the Bug

When clicking on the Floccus Icon in the Symbolbar in Firefox it open the below window but it never "opens" the Floccus Configuration-Page. It is stuck in the "progress" window. See below:

![2024-02-12 11_04_23-Clipboard](https://github.com/floccusaddon/floccus/assets/25898240/74c015e2-9ac2-4b0d-8edd-0495e62a67bb)

Let me know when I shall provide some debug output or something else.

### Expected Behavior

Configuration-Page of Floccus is opened

### To Reproduce

Click on Floccus Icon in the Symbolbar in Firefox

### Debug log provided

- [ ] I have provided a debug log file

**Comment by pinpontitit** [comment]
I have the same Firefox and Floccus versions and cannot reproduce sorry :-(

**Comment by marcelklehr** [comment]
@DefCon-CC Can you try uninstalling floccus and reinstalling?

**Comment by DefCon-CC** [comment]
> @DefCon-CC Can you try uninstalling floccus and reinstalling?

Yes I did. It solved my problem.
