### ISSUE TITLE
SendIntent crashes on Android

### ISSUE THREAD

**Issue by kolinger** [floccusaddon/floccus#1542]
### Which version of floccus are you using?

5.0.7

### Describe the Bug

Android app crashes here on `SendIntent.finish()`

https://github.com/floccusaddon/floccus/blob/develop/src/ui/views/native/AddBookmarkIntent.vue#L173

When new bookmark is saved via SendIntent/share to Floccus. The reason is that AndroidManifest.xml isn't inline with send-intent, it's missing activity that should handle the SendIntent and instead Floccus tries to handle SendIntent itself and thus crashes - this is outline in send-intent documentation: https://github.com/carsten-klaffke/send-intent?tab=readme-ov-file#android

Apart of that Send intent doesn't work properly, it doesn't auto sync, it seems buggy overall. For example most of the time added bookmark doesn't propagate into the tree unless floccus is restarted. The communication between SendIndent and main activity doesn't seem to work right. 

### Expected Behavior

No crash

### To Reproduce

Share URL to Floccus

**Comment by kolinger** [comment]
If I neutralize SendIntent.finish() then bookmark gets added reliably into the tree and auto sync works too but of course now floccus stays open and send intent is never finished. This makes sense since finish() exits the activity that handled the intent and if finish() is removed then the activity continues and can do everything but that's not how send intent should work.

Not sure how was floccus programmed in mind with this but there should be some kind of mechanism to make sure bookmark is saved before finish() is called. Also not sure how to handle auto sync in this instance since the activity exits and doesn't have time to handle auto sync as usual. I guess the proper way would be handling sync in background and signal the background activity to do sync and then intent can exit peacefully.

Also when main activity is resumed there should be check if tree was changed in background since as of now main activity thinks the tree didn't change when it was modified by SendIntent instance and shows old render of the tree.

**Comment by kolinger** [comment]
I think there is fundamental problem - missing parts.

If I neutralize SendIntent.finish() then bookmark gets added reliably into the tree and auto sync works too but of course now floccus stays open and send intent is never finished.  Also the floccus I see isn't the actual floccus that's the activity of send intent and thus if this activity exits then main activity resumes and doesn't see new bookmark/changes, quite confusing. This makes sense since finish() exits the activity that handled the intent and if finish() is removed then the activity continues and can do everything but that's not correct then two floccuses exist at the same time.

Not sure how was floccus programmed in mind with this but there should be some kind of mechanism to make sure bookmark is saved before finish() is called. Also not sure how to handle auto sync in this instance since the activity exits and doesn't have time to handle auto sync as usual. I guess the proper way would be handling sync in background and signal the background activity to do sync and then intent can exit peacefully? Now auto sync is handled by main activity when it runs but in send intent scenario main activity would be paused/exited. As a hack we could just wait for sync to end before calling finish() but that's not ideal for sure since that could be long time.

Also when main activity is resumed there should be check if tree was changed in background since as of now main activity thinks the tree didn't change when it was modified by send intent activity and shows old render of the tree and also synces old version of the tree until is floccus restarted.

The crash makes it seem like it's working more properly since it kills the main activity and forces to reload the tree when floccus is next activated but of course then auto sync doesn't have chance to run since floccus is crashed. If the crash is fixed then send intent gets it's own activity as it should and then the mentioned fundamental issues arise. 

As I see it now floccus isn't expecting this dual activity moment or the fact that send intent activity doesn't have time for auto sync.

Unrelated but related - how does the synchronization interval work? I mean the slider in settings - if I set some periodic time - how can floccus execute sync in this interval if main activity isn't in foreground? If the activity isn't active/foreground then most likely it would be paused thus can't execute sync in interval? This makes the slider very misleading!

Not sure if I don't miss something but looks like this change is lot of work since current implementation isn't quite ideal since main activity handles everything but can't since is paused most of the time.

This reflects pretty much my user experience that sync doesn't happen unless I manually open floccus. Send intent auto sync will also never occur and even if I wait days the 10 minute (or whatever set) periodic sync will never occur either since main activity of floccus is one of paused/exited/crashed.

**Comment by kolinger** [comment]
If I fix the crash (declaring extra activity in AndroidManifest as per send-intent readme) and neutralize SendIntent.finish() then bookmark gets added reliably into the tree and auto sync works too but of course now floccus stays open and send intent is never finished.  Also the floccus I see isn't the actual floccus that's the activity of send intent and thus if this activity exits then main activity resumes and doesn't see new bookmark/changes, quite confusing. This makes sense since finish() exits the activity that handled the intent and if finish() is removed then the activity continues and can do everything but that's not correct then two floccuses exist at the same time. If fininish() is called then added bookmark isn't visible the same way in main activity.

There should be some kind of mechanism to make sure bookmark is saved before finish() is called. Also not sure how to handle auto sync in this instance since the activity exits and doesn't have time to handle auto sync as usual. I guess the proper way would be handling sync in background and signal the background activity to do sync and then intent can exit peacefully or just wait for AlarmManager to trigged periodic sync - not ideal that could take ages.

There needs to be a check if tree was changed in background since as of now main activity thinks the tree didn't change when it was modified by send intent activity and shows old render of the tree and also synces old version of the tree until floccus is  restarted.

The crash makes it seem like it's working more properly since it kills the main activity and forces to reload the tree when floccus is next activated but of course then auto sync doesn't have chance to run since floccus is crashed. If the crash is fixed then send intent gets it's own activity as it should and then the synchronization between main activity issue arises.

This reflects pretty much my user experience that sync doesn't happen after using Send intent unless I manually open floccus and periodic sync will also never occur even if I wait days since main activity of floccus is crashed thus AlarmManager never gets triggered.

**Comment by marcelklehr** [comment]
Capacitorjs has a background runner API but it's limited to 30s on iOS which is too little time sadly.

I think fixing the crash and going back to the sharer App is a good enough solution for now. If people want to sync, they'll need to remember to open floccus. I'll add a regular interval to reload the current tree in the main screen so the changes from the share intent will be reflected.

**Comment by kolinger** [comment]
30 seconds sound like long time. When floccus needs more than 10 seconds to do sync? I would think typical sync is couple seconds with reasonable connection to the server and 10 seconds or more only with bad connection and timeouts. Although background task is maybe too much work just for this, not sure since I have experience only with Android not Capacitor.

I guess if there isn't auto-sync action then AlarmManager should sync it eventually even without opening floccus again?

Doesn't make more sense to check tree state after resume and do tree reload then instead of time interval?

**Comment by marcelklehr** [comment]
> Doesn't make more sense to check tree state after resume

Mh, not sure if there's an event for resume

**Comment by kolinger** [comment]
[Here they say](https://capacitorjs.com/docs/apis/app#api) `addListener('resume', ...)`? I would assume there needs to be some way to get pause/resume events since those are must have - not sure how would people live without them.

**Comment by marcelklehr** [comment]
> When floccus needs more than 10 seconds to do sync?

If you have a lot of changes it can take minutes.
