### ISSUE TITLE
This profile will be synced soon across issue across Edge, Firefox, Brave

### ISSUE THREAD

**Issue by bun1010** [floccusaddon/floccus#1543]
### Which version of floccus are you using?

Edge 5.09, Brave 5.09, Firefox 5.08

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Microsoft Edge Version 121.0.2277.112 (Official build) (64-bit), Brave 1.62.162, Firefox 122.0.1

### What kind of WebDAV server are you using? (if relevant)

[Self hosted ](https://hub.docker.com/r/ugeek/webdav)

### Describe the Bug

Sync starts to work from one or two browsers then when trying add the third, or the same set of browsers on another machine I get the message below and it won't sync again across any of the browsers (get's stuck with this message):
This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing.

### Expected Behavior

Sync to work across all browsers

### To Reproduce

I downloaded the extensions from the respective addon websites for each browser, was able to authenticate to my local webdav server and I can see the files being copied there (bookmarks.xbel,bookmarks.xbel.lock). Just selected the toolbar folder as the sync folder for each browser and left all other options as default.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey!

So, bookmarks.xbel.lock should be deleted after each sync run, so other clients know that it's ok to do their sync. Could you provide some logs for the sync run that does go through? It seems that this one doesn't delete the lock file, then.

**Comment by bun1010** [comment]
Thanks for your help

Here is what I have from the logs:
2024-02-15T20:10:40.491Z Starting sync process for account jack@192.168.1.117
2024-02-15T20:10:40.705Z onSyncStart: begin
2024-02-15T20:10:40.706Z http://192.168.1.117:8081/bookmarks.xbel.lock
2024-02-15T20:10:40.743Z Resource is locked, trying again soon

for your information, I am running this webdav server on my raspberry PI on my local home network installed in docker from this site:

https://hub.docker.com/r/ugeek/webdav
