### ISSUE TITLE
sync Issues

### ISSUE THREAD

**Issue by TimeKeyRoll** [floccusaddon/floccus#1545]
### Which version of floccus are you using?

5.0.9

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Edge

### Describe the Bug

I have reinstalled the extension but I continue to see the same imported data that I previously imported before deleting the app. After deleting the app, I also deleted the bookmark file from Google Drive. But I still see the same imported data every time I download the extension and I have checked that there is no file stored in Google Drive.

Does Floccus save the file locally or somewhere secretly in Google Drive even after deletion? 

Does anyone know how it keeps getting synced with the previous data which is not even stored anymore? 

### Expected Behavior

It should not show the previously imported data even after re-deleting or re-downloading the app.

### To Reproduce

shall work fine

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Mmh, It seems there is a misunderstanding of what this extension does, perhaps. Can you list step-by-step, as dumbed-down as possible, what you did and where you got an outcome that wasn't expected, please?

**Comment by TimeKeyRoll** [comment]
I have two browsers A and B with different emails. Both browsers have their extensions installed with their respective emails and are synced with Google Drive. However, I am unable to see one-way or two-way sync in any of the accounts only the bookmark files in both Gmail.

For example, I can see the bookmark file in Browser A and B, and I can also see the bookmark files of a new profile in both browsers. So, in Browser A, I see the bookmark file of Browser A & B and vice versa. But there is no display of imported bookmarks in the browser.

Please let me know if you need further clarification.

**Comment by marcelklehr** [comment]
Gmail? Can you perhaps make a screencast video showing the problem?
