### ISSUE TITLE
password included in export profile

### ISSUE THREAD

**Issue by j-lakeman** [floccusaddon/floccus#1546]
### Which version of floccus are you using?

5.0.8

### Sync method

Nextcloud Bookmarks

### Describe the Bug

When exporting a profile, the password / token gets exported as well.

### Expected Behavior

Field shouldn't be exported / left empty IMHO. This would increase security if you want to put the export file in a git repository or share it between different devices.

### To Reproduce

1. export profile
2. see “password” key

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @j-lakeman 
This is sort of by design. The whole point of the account export is to be able to quickly setup the same accounts on other devices. If you would have to re-enter the password this functionality would be a bit pointless. I understand that this is not entirely ideal security wise.

**Comment by Mace404** [comment]
This makes me question the whole security design of this addon.
Why store the main password for the account? Shouln't just the device/session token be stored? Now if I remove a device from the Nextcloud security page it just ceates a new device/session?

**Comment by marcelklehr** [comment]
@Mace404 The use of the word password and / or the word account may be ambiguous here. Let me try to clarify: When you use Nextcloud Bookmarks to sync, you login with Nextcloud as part of the sync profile setup (previously called "accounts" in floccus). Floccus doesn't store this password and doesn't have access to it. Floccus in this case receives an app password or device token instead which is also part of the export if you export a profile. If you have a profile that syncs via WebDAV for example there is no device token, so the passwords will be exported directly.


> Why store the main password for the account?

This doesn't happen.

> Shouln't just the device/session token be stored?

Yes that's what happens.

> Now if I remove a device from the Nextcloud security page it just ceates a new device/session?

No, it will fail to authenticate.

**Comment by Mace404** [comment]
> > Why store the main password for the account?
> 
> This doesn't happen.
> 

Then why is my password in an export file? (in clear text)

> > Shouln't just the device/session token be stored?
> 
> Yes that's what happens.
> 
> > Now if I remove a device from the Nextcloud security page it just ceates a new device/session?
> 
> No, it will fail to authenticate.

Just did and it re-added itself because of the stored password.

Now created an app password myself and entered that to have a bit more control but your description of storing just the device/session is not wat is happening in my experience.
