### ISSUE TITLE
E017 network error

### ISSUE THREAD

**Issue by Nietzscheanman** [floccusaddon/floccus#1547]
### Which version of floccus are you using?

5.0.9

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave 1.62.165

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

28.0.2

### Describe the Bug

**What went before:** Have Floccus running on desktop without any issues (i.e. syncing to Nextcloud as expected). Desktop is using Floccus 4.19.1 (not sure how to update it to latest version, and reluctant anyway given the current issue). Nextcloud is hosted on local server on the LAN.

**Current issue:** 
**Once I try to sync I get "E017: Network error: check your network connection and your account details"**, even though the network connection seems to be fully operational (Nextcloud is syncing + everything works from the browser with the same address and account details).

### Expected Behavior

Same syncing behaviour as on the desktop.

### To Reproduce

1. **Wanted to set up Floccus on laptop** so it syncs with desktop bookmarks via Nextcloud.
2. Note: laptop is also synching with Nextcloud without any issues for a long time already (both via LAN or via VPN when remote).
3. Laptop is on same LAN. Alternatively, it can connect via VPN to the server to access the LAN (tried both while troubleshooting this issue, wireguard or not does not make a difference) and thus sync with Nextcloud, which works as intended.
4. When installing Floccus using the exact same login as on the desktop etc. I get sent from the setup process of Floccus to the Nextcloud portal in my browser to grant access (which seems to confirm that the address is correct).
5. **Once I try to sync I get "E017: Network error: check your network connection and your account details"**, even though the network connection seems to be fully operational (Nextcloud is syncing + everything works from the browser with the same address and account details).

### Debug log provided

- [ ] I have provided a debug log file

**Comment by Nietzscheanman** [comment]
Update: no longer syncing on desktop either (nothing changed to settings etc.).

**Comment by marcelklehr** [comment]
Hi @Nietzscheanman 
I'm sorry for the troubles.

Can you try the following?

#### Firefox
* Go to `about:debugging`
* go to "This firefox"
* click on `Inspect` button next to floccus entry
* go to the network tab in the inspector
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome / Chrome-based
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests

**Comment by Nietzscheanman** [comment]
Hello,

Inspect views does not list the option you refer to

![image](https://github.com/floccusaddon/floccus/assets/148869219/7b3d2d78-ba65-42d5-9d0b-14a5c2d2ebed)

I Think I did find what you were referring to however:
![image](https://github.com/floccusaddon/floccus/assets/148869219/e6cfb871-70d4-4902-b112-3226f4daa02c)

**Comment by marcelklehr** [comment]
CERT_AUTHORITY_INVALID means your SSL/TLS setup is broken

**Comment by Nietzscheanman** [comment]
There is no SSL certificate, it just runs on the LAN so figured not worth the hassle (and it used to work before with Floccus)?

**Comment by marcelklehr** [comment]
> Floccus will not let me create an account with an http address.

It warns you, but it should still work.

Can you check the response body of that 400 Error to see what it says?

**Comment by Nietzscheanman** [comment]
Hello,

No it will not let me create the account (it indeed shows the warning but then nothing happens when clicking "connect"). I can create an https one and then remove the s in the option menu, thus triggering the 400 error.

![image](https://github.com/floccusaddon/floccus/assets/148869219/9ebd7958-5d38-42cb-89b5-d34fc34e3147)

There is a 2nd one as well with request method "delete" instead of "post".

Thanks

**Comment by marcelklehr** [comment]
Can you show the Request body tab?

**Comment by Nietzscheanman** [comment]
![image](https://github.com/floccusaddon/floccus/assets/148869219/2cc66311-0030-4256-a775-cf00c6ae4774)

**Comment by marcelklehr** [comment]
I mean the  Request body and response body of the network request :)

**Comment by Nietzscheanman** [comment]
Do you mean this?

![image](https://github.com/floccusaddon/floccus/assets/148869219/dcc74f5b-64e0-40d7-b8d5-b07c463d778a)

**Comment by marcelklehr** [comment]
When examinig a network request in the Netowrk tab there is usually a sub tab line where you can see request and response bodies

**Comment by Nietzscheanman** [comment]
The only thing I can additionally find here is that it says "The plain HTTP request was sent to HTTPS port" (not an IT guy as you may have noticed :)

**Comment by marcelklehr** [comment]
> The plain HTTP request was sent to HTTPS port

that's not good. If you don't use HTTPS you shouldn't use that HTTPS port

**Comment by Nietzscheanman** [comment]
OK, not sure what changed because it used to work before with the same port :/

Anyway, I think it probably means no more Floccus for me since I lack the technical knowhow to set up an http port for Nextcloud via docker. Tried looking around a bit already and will look into it a bit more but I don't want to mess up my Nextcloud somehow.

Thanks for the responses.
