### ISSUE TITLE
Couldn't authenticate with the server

### ISSUE THREAD

**Issue by barnycloud** [floccusaddon/floccus#1552]
### Which version of floccus are you using?

5.0.9

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome (122.0.6261.95)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

6 (27.1.5)

### Describe the Bug

In my Chrome Browser the error appears in the floccus extension:  E018: Couldn't authenticate with the server. Synchronizing is not possible snce 2 weeks. The OS Chrome is using Windows 11 (22H2, Build 22621). In a Laptop using Win 10 (22H2 (Build 19045) and the same Chrome Browser version, everything works fine. In MS edge browser everything works, too)

### Expected Behavior

Synchronizing the boomarks

### To Reproduce

Two weeks ago, the same problem was present. Deinstalling the floccus extension and reinstalling helped for a short time.
As mentioned above, in an other PC using Win 10 and in MS Edge synchronizing the bookmarks worked fine.

### Debug log provided

- [X] I have provided a debug log file

**Comment by barnycloud** [comment]
Addendum:
The problem is spreading. I am now getting this message from Edge: E033: Redirect detected. Please make sure the server supports the selected sync method and URL you entered is correct doesn't redirect to a different location. If the redirect is part of your setup, you can disable this check in the settings.. Edge also runs under Windows 11.

**Comment by marcelklehr** [comment]
Is there anything in your Nextcloud or local machine setup that changed 2 weeks ago? An update of some sort, perhaps?

**Comment by barnycloud** [comment]
Thank You for Your response.
In Chrome synchronising is not successfull since thre weeks. In Edge the problem seemed to be present since three days, but the error message says 2 weeks
Until now this problem seems to be present only the Windows 11 machine. Two days ago Windows 11 crashed, but the backup could restore it. On the server nothing was changed. On the the Windows 11 machine (Fujitsu Esprimo) the usual updates were done. 
Today I will get a Mac Mini device (I hope the Windows trouble will get to an end) and we will see (running the Edge browser on it).

**Comment by marcelklehr** [comment]
Can you try debugging the network requests as follows?

## How to debug network

#### Firefox
* Go to `about:debugging`
* go to "This firefox"
* click on `Inspect` button next to floccus entry
* go to the network tab in the inspector
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests

**Comment by barnycloud** [comment]
Thank you for your answer. I have not been able to take care of the problem for the last few days. I can only find the entry in Chrome at chrome://extensions: 
Ansichten prüfen ServiceWorker
When I click on 'Service Worker', I see a list under Network. I honestly don't know how to get to 'Sync Now'.
A screenshot:

![Screenshot 2024-03-06 104715_floccus](https://github.com/floccusaddon/floccus/assets/10930712/33a5e66e-eb91-478f-b969-a604b9df9367)
.

**Comment by marcelklehr** [comment]
![image](https://github.com/floccusaddon/floccus/assets/986878/eb5a646a-9e28-45b3-b05d-73b3111d9ff8)


"Sync now" is simply the blue sync button of your profile in the floccus UI

**Comment by marcelklehr** [comment]
Can you make sure the bookmarks app is still installed on your server?

**Comment by barnycloud** [comment]
Thank You for the information.
The 'bookmark' app is still installed on the nextcloud server. And in other operating systems floccus is working, for example in Firefox running on Mac OS Sonoma, and in Chromium running on Linux Ubuntu. The problem seems to be Windows 11, I suppose.

**Comment by barnycloud** [comment]
I have updated the floccus addon in Chrome (running in Windows 11) to version 5.0.10 . But the problem persists. In Firefox everything (floccus version 5.0.10) is working as well in Windows 11 as in Mac OS Sonoma. In MS Edge running on Windows 11 floccus addon is working as well.

**Comment by barnycloud** [comment]
I read that You wait for more information. What further information do You need.?Thge screenshot shown above, is it not enough?

**Comment by barnycloud** [comment]
Thank you very much for your comment. The problem only occurs with Chrome under Windows 11. I do not use WLAN on this PC, it is connected via a network cable. I can access the Nextcloud website here with Chrome without any problems.

**Comment by marcelklehr** [comment]
Mmh, very strange. Can you investigate some more in chrome://extensions ? Eg. you should be able to click on the requests with statuses 401 and 307 and see the sent and received data as well as the sent and received headers. Make sure to anonymize sensitive data before posting here.

**Comment by barnycloud** [comment]
It's really strange. I have now removed the floccus addon from Chrome (Windows 11) and added it again. Then I exported the settings / profile from the floccus addon in Chromium (Kubuntu) and imported it into Chrome (Windows 11). And lo and behold, floccus works in Chrome (Windows 11), at least so far. Other addons that I have running in Chrome (Windows 11), such as SiteBar, Zotero, FoxitReader among others, have no problems (as far as I can tell). I will continue to report, hopefully only good things.

**Comment by barnycloud** [comment]
I now have floccus working with Firefox on Windows and Mac. No problem. After I uninstalled and reinstalled floccus in Chrome (version 123.0.6312.122) on Windows 11, floccus synchronises without any problems.

**Comment by wwdok** [comment]
This issue still exists in v5.2.7 when I add new bookmark and click the push button
![image](https://github.com/user-attachments/assets/9f7eb5d8-ae50-480c-9251-a88d48b62544)
This is part of the log:
```
2024-09-12T11:51:59.399Z Starting sync process for account floccus_bookmarks
2024-09-12T11:51:59.410Z onSyncStart: begin
2024-09-12T11:51:59.410Z https://dav.jianguoyun.com/dav/Floccus/bookmarks.xbel.lock
2024-09-12T11:51:59.503Z Setting lock: https://dav.jianguoyun.com/dav/Floccus/bookmarks.xbel.lock
2024-09-12T11:51:59.735Z onSyncStart: completed
2024-09-12T11:51:59.741Z Failed to load pending continuation. Continuing with normal sync
2024-09-12T11:51:59.741Z Using "merge overwrite" strategy (no cache available)
2024-09-12T11:51:59.741Z Retrieving local tree
2024-09-12T11:51:59.752Z Overriding title of built-in node 1 书签栏 => Bookmarks Bar
2024-09-12T11:51:59.767Z Filtering out unaccepted local bookmarks
2024-09-12T11:51:59.768Z Retrieving server tree
2024-09-12T11:51:59.769Z Filtering out invalid server bookmarks
2024-09-12T11:51:59.769Z Generating indices for local tree
2024-09-12T11:51:59.771Z Generating indices for cache tree
2024-09-12T11:51:59.771Z Generating indices for server tree
2024-09-12T11:51:59.771Z { localTreeRoot: 
...
2024-09-12T11:51:59.856Z Executed 51 actions from 56 actions
2024-09-12T11:51:59.856Z Executed 52 actions from 56 actions
2024-09-12T11:51:59.856Z Executed 53 actions from 56 actions
2024-09-12T11:51:59.856Z Executed 54 actions from 56 actions
2024-09-12T11:51:59.856Z Executed 55 actions from 56 actions
2024-09-12T11:51:59.856Z Executed 56 actions from 56 actions
2024-09-12T11:51:59.867Z Overriding title of built-in node 1 书签栏 => Bookmarks Bar
2024-09-12T11:51:59.891Z onSyncComplete
2024-09-12T11:52:00.141Z Syncing failed with E018: Couldn't authenticate with the server.
2024-09-12T11:52:00.142Z onSyncFail
2024-09-12T11:52:00.142Z Freeing lock: https://dav.jianguoyun.com/dav/Floccus/bookmarks.xbel.lock
```
I am sure I paste the ritght dav password
