### ISSUE TITLE
Kiwi browser (Android) WebDav - "could not find an active window"

### ISSUE THREAD

**Issue by hugofant** [floccusaddon/floccus#1553]
### Which version of floccus are you using?

V5.0.9

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Kiwi (Android)

### Describe the Bug

installation worked well, but when configuring Webdav error message "could not find an active windows" appears. 
Same procedure and same connection data work well on PC (firefox and also chromium).

### Expected Behavior

verifying data and connecting to webdav server

### To Reproduce

fresh install and start configuration

### Debug log provided

- [ ] I have provided a debug log file

**Comment by tomsik-radek** [comment]
I'm seconding this issue. Kiwi 120.0.6099.116, Floccus extension 5.0.9. Lenovo P11 Gen2, Android 13

**Comment by tomsik-radek** [comment]
> ### Which version of floccus are you using?
> 
> V5.0.9
> ### Sync method
> 
> WebDAV
> ### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.
> 
> Kiwi (Android)
> ### Which version of Nextcloud Bookmarks are you using? (if relevant)
> 
> _No response_
> ### Which version of Nextcloud? (if relevant)
> 
> _No response_
> ### What kind of WebDAV server are you using? (if relevant)
> 
> _No response_
> ### Describe the Bug
> 
> installation worked well, but when configuring Webdav error message "could not find an active windows" appears. Same procedure and same connection data work well on PC (firefox and also chromium).
> ### Expected Behavior
> 
> verifying data and connecting to webdav server
> ### To Reproduce
> 
> fresh install and start configuration
> ### Debug log provided
> 
>     * [ ]  I have provided a debug log file

I _kinda_ got around this. Log into the Android app, export your profile and import it into the Kiwi extension. I had to mess with folder mapping a bit, but it is now syncing.

**Comment by marcelklehr** [comment]
This is an upstream issue with Kiwi. Please report it to its developers

**Comment by tomsik-radek** [comment]
> This is an upstream issue with Kiwi. Please report it to its developers

Do you have anything we can give them to report this? Because I (and probably them) have no clue what "could not find an active window" means

**Comment by marcelklehr** [comment]
It's definitely not an error message from floccus. I believe it occurs when using the browsers chrome.permissions.contains API
