### ISSUE TITLE
Invalid value for origin pattern

### ISSUE THREAD

**Issue by LannyChung** [floccusaddon/floccus#1554]
### Which version of floccus are you using?

5.0.9

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 122.0.6261.112

### What kind of WebDAV server are you using? (if relevant)

 https://dav.jianguoyun.com/dav/

### Describe the Bug

I have encountered a problem when I synchronized my bookmarks. The error message is as follows, but the configuration is correct. I could use it norm
![微信截图_20240306155247](https://github.com/floccusaddon/floccus/assets/53028653/393e4e91-91dc-4918-b616-6ef68bb46f13)
![微信截图_20240306155325](https://github.com/floccusaddon/floccus/assets/53028653/e474bdae-bbe0-4b4d-b8d6-a15227aee823)
![微信截图_20240306155401](https://github.com/floccusaddon/floccus/assets/53028653/7e2c8a16-34d8-4c21-884d-e10bb0242589)

### Expected Behavior

normal synchronization

### To Reproduce

*

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi :wave: 

What is the value of the bookmarks file setting? Have you entered `dav://` into any settings fields?

**Comment by LannyChung** [comment]
> Hi 👋
> 
> What is the value of the bookmarks file setting? Have you entered `dav://` into any settings fields?

Bookmark path: floccus/bookmarks.xbel.
 I'm sure there is no path containing dav://.
 And it was working before, but suddenly it stopped working without any configuration changes.

**Comment by ease-zh** [comment]
+1

**Comment by marcelklehr** [comment]
mmmh. It might not be because of the config. Perhaps the url is in one of your bookmarks that's causing this.

**Comment by minjun98** [comment]
这是一个很狗血的BUG，就是在初始设置的时候不要删除掉他自带的https:// 开头，只要把后面的地址填上去就好了，如果在初始设置的时候没有提醒是最好的，这个BUG我一时间不知道该怎么评价

**Comment by marcelklehr** [comment]
@minjun98 Sorry, I don't understand. Even translation didn't help :S

**Comment by LannyChung** [comment]
> 这是一个很狗血的BUG，就是在初始化设置的时候不要删掉他自带的https://开头，只要把后面的地址填上去就好了，如果在初始化设置的时候没有提醒是最好的的，这个BUG我一时间不知道怎么评价

我的 mac 设备上可以正常使用，但 windows 设备就会出现这个问题，并未做初始化设置，而是通过导出账户，导入账户进行操作的

**Comment by marcelklehr** [comment]
Should be fixed in the latest version now.

**Comment by LannyChung** [comment]
> Should be fixed in the latest version now.

After testing, it can be used normally.
