### ISSUE TITLE
Android App Stuck on Splash Screen

### ISSUE THREAD

**Issue by Hamster45105** [floccusaddon/floccus#1557]
### Which version of floccus are you using?

5.0.10

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 14 - One UI 6.0 (Galaxy A54)

### What kind of WebDAV server are you using? (if relevant)

OwnCloud

### Describe the Bug

Opening the app just takes you to the splash screen with the app icon and nothing happens. It was working perfectly fine before I updated the app to 5.0.10

Screenshot:

![Screenshot_20240309_164320_floccus bookmark sync](https://github.com/floccusaddon/floccus/assets/133548095/9845fa04-e96f-418d-ade8-d91d96e9932a)

Seems to be similar to: https://github.com/floccusaddon/floccus/issues/1510

### Expected Behavior

The app should open normally.

### To Reproduce

1. Open app

### Debug log provided

- [ ] I have provided a debug log file

**Comment by 1Dimension1** [comment]
+1

**Comment by roamer4223** [comment]
Same issue

**Floccus version:** 5.0.10

**Sync method:** Google Drive

**OS & Device:** GrapheneOS (Android 14) on Pixel 8 Pro

Apology if this is unhelpful as my coding knowledge is not currently up to scratch in this area but in the logs I see this sort of thing repeating constantly:

1709979513.299  8656  8656 I auditd  : avc=type=1400 audit(0.0:10775): avc:  denied  { read } for  comm="deideas.floccus" name="u:object_r:odsign_prop:s0" dev="tmpfs" ino=350 scontext=u:r:untrusted_app_32:s0:c230,c256,c512,c768 tcontext=u:object_r:odsign_prop:s0 tclass=file permissive=0 app=org.handmadeideas.floccus



Hope that helps. Haven't commented much on Github so, again, sorry if I am commenting in an unusual/unhelpful manner

**Comment by marcelklehr** [comment]
Damn. I'm sorry. This should only affect beta testers, though. I'll push out a fix soon.

**Comment by roamer4223** [comment]
@marcelklehr  No apology needed on my end! Thank you and let me know if you'd like more logs or anything from me.

**Comment by marcelklehr** [comment]
v5.0.11 is out

@roamer4223 If you don't mind me asking, how do you get the app? fdroid or direclty from github?

**Comment by Hamster45105** [comment]
Thanks for fixing it so quickly!

I can confirm it's working again for me now.

**Comment by roamer4223** [comment]
> v5.0.11 is out
> 
> @roamer4223 If you don't mind me asking, how do you get the app? fdroid or direclty from github?

Wow thank you for the quick fix, all working now. I get the app directly from Github using 'Obtainium'. Thanks again, awesome project by the way!
