### ISSUE TITLE
SYNOLOGY NAS - E019: HTTP status 405. Failed PUT request

### ISSUE THREAD

**Issue by pferronato** [floccusaddon/floccus#1561]
### Which version of floccus are you using?

5.0.10

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave

### What kind of WebDAV server are you using? (if relevant)

2.4.5-10131

### Describe the Bug

trying the sycronization I got:
E019: HTTP status 405. Failed PUT request. Check your server configuration and log. Last synchronized: 0 seconds ago

logs:
2024-03-13T14:35:56.454Z Starting sync process for account webdav@ironborn65.synology.me
2024-03-13T14:35:56.456Z onSyncStart: begin
2024-03-13T14:35:56.457Z https://ironborn65.synology.me:5006/bookmarks.xbel.lock
2024-03-13T14:35:56.473Z https://ironborn65.synology.me:5006/bookmarks.xbel.lock
2024-03-13T14:35:56.483Z Syncing failed with E019: HTTP status 405. Failed PUT request. Check your server configuration and log.
2024-03-13T14:35:56.483Z onSyncFail

### Expected Behavior

to syncronize

### To Reproduce

add webDAV extension to Synology DSM 7.1.1-42962 Update 6
"WebDAV Server allows users to edit and manage files stored on the remote servers."
configure user-password + folder + permissions

it's all fine because I can connect using CyberDuck and drop files in the 'bookmarks' dedicated shared folder using the ad-hoc account created

Synology log shows nothing when trying the sync with floccus

thanks for the support you can give

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Your webdav URL is likely wrong, you may need to add a subfolder or something else is wrong. WebDAV in floccus works fine according to my automated tests, so it doubt it's a problem on the floccus end. Sorry.
