### ISSUE TITLE
floccus starts to a blank screen and never recovers

### ISSUE THREAD

**Issue by alinanorakari** [floccusaddon/floccus#1563]
### Which version of floccus are you using?

5.0.9 Android

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 123.1.0 on a Google Pixel 4a with GrapheneOS sunfish-factory-2024021100 using Android 13

### Which version of Nextcloud? (if relevant)

27.1.4

### What kind of WebDAV server are you using? (if relevant)

Self-hosted NextCloud 27.1.4

### Describe the Bug

No matter how often I use the back gesture, force stop floccus and floccus bookmark sync or reboot my phone, it will show a splash screen with the floccus icon (which I think comes from the OS itself), then immediately fade to that entirely blank black screen (white in light mode) with the only thing being displayed being the phone's status bar and the phone's bottom indicator for swiping up.

### Expected Behavior

I expected floccus, after importing my json, to continue into any sort of UI, be it a sync screen, or further setup. In case of an error I expected floccus to display and error and provide a way to mitigate and try again, maybe provide some error code or similar that I could use in a search or an issue.

### To Reproduce

- Install floccus bookmark sync (5.0.9) in F-Droid from the F-Droid repository on a Pixel 4a running GrapheneOS release [sunfish-factory-2024021100](https://releases.grapheneos.org/sunfish-factory-2024021100.zip)
- import my json (can I upload this privately somewhere?)
- Confirm the "Successfully imported profile(s)" with OK
- still on the export/import screen now showing both profiles for export, tap the hamburger menu and tap the first of the two profiles in the menu (either Firefox root bookmarks folder or tabs, the UI doesn't distinguish between the two because they share the same login name)
- the screen will go blank (white or black depending on Android's dark mode toggle) and no gestures, closing and reopening, force stopping of floccus and floccus bookmark sync or phone rebooting will get floccus out of that screen

### Debug log provided

- [ ] I have provided a debug log file

**Comment by alinanorakari** [comment]
Thank you. I'll roll back for now

**Comment by marcelklehr** [comment]
You may not need to rollback, https://github.com/floccusaddon/floccus/releases/tag/v5.0.11 is out

**Comment by j-lakeman** [comment]
5.0.11 solved it for me. Cheers @marcelklehr!

**Comment by alinanorakari** [comment]
Downgrading didn't solve it and 5.0.11 doesn't solve it for me, either. I tried updating directly and also uninstalling and installing, then doing the import again. I just want to sync my bookmarks and tabs 😭

**Comment by alinanorakari** [comment]
Just to be extra clear, it hasn't worked for me on Android at all so far. I'm a recent convert from iOS to Android

**Comment by alinanorakari** [comment]
https://github.com/floccusaddon/floccus/assets/4239297/486240b3-ef73-4a6e-8248-8ca0f5a3559e

I recorded a video of my steps because I can't be sure I'm not doing anything wrong. Please let mW know if there is anything I should do differently

**Comment by marcelklehr** [comment]
Hi @alinanorakari 
I'm sure we'll get to the bottom of this. Could you send me your floccus export json file via https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw ?

**Comment by marcelklehr** [comment]
Thank you for providing the file. You have a tabs profile in your export, which is likely causing problems. The android app has no notion of tabs.

As a quick fix you can

1. Stop the app
2. Remove all stored data from the app
3. Re-export your profiles, this time without the tabs profile
4. Import again
5. Manually create a replica of the tabs profile in the android app

I'll soon fix the app so that tabs profiles will be converted to normal ones upon import.
