### ISSUE TITLE
Doesn't work on kiwi android.

### ISSUE THREAD

**Issue by moon16u** [floccusaddon/floccus#1564]
### Describe the feature you'd like to request

I hope to support kiwi android, thanks!
When syncing on kiwi android, it says "Could not find an active window."

### Describe the solution you'd like

I hope to support kiwi android, thanks!

### Describe alternatives you've considered

I hope to support kiwi android, thanks!

**Comment by marcelklehr** [comment]
This is a kiwi bug. You can report this to them. Tell them ['chrome.permissions.contains'](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/contains) doesn't work
