### ISSUE TITLE
Bookmarks destroyed, backups can't be loaded

### ISSUE THREAD

**Issue by timcurran** [floccusaddon/floccus#1566]
### Which version of floccus are you using?

5.0.10

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Edge Version 122.0.2365.92 (Official build) (64-bit)

### Describe the Bug

Today I found that my bookmark order was suddenly scrambled, with at least one critical folder missing. First move was to go to a backup (i.e. a previous version stored by Google Drive). 

None of the previous ten versions would load (except a couple of the most recent, which all had the same missing/scrambled folders). Instead of loading, they created Google Drive files with the same exact name, only much, much smaller (e.g. 130KB vs 450 bytes) and no bookmarks at all. 

I finally tried a month-old stored backup which happens to be unencrypted (i.e. a pure, human-readable XML version of the XBEL file). In order to load it, I removed the passphrase. Now I get the error "E034: Remote bookmarks file is unreadable. Did you forget to set an encryption passphrase? Last synchronized: 2 hours ago" In other words, Floccus won't load an *unencrypted* version of its own file format. Something is obviously very wrong.

What can I do to recover my bookmarks?

### Expected Behavior

Floccus to sync all bookmarks in order and load previous files that have the same passphrase.

### To Reproduce

1. Load a previous version of bookmarks.xbel to Google Drive (I suspect to reproduce, you'll have to use an xbel created under a *previous version* of Floccus). Give it a slightly different name (e.g. bookmarks-1.xbel).
2. Change the filename in the "Server Details" setting tab to match.
3. Attempt a Pull Down Once sync.
4. All your bookmarks will suddenly disappear and there will be an empty duplicate-name file on Google Drive.
5. Follow the same steps with a passphrase-free (unencrypted xbel). Intead of the duplicate file, you'll get ....
6. Debug log will say something like this:

`2024-03-19T23:15:40.599Z Starting sync process for account Google Drive: bookmarks 2-11-24.xbel`
`2024-03-19T23:15:40.603Z onSyncStart: begin`
`2024-03-19T23:15:41.454Z Syncing failed with E034: Remote bookmarks file is unreadable. Did you forget to set an encryption passphrase?`
`2024-03-19T23:15:41.463Z onSyncFail`

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi,

floccus cannot read arbitrary files on your Drive, but only files it created itself. So, you will have to copy the contents of one of your backup files into a file created by floccus.

**Comment by timcurran** [comment]
Sorry if I wasn't clear. The file I refer to IS a floccus-created xbel
file. It's just unencrypted.

----
Tim Curran
Home/Cell 917-208-5321
email: ***@***.***
web: www.timcurran.com
LinkedIn: linkedin.com/in/currannews/
Skype (Video): tacurran

Message sent from my Samsung Android. Damn you, autocorrect!

**Comment by timcurran** [comment]
I've attached the file I was referring to.

  bookmarks 2-11-24.xbel
<https://drive.google.com/file/d/1clrFmx5xoZuRnGemaWwnn2DHpKA42jRB/view?usp=drivesdk>



----
Tim Curran
Home/Cell 917-208-5321
email: ***@***.***
web: www.timcurran.com
LinkedIn: linkedin.com/in/currannews/
Skype (Video): tacurran

Message sent from my Samsung Android. Damn you, autocorrect!

**Comment by marcelklehr** [comment]
So, I would recommend the following steps to recover:

1. Load a previous version of bookmarks.xbel to Google Drive. Instead of giving it a different name or somesuch, copy the old file contents into the current bookmarks.xbel that is synced by floccus. The old floccus file will need to be encrypted just like the current file.
2. Do not change the file name in the server details settings 
3. Attempt a Pull Down Once sync

If you only have unencrypted backups, you will need to disable encryption in floccus before following the steps.

**Comment by timcurran** [comment]
After my initial report, I discovered that the Floccus app on my phone had
a relatively recent copy of the bookmarks. And, as a bonus, the app permits
exporting an html bookmark file. So was able to reconstruct my bookmarks.

I was mainly trying to report a possible bug. But if you haven't received
any other similar reports, it may just be a fluke with my setup.

Thanks for your help.


*Tim Curran*
*Home/Cell 917-208-5321 *
*email: ***@***.*** ***@***.***>*
*web: www.timcurran.com <http://www.timcurran.com>*
*LinkedIn: linkedin.com/in/currannews/
<http://www.linkedin.com/in/currannews/>*
*Skype (Video): tacurran*

(IF TEXT IS IN ALL CAPS, I'M NOT YELLING. IT'S BECAUSE THAT IS HOW WE ROLL
WHEN SCRIPTING TV NEWS)

**Comment by marcelklehr** [comment]
Ah, that's great. Closing
