### ISSUE TITLE
Android app never gets past splash screen

### ISSUE THREAD

**Issue by rudism** [floccusaddon/floccus#1567]
### Which version of floccus are you using?

5.0.11

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 12 XTRONS head unit for car

### Describe the Bug

On the Android 12 head unit in my car, when I launch Floccus (tried both f-droid and play store versions) it just sits forever on the white splash screen with a blue cloud check mark icon in the center and never advances into the app, even after several minutes of waiting.

### Expected Behavior

The app should finish launching and let me set up my sync options.

### To Reproduce

This is a stock, non-rooted Android 12 XTRONS head unit installed in the dashboard of my car. Not sure how you could reproduce (I have several other Android devices and floccus works fine on all of those). I can't produce floccus debug logs from the head unit since I can't get past the splash screen to configure the sync settings, but I used a LogCat app on the device to capture these logs from floccus when I launch it, in case it gives some clue to what's going on.

[23_03-14-29-59_649.log](https://github.com/floccusaddon/floccus/files/14733440/23_03-14-29-59_649.log)

I tried removing and reinstalling, restarting the unit, clearing the app's cache, and made sure all permissions are granted, but have never gotten past the white splash screen with the logo in the center.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by rudism** [comment]
Based on this error:

```
1711222207.586 10110 21066 21066 E Capacitor/Console: File: http://localhost/js/native.js - Line 2 - Msg: Uncaught ReferenceError: globalThis is not defined
```

My best guess is the webview on that device is too old (it's v60-something, I forget exactly). It has its own `com.android.webview` package that doesn't update with Google's version from the play store so it seems to be locked in, as the device itself is very unlikely to get any software updates from the manufacturer. Possible solution that I found involves adding some polyfills to get capacitor working on older webview versions:

https://forum.ionicframework.com/t/problems-with-white-screen-after-splash-screen-on-android-7-and-below-ionic-7-with-angular/238019

**Comment by marcelklehr** [comment]
I added support for Android Chrome v60+, hopefully that works
