### ISSUE TITLE
Android: Assign and change a nickname to each probile

### ISSUE THREAD

**Issue by andbenn** [floccusaddon/floccus#1569]
### Describe the feature you'd like to request

I would like to assign a nickname and be able to edit nicknames for my floccus profiles on Android.  Obviously I should not not be able to rename one that would cause a duplicate.

### Describe the solution you'd like

I'm using webdav, so my profile names look something like this in the UI:

user@email.com@somesit....

As I have a couple profiles, these repeat.  I'd like to be able to give each a nickname, such as "Firefox Work Bookmarks" or "Brave desktop tabs"

This would help me realize what profile to choose to find something.

Even cooler, the name persists with the data, such that changing a nickname in a browser or mobile changes the other upon next sync.

### Describe alternatives you've considered

Guesswork by selecting a profile and determining what it is.  Bookmarks or tabs?  work or desktop or laptop ?

**Comment by marcelklehr** [comment]
Great idea! This has already been requested here #1294 and will be implemented soon :)
