### ISSUE TITLE
E017: Network error: Check your network connection and your account details Last synchronized

### ISSUE THREAD

**Issue by BashBandito** [floccusaddon/floccus#1570]
### Which version of floccus are you using?

5.0.10

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Floorp 11.11.2, Vivaldi 6.6.3271.55, Android 14

### What kind of WebDAV server are you using? (if relevant)

Using WebDAV Server on Synology NAS

### Describe the Bug

Shortly after successfully setting up floccus, I receive this error whenever I open the extension. I try to manually sync and it continues to show the same error message. Sometimes it will suddenly sync and the error goes away but for the most part the error is persisting.

E017: Network error: Check your network connection and your account details Last synchronized

### Expected Behavior

I expect floccus to sync, whether it's the automatic sync or manual sync.

### To Reproduce

All I am doing is launching the browser and checking the floccus extension on both floorp and vivaldi. The same occurs when checking the android app.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi

Are you using a self-signed certificate for your webdav server?

**Comment by marcelklehr** [comment]
You are using a self-signed letsencrypt certificate? That sounds like an oxymoron to me :thinking: 

Did you get the certificate from letsencrypt? Or did you generate it yourself without enlisting a commonly known Certificate Authority?

**Comment by marcelklehr** [comment]
Is currently out on F-Droid and in open testing phase on google play and will soon be on production in google play as well

**Comment by Eschguy** [comment]
just started getting this error on Firefox.

**Comment by marcelklehr** [comment]
Very strange

**Comment by marcelklehr** [comment]
Can you rule out Adblockers , other addons or any kind of proxy?

**Comment by marcelklehr** [comment]
Can you check the extension permissions for floccus in chrome://extensions to see whether it can access the network?

**Comment by marcelklehr** [comment]
It really seems like it's a network thing, but I assume you have ruled that out already, otherwise you wouldn't be here. Maybe it's a browser bug? Can you try with firefox, perhaps?

**Comment by los0220** [comment]
I've had the same error for over a month with self-signed cert and NextCloud bookmarks. When I click `DEBUG LOGS`, they are empty. 
I tried reinstalling the extension and reconnecting without any luck.

**Comment by marcelklehr** [comment]
@los0220 Chrome does not allow self-signed certificates anymore in extensions it seems. So, I recommend using a let's encrypt cert.

**Comment by marcelklehr** [comment]
@iamhaval Perhaps you can dig into the network debug inspector a bit in your browser? 

#### Firefox
* Go to `about:debugging`
* go to "This firefox"
* click on `Inspect` button next to floccus entry
* go to the network tab in the inspector
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `Service Worker` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests

**Comment by marcelklehr** [comment]
I don't know the answer to these questions. If you debug the network requests in the browser debugger you may find the cause for the failed network requests from the perspective of the browser.

**Comment by marcelklehr** [comment]
Is there some kind of exaplanation somewhere in the inspector interface why the requests fail when using HTTPS?

**Comment by marcelklehr** [comment]
I think it's likely related to your SSL config. Can you try checking the config using `openssl s_client -connect example.com:443` if you're on Linux.

**Comment by marcelklehr** [comment]
@iamstonecutter ping

**Comment by marcelklehr** [comment]
> Is it safe to paste the terminal output of that command in here?

I believe so

**Comment by marcelklehr** [comment]
mh, looks alright, indeed

**Comment by marcelklehr** [comment]
In the Network debugger above, can you see a column called "status", this should tell us why the request failed.

**Comment by marcelklehr** [comment]
Thank you for the screenshot. Since it says ERR_NAME_NOT_RESOLVED, it would seem to be a DNS issue then :thinking:

**Comment by marcelklehr** [comment]
I researched this a bit and it seems that perhaps chrome is running out of sockets:

When this happens, can you try

1. a dns cache flush which can be done on: chrome://net-internals/#dns
2. a flush of socket pools which can be done on chrome://net-internals/#sockets

**Comment by marcelklehr** [comment]
> Just curious, are you thinking that it might be the browser? I ask this because it also happens with Firefox.

Oh. So far I've assumed it only happens with Chrome, because I have the same error in my chrome tests for Nextcloud Bookmarks, but I cannot reproduce this locally.

DNS would indicate it may be a problem with Pi-hole or Tailscale, yes, although I'm also using pi-hole at home without problems.

**Comment by marcelklehr** [comment]
For your other self-hosted apps do you have browser extensions that interface with them as well?

**Comment by sunjam** [comment]
fyi, this is the exact same message displayed by the Floccus app on Android if it is in airplane mode and attempting to sync with the internet disabled.

**Comment by marcelklehr** [comment]
Mmmh, all very strange, I think the airplane mode is likely not the culprit, thanks for the fyi, though, @sunjam :)
