### ISSUE TITLE
WebDAV lock not removed after 30 min; icon doesn't indicate a problem

### ISSUE THREAD

**Issue by andbenn** [floccusaddon/floccus#1572]
### Which version of floccus are you using?

5.0.10

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave

### What kind of WebDAV server are you using? (if relevant)

To/From my Fastmail account

### Describe the Bug

I have Brave syncing it's tabs to a profile.  This is the only browser using this profile - it's not shared.
Somehow a .lock file appeared for this profile from a previous day.  Upon waking up, floccus tried to sync, and continues to wait.  it's been over an hour.

Does the lock removal code work for WebDAV?  These shouldn't last this long, should they?

I did restart my browser and the .lock file is still there.

Related, the plugin icon in the browser bar is in the OK state.  It should probably be in the X state indicating at least one profile error.

### Expected Behavior

Lock file to be removed after half hour (per online docs)

### To Reproduce

Set up a profile to sync tabs to a webDAV source
Generate or capture a lock file
Copy captured file to block a sync
Attempt a sync for this profile
// This profile will be synced soon. We're waiting for other devices of yours, or other profiles to this device to finish syncing
// after 30 mins pass, the lock file should be removed with a sync
// icon should show an X if any profile isn't working

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
In v5.x this has been increased to 2h. If it still isn't removed after that, this is a great find as so far I've assumed this symptom stems from multiple browsers consecutively locking each other out, but if you only have one browser, there might be a different reason for this.

**Comment by marcelklehr** [comment]
Hello @andbenn

Did this resolve itself by now?

**Comment by andbenn** [comment]
Hi @marcelklehr .  I let the lock exist and go for several days and the lock was not released.  I ended up deleting the .lock file for that profile from my folder view on the host of my webdav files (Fastmail).  I have not need it since, knock on wood.

**Comment by marcelklehr** [comment]
Mmh. Weird that it would not clear that up on its own... Closing this then for now. Feel free to shout here or open a new issue if this should resurface.
