### ISSUE TITLE
Cannot request origin permission for *://*/* since it was not declared in the manifest

### ISSUE THREAD

**Issue by mattdale77** [floccusaddon/floccus#1576]
### Which version of floccus are you using?

5.0.10

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Librewolf 122.0.1

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

28.0.4

### What kind of WebDAV server are you using? (if relevant)

N/A

### Describe the Bug

When trying to add a profile I type in my server name https://cloud.mysite.com but I get the following error and cannot proceed

Cannot request origin permission for *://*/* since it was not declared in the manifest

### Expected Behavior

I would expect to move on to enter my username and password and be able to create the profile

### To Reproduce

Install Floccus
Try to create profile
Enter https URL
Observe error

### Debug log provided

- [ ] I have provided a debug log file

**Comment by mattdale77** [comment]
Possibly related. In the extensions debug window there is a warning on the Floccus extension which may be related

Reading manifest: Warning processing browser_action.chrome_style: An unexpected property was found in the WebExtension manifest.

**Comment by nilsjor** [comment]
I am getting the identical error using Mullvad Browser. Posting my specs below:

### Which version of floccus are you using?

5.0.10
### Sync method

Nextcloud Bookmarks
### Which browser are you using?

Mullvad Browser 13.0.13 (based on Mozilla Firefox 115.9.1esr)
### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3
### Which version of Nextcloud? (if relevant)

Nextcloud Hub 5 (27.0.2)

**Comment by nilsjor** [comment]
To clarify, the same error appears if trying to use WebDAV as well. It seems it is not strictly related to the sync method, but rather the way requests are made.

Both Librewolf and Mullvad are security-focused browsers based on Firefox, so there may be some commonality there

It seems this may be related
https://www.extension.ninja/blog/post/solved-only-permissions-specified-in-the-manifest-may-be-requested/

**Comment by nilsjor** [comment]
Been conducting some tests with building the xpi locally, and replacing inside the various manifest files "*://*/*" with "<all_urls> and even explicitly the actual domain name of my server. The error code remains the same, which baffles me... 

There seems to be a file called `\dist\js\options.js` that is automatically generated when building. It has a segment
```js
await s.default.permissions.request({origins:["*://*/*"]})
```
and this does not seem to change, even when modifying the manifests.

On a side-note @mattdale77, a work-around that I was able to do for Mullvad Browser was to correctly configure a profile on a "vanilla" Firefox; export, then import that profile into Mullvad. **Note**: this will expose your password in plaintext in the exported json file...

**Comment by marcelklehr** [comment]
aaah. I think I've found the culprit. What's the user agent string of mullvad / librewolf?

**Comment by aiquiral** [comment]
> aaah. I think I've found the culprit. What's the user agent string of mullvad / librewolf?

After reading this, I was like “OMG, all I had to do was turn off my User Agent Switcher add-on on Firefox.” But no, that did not work. 

I can confirm that Floccus is working perfecly on Librewolf, but not on my hardened Firefox.

**Comment by aiquiral** [comment]
@nilsjor 

> a work-around that I was able to do for Mullvad Browser was to correctly configure a profile on a "vanilla" Firefox; export, then import that profile into Mullvad.

I tried something similar. I configured the profile on Android and then imported it to my hardened Firefox successfully. However, synchronisation is not working. It is stuck. Probably because it is throwing the same error in the background or something.

**Comment by nilsjor** [comment]
> aaah. I think I've found the culprit. What's the user agent string of mullvad / librewolf?

For Mullvad, it's the same at the Tor Browser.

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0

**Comment by marcelklehr** [comment]
> this does not seem to change, even when modifying the manifests.

You will need to adjust the code in the source files as well (in `src/`, you can grep for the line, it's the same line)

**Comment by marcelklehr** [comment]
I can confirm the behavior. I'm not sure if it's a bug or a feature, but either way it's most likely an issue with mullvad/librewolf. You may want to open an issue over at mullvad [github.com/](https://github.com/mullvad/mullvad-browser)
