### ISSUE TITLE
Support for js and file links for Nextcloud bookmarks

### ISSUE THREAD

**Issue by mio-19** [floccusaddon/floccus#1579]
### Describe the feature you'd like to request

I saw that recent Nextcloud Bookmarks added the support for javascript and file links. The current latest version of floccus shows that only http and ftp is supported for Nextcloud. I would like to request floccus to support js and file links for Nextcloud backend.

### Describe the solution you'd like

^

### Describe alternatives you've considered

N/A

**Comment by marcelklehr** [comment]
Yes, that's on my todo list :)

**Comment by marcelklehr** [comment]
See #1445
