### ISSUE TITLE
Instant sync option for local changes

### ISSUE THREAD

**Issue by Emporea** [floccusaddon/floccus#1581]
### Describe the feature you'd like to request

Whenever local changes are made, whether to a browser extension, Android app, etc., sync should be triggered immediately, or at least there should be an option to do so in the settings menu.

Davx5 also has this implemented and it works nicely and things work as expected.

### Describe the solution you'd like

Check for local changes, trigger a sync.

### Describe alternatives you've considered

lowering the sync interval, syncing manually etc.

**Comment by marcelklehr** [comment]
Syncing is currently triggered a few seconds after you make a change
