### ISSUE TITLE
Error: "Invalid value for origin pattern [...] Wrong scheme type"

### ISSUE THREAD

**Issue by yayaasd** [floccusaddon/floccus#1585]
### Which version of floccus are you using?

5.0.12

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Edge Version 124.0.2478.51 

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.0.2

### Which version of Nextcloud? (if relevant)

28.0.5

### Describe the Bug

after Update of Floccus, the sync stopped.
see debug log:
`2024-05-03T18:41:21.982Z Starting sync process for account USERNAME@null
2024-05-03T18:41:21.985Z Syncing failed with Invalid value for origin pattern https:/cloud.domain.com/: Wrong scheme type.
2024-05-03T18:41:21.986Z QUEUING DELETE https:/cloud.domain.com/index.php/apps/bookmarks/public/rest/v2/lock
2024-05-03T18:41:21.987Z FETCHING DELETE https:/cloud.domain.com/index.php/apps/bookmarks/public/rest/v2/lock
2024-05-03T18:41:22.058Z Receiving response for DELETE https:/cloud.domain.com/index.php/apps/bookmarks/public/rest/v2/lock`

### Expected Behavior

sync should work.

### To Reproduce

deleted profile and re-created - same behaviour

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
mh. Nothing was changed on the URL normalization front, though. Very weird :S

**Comment by marcelklehr** [comment]
Can you make sure you don't have a bookmark that contains `https:/cloud.domain.com/:` in the url part ?

**Comment by yayaasd** [comment]
nope - no bookmark with that.
the cloud.domain.com is the Nextcloud Server URL - I do not have this in my bookmarks.

also there is a problem with the timezone, maybe this is connected to this? 
`Failed to parse time string (cloud.domain.com Bookmarks (USERNAME) (14. Februar 2021)) at position 0 (c): The timezone could not be found in the database`

I already figured out to deploy the "timezone" variable due to this is needed from php8.2 --> but still an error there.

how to debug this?

**Comment by marcelklehr** [comment]
The timezone seems unrelated.

If you would be up for a bit of dabbling... you can access the console as follows:

#### Firefox
* Go to `about:debugging`
* Go to `This firefox`
* click on `debug` button next to floccus entry to open the console

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `Service worker` button in floccus' entry next to "Inspect views: " to open the console

**Comment by yayaasd** [comment]
what exactly do u need from that view?
see:
![image](https://github.com/floccusaddon/floccus/assets/8055381/91ae7fa3-6af1-498b-ab71-798b8693ecc9)

**Comment by marcelklehr** [comment]
hrm, the stack trace is scrambled because the code is minified :(

**Comment by marcelklehr** [comment]
Does this also happen on other browsers?

**Comment by yayaasd** [comment]
> Does this also happen on other browsers?

tryed firefox, the version there is still 5.0.10.
no other browsers in use for the moment

**Comment by marcelklehr** [comment]
I think it's rather unlikely that v5.0.12 specifically is the problem. Could you test with the firefox build of v5.0.12 https://github.com/floccusaddon/floccus/releases/tag/v5.0.12 on firefox? This has been reported already in march over here, I think: https://github.com/floccusaddon/floccus/issues/1554

**Comment by yayaasd** [comment]
> I think it's rather unlikely that v5.0.12 specifically is the problem. Could you test with the firefox build of v5.0.12 https://github.com/floccusaddon/floccus/releases/tag/v5.0.12 on firefox? This has been reported already in march over here, I think: #1554

ok, really feeling a bit dumb, but not able to install the extension (non-verified extension error message)
also tried to change the settings in firefox within about:config but not allowing me to installing the new version :(

**Comment by yayaasd** [comment]
all right, managed to find a difference. I installed chrome () with floccus 5.0.12 and was able to see the domain part in the profile:
![image](https://github.com/floccusaddon/floccus/assets/8055381/71630593-bae4-4e14-910d-fa6adfc19c70)


in Edge, there is no domain part --> showing NULL 
![image](https://github.com/floccusaddon/floccus/assets/8055381/990ec268-ba35-4d84-b3be-3bcb258b36c0)


seems that the new version is not putting the url back into the pattern

**Comment by marcelklehr** [comment]
If it works on chrome, then this is a bug in Edge

**Comment by marcelklehr** [comment]
:tada:
