### ISSUE TITLE
F-droid build of floccus is broke

### ISSUE THREAD

**Issue by jrfVP42bLiUWAYOShp5r** [floccusaddon/floccus#1586]
Using LineageOS 21, most recent version.

I today upgrade to 5.0.12. It doesn't start, only shows a blank screen. I cleared the cache, deleted storage, reinstalled app, nothing helped.
Had to reinstall 5.0.11. works flawless.

**Comment by marcelklehr** [comment]
Ah, the bug is already resolved. Thank you for reporting, still.

**Comment by eikedw** [comment]
Hi @marcelklehr ,

quite possible I miss something, but the f-droid version 5.0.12 mentioned by the OP is based on revision c8cf591, i.e. --- as of now --- still being the latest version of the code in https://github.com/floccusaddon/floccus/tree/develop/android. How did You come to the conclusion the bug may already be fixed :) ? Which commit should have helped?

That said, I am having the same problems as the OP (although I did not clear the cache or downgraded to the working 5.0.11 I had before).

For the record: Pixel phone running Android 13.

Many thanks, for providing floccus.

**Comment by marcelklehr** [comment]
This is the commit that fixed it: https://github.com/floccusaddon/floccus/commit/250257c6194c311818d77e4ea591438da7f6af28

**Comment by marcelklehr** [comment]
Clarification: The bug is fixed in the source code ;)

**Comment by eikedw** [comment]
Ah, sorry, I did not notice the Android build in "android" directory is dragging in things from "../src".
Thanks for the clarification!

**Comment by jrfVP42bLiUWAYOShp5r** [comment]
Thanks for the info.
