### ISSUE TITLE
iOS app with Nextcloud self signed certificate

### ISSUE THREAD

**Issue by banjoman05** [floccusaddon/floccus#1590]
### Which version of floccus are you using?

latest iOS app

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iPadOS 17.4.1, iPad Pro 11 inch third gen

### Which version of Nextcloud Bookmarks are you using? (if relevant)

v13.1.3

### Which version of Nextcloud? (if relevant)

v29.0.0

### Describe the Bug

Installed iOS app from app store on iPad. When inputting Nextcloud URL, a message is displayed and you are not allowed to skip/allow/ignore/etc...

"The certificate for this server is invalid. You might be connecting to a server that is pretending to be "[IP ADDRESS]" which could put your confidential information at risk."

This Nextcloud instance is already in use on desktop Firefox Addon and I was able to bypass any certificate issues.

### Expected Behavior

Ability to ignore error, as this is expected behavior when using self-signed certificates on internal networks.

### To Reproduce

Attempt to connect to Nextcloud with a self-signed certificate in the iOS app.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @banjoman05 
This is a known issue that is hard to fix, because I don't want to simply ignore SSL errors for security reasons. For now Android and iOS versions of floccus cannot sync with a self-signed certificate.
