### ISSUE TITLE
Possible Firefox memory leak

### ISSUE THREAD

**Issue by balporig** [floccusaddon/floccus#1593]
### Which version of floccus are you using?

5.1.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 125.0.3

### Describe the Bug

Setup

75k bookmarks spread across 8 non-nested profiles synced between several Firefox and Chromium based browsers on different platforms with auto-sync disabled

Issue

When opening Firefox for the first time there is huge memory spike up to 40 GB. Each time you reopen the browser there is significant spike, that takes few minutes to reach it's peak and disappears after several minutes. With auto-sync disabled there shouldn't be any background processing on startup. The issue is not present in Chromium based browsers

### Expected Behavior

There shouldn't be any noticeable memory usage on startup with auto-sync disabled

### To Reproduce

You need couple of profiles each with few thousand bookmarks, the more profiles with more bookmarks, the larger the memory spike

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
75k bookmarks, huh?

I know exactly which code triggers this :D :S and it's hard to circumvent :thinking:

**Comment by marcelklehr** [comment]
> Interesting, can you point to the code to have a look?

You can see it in the fixing commit

**Comment by marcelklehr** [comment]
> Looks like https://github.com/floccusaddon/floccus/issues/1548 is non issue anymore as long you keep each profile under 5 MB

Interesting
