### ISSUE TITLE
WebDAV lock not removed after 4 days

### ISSUE THREAD

**Issue by andbenn** [floccusaddon/floccus#1594]
### Which version of floccus are you using?

5.1.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave

### What kind of WebDAV server are you using? (if relevant)

Fastmail

### Describe the Bug

Similar or the same as #1572 filed earlier by me.

My work browser syncs both a profile of bookmarks and tabs to webdav.  It's the only browser hitting the profiles, as no other browser is.  The lock file has been there since Saturday morning, it's now Tuesday evening.  I noticed today some browser tabs keep reappearing.  Saturday morning is strange, as my work laptop was not powered on then

I also have a free NextCloud instance I can redirect my profiles to on the other side of the planet.  I may do that to attempt to rule out a floccus issue versus a Fastmail webdav issue in the next few days.  Would appreciate thoughts, in case they arrive before I make a transition.

I wish the icon had told me that a sync had been pending for over a day.

I'm going to rename the lock file and save it.  I can easily reenter this scenario by reversing it.  Let me know if you'd want me to do anything.

### Expected Behavior

Sync's to clear after a certain time period as written up online

### To Reproduce

Tab and or Browser webdav to Fastmail.  Not a popular or easy case to handle.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by andbenn** [comment]
I saved the tab profile and the tab lockfile.  Such that I should be able to pause that browser, rename and shift these files around, and regenerate the scenario.

Two of my tabs were open on Brave searches.  After renaming the lock file, the two search tabs kept reappearing and duplicating.  Not sure why.  I ended up pausing the profile, and renaming both, then pushing my browser back out.

Let me know if you'd want me to do anything.  i haven't had time yet to try moving them to my NextCloud space.

**Comment by marcelklehr** [comment]
How large are your bookmarks files on the webdav share?

**Comment by andbenn** [comment]
Tabs are 21 KB
Bookmarks are 282 KB

**Comment by marcelklehr** [comment]
Ok, that's not a lot. there goes that theory :D

**Comment by marcelklehr** [comment]
Aha! I was able to reproduce!
