### ISSUE TITLE
error: "Syncing failed with The operation was aborted."

### ISSUE THREAD

**Issue by Simplenuity** [floccusaddon/floccus#1595]
### Which version of floccus are you using?

5.1.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 113.0.2 (64-bit), Google Chrome 124.0.6367.155 (Official Build) (64-bit), Opera (outdated version) 92.0.4561.43

### Which version of Nextcloud? (if relevant)

25.0.8

### What kind of WebDAV server are you using? (if relevant)

Nextcloud instance offered by Webo.hosting

### Describe the Bug

On all browsers syncing fails with error message
`Failed to fetch Last synchronized: 1 week ago`

Debug file:
```
Starting sync process for account
************@nextcloud.webo.host
onSyncStart: begin
Syncing failed with The operation was aborted. 
onSyncFail
```

### Expected Behavior

successful syncing

### To Reproduce

trying to sync either via predefined interval or manually invoked

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
You are getting the same error on all Browsers you listed?

**Comment by LokChunYu** [comment]
chrome,Edge,firefox both the following prompts "This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing."

**Comment by marcelklehr** [comment]
@LokChunYu This is a different bug, see #1548

**Comment by marcelklehr** [comment]
I'm unable to reproduce this. How many bookmarks do you have? Is there anything special about your setup? Did floccus work before updating to v5.1.0?

**Comment by LokChunYu** [comment]
Worked fine before upgrading v5.1.0, I synced bookmarks via WebDAV URLs with 600+ bookmarks

**Comment by marcelklehr** [comment]
Thank you for investigating further.

Case 1: The local bookmarks folder seems to be empty, which is why no file is created on the server.

Case 2: The empty file causes the error. The log in this case doesn't help determine what caused the empty file.

**Comment by marcelklehr** [comment]
> on purpose and after bad experiences (data loss)

Nextcloud should be able to keep past versions of the xbel file, which might help. In general, sync is not a backup, of course, so I very much encourage everyone to backup their bookmarks regularly

**Comment by marcelklehr** [comment]
>  the XBEL file has been corrupted!

Very strange :thinking:

**Comment by marcelklehr** [comment]
Huh, could you open the debugger in your browser to check what happens to  the network request here?

The following are the steps to do that:

#### Firefox
* Go to `about:debugging`
* go to "This firefox"
* click on `Inspect` button next to floccus entry
* go to the network tab in the inspector
* trigger a sync by clicking the `sync now` button for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `Service worker` link in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking the `sync now` button for the account of your choice
* check the failing network requests

**Comment by marcelklehr** [comment]
It seems that the issue is a NS_ERROR_NET_PARTIAL_TRANSFER, so I'm guessing something is wrong with the network between floccus and your nextcloud that causes a mere partial transfer of the file. Since floccus is on the receiving end, there's not much I can do here.
