### ISSUE TITLE
Push / pull changes folder tree

### ISSUE THREAD

**Issue by jxcx** [floccusaddon/floccus#1596]
### Which version of floccus are you using?

5.1.0

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

firefox-esr 115.10.0esr-1~deb12u1 amd64

### Describe the Bug

Floccus seems to have problems with certain folder paths and names.

Here is a minimal example that triggers the problem(s).

Initially, firefox has bookmarks:

```
   + Bookmarks Menu
   +--+ x/
   |  \--+ a/
   |     \--+ 0/
   |        +--- b1 <https://github.com/floccusaddon/>
   |        \--- b2 <https://github.com/floccusaddon/floccus>
   \--+ y/
      \--+ a/
         \--+ 0/
            +--- b3 <https://www.mozilla.org/en-US/>
            \--- b4 <https://www.mozilla.org/en-US/privacy/firefox/>

```
If I push up to google drive ( floccus-5.1.0-2024-05-08-full_2.log uploaded privately ), the xbel file looks like:

```
   + Bookmarks Menu
   +--+ x/
   |  \--+ a/
   |     |--+ 0/
   |     |  +--- b1 <https://github.com/floccusaddon/>
   |     |  \--- b2 <https://github.com/floccusaddon/floccus>
   |     \--+ 0/
   |        +--- b3 <https://www.mozilla.org/en-US/>
   |        \--- b4 <https://www.mozilla.org/en-US/privacy/firefox/>
   \--+ y/
      \--+ a/
```

The subfolder "y/a/0" has been moved to another parent "x/a/", so now there are 2 folders "x/a/0".

Then, if I pull down ( floccus-5.1.0-2024-05-08-full_3.log uploaded privately ), the firefox bookmarks now look like:

```
   + Bookmarks Menu
   +--+ x/
   |  \--+ a/
   \--+ y/
      \--+ a/
         |--+ /
         |  +--- b2 <https://github.com/floccusaddon/floccus>
         |  \--- b1 <https://github.com/floccusaddon/>
         \--+ /
            +--- b4 <https://www.mozilla.org/en-US/privacy/firefox/>
            \--- b3 <https://www.mozilla.org/en-US/>
```

The two subfolders named "x/a/0" have been moved to "y/a/", and the folder names that were "0" are now empty strings "" which firefox denotes by "(no title)". Also, the bookmark order is broken.

### Expected Behavior

Push and pull should not change anything.

### To Reproduce

As in the bug section: start with the initial bookmarks, then push and pull.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank you for the great bug report, btw! Really well isolated! :blue_heart:

**Comment by marcelklehr** [comment]
And, this one will fix the failed ordering bug: https://github.com/floccusaddon/floccus/pull/1601

**Comment by jxcx** [comment]
I only use floccus to sync.
Thanks for the thanks! I sought to isolate the problem with folders named '0'.
And of course, thanks for floccus and all your work !!!
