### ISSUE TITLE
[Git Adapter] Possible rate-limites when using github

### ISSUE THREAD

**Issue by bigdiff** [floccusaddon/floccus#1599]
### Which version of floccus are you using?

5.1.0

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave Version 1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

N/A

### Which version of Nextcloud? (if relevant)

N/A

### What kind of WebDAV server are you using? (if relevant)

N/A

### Describe the Bug

Github seems to heavily rate-limit the git adapater, I've setup two profile one for bookmarks and one for open tabs, and it seems there is a 15 minute limit between 2~3 requests.

### Expected Behavior

I'm not sure if this is a known thing, IMO it is worth mentioning when adding a git adapter profile.

### To Reproduce

Setup at least two profile, make some changes in both profile and notice the "Scheduled" appearing on both profiles for 15 minutes and it retries every so often.

```log
2024-05-09 (git) checkout branch main
2024-05-09 Resource is locked, trying again soon
```

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hhm, yeah, when the resource is locked, floccus retries every minute :S That doesn't go down well with rate limiting I imagine :/

**Comment by marcelklehr** [comment]
> I now have 6 tags for floccus-locks and the repo is empty with just a readme.

Wut?!

**Comment by marcelklehr** [comment]
Yeah, it should only ever do that if the branch cannot be found... I'm gonna take that part out I guess. Can't have floccus bulldoze the entire repo.

**Comment by marcelklehr** [comment]
> we can keep the try catch in https://github.com/floccusaddon/floccus/pull/1602 but instead of initializing a new repo we can put the error into the logger, what do you think?

The try-catch is only used to set up a new repo, so if we don't want that, the error will be caught higher up and displayed, no need to log it manually.
