### ISSUE TITLE
Blank screen for Android app v5.0.12 (F-Droid)

### ISSUE THREAD

**Issue by de-code** [floccusaddon/floccus#1604]
### Which version of floccus are you using?

5.0.12

### How many bookmarks do you have, roughly?

0

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 14

### Describe the Bug

After upgrading to the latest version 5.0.12 (via F-Droid) I am seeing a blank screen (or sometimes the Logo).
Clearing data didn't help.
Since this isn't even showing any first setup dialog after resetting the data, it should be unrelated to bookmark service.

Re-installing the previous version 5.0.11 works.

Observation: F-Droid shows 5.0.12 as 3.2 MB, whereas 5.0.11 is 6.7 MB

### Expected Behavior

Bookmarks or first setup-dialog shown

### To Reproduce

Install 5.0.12 via F-Droid.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @de-code 

This is fixed in v5.1.0 which is pending release on F-Droid. Should be any day now. :crossed_fingers:

**Comment by ojde** [comment]
Just updated from IzzyOnDroid F-Droid repo. Works again. Thanks!

**Comment by de-code** [comment]
Thank you for the quick fix. It is indeed working again. :bow:
