### ISSUE TITLE
[Gitlab] Issues pulling/pushing bookmarks to gitlab

### ISSUE THREAD

**Issue by bigdiff** [floccusaddon/floccus#1609]
### Which version of floccus are you using?

5.1.1

### How many bookmarks do you have, roughly?

< 30

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

125.0.3

### Which version of Nextcloud Bookmarks are you using? (if relevant)

N/A

### Which version of Nextcloud? (if relevant)

N/A

### What kind of WebDAV server are you using? (if relevant)

N/A

### Describe the Bug

when adding the username and the access token to floccus I get a 422 response for pulling or pushing bookmarks

### Expected Behavior

The authentications is working as expected but it seems something else is failing in the process

### To Reproduce

copy the https repo url and use it in floccus
add username and the access token then proceed with the rest of the settings

### Debug log provided

- [X] I have provided a debug log file

<details>
  <summary>Logs</summary>
  
  ```log
    Starting sync process for account lsitterding@framagit.org:firefox.xbel
    onSyncStart: begin
    (git) init
    (git) fetch from remote
    Syncing failed with HTTP Error: 422 
    onSyncFail
  ``

</details>

```
Starting sync process for account bigdiff@gitlab.com:bookmarks.xbel
onSyncStart: begin
(git) init
(git) fetch from remote
Syncing failed with HTTP Error: 422 
onSyncFail
```

**Comment by marcelklehr** [comment]
Did you manually push an initial commit to the repo before?

**Comment by marcelklehr** [comment]
Can you try pushing a branch with a commit?

**Comment by marcelklehr** [comment]
huh. Seems to be a gitlab thing:

> 422 The change you requested was rejected. Make sure you have access to the thing you tried to change. Please contact your GitLab administrator if you think this is a mistake.

**Comment by noraj** [comment]
Most of the time, one have 2FA enabled, so one must use a PAT (personal access token) instead of password.

Since 422 is an authorization error, could you confirm that `write_repository` and `read_repository` are enough? Since we are using Git-over-HTTP that should be the case.

![Image](https://github.com/user-attachments/assets/2a7b9e86-1321-4d8f-96f2-7b8d142de50a)
