### ISSUE TITLE
Cannot login with Yubikey 2FA

### ISSUE THREAD

**Issue by hellomiakoda** [floccusaddon/floccus#1610]
### Which version of floccus are you using?

5.1.0

### How many bookmarks do you have, roughly?

309

### Are you using other means to sync bookmarks in parallel to floccus?

N9

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Fennec

### Which version of Nextcloud? (if relevant)

Recebtly updated

### Describe the Bug

Android app seems to now use it's own littke browser to log in to NextCloud during profile creation.... which doesn't support logging in to NextCloud, rendering the app useless.
It fails at the part where NextCloud asks for my YubiKey

### Expected Behavior

"Sign in to NextCloud" opens Fennec or other phone browser, and sign in proceeds as normal. NextCloud asks for my YubiKey, I connect it with the dongle, touch it, and lofe proceeds as normal

### To Reproduce

Set up NextCloud syncing with a NextCloud server that uses Yubi keys

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @hellomiakoda 
This might be fixed now, the android app is using the system browser to do the Nextcloud login now

**Comment by marcelklehr** [comment]
Please shout if you still have problems
