### ISSUE TITLE
Floccus cannot find folder in webdav or github

### ISSUE THREAD

**Issue by beyercj** [floccusaddon/floccus#1611]
### Which version of floccus are you using?

5.1.1

### How many bookmarks do you have, roughly?

50

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which version of Nextcloud Bookmarks are you using? (if relevant)

Firefox 115.10.0esr

### Describe the Bug

When I setup a profile and browse folder, floccus cannot find the folder hirarchie and shows the spinner indefinitely. Version 5.1.0 works fine on Android and worked fine on Firefox under Linux, floccus 5.1.1 shows "Folder not found" and tries to synchronise indefinitely.

### Expected Behavior

Shows folder menu to choose

### To Reproduce

Tried many times, deleted profile and tried to re-create, same problem

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Mmh, I cannot reproduce this? Could you try this with a fresh firefox profile? There was a similar issue before which was somehow due to a firefox bug.

**Comment by beyercj** [comment]
I think you are correct. Just had a problem with my firefox profile, solved it  as per mozilla help and can now connect floccus to the server. Thank you for your quick response and for solving the s problem with synchronisation.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 14/05/2024, 08:01 Marcel Klehr ***@***.***> wrote:

   
  Mmh, I cannot reproduce this. Could you try this with a fresh firefox profile? There was a similar issue before which was somehow due to a firefox bug.
