### ISSUE TITLE
5.1.1 release size tripled from 5.1.0

### ISSUE THREAD

**Issue by Daryes** [floccusaddon/floccus#1612]
### Which version of floccus are you using?

5.1.1

### How many bookmarks do you have, roughly?

around 1000

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox esr 115

### Describe the Bug

Very basic : compare the assets file size between both 5.1.x versions :
* https://github.com/floccusaddon/floccus/releases/tag/v5.1.1
* https://github.com/floccusaddon/floccus/releases/tag/v5.1.0

I usually pay attention to this sort of detail, and was extremely surprised to see a mean size of 6 MB increased to 15-16 MB.

Hopefully, it is only due to these new js.map files :
```
$ du -sh dist/js/*.map |sort -h
4.0K    dist/js/30.js.map
4.0K    dist/js/353.js.map
4.0K    dist/js/466.js.map
4.0K    dist/js/486.js.map
4.0K    dist/js/811.js.map
8.0K    dist/js/541.js.map
24K     dist/js/171.js.map
36K     dist/js/176.js.map
36K     dist/js/446.js.map
40K     dist/js/142.js.map
72K     dist/js/264.js.map
104K    dist/js/588.js.map
240K    dist/js/test.js.map
788K    dist/js/136.js.map
6.0M    dist/js/454.js.map
6.2M    dist/js/background-script.js.map
11M     dist/js/native.js.map
12M     dist/js/options.js.map
```

Unless I am mistaken, it seems they are for debugging purpose with the minified files.
I can understand the need, but for such size in a browser plugin, it might be debatable.

### Expected Behavior

N/A

### To Reproduce

N/A

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Yes, the source maps are now shipped to improve debugging.
