### ISSUE TITLE
Blank popup ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by Chway** [floccusaddon/floccus#1613]
### Which version of floccus are you using?

5.1.2

### How many bookmarks do you have, roughly?

100

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave 1.65.132

### Describe the Bug

The popup and option's page are blank, I'm getting a ERR_FILE_NOT_FOUND for 690.js. I tried installing the version from the Chrome Web Store first, I had the issue, I then decided to try the version you uploaded a few minutes ago, (5.1.2) using 
floccus-build-v5.1.2-chrome.zip, it's still happening.

### Expected Behavior

I expected to see the popup or the option's page correctly showing..

### To Reproduce

Click on floccus icon from the toolbar, or right-click the icon, then click "Options", a blank popup/page show up.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Oh my. Thank you for the heads up. Will fix that shortly.

**Comment by marcelklehr** [comment]
Update is in review on Chrome store. Firefox update is out now.
