### ISSUE TITLE
Bookmarks not syncing

### ISSUE THREAD

**Issue by Chway** [floccusaddon/floccus#1615]
### Which version of floccus are you using?

5.1.2

### How many bookmarks do you have, roughly?

100

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave 1.65.133

### Describe the Bug

The extension refuse to sync my bookmarks, clicking any of the three buttons (Pull/Push/Sync) have no effect, I can see in the console log that messages are sent to the service worker but nothing more, the auto sync doesn't seem to trigger either. The issue happen on both floccus 5.1.2 and 5.1.1, no problem on 5.1.0 with the same settings. The issue happen on Brave and Chrome, after a fresh install of the extension, whatever the extension come from Chrome Web Store or this repo. No issue on Firefox, where the extension has been running for a couple weeks now and is still running fine with the last version. The log file is completely empty..

### Expected Behavior

Clicking "Pull down once" should grab the bookmarks I have saved on my Git repo.

### To Reproduce

- Install the extension and create a new profile using Git.
- Open popup, click "Pull down once" (or "Push up", "Sync now")

### Debug log provided

- [ ] I have provided a debug log file

**Comment by djwyman** [comment]
I am having the same issue on brave.  I installed the extension on edge, and it works, but not on brave.

**Comment by Magic989** [comment]
I am also on version 5.1.2, and floccus on edge, chrome and firefox all fail to work.

**Comment by Investigamer** [comment]
Having the same issue with Floccus on Brave, but not on Firefox.
**Details**: Floccus **5.1.2**
**Using**: Nextcloud Bookmarks (self hosted)
Firefox (**working**), Brave (**not working**)

**Comment by Magic989** [comment]
My floccus works fine on firefox, but the interface doesn't show up when I
click the button. However, floccus in chrome and edge browsers can display
the interface but cannot synchronize bookmarks.

Chris ***@***.***> 于 2024年5月15日周三 13:31写道：

**Comment by marcelklehr** [comment]
> My floccus works fine on firefox, but the interface doesn't show up when I
click the button. 

This should be fixed by updating your addons.

**Comment by marcelklehr** [comment]
>  floccus on edge, chrome and firefox all fail to work.

Confirmed.

**Comment by Magic989** [comment]
But I am using the latest version of the addons. .It was normal when using
version 5.1.1, but I clicked the update button in the browser to update
automatically. I don't know if it has anything to do with this operation.

Marcel Klehr ***@***.***> 于 2024年5月15日周三 14:08写道：

**Comment by marcelklehr** [comment]
The initial v5.1.2 build for firefox was had a problem which was resolved with an update

**Comment by marcelklehr** [comment]
This is a similar problem with the build for Chrome but not the same :/ I've pushed a new build to the Chrome webstore which should make it to you soon.

**Comment by Magic989** [comment]
Oh, thank you for your hard work😘.

Marcel Klehr ***@***.***> 于 2024年5月15日周三 14:38写道：

**Comment by Chway** [comment]
The last build fixed my syncing issues for both Brave and Chrome. 

I might have something else, but not certain if it's a bug, when selecting HTML as file format, by default, floccus doesnt save the file as .html but .xbel, the content of the file is HTML tho. I have to manually edit the file path.

**Comment by marcelklehr** [comment]
> I might have something else, but not certain if it's a bug, when selecting HTML as file format, by default, floccus doesnt save the file as .html but .xbel, the content of the file is HTML tho. I have to manually edit the file path.

Yeah that's a known issue that I haven't gotten around to fixing yet :)
