### ISSUE TITLE
google drive donot sync in chrome linux mint

### ISSUE THREAD

**Issue by anwaruddin2k** [floccusaddon/floccus#1616]
### Which version of floccus are you using?

5.1.2

### How many bookmarks do you have, roughly?

2k

### Are you using other means to sync bookmarks in parallel to floccus?

yes

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

chrome linux

### Describe the Bug

![unnamed](https://github.com/floccusaddon/floccus/assets/53415502/4820047c-c8a5-41f6-b0bb-af35ecdcc506)

### Expected Behavior

tried to sync with google drive but it gives same message again even after clearing cache

### To Reproduce

using extentions and google drive

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @anwaruddin2k 
Does it work for you with the same account in android / any other floccus installation?

**Comment by anwaruddin2k** [comment]
> Hi @anwaruddin2k 
> Does it work for you with the same account in android / any other floccus installation?

I have tried it in pc and Android and it doesn't work in both devices.

**Comment by marcelklehr** [comment]
Can you try reconnecting your Google account in the settings?

**Comment by anwaruddin2k** [comment]
![image](https://github.com/floccusaddon/floccus/assets/53415502/b31f597c-1a9c-4d01-b1a1-e2f70d202c67)

**Comment by anwaruddin2k** [comment]
E018: Couldn't authenticate with the server. Last synchronized: 0 seconds ago

it gives same error message

**Comment by anwaruddin2k** [comment]
its working now . I changed name of .xbel file . I donot know why it wasn't working before

**Comment by anwaruddin2k** [comment]
[floccus-5.1.2-2024-05-16-full (1).log](https://github.com/floccusaddon/floccus/files/15338682/floccus-5.1.2-2024-05-16-full.1.log)

**Comment by marcelklehr** [comment]
I cannot reproduce this, sadly. I also don't see an overall increase of API errors in the Google API deashboards since the last releases, which would have pointed to a bug in the code. Which browser are you using?
