### ISSUE TITLE
HTTP status 414 error when syncing bookmarklet to Nextcloud Snap

### ISSUE THREAD

**Issue by ImintA2** [floccusaddon/floccus#1617]
### Which version of floccus are you using?

5.1.2

### How many bookmarks do you have, roughly?

500

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Catsxp 4.5.1

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

27.1.9

### Describe the Bug

I have some bookmarklets, and they're causing the syncing process to stuck in a loop of retrying with error:
`2024-05-16T11:28:07.924Z Syncing failed with E019: HTTP status 414. Failed GET request. Check your server configuration and log.`

From my understanding, this happens because Apache server has a default `LimitRequestLine` set to 8190.
It'd throw a `Request-URI Too Long` error if a GET Request exceed the limit.

You could say this is a server configuration issue because one should be able to solve this by increasing the `LimitRequestLine` value, however there's no way to edit this setting in the Snap version of Nextcloud which is what I'm using so I'm out of luck.

### Expected Behavior

Hopefully an option to ignore items that are too long so the syncing process won't stuck in a retry loop.
Or an option to exclude bookmarklet also works.

### To Reproduce

Attempt to sync a bookmark/tab that's too long (>8190 characters) to a Nextcloud installed with Snap.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Ah, that's a nice catch. I have a fix for this in mind already.

**Comment by marcelklehr** [comment]
Should be fixed in v5.1.3
