### ISSUE TITLE
Multiplatform Brave/Kiwi extension permanently says “Not synchronized, yet” on all devices

### ISSUE THREAD

**Issue by sming** [floccusaddon/floccus#1619]
### Which version of floccus are you using?

5.1.2

### How many bookmarks do you have, roughly?

1000

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave Macos, Kiwi Android

### Describe the Bug

👋  thanks for Floccus, it’s a great initiative.

So 2-3 weeks ago I tried tab syncing and that led to wild behavior so I had to boot Brave —no-extensions (sic.) and disable the floccus extension.

However, since then I’ve removed the tab-sync profile and added a new bookmark sync profile on 3 devices: 2 MBP’s and 1 Android phone, the MBP’s are Brave and the phone Kiwi (which allows extensions, which is **awesome**).

All report “Not synchronized, yet” no matter how much I provoke the extension lol. I’ve disabled, reenabled, I’ve toggled “sync automatically”, I simply cannot get it to run/do anything on any device.

### Use Case: floccus does an initial sync

* I am a user
* Who wants to sync his bookmarks across his MBP’s and Android phone
* So that I can enjoy consistent bookmarking across devices

#### Proposed Solution

* N/A just fix the bug :)

## Steps to Reproduce the Problem

  1. install floccus one by one on MBP’s (Brave) and then Kiwi (phone)
  1. configure them to sync to a file with the path `bookmarks.xbel` (I tried configuring a dir path but it always went red/error in the UI for some reason)
  1. wait 30 mins
  1. inspect floccus in each browser and all report 
  
 “GOOGLE-DRIVE
 “Bookmarks
 “Google Drive: bookmarks.xbel
 “All good
 “Not synchronized, yet

I.e. the service/extensions are doing no work

I don’t know where my floccus account is so didn’t provide log files - sorry!

### Debug log provided

- [ ] I have provided a debug log file

<img src="https://github.com/floccusaddon/floccus/assets/1403866/e2eea1db-8643-43fa-9abb-8d5b8ccac21f">

**Comment by marcelklehr** [comment]
This is likely due to faulty build of v5.1.2. You should try force-updating the extension to get the update.

**Comment by marcelklehr** [comment]
Closing in the hope that this has been resolved. Comment here if you are still experienceing this and I will reopen.
