### ISSUE TITLE
Google Chrome: Bookmarks Menu not synching

### ISSUE THREAD

**Issue by bernd-wechner** [floccusaddon/floccus#162]
Latest Chrome store release (3.06). Synching seems fine except none of the Bookmarks Menu items that I have in Firefox seem to arrive in Chrome.

**Comment by marcelklehr** [comment]
Yep, that's by design, as floccus doesn't know where you want those to end up. You will need to set up a new account to exclusively sync the menu, by setting the server folder and the local sync folder to something custom (The server folder should probably be `/Bookmarks Menu`)

**Comment by bernd-wechner** [comment]
Fair enough. Still, given the convenience factor is high I'd consider mapping to menu to "Other bookmarks". Here is the default layout of the Chrome Bookmarks manager:

![image](https://user-images.githubusercontent.com/7296506/44939632-2fb21880-adca-11e8-91db-702bbace20a5.png)

So clearly "Other bookmarks" has reasonable candidature. Just a thought for enhanced UX.

**Comment by marcelklehr** [comment]
Well, Firefox has the bookmarks toolbar, the menu *and* Other bookmarks, while chrome only has the first two, which makes things a little tricky.

**Comment by bernd-wechner** [comment]
True. Indeed. Wonder what Xmarks did? Really slick UX is a challenge I admit ;-).

**Comment by bernd-wechner** [comment]
I suspect what they did is mapped the Firefox bookmarks menu to a folder under Chrome's toolbar or Other list, though this would need special smart handling of course, for example:

FF Toolbar -> GC Toolbar
GC Toolbar (except for Menu folder) -> Firefox Toolbar
GC Toolbar (Menu folder) -> Firefox menu

which is admittedly a special case and a little messy. But it does target slick seemless UX ;-)

**Comment by marcelklehr** [comment]
The same is already possible with floccus. You can create a separate account for the same server in chrome, select Bookmarks Menu as the server folder and select whatever folder you want as the local folder.

**Comment by marcelklehr** [comment]
I'll document this in the README.
