### ISSUE TITLE
All Nextcloud bookmarks are gone after setting up the Android app

### ISSUE THREAD

**Issue by allan-null** [floccusaddon/floccus#1624]
### Which version of floccus are you using?

5.1.3 F-Droid

### How many bookmarks do you have, roughly?

50

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 14, Samsung Z Fold 4

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.0.2

### Which version of Nextcloud? (if relevant)

29.0.1

### Describe the Bug

All bookmarks got deleted when first running the app account setup.

### Expected Behavior

Sync the bookmarks.

### To Reproduce

1. Waste hours tiding up your bookmarks on the Nextcloud web interface;
2. Install Floccus app;
3. Setup your Nextcloud account;
4. Leave everything else default;

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @allan-null 
I'm sorry this happened to you. That's terrible. It's quite unusual, though, and I just tried it and cannot reproduce it. Something else must have happened, I think.

**Comment by allan-null** [comment]
@marcelklehr I will dig further into this issue and try to provide more info next week. I am using the Firefox extension everything it works just fine.

**Comment by marcelklehr** [comment]
Can you try v5.1.4 from this repo?

**Comment by marcelklehr** [comment]
@slavexe which version are you using?

**Comment by slavexe** [comment]
> Can you try v5.1.4 from this repo?

5.1.4 is the only version I've tried so far. 

By the way, I came back to my phone about an hour later and all my bookmarks were there, so it seems the autosync feature is working as intended (at least in my case).

**Comment by marcelklehr** [comment]
We were able to fix this in v5.1.7 I believe

**Comment by allan-null** [comment]
> We were able to fix this in v5.1.7 I believe

Sorry for the late reply. Just confirming the issue is fixed for me with the v5.1.7 release.
