### ISSUE TITLE
iOS 5.1.4 doesn't update any bookmarks

### ISSUE THREAD

**Issue by Fletch-99** [floccusaddon/floccus#1626]
### Which version of floccus are you using?

5.1.4

### How many bookmarks do you have, roughly?

300

### Are you using other means to sync bookmarks in parallel to floccus?

Yes

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iOS 5.1.4

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.0.2

### Which version of Nextcloud? (if relevant)

v29

### Describe the Bug

On iOS, it doesn't sync any changes from Nextcloud Bookmarks. It can write changes to Nextcloud Bookmarks but it doesn't receive any changes. 

### Expected Behavior

Synced Bookmarks using the iOS Floccus app. 

### To Reproduce

No changes on sync. I've tried and deleted my profile and created it again but still doesn't get any bookmarks. Now with the new empty profile, If I try to sync using the "Always merge local changes with changes from other browsers" and "Always upload local changes and undo changes from other browsers"  it will **delete** all bookmarks on Nextcloud. The second sync option "Always undo local changes" leave the iOS app empty. 

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @Fletch-99 

Thank you for reporting this. A patch its on its way already.
