### ISSUE TITLE
No background synchronization

### ISSUE THREAD

**Issue by fourteenminusone** [floccusaddon/floccus#1632]
### Which version of floccus are you using?

5.1.4

### How many bookmarks do you have, roughly?

100

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave 1.65.133 and Android v5.1.7

### Describe the Bug

Hi,
I'm noticing that synchronization doesn't happen automatically when I add a bookmark, nor in the background.

### Expected Behavior

I expect that, once I add a bookmark on the laptop, in the background and automatically this will also be visible on the mobile phone without having to click any synchronization button and vice versa.

### To Reproduce

For example, I have the floccus extension installed on the Brave browser on my laptop and the Android application on my phone. If I add a bookmark from the PC, to see it on Android I necessarily have to do manual synchronization otherwise I won't see anything and the same happens vicevera. Is it a desired behavior?

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @fourteenminusone 
Does synchronization work when you click the sync button in the UI manually?

**Comment by fourteenminusone** [comment]
Yes

Il mar 4 giu 2024, 13:59 Marcel Klehr ***@***.***> ha scritto:

**Comment by marcelklehr** [comment]
I can only replicate this with deleting items. When creating or updating items it auto-syncs after 7 seconds for me. I'll look into why deletion doesn't trigger it.

**Comment by fourteenminusone** [comment]
Also the deletion procedure does not trigger the autosync. I have to click
the sync button to trigger it.

Il giorno mar 4 giu 2024 alle ore 14:13 Marcel Klehr <
***@***.***> ha scritto:

**Comment by marcelklehr** [comment]
Is auto-sync enabled in the settings of your profile?

**Comment by marcelklehr** [comment]
I can not reproduce this anymore with the latest version, both when adding and when deleting a bookmark, after 7 seconds a sync is run.
