### ISSUE TITLE
Hide Floccus Update page

### ISSUE THREAD

**Issue by hartsberger** [floccusaddon/floccus#1634]
### Describe the feature you'd like to request

Every time the Floccus Add-On is getting an update, the following url gets opened in Edge browser: 
extension://gjkddcofhiifldbllobcamllmanombji/dist/html/options.html#/update

![2024-06-05 08_58_59-Window](https://github.com/floccusaddon/floccus/assets/60740965/6fad0f78-031d-48c8-884c-31a12302379c)

I don't know the url used for other browsers e.g. Firefox. But it should be something similar. 

There the user gets the information that the update of Floccus Add-On is successfull and some ways to contribute are mentioned. 

For some users this whole page is confusing and annoing. When they open the Edge browser, they see this page and sometimes they don't even know what this is all about. 
We force install the Floccus Add-On via GPO on Microsoft Edge and Mozilla Firefox. 
The user that don't have even configured Floccus don't know why this page even opens. 

Feature Request: 
Give enterprises the posibility to hide this url. 

### Describe the solution you'd like

The update url should only be shown, when the Add-On is configured correctly. For example only when there was at least one successfull sync. 
This way only users who have already interacted with the Add-On get the update notification. 

Additionally it would be great if the user could enable and disable the update notification somewhere in the options of the Add-On or during configuration of the first sync connection. 

### Describe alternatives you've considered

Add another option on the update page itself to let the user enable or disable further update notifications.

**Comment by marcelklehr** [comment]
Good idea! As an aside, if your company benefits from using floccus, please consider a donation to support the project :blue_heart:
