### ISSUE TITLE
ios: E017

### ISSUE THREAD

**Issue by tong-hao** [floccusaddon/floccus#1635]
### Which version of floccus are you using?

v5.1.7

### How many bookmarks do you have, roughly?

300

### Are you using other means to sync bookmarks in parallel to floccus?

Yes, I also sync via chrome

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

chrome 125

### Describe the Bug

![00431B08-F850-4BC6-8FA1-82BBE1CC6C96_1_201_a](https://github.com/floccusaddon/floccus/assets/28890406/373eb7a6-ac0b-4d15-8651-4d8eb04ebe58)

### Expected Behavior

sync success.

### To Reproduce

![00431B08-F850-4BC6-8FA1-82BBE1CC6C96_1_201_a]

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
What kind of WebDAV server are you using? Is it self-hosted? Are you using a self-signed certificate?
