### ISSUE TITLE
Dividers/separators on FIrefox don't always work as expected

### ISSUE THREAD

**Issue by BoscoDomingo** [floccusaddon/floccus#1645]
### Which version of floccus are you using?

5.1.4

### How many bookmarks do you have, roughly?

~500-1k

### Are you using other means to sync bookmarks in parallel to floccus?

Yes, via Firefox account

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Mozilla Firefox 126.0.1

### Describe the Bug

Dividers/separators aren't always synced correctly. When they aren't, they are duplicated multiple times (usually between 3-7) and oftentimes also reordered (normally pushed to the top or the bottom of the folder they are in).

An example where there should've only been one:
![image](https://github.com/floccusaddon/floccus/assets/46006784/8e760fd6-17eb-4c37-b76d-5b2565dbe543)

### Expected Behavior

For separators to be treated like any other bookmark

### To Reproduce

Try using separators inside a folder. It is not a deterministic bug, which is what makes it so weird.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> Yes, via Firefox account

This is known to cause issues. Make sure to disable bookmarks syncing in Firefox Sync before using Floccus to sync.

**Comment by BoscoDomingo** [comment]
> > Yes, via Firefox account
> 
> This is known to cause issues. Make sure to disable bookmarks syncing in Firefox Sync before using Floccus to sync.

@marcelklehr I can't since the Android app didn't work, therefore I still need to use Firefox's native sync. If you're 100% sure that's the culprit, we can close this issue. However, it has only happened for separators. All other bookmarks have kept their ordering and are working as expected

**Comment by marcelklehr** [comment]
>  It is not a deterministic bug, which is what makes it so weird.

This hints that it might be linked to Firefox Sync, but I don't know of course.

> I can't since the Android app didn't work

Ah, well. Sorry for that.

**Comment by BoscoDomingo** [comment]
> > It is not a deterministic bug, which is what makes it so weird.
> 
> This hints that it might be linked to Firefox Sync, but I don't know of course.
> 
> > I can't since the Android app didn't work
> 
> Ah, well. Sorry for that.

It's fine, more than enough for free open source software. I literally cannot ask you for anything!

Might be worth taking into account that the Android app doesn't play nice with Git due to the SSH identification instead of regular user+password credentials, in any case. Will close the issue for now 👍🏼
