### ISSUE TITLE
Error: Cannot find module './en_US/messages.json'

### ISSUE THREAD

**Issue by dsiminiuk** [floccusaddon/floccus#1646]
### Which version of floccus are you using?

v5.2.0 chrome.zip

### How many bookmarks do you have, roughly?

1000

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

MS Edge

### Describe the Bug

Error shows up on the Errors list of the "Manage Extensions" page for this extension. 

### Expected Behavior

The extension should work.

### To Reproduce

Load unpacked.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by dsiminiuk** [comment]
After removing and re-installing, I believe now this might be a message from a previous installation.

Sorry for the noise. Closing.

**Comment by dsiminiuk** [comment]
Closing

**Comment by dsiminiuk** [comment]
No, it is a new error. Re-opening.

**Comment by marcelklehr** [comment]
Hey @dsiminiuk
This is a known error that is non-critical. When your browser locale is set to en-US tries to load the en_US messages, but fails, producing this error message, and falling back to simple en. As long as your floccus UI still shows text, all is good :)
