### ISSUE TITLE
Floccus requesting unneccesary permissions

### ISSUE THREAD

**Issue by neilmendoza** [floccusaddon/floccus#1647]
### Which version of floccus are you using?

5.2.0.3

### How many bookmarks do you have, roughly?

500

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Describe the Bug

Floccus now requesting permission to read and change browsing history.

### Expected Behavior

A bookmark addon should not need access to browsing history.

### To Reproduce

Install 5.2.0.3 in Brave.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @neilmendoza 

I realize that this may be unexpected. The new history permission is only used if you opt in to collecting click statistics and sending them to your nextcloud bookmarks app. Where would you expect to see an explanation for this change?

**Comment by marcelklehr** [comment]
It may be possible to request the history permission on demand at runtime to avoid asking on every install. I'll look into this.

Mental note: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request

**Comment by marcelklehr** [comment]
History is now optional in https://github.com/floccusaddon/floccus/releases/tag/v5.2.1
