### ISSUE TITLE
Cannot share bookmarks without force stop (Android)

### ISSUE THREAD

**Issue by kozmik-moore** [floccusaddon/floccus#1649]
### Which version of floccus are you using?

5.1.7

### How many bookmarks do you have, roughly?

20

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 5.1.7

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.2.0

### Which version of Nextcloud? (if relevant)

28.0.6

### Describe the Bug

When trying to create a bookmark from the web browser on Android, the bookmark is not populated in the app unless the app is force stopped and restarted. This is true for both Firefox and Opera web browsers.

### Expected Behavior

When I use the "share" feature in the web browser, a bookmark is created immediately in the floccus app.

### To Reproduce

1. Navigate to a web browser and select a tab pointing to a web page.
2. Select "share" from the browser app menu and select floccus as the target.
3. Check/edit the details of the dialog that appears for the floccus app and save.
4. Open the floccus app and navigate to the folder where the newly-created bookmark was added.
5. See that the bookmark is not present
6. Navigate to the Android settings app and locate the app settings for the floccus app.
7. Select "Force stop" for floccus.
8. Select "Open" for floccus.
9. Navigate to the folder where the newly-created bookmark was added.
10. See the bookmark in the folder in step 4.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @kozmik-moore 
Thanks for the feedback! I can confirm this. I'll look into solving it :)

**Comment by kozmik-moore** [comment]
Thank you. And thank you for the very prompt response.
