### ISSUE TITLE
Settings button is unresponsive (iOS)

### ISSUE THREAD

**Issue by yougotwill** [floccusaddon/floccus#1659]
### Which version of floccus are you using?

v5.2.1

### How many bookmarks do you have, roughly?

200 ish

### Are you using other means to sync bookmarks in parallel to floccus?

Yes via Mozilla account

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iOS 17.5.1 (21F90)

### Describe the Bug

I cannot open the settings menu from the gear icon. You can tap the button but it does nothing 

### Expected Behavior

When you tap the gear icon the settings window appears. 

### To Reproduce

1. Tap gear icon in toolbar. 

### Debug log provided

- [ ] I have provided a debug log file

**Comment by itoldusoandso** [comment]
Same thing.. I just updated to latest floccus on iPhone. Settings button is dead, pressing it shows it reacts but settings don't open. iOS is 17.4.1 but maybe it's an issue across the board. Thanks

**Comment by marcelklehr** [comment]
Confirmed. Will be fixed with the next release.
