### ISSUE TITLE
Improve the auto disable profiles after 10 failures

### ISSUE THREAD

**Issue by bigdiff** [floccusaddon/floccus#1660]
### Describe the feature you'd like to request

Now after disconnecting for a little bit all my profiles across multiple browsers are disabled and I have to manually go through all of them and enable (turn on auto-sync) again.

I get this error messages:

Failed to fetch Last synchronized: 7 hours ago
Retried 10 times before disabling this profile

### Describe the solution you'd like

I think it is best to increase the interval which it auto-syncs retries after a failure. For example if I've set the sync interval to 20 minutes when it first fails in should increase the interval to 1 hour then to 2 hours after the next failure then 4, 8, 16, 32 ...etc (these numbers are just exmaples)

This to avoid the problem mentioned before. Or an option can be added to disable the "disable auto syncing after 10 failures"

### Describe alternatives you've considered

The alternative now is to go through the 20 or so profiles I have in each browser and enable them again :sweat_smile: or export all the profiles change the option in the json and import them again lol

**Comment by marcelklehr** [comment]
@bigdiff You're right. Exponential backoff is a better way to handle this. Thanks for the feedback! :)
