### ISSUE TITLE
Add button to empty trash bin

### ISSUE THREAD

**Issue by vitorhmcorreia** [floccusaddon/floccus#1661]
### Describe the feature you'd like to request

Hey there!

Following the addition of the trash bin, I'd find it very helpful to have a button to bulk empty the trash bin, as opposed to having to click on each bookmark.

Use case: over time I've hoarded tens of bookmarks and I'm now in the process of deleting them, either because they serve no use anymore or have become unavailable. Sometimes I'm deleting > 20 bookmarks + folders at a time, and a button empty the trash bin on one go would be awesome.

### Describe the solution you'd like

The user journey could be something along the lines of:

- click on Bookmarks > Trash Bin > new button (wherever is possible to place it) to 'Empty trash bin'.

### Describe alternatives you've considered

Other than deleting one by one, I've considered evaluating how I could do it directly in the database.
Having said, I've been around long enough to know that by doing that, I'd be inviting trouble 😁

**Comment by marcelklehr** [comment]
Hello @vitorhmcorreia 
Thank you for your feedback!
This has already been reported on the bookmarks app repository: https://github.com/nextcloud/bookmarks/issues/2183
I'm thus closing this

**Comment by vitorhmcorreia** [comment]
Thank you @marcelklehr 😀
