### ISSUE TITLE
[Android] Settings button does not work

### ISSUE THREAD

**Issue by heapifyman** [floccusaddon/floccus#1663]
### Which version of floccus are you using?

5.2.3

### How many bookmarks do you have, roughly?

1k

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 14, June 2024, Google Pixel 6

### Describe the Bug

Pressing the settings button does nothing.

Probably related to #1659

### Expected Behavior

Settings should open.

### To Reproduce

1. Open floccus Android app
2. Press the settings button in the upper right corner

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Confirmed. Will be fixed with the next release.
