### ISSUE TITLE
Safari / MacOS / Sync failing

### ISSUE THREAD

**Issue by exoticatom** [floccusaddon/floccus#1672]
### Which version of floccus are you using?

5.24

### How many bookmarks do you have, roughly?

2000

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Safari

### Describe the Bug

unable to sync book marks with GitHub and Safari.
Same profile works with Chrome, Firefox and Opera.

Following error is shown on the first and every sync: The operation couldn’t be completed. (Capacitor.CapacitorUrlRequest.CapacitorUrlRequestError error 0.)
[floccus-5.2.4-2024-07-13-full.log](https://github.com/user-attachments/files/16203637/floccus-5.2.4-2024-07-13-full.log)

### Expected Behavior

Bookmarks sync should work with GitHub and Safari,

### To Reproduce

Configure git hub for syncing bookmarks. 

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey!

So, you installed floccus on MacOS Safari? From where?

**Comment by exoticatom** [comment]
Hey Marcel, thank you for answering.

Sorry, I meant MacOS floccus sync. (I wanted to use it with Safari), I had wrong assumption that it would be installed as Safari extension which is not. 

Installed it from Mac appstore.

**Comment by exoticatom** [comment]
Some additional info.

1) Syncing with google drive works, but not with github.
2) All other browsers I have (chrome, firefox, opera)  are working with the same github profile.
3) I tried creating github profile from scratch, but that also failed with same error.

**Comment by marcelklehr** [comment]
That is a known issue. Git sync currently doesn't work in the native apps, this will be fixed soon, though.

**Comment by exoticatom** [comment]
Ok thank you. I searched for it, couldn't find reference. Wish you nice WE
