### ISSUE TITLE
125k bookmarks: Stopped working altogether

### ISSUE THREAD

**Issue by cjpalermo21** [floccusaddon/floccus#1676]
### Which version of floccus are you using?

5.2.4

### How many bookmarks do you have, roughly?

125k

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 128.0

### Which version of Nextcloud Bookmarks are you using? (if relevant)

N/A

### Which version of Nextcloud? (if relevant)

N/A

### What kind of WebDAV server are you using? (if relevant)

N/A

### Describe the Bug

Stopped working around July 2 (newest iteration). Now, just sits and never proceeds (10+ hours).

Prior - it was working fine (after the changes) - suddenly, from 5.2.0 to 5.2.4 the process stopped working

### Expected Behavior

Expected my bookmarks to be synced to Google Drive

### To Reproduce

I hit the button. It begins. It never concludes.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey Chris,

I just re-read your email: You said you'd deleted the file on google drive. Did you also empty the trash? That seems to be  necessary sometimes. You also mentioned you are seeing `E018: Couldn't authenticate with the server.` Is that still the case?

**Comment by cjpalermo21** [comment]
I haven't actually tried since then ... but I can.

Chris

**Comment by marcelklehr** [comment]
> I haven't actually tried since then ... but I can.

Yes, please :) I'm sure we'll figure this out :)

**Comment by cjpalermo21** [comment]
Hi Marcus,

It would appear your recommendation to "empty the trash" did the trick.
Things seem to be moving correctly once again!

No idea why there was an issue; but yeah - I'm on 5.2.4 and it's lightning
quick.

Thanks again!

Chris
