### ISSUE TITLE
Very high load

### ISSUE THREAD

**Issue by poelzi** [floccusaddon/floccus#1677]
### Which version of floccus are you using?

5.2.4

### How many bookmarks do you have, roughly?

2k

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.2.2

### Which version of Nextcloud? (if relevant)

29.0.1

### Describe the Bug

The load in the background process is high, very high. So high, that the browser becomes sluggish and only disabling works.
Attached a profile from firefox profiler on the extension process:
[floccus profile - Firefox 2024-07-18 12.47 profile.json.gz](https://github.com/user-attachments/files/16282673/floccus.profile.-.Firefox.2024-07-18.12.47.profile.json.gz)
 

### Expected Behavior

not that high of a load

### To Reproduce

dunno

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thank you for the feedback @poelzi !
Is this a regression in your opinion, ie. has this been different before, or is this your first time using floccus?

**Comment by poelzi** [comment]
I'm not sure, it could be that it was always the case. My nextcloud is a bit sluggish at the moment, maybe some network io queues up ?

**Comment by marcelklehr** [comment]
Do you have automated error reporting enabled? (Not saying you should, but that might be an avenue to pursue for troubleshooting)

**Comment by marcelklehr** [comment]
This should be fixed in the latest version.
