### ISSUE TITLE
Cancel button doesn't work

### ISSUE THREAD

**Issue by InfamousUser** [floccusaddon/floccus#1682]
### Which version of floccus are you using?

5.2.4

### How many bookmarks do you have, roughly?

5000

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 128.0, Chrome 125.0.6422.76

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.2.2

### Which version of Nextcloud? (if relevant)

29.0.4

### Describe the Bug

Pressing cancel button while syncing doesn't change syncing.

### Expected Behavior

Pressing cancel button while syncing changes the syncing status.

### To Reproduce

1. Sync
2. Don't sync

### Debug log provided

- [ ] I have provided a debug log file

**Comment by InfamousUser** [comment]
I see it has cancelled now, while I was writing the bug report. I accidentally started a sync while backing up and restoring bookmarks so I tried to stop it but it took a good minute or two to stop syncing. This make the button useless, might as well wait for it to stop the sync...

**Comment by marcelklehr** [comment]
> I see it has cancelled now, while I was writing the bug report.

Yes, the cancel button doesn't work as immediately as it should

**Comment by marcelklehr** [comment]
It's kind of hard to immediately stop a running code fragment. In the next release the cancel action will just reload the whole extension to make this more immediate.

**Comment by InfamousUser** [comment]
Aren't interrupts made to handle things like these? I don't know too much about programming though, so maybe I'm completely wrong...
