### ISSUE TITLE
xbel file corruption preventing sync

### ISSUE THREAD

**Issue by Simplenuity** [floccusaddon/floccus#1684]
### Which version of floccus are you using?

5.2.4

### How many bookmarks do you have, roughly?

about 1.5k

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 113.0.2 (64-bit), Google Chrome 126.0.6478.182 (Official Build) (64-bit), Opera (outdated version) 92.0.4561.43

### Which version of Nextcloud Bookmarks are you using? (if relevant)

n/a

### Which version of Nextcloud? (if relevant)

28.0.5.1

### What kind of WebDAV server are you using? (if relevant)

Nextcloud instance offered by Webo.hosting

### Describe the Bug

After some undefined time (can be some days or weeks) configured auto-sync stops working with error:

"Cannot read properties of undefined (reading 'tagName')"

It turns out that this is caused by file corruption of the synced xbel file. The content of the file gets randomly cut off at some stage, i.e. part of it is missing at the end of the file.

Only one browser is configured to always upload local changes, all other browsers are configured to only download while discarding local changes.

The installed Nextcloud client is working fine. All files are kept in sync, including the corrupt xbel file. No other file has been corrupted therefore I assume the corruption might have to do with the floccus upload process?
Is there a way to influence the way floccus uploads the xbel file? For example is it possible to only replace an older file online after the local xbel file has completely and successfully been uploaded? Or is the upload incremental anyway?

### Expected Behavior

The integrity of the xbel file is secured no matter whether it's completely replaced by a new file version or the file online gets incrementally updated.

### To Reproduce

Unfortunately no steps to reproduce available. File corruption seems to occur randomly.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @Simplenuity 
Thank you for the feedback!

> The installed Nextcloud client is working fine. All files are kept in sync, including the corrupt xbel file. No other file has been corrupted therefore I assume the corruption might have to do with the floccus upload process?

That seems likely, yes. What is the rough size of the full, non-corrupted file? It may be too big for the server. The nextcloud client uses some nextcloud specific hacks to circumvent such limitations.

> Is there a way to influence the way floccus uploads the xbel file? For example is it possible to only replace an older file online after the local xbel file has been completely and successfully been uploaded? Or is the upload incremental anyway?

I'm afraid we'd be running into other race conditions then: What if the client machine goes offline before the file was moved in place?

I think the best course of action is to talk  to your hoster, if that is possible.

**Comment by marcelklehr** [comment]
> The file size is currently about 270 kB.

Mh, that size doesn't seem very large, but that is after the corruption, right?

> could you please let me know how the update process works?

So, floccus just does a PUT request on the file and uploads the new contents in the HTTP body. That's standard webdav. No incremental uploads like the Nextcloud Desktop client does.

**Comment by marcelklehr** [comment]
Cool, keep me posted :)

**Comment by marcelklehr** [comment]
Ah, thanks for the follow-up @Simplenuity! Your message got lost in my inbox.
So, the hoster wasn't too helpful it seems :/ 

> From my memory I have not experienced the file corruption whithout the Nextcloud client running, i.e. syncing also the xbel file from the server to a local folder. However I couldn't identify any clear error message in the log files in connection with file corruption, but will check more timely in the future.

Perhaps you could confine floccus sync to a folder that is not synced via the nextcloud client?

> add an additional sync option: a local file

Sigh. Yes, that would be a superb feature. It's sadly not possible to access the file system directly from a web extension. You can try using LoFloccus instead which is basically a local WebDAV server, allowing you to sync floccus to a local file. But a direct floccus to filesystem connection is not possible sadly :(
