### ISSUE TITLE
syncing browser tabs (read only, no upload) fails while same config works when changed to sync bookmarks

### ISSUE THREAD

**Issue by vacy** [floccusaddon/floccus#1685]
### Which version of floccus are you using?

5.2.4

### How many bookmarks do you have, roughly?

5

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome Version 126.0.6478.183 (Offizieller Build) (64-Bit)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.2.2

### Which version of Nextcloud? (if relevant)

28.0.8

### Describe the Bug

i want to setup a folder in nextcloud that contains tabs to be opened on any browser startup.
configure floccus to sync from nextcloud as browser tabs, not bookmarks.
tried to configure nested and not nested profiles.
also configured to only download, not upload tabs.

On all syncs i get that message in floccus "No tab with id: 1997147818." The ID does not change.

But if I do change the config from browser tabs to bookmarks sync, then it works fine while i dont change any other config.

### Expected Behavior

just sync and open the bookmarks contained in the nextcloud folder as tabs

### To Reproduce

# relevant json config:

### this does not work:
[
  {
    "localRoot": "tabs",
    "strategy": "slave",
    "syncInterval": 15,
    "nestedSync": false,
    "failsafe": true,
    "allowNetwork": false,
    "errorCount": 30,
    "clickCountEnabled": false,
    "type": "nextcloud-bookmarks",
    "serverRoot": "/startup-bookmarks",
    "includeCredentials": false,
    "allowRedirects": false,
    "enabled": true,
    "syncing": 0.15,
    "scheduled": false,
    "error": null
  }
]

### this works:
[
  {
    "localRoot": "242",
    "strategy": "slave",
    "syncInterval": 15,
    "nestedSync": false,
    "failsafe": true,
    "allowNetwork": false,
    "errorCount": 0,
    "clickCountEnabled": false,
    "type": "nextcloud-bookmarks",
    "serverRoot": "/startup-bookmarks",
    "includeCredentials": false,
    "allowRedirects": false,
    "enabled": true,
    "syncing": false,
    "scheduled": false,
    "error": null,
    "lastSync": 1721812503341
  }
]

### Debug log provided

- [X] I have provided a debug log file
- NOTE: i uploaded a redacted logfile to your nextcloudserver, filename: vacygithub-floccus-5.2.4-2024-07-24-redacted.log

**Comment by marcelklehr** [comment]
Hi @vacy

Floccus expects the bookmarks on the server to be in a sub folder for each browser window. So, for your use case, you will need to create a new subfolder under /startup-bookmarks and put the links to open as tabs in there.

**Comment by vacy** [comment]
@marcelklehr 
thanks for the quick reply :)
it kinda works that way, the error stays though.

aaand it does not seem to be what i did expected.
it does not open the tabs upon browser startup, does it? only on a sync?

**Comment by marcelklehr** [comment]
> it does not open the tabs upon browser startup, does it? only on a sync?

It should sync a few seconds after browser startup, but only if the last sync is more then X minutes old (X being the interval you configured)

> it kinda works that way, the error stays though.

Can you try clearing the cache in the profile settings?

**Comment by vacy** [comment]
sorry, i didnt check anymore before i deleted the profile. i just go with regular sync by floccus :)
