### ISSUE TITLE
Folder named with asterisks can't be opened from android app

### ISSUE THREAD

**Issue by RAPXT** [floccusaddon/floccus#1686]
### Which version of floccus are you using?

Firefox: 5.2.5 // Android: 5.2.4

### How many bookmarks do you have, roughly?

ca. 400

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Describe the Bug

I have my bookmarks sorted in folders. Folder names consist of only letters and numbers except one folder which is named liked this: `*EXAMPLE*`

From Firefox i have no problem accessing all my bookmarks. In the Android app on the other hand, i can open all conventionally named folders, but the one folder named with asterisks can't be opened. If i click on it, it only becomes highlighted but nothing else happens.

Maybe we should take a closer look, if other symbols are also affected.

### Expected Behavior

It should open just like any other folder.

### To Reproduce

1. Open the Android app
2. Rename a folder like this scheme: `*EXAMPLE*`
3. The folder named with asterisks shouldn't open now, where as any other should.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Mmh, I can't seem to reproduce this. Maybe the reason is rather the contents of the folder than the title?

**Comment by marcelklehr** [comment]
Could you otherwise perhaps share an export of your bookmarks with my privately?

**Comment by RAPXT** [comment]
Sorry for taking so long for a respone. I hope you can understand that i don't want to share my very private bookmarks with anyone except myself =D

But as far as contents of it is concerned, I've noticed that i have a lot of "about:about" (Firefox internal page) bookmarks. Maybe that could be the culprit?! I'll try something and let you know when i'm finished.

**Comment by marcelklehr** [comment]
> Sorry for taking so long for a respone. I hope you can understand that i don't want to share my very private bookmarks with anyone except myself =D

Of course, that's one of the reasons floccus exists :)

**Comment by marcelklehr** [comment]
@RAPXT Any news on this?

**Comment by RAPXT** [comment]
Yes, in the meantime i did reflash and resetup my android. Now it works (even with asterisks). The folder opens a bit slower, but that maybe because of very many bookmarks. Other than that, everything works as expected. Apologies for that non-error.
