### ISSUE TITLE
Push rejected because it was not a simple fast-forward. Use "force: true" to override.

### ISSUE THREAD

**Issue by eglimpse** [floccusaddon/floccus#1688]
### Which version of floccus are you using?

5.2.5

### How many bookmarks do you have, roughly?

10k

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chromium Version 127.0.6533.89 (Official Build, ungoogled-chromium) (64-bit)

### Describe the Bug

"Push rejected because it was not a simple fast-forward. Use "force: true" to override."

Pushing to local Bonobo Git Server Repository I specifically just set up for this today. I'm a new user of this extension. 

Here's my single profile export.

[
  {
    "localRoot": "0",
    "strategy": "default",
    "syncInterval": 15,
    "nestedSync": false,
    "failsafe": true,
    "allowNetwork": true,
    "label": "BookmarksSyncErikglimpse",
    "errorCount": 1,
    "clickCountEnabled": false,
    "type": "git",
    "url": "http://localhost/Bonobo.Git.Server/BookmarksSyncErikglimpse.git",
    "username": "bookmarksUser",
    "password": "HIDDEN",
    "branch": "main",
    "bookmark_file": "bookmarks.xbel",
    "bookmark_file_type": "xbel",
    "includeCredentials": false,
    "allowRedirects": false,
    "force": true,
    "enabled": false,
    "syncing": false,
    "scheduled": false,
    "error": "Push rejected because it was not a simple fast-forward. Use \"force: true\" to override."
  }
]

Here's my log: 

2024-08-03T01:30:40.148Z Starting sync process for account BookmarksSyncErikglimpse
2024-08-03T01:30:40.188Z onSyncStart: begin
2024-08-03T01:30:40.188Z (git) init
2024-08-03T01:30:40.196Z (git) fetch from remote
2024-08-03T01:30:40.250Z (git) writeFile /846c731431f5e5eca257c0dbe6af506d6b35249e73956b3d2d5ffb5c818831b11722648640188//README.md
2024-08-03T01:30:40.250Z (git) add .
2024-08-03T01:30:40.252Z (git) commit
2024-08-03T01:30:40.256Z (git) push
2024-08-03T01:30:40.299Z onSyncFail
2024-08-03T01:30:40.300Z Syncing failed with Push rejected because it was not a simple fast-forward. Use "force: true" to override.
2024-08-03T01:30:40.300Z onSyncFail

### Expected Behavior

It should perform the first initial commit of all my bookmarks.

### To Reproduce

Set up new Floccus Profile with a new Bonobo Git Server Repository on Windows 11 with Chromium.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Mmh, Floccus seems to first think that the branch does not exist, but when pushing it does exist already. I assume this error persists when retrying? What is the state of the repository exactly?

**Comment by eglimpse** [comment]
It doesn't appear that Bonobo Git Server is actively being supported, and it might lack what is required to exchange data with Floccus. I just set up Gitea, and it's a much better experience in general for a self-hosted Git server. And it works very well with Floccus, as long as you set up a key for the user, and use it instead of a password in the Floccus profile setup. Otherwise you'll have to directly log into the Gitea web interface through the specific Chromium profile to enable syncing to the Gitea Git server with Floccus. Not sure if that was intended or no, but adding and using a key instead of a password in Gitea resolves this issue.
You should be able to close this issue, since Bonobo is basically dead and too technically limited potentially.

**Comment by marcelklehr** [comment]
Yes, for most git services you will need to create an access token for floccus, that is expected :) I'm glad you got it to work!
