### ISSUE TITLE
Floccus iOS Git error

### ISSUE THREAD

**Issue by Retch** [floccusaddon/floccus#1690]
### Which version of floccus are you using?

5.2.5

### How many bookmarks do you have, roughly?

300

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iOS 17.6 - iPhone 12 Pro

### Describe the Bug

I set up sync on the Floccus app on iOS manually and with importing the Floccus profile export from Chrome. In both cases, the app says "failed to checkout". Sync with Firefox works. Github.com is used.

![floccus_ios_error](https://github.com/user-attachments/assets/efb8d5a6-ac78-4d0c-89e9-88e8549964f2)
![floccus_github](https://github.com/user-attachments/assets/f29f5522-04a5-4860-8863-c217d9060336)

### Expected Behavior

I expect it to do a fetch automatically if it wants a fetch. I'm not able to perform a fetch.

### To Reproduce

Use Git sync on iOS.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @Retch 
Thank you for your feedback! Git sync is currently not working on mobile, yet. This is a known issue: see #1608 
I'm sorry about the inconvenience.
