### ISSUE TITLE
Android app sync

### ISSUE THREAD

**Issue by kalekad** [floccusaddon/floccus#1692]
### Which version of floccus are you using?

5.2.5

### How many bookmarks do you have, roughly?

500

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

LineageOS 20(Android 13)

### Describe the Bug

Returning to the open application will start the synchronisation.

### Expected Behavior

When returning to an open application, synchronization will not occur for no apparent reason.

### To Reproduce

Open the app, quit the app (it's in recently launched apps) and return to the app.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> When returning to an open application, synchronization will not occur for no apparent reason.

Are you certain that you had not added any bookmarks recently before returning to the app?

**Comment by IngoBelka** [comment]
I can confirm this behaviour. For me, Huawei MediaPad with Android 9, it's the same. Cause of this I find a big amount oft *.lock files in my Nextcloud waste basket. I set AutoSync off and SyncIntervall 1 time a day.

![Screenshot_20240820_102037_org handmadeideas floccus](https://github.com/user-attachments/assets/bdbaa2dd-3d2a-4b46-a86f-d9ef6327ec57)
