### ISSUE TITLE
"Resource is locked, trying again soon". How to fix this?

### ISSUE THREAD

**Issue by andreynering** [floccusaddon/floccus#1693]
### Which version of floccus are you using?

5.2.5

### How many bookmarks do you have, roughly?

274

### Are you using other means to sync bookmarks in parallel to floccus?

Yes, Chrome sync

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 127.0.6533.99

### Describe the Bug

I noticed today that the sync is locked. It seems to be in this state for a few days. The button to manually sync is in a read-only state, so I can't force it to sync. I don't know what to do to fix the problem.

Logs:

```log
2024-08-07T20:33:46.510Z Starting sync process for account JobScore
2024-08-07T20:33:46.514Z onSyncStart: begin
2024-08-07T20:33:46.514Z (git) init
2024-08-07T20:33:46.538Z (git) fetch from remote
2024-08-07T20:33:47.438Z (git) checkout branch main
2024-08-07T20:33:47.445Z onSyncFail
2024-08-07T20:33:47.445Z Resource is locked, trying again soon
```

![Screenshot 2024-08-07 at 17 33 41](https://github.com/user-attachments/assets/764e29e2-88df-4dde-93f3-b39369499bfc)

### Expected Behavior

Sync should happen.

### To Reproduce

Sorry, I don't know how to reproduce it.

### Debug log provided

- [X] I have provided a debug log file

**Comment by andreynering** [comment]
Oh, rubber duck 🦆 🤦‍♂️ 

I just opened the issue and noticed the sync happened as expected.

![Screenshot 2024-08-07 at 17 40 01](https://github.com/user-attachments/assets/6152cfb4-ea7c-4f30-9165-945464dfcb3f)

Maybe still worth keeping open, though? I don't know why such lock would happen. Does it "expire" automatically after some time?

**Comment by marcelklehr** [comment]
> Does it "expire" automatically after some time?

Yes it does :)

**Comment by andreynering** [comment]
@marcelklehr What explains the lock, though? Just curious to understand what happened.

**Comment by marcelklehr** [comment]
The reason for the lock is that we can't have multiple clients sync at the same time without getting into trouble. So, in order to only ever have one client sync bookmarks, the client that came first sets a lock. All other clients then see the lock and wait until it's gone again and it's their turn. Sometimes, it can happen that while a client is syncing, the computer is put to sleep or the browser is closed or some other event interrupts the sync run without the client being able to release the lock, this then causes the other clients to wait indefinitely, in theory. However, I've built in a timeout after which they assume something is wrong, give up waiting and just sync anyway.

**Comment by rhclayto** [comment]
How long is the timeout? Can we force the lock to expire? I'm trying to debug some problems when Floccus is syncing with Nextcloud Bookmarks, & I keep having to wait for the lock to expire to continue debugging.

**Comment by metal450** [comment]
For the git sync method, the way to release the lock is to manually delete the `floccus-lock-xxx` tag in the git repo

**Comment by patienttruth** [comment]
@rhclayto 
> Edit: It's 30 minutes (in the Nextcloud Bookmarks code), & I figured out how to delete the lock through an API call (`DELETE /apps/bookmarks/public/rest/v2/lock`).

Would you mind sharing how you used the API call? Thanks.

@marcelklehr do you know if the lock applies across profiles, or per profile?

With gratitude,

**Comment by marcelklehr** [comment]
@patienttruth In all likelyhood, you do not need to do anything for the lock to be freed, nowadays. It will be released automatically after a certain time, but in recent versions of floccus you can even force a sync in this situation.

**Comment by patienttruth** [comment]
I appreciate the response @marcelklehr. Currently I have a tabs profile for my laptop and my PC (2 different profiles) and a book marks profile that they both sync to. The laptop hasn't been on in a day or two, so I don't think it should be locking anything.

My PC has both its tab profile and the bookmarks profile saying "Synchronization in progress.", however when I check a log all I see appears to be outdated by a couple days. This is just after disabling, enabling and requesting a sync. I believe the PC was left on overnight so I'd think it could sort everything out if it weren't stuck on something.

Any other ideas?

```
2025-04-21T23:37:47.306Z Receiving response for GET https://lab.URL.com/index.php/apps/bookmarks/public/rest/v2/bookmark?page=1&limit=1
2025-04-21T23:37:47.307Z QUEUING POST https://lab.URL.com/index.php/apps/bookmarks/public/rest/v2/lock
2025-04-21T23:37:47.308Z FETCHING POST https://lab.URL.com/index.php/apps/bookmarks/public/rest/v2/lock
2025-04-21T23:37:47.480Z Receiving response for POST https://lab.URL.com/index.php/apps/bookmarks/public/rest/v2/lock
2025-04-21T23:37:47.483Z Resource is locked, trying again soon
```
