### ISSUE TITLE
floccus doesnt sync anywhere anymore it says sheduling on most devices a if it try to sync it does nothing

### ISSUE THREAD

**Issue by IzunaMoon** [floccusaddon/floccus#1695]
### Which version of floccus are you using?

5.2.5

### How many bookmarks do you have, roughly?

6 in publiek folders we share with man about 120 in hour groups folder 

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

firefox 129.0 (64-bit) edge 127.0.2651.86 (Official build) (64-bit) crome 127.0.6533.100 (Officiële build) (64-bits)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.2.4

### Which version of Nextcloud? (if relevant)

29.0.4

### Describe the Bug

floccus is keep switching between syncing a scheduling but it does not sync i try to alter de bookmarks a it did nothing
![image](https://github.com/user-attachments/assets/fe3a49ee-0574-4396-bb2f-ba304de2969c)

ps this issue seem to have started around 2 3 hours ago on hour end

### Expected Behavior

sync bookmarks with de right folders

### To Reproduce

i already have this issue with a fress floccus install so just download floccus add de add one link de nextcloud server bookmarks a done

### Debug log provided

- [ ] I have provided a debug log file

**Comment by IzunaMoon** [comment]
small update i try it with another nextcloud server a it seem to work so i'm gonna look further into it  but ithink it is more a issue with de nextcloud than floccus now i keep updated if i find more

**Comment by marcelklehr** [comment]
This *should* theoretically resolve itself on its own
