### ISSUE TITLE
Unescaped HTML tag `<script>` in bookmark title names

### ISSUE THREAD

**Issue by artshade** [floccusaddon/floccus#1697]
### Which version of floccus are you using?

5.2.6

### How many bookmarks do you have, roughly?

20k

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Google Chrome, 127.0.6533.120 (Official Build) (64-bit)

### What kind of WebDAV server are you using? (if relevant)

[RClone WebDav](<https://rclone.org/commands/rclone_serve_webdav/>) (built-in server).

```sh
$ rclone --version;
rclone v1.67.0
- os/version: alpine 3.20.0 (64 bit)
- os/kernel: 4.4.302+ (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.4
- go/linking: static
- go/tags: none
```

### Describe the Bug

Sincere appreciation for the project! Thank you! ✨

When tried syncing bookmarks with the following bookmark added, the whole set of bookmarks got missing in clients after manual import. A bookmark example with `<script>` tag:

Title: `HTML - <script> Tag - Tutorialspoint`
URL: `https://www.tutorialspoint.com/html/html_script_tag.htm`

### Expected Behavior

Safe parsing of bookmarks data.

## Initial state of bookmarks

![image](https://github.com/user-attachments/assets/bb097c62-7e35-4f77-8245-75b12f145b80)

#### Push

The bookmarks file on WebDav remote:
```html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE><!--- highestId :13: for Floccus bookmark sync browser extension -->
<DL><p>
<DT><H3 ID="1">test</H3>
<DL><p>
  <DT><A HREF="https://example.com/" TAGS="" ID="2">Example Domain</A>
  <DT><A HREF="https://example.com/test" TAGS="" ID="3">Example Domain (issue) <script> 123</A>
  <DT><A HREF="https://example.com/copy" TAGS="" ID="9">Example Domain (copy)</A>
  <DT><A HREF="https://example.com/jscs" TAGS="" ID="10">Example Domain (JavaScript comment start) /* 456</A>
  <DT><A HREF="https://example.com/copy2" TAGS="" ID="11">Example Domain (copy 2)</A>
  <DT><A HREF="https://example.com/jsce" TAGS="" ID="12">Example Domain (JavaScript comment end) "*/"? - Test</A></A>
  <DT><A HREF="https://example.com/copy3" TAGS="" ID="13">Example Domain (copy 3)</A>
</DL><p>
</DL><p>
</html>
```

#### Pull attempt

![image](https://github.com/user-attachments/assets/12655735-0cde-4b80-93d0-1219a0460eef)

#### Pull ("fail-safe" disabled)

![image](https://github.com/user-attachments/assets/0571af09-df5f-4793-b464-31c46e3dc231)

#### Push (2 time)

The bookmarks file on WebDav remote:
```html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE><!--- highestId :13: for Floccus bookmark sync browser extension -->
<DL><p>
<DT><H3 ID="1">test</H3>
<DL><p>
  <DT><A HREF="https://example.com/" TAGS="" ID="2">Example Domain</A>
  <DT><A HREF="https://example.com/test" TAGS="" ID="3">Example Domain (issue)  123</A>   <DT><A HREF="https://example.com/copy" TAGS="" ID="9">Example Domain (copy)</A>   <DT><A HREF="https://example.com/jscs" TAGS="" ID="10">Example Domain (JavaScript comment start) /* 456</A>   <DT><A HREF="https://example.com/copy2" TAGS="" ID="11">Example Domain (copy 2)</A>   <DT><A HREF="https://example.com/jsce" TAGS="" ID="12">Example Domain (JavaScript comment end) "*/"? - Test</A></A>   <DT><A HREF="https://example.com/copy3" TAGS="" ID="13">Example Domain (copy 3)</A> </DL><p> </DL><p> </html></A>
</DL><p>
</DL><p>
</html>
```

#### Pull (2 time; "fail-safe" disabled)

![image](https://github.com/user-attachments/assets/9b8e7157-8a98-464d-b035-025ab265398a)

#### Imported the version from remote

![image](https://github.com/user-attachments/assets/23eeb0f3-7ee1-446e-a6f4-2dd1aeef8dfd)

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @artshade 
The thing is that we cannot make use of DOM methods, because floccus sync happens in a service worker...

**Comment by marcelklehr** [comment]
I've been actively trying to avoid JSDOM because it's huge. Additionally, the bookmarks html spec does not accept just any html with the right elements, but a very specific subset of HTML that is best hand-crafted, IMO.

**Comment by marcelklehr** [comment]
I'm not using regular expressions to parse HTML. I'm using a parser.

**Comment by marcelklehr** [comment]
I'm not inclined to continue this conversation unless you are committing to constructive communication. Please refrain from making snark remarks. If you have something to say, say it outright.

**Comment by marcelklehr** [comment]
Concretely, referring back to your example:

```
<html><head></head><body><dt><a href="https://example.com/">12"3"&lt;script&gt;456</a></dt><dt><a href="https://example.com/test">456&lt;script&gt;"7"89</a></dt></body></html>
```

This may be valid html, but it's not a valid bookmarks file. Firefox for example, will fall back to just importing the links without any hierarchy.

**Comment by marcelklehr** [comment]
Then let's be constructive: Why is floccus currently using a "parser" instead of a parser to parse the bookmarks format?
