### ISSUE TITLE
[Android] re-directed to cloud rather than "Grant Access" screen after successful login

### ISSUE THREAD

**Issue by sunjam** [floccusaddon/floccus#1700]
### Which version of floccus are you using?

5.2.5

### How many bookmarks do you have, roughly?

3k

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 129.0.1

### Which version of Nextcloud Bookmarks are you using? (if relevant)

unsure, cannot access host

### Which version of Nextcloud? (if relevant)

v29

### What kind of WebDAV server are you using? (if relevant)

Nextcloud

### Describe the Bug

After logging into my Nextcloud account I am not shown the option to grant access, but instead re-directed into Nextcloud itself.

### Expected Behavior

After successful login, `Grant Access` button step.

### To Reproduce

Log into Nextcloud from Floccus: Username, Password, Two Factor.
Re-directed to actual cloud default app (Files or Dashboard)
Closing out of this (`X`) takes me to the "Abort" step in Floccus.
Select `Abort` and then `Login` again.
`Grant Access` screen appears.

Occurred while testing #1129 on a new Android device.  An alternative method for authentication would be 
- #1535 
### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
I think this is an upstream issue in Nextcloud that has to do with using Twofactor. It seems to work without twofactor for me.

**Comment by sunjam** [comment]
Okay, definitely needs addressing. I would be curious what other applications are impacted and will look for an open server issue.

**Comment by sunjam** [comment]
> I think this is an upstream issue in Nextcloud that has to do with using Twofactor. It seems to work without twofactor for me.

From mobile devs chat:
This depends how the login mechanism is done.
The app needs to send a specific header: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html

**Comment by marcelklehr** [comment]
I'm using login flow v2, I'm not aware of any header that needs setting.

**Comment by sunjam** [comment]
https://cloud.nextcloud.com/index.php/call/ex4id6qh

**Comment by marcelklehr** [comment]
Based on the description in the link you sent I'm not doing anything wrong.
