### ISSUE TITLE
Floccus unavailable in ChromeWebStore and reporting that existing installs may no longer be supported.

### ISSUE THREAD

**Issue by delinuxco** [floccusaddon/floccus#1705]
### Which version of floccus are you using?

5.2.5

### How many bookmarks do you have, roughly?

500

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chromium

### Describe the Bug

ChromeWebStore says floccus unavailable to install on new Chromium browser install. 
On existing installs, says it will not be supported much longer.
![ksnip_20240823-072116](https://github.com/user-attachments/assets/ed1a1c04-01cb-4290-b37b-b00aa3e4c6a3)

### Expected Behavior

Should be available for install.

### To Reproduce

Go to ChromeWebStore

### Debug log provided

- [ ] I have provided a debug log file

Note: of the devices that is stil installed, syncing via WebDav is working fine.

**Comment by delinuxco** [comment]
Well, I think this issue is related to the degoogled Chromium AppImage and not floccus

**Comment by marcelklehr** [comment]
> Well, I think this issue is related to the degoogled Chromium AppImage and not floccus

So, Degoogled Chromium will no longer support floccus?
