### ISSUE TITLE
Google Drive Link Account Not Working (Firefox)

### ISSUE THREAD

**Issue by Galthariel** [floccusaddon/floccus#1712]
### Which version of floccus are you using?

5.2.6

### How many bookmarks do you have, roughly?

3.000

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 130.0

### Which version of Nextcloud Bookmarks are you using? (if relevant)

NA

### Which version of Nextcloud? (if relevant)

NA

### What kind of WebDAV server are you using? (if relevant)

NA

### Describe the Bug

While setting up the add-on and selecting Google Drive as the option, it opens another window to authorize, and after I choose my Login info I get a message saying "SOMETHING WENT WRONG".

I already tried with all Add-ons Disabled and also in a Private Browsing

### Expected Behavior

I expect to be able to link Floccus to my Google Drive

### To Reproduce

See above in the Bug Description

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
This is somehow a known issue with a long history that I have not been able to reproduce so far :/

See https://github.com/floccusaddon/floccus/issues/1562 for the history on this. I'm closing this ticket in favor of that. Comment here, if you believe your issue is different from the one I linked.

**Comment by Kopilut** [comment]
> This is somehow a known issue with a long history that I have not been able to reproduce so far :/
> 
> See #1562 for the history on this. I'm closing this ticket in favor of that. Comment here, if you believe your issue is different from the one I linked.

Did you tested that on Firefox with containers enabled?
