### ISSUE TITLE
Syncing Problems when changing the titles of bookmarks in the browser (at least Firefox)

### ISSUE THREAD

**Issue by elmanuke** [floccusaddon/floccus#1720]
### Which version of floccus are you using?

v5.2.7

### How many bookmarks do you have, roughly?

50

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 130.0 (64-Bit)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

v14.2.5

### Which version of Nextcloud? (if relevant)

v29.0.5

### What kind of WebDAV server are you using? (if relevant)

I do not use a WebDAV server for syncing

### Describe the Bug

When I do changes to my bookmarks in the Firefox Browser, i.e. changing the title, I have problems uploading these changes to nextcloud. The floccus addon shows the error "E018: Couldn't authenticate with the server.", sometimes even several times:
![Bildschirmfoto 2024-09-15 um 17 16 34](https://github.com/user-attachments/assets/2abc3ab7-03a8-4848-91e4-6cd1b4050910)

When I download the bookmarks from the remote server, my local title changes are overwritten (just as expected).
However, when adding or removing bookmarks locally within Firefox, the described syncing problem does not occur. It is just related to title changes of existing bookmarks.

### Expected Behavior

I would expect the changes to be uploaded to the remote Nextcloud server

### To Reproduce

1. Create a profile and setup some bookmarks and sync them with Nextcloud bookmarks
2. Change the title of a bookmark in Firefox
3. Try to upload the change you made to Nextcloud
4. Observe the error

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @elmanuke 
This is a strange one. Can you check the nextcloud log for errors? Is it possible that these are bookmarks that you don't have write access in Nextcloud Bookmarks, because they were shared with you by someone else?

**Comment by elmanuke** [comment]
Hi @marcelklehr,
thanks for answering so quickly! I use nextcloud with the [hetzner storageshare](https://docs.hetzner.com/konsoleh/storage-share/general) and I haven't found out how to get the logs of the nextcloud instance..
Also the write access should not be a problem..

But I tried a bit around and found out, that for some reason it does only affect some of my bookmarks. And these are the bookmarks, that are marked as duplicates in the nextcloud bookmarks app. However, I do not know who these bookmarks are labled as duplicates as they are only in one folder and actually only exist once, just like all the other bookmarks.
<img width="294" alt="grafik" src="https://github.com/user-attachments/assets/d9008bc5-8ccf-4917-9a2c-8b8e592794c1">

Even exporting all bookmarks as an html file, deleting everything in nextcloud bookmarks and importing them again did not help. After uploading via a sync with floccus, I again was not able to change the title of these 38 bookmarks within firefox.

Do you have an idea what could be the reason for the wrong duplicates and why that creates the weird title change error described above?

**Comment by marcelklehr** [comment]
This may have to do with the new trash bin feature in Nextcloud Bookmarks, could you try clearing the trash bin in Nextcloud Bookmarks?

**Comment by elmanuke** [comment]
I tried it, but it did not help. The weird thing is that, even after deleting all bookmarks in Nextcloud and uploading them again, I still have exactly the same behaviour.

However, I found another way how to get rid of the wrong duplicates: I changed the titles of all wrong duplicates in Nextcloud, downloaded them via floccus, changed the titles back in Firefox and uploaded them again via floccus. Now I got rid of that strange behaviour, but it's a lot of manual and individual bookmark debugging..

**Comment by marcelklehr** [comment]
So, the steps to reproduce would be

1. Create two bookmarks with the same url in two different folders
2. Try to change the title of one of the two bookmarks
3. boom

Would this be correct?

**Comment by elmanuke** [comment]
Ah not really, I did not have any duplicate bookmarks in two separate folders, Nextcloud bookmarks for some reason just thought, that there were duplicates. But I have no idea why the bookmarks were interpreted as duplicates.

**Comment by marcelklehr** [comment]
Mmmh, the only reason for duplicates being detected where there are non to my knowledge could be the trash bin :/ But you said you'd cleared that before trying again.
