### ISSUE TITLE
Bookmarks are not synced in the mobile app

### ISSUE THREAD

**Issue by Minitajfun** [floccusaddon/floccus#1721]
### Which version of floccus are you using?

5.2.7

### How many bookmarks do you have, roughly?

60

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 14

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.2.5

### Which version of Nextcloud? (if relevant)

29.0.5

### Describe the Bug

The floccus mobile app is not synchronizing bookmarks.
`! Failed to map parentId: 0` is displayed at the top of the screen.
![Screenshot_2024-09-19-01-44-51-620_org handmadeideas floccus](https://github.com/user-attachments/assets/a2cfd3a6-b1da-42b4-a6a2-3fcc8e6947a6)

### Expected Behavior

Bookmarks should be synced

### To Reproduce

1. Open app
2. Press sync button or wait for synchronization to start automatically
3. After a while, synchronization will stop. `! Failed to map parentId: 0` will be displayed at the top of the screen.

### Debug log provided

- [x] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hello @Minitajfun 

Do you per chance have multiple profiles for different nextcloud accounts on the same nextcloud setup? There was a problem with that in the mobile app previously, which may have left you with the wrong set of bookmarks for a profile.

Nontheless, For now you can check, if the server or the app have the right set of bookmarks, perhaps make a backup to be sure you won't lose anything, and do a force up or download. If even that doesn't work, you can trigger a fresh sync in the settings by clearing the cache, for this I really recommend doing a backup though.
