### ISSUE TITLE
Manually adding bookmark android app throws error

### ISSUE THREAD

**Issue by whisperdancer** [floccusaddon/floccus#1725]
### Which version of floccus are you using?

5.2.7

### How many bookmarks do you have, roughly?

500

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 130.0.1

### Which version of Nextcloud Bookmarks are you using? (if relevant)

Latest

### Which version of Nextcloud? (if relevant)

29.x

### Describe the Bug

I tried adding a bookmark via the flocus android app and received an error "Failed to map parent Id" It then added a lock and unable to sync until the app eventually removed the locks.

### Expected Behavior

I expected to be able to add a bookmark using android app and not receive an error. 

### To Reproduce

1. Manually add bookmark using android app. Add it one or 2 levels down the bookmark tree.
2. Get error "failed to map parentId"
3. Now all clients are stuck in a "Scheduled" mode and won't sync until some time has passed and flocus removes the locks.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by whisperdancer** [comment]
I just found this page which discusses my issue. https://floccus.org/faq/

I will wait 2 hours and report back if it has started syncing again. Note, I removed the android app and cleared cache. If all goes well with the browser, then I will install android app again and I believe it should sync ok.

Thanks

**Comment by whisperdancer** [comment]
Update, flocus removed the locks and the issue is resolved. Syncing great again. However, the issue with adding a manual bookmark via the android app which caused the issue remains.

**Comment by marcelklehr** [comment]
You can get around the failed to map parentId error by triggering a sync from scratch in the profile settings. Make sure to have a backup of your bookmarks before you do this.
