### ISSUE TITLE
Linkwarden not completely syncing

### ISSUE THREAD

**Issue by csamolot** [floccusaddon/floccus#1728]
### Which version of floccus are you using?

5.3.0 beta 1

### How many bookmarks do you have, roughly?

150

### Are you using other means to sync bookmarks in parallel to floccus?

Yes, I also sync via Mozilla

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android Iceraven 2.23.1

### Describe the Bug

With the new Linkwarden sync. When having multiple sub folders on Linkwarden I'm unable to completely syn the folders on Android as I get an Failed to map paarentid:0 error

### Expected Behavior

Should be able to sync all folders 

### To Reproduce

Tried multiple devices as I'm unable to delete the profile as wehn you go to settings of the profiles it's blank with just a save button

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
> Sync method
> Git

Ah, that template needs an upgrade :D 

Thank you for the feedback! Both issues have been fixed already in the code, the final v5.3.0 release will be published soon :) 

A word of caution:

> I also sync via Mozilla

This is dangerous, as Mozilla's Bookmarks sync can change the IDs of bookmarks which confuses floccus. Generally, I don't recommend doing Firefox Bookmarks Sync and Floccus at the same time.

**Comment by csamolot** [comment]
Awesome thank you and I will stop syncing with Mozilla as well
