### ISSUE TITLE
JavaScript bookmarks disappearing intermittently

### ISSUE THREAD

**Issue by kvibber** [floccusaddon/floccus#1729]
### Which version of floccus are you using?

5.3.0

### How many bookmarks do you have, roughly?

2.2k

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 130.0.1 and Vivaldi 6.9.3447.48

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.2.6

### Which version of Nextcloud? (if relevant)

29.0.7

### Describe the Bug

JavaScript bookmarks occasionally disappear during sync.

### Expected Behavior

JavaScript bookmarks should sync the same way other bookmarks do.

### To Reproduce

I haven't fully narrowed it down yet, but it *seems* like syncing from Vivaldi drops any JavaScript bookmarks that were added by another browser (possibly including other Vivaldi instances). If I add a JS bookmark to the bookmarks bar in Firefox, it never makes it to Vivaldi and always ends up missing after a few syncs. If I do the same on Vivaldi, it sticks around, at least for a while. They did eventually disappear after syncing to another device also running both Firefox and Vivaldi, which makes me suspect that on Vivaldi, the Floccus extension might just be deleting any incoming JS bookmarks, regardless of which browser created them.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @kvibber 

Are you on 5.3.0 on Vivaldi as well? I'll try to reproduce

**Comment by kvibber** [comment]
First, thanks for looking into this!

Second, It's even weirder than I thought, and doesn't seem to be Vivaldi-specific.

It did turn out that both Vivaldi instances were still running Floccus 5.2.7, but...

After making sure that my Linux and Windows copies of Vivaldi and Firefox *all* were running Floccus 5.3.0, I started experimenting with adding a bookmarklet using one browser or another, noting which one in the name (ex: FL for Firefox on Linux, VW for Vivaldi on Windows), and also looking at the relevant folder on the server through the web interface.

I have confirmed that *sometimes* sync in *either* browser on *either* Windows or Linux will delete some or all of the JS bookmarks on the server, even if it's the only connected browser running at the time. And *sometimes* sync will re-add them.

I'm attaching the redacted log from a Firefox/Linux session in which sync removed 3 of 5 bookmarklets on the server without deleting them locally, then added them back in a later sync.

[floccus-5.3.0-2024-09-30-redacted-2.log](https://github.com/user-attachments/files/17182706/floccus-5.3.0-2024-09-30-redacted-2.log)

**Comment by marcelklehr** [comment]
I was able to reproduce this :tada: 
Deletion appears to happen when the browser is freshly started.

**Comment by marcelklehr** [comment]
v5.3.1 was just released and has the fix for this

**Comment by kvibber** [comment]
Thanks! I had to pull the full data down on two browsers, but now that I've got all of them running 5.3.1, it seems to be working perfectly!
