### ISSUE TITLE
Chinese characters convert to ascii codes

### ISSUE THREAD

**Issue by RedKappa** [floccusaddon/floccus#1730]
### Which version of floccus are you using?

3.5.0

### How many bookmarks do you have, roughly?

213

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Edge 130.0.2849.5 

### What kind of WebDAV server are you using? (if relevant)

jianguoyun.com

### Describe the Bug

I Pushed up once,the Chinese characters in the bookmarks.html converted to ascii codes.It seemed to be garbled and made I can't know what the bookmarks is.
![image](https://github.com/user-attachments/assets/2444bec8-1ec3-4da1-b70a-dca46b80334d)

### Expected Behavior

Convert ascii codes to Chinese characters as before.This bug didn't exist in the past.

### To Reproduce

0.Set the File format as html.
1.Bookmarks the page which has a Chinese tilte.
2.Push up once.
3.Check the file created.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @RedKappa 
I understand your predicament. You can open the file in a browser to see the correct characters, as it *is* valid HTML, but the html entities are not great for editing in a text editor. I'll see what I can do.

**Comment by marcelklehr** [comment]
The fix for this has been released
