### ISSUE TITLE
Error Code in Floccus Firefox Extension with Linkwarden

### ISSUE THREAD

**Issue by xtr3-m3** [floccusaddon/floccus#1734]
### Which version of floccus are you using?

5.3.0

### How many bookmarks do you have, roughly?

50

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Linkwarden

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 130.0.1

### Describe the Bug

![floccus_error](https://github.com/user-attachments/assets/4819d8ab-715a-4552-ab3e-4d94d00517ca)

I get a sync error, when floccus is linked with Linkwarden. The sync is successful, but i always get the error message.
`E019: HTTP status 409. Failed POST request. Check your server configuration and log. `

[floccus-5.3.0-2024-10-02-redacted.log](https://github.com/user-attachments/files/17233943/floccus-5.3.0-2024-10-02-redacted.log)

### Expected Behavior

Successful Sync without any error Codes

### To Reproduce

Just start a Linkwarden Sync.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @xtr3-m3 
This indicates that there was a conflict when trying to sync the bookmarks. Does the error persist when you try syncing again? It should be only temporary.

**Comment by xtr3-m3** [comment]
Hi Marcel,

the error persist even when i try to sync again. Another thing i noticed: When i delete a bookmark in my browser (Firefox), it should also deleted in Linkwarden? At the moment, nothing happens and the bookmarks stays in Linkwarden.

**Comment by xtr3-m3** [comment]
Hello,

update for my case. Its now working like it should. :)
I reinstalled the extension and setup Linkwarden again, first i had the same error, but then i used the download once button in the extension. It synched a short time and everything was fine!

**Comment by marcelklehr** [comment]
> Could this be a byproduct of not allowing duplicates in the Linkwarden settings and not really an "error" so much as the server refusing or not accepting a duplicate?

Yes, this might be the cause, floccus doesn't sort out duplicates before uploading to linkwarden.

**Comment by PawsFunctions** [comment]
> > Could this be a byproduct of not allowing duplicates in the Linkwarden settings and not really an "error" so much as the server refusing or not accepting a duplicate?
> 
> Yes, this might be the cause, floccus doesn't sort out duplicates before uploading to linkwarden.

100% verified, Preventing duplicate links causes this error. I definitely have duplicate links, and Floccus was unable to complete syncing. Disabling this feature stopped the error, and it has been working fine for the past few days

![Image](https://github.com/user-attachments/assets/7428c11e-3d99-4ea2-92ec-4d4f4ba55967)
