### ISSUE TITLE
Can't login with Google on Lemur Browser

### ISSUE THREAD

**Issue by Don1250** [floccusaddon/floccus#1737]
### Which version of floccus are you using?

5.3.0

### How many bookmarks do you have, roughly?

426

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Lemur Browser 2.7.0.033 (127.0.6533.144)

### Describe the Bug

Can't login with Google can you fix it?

### Expected Behavior

It won't login or giving popup to login with Google ..

### To Reproduce

It behaviour normally running fine...

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @Don1250 
That's most likely an issue with the browser you're using :S I can look into it but I don't have high hopes that this can be solved. What you can try however, is importing a working GoogleDrive profile from a different browser.

**Comment by Don1250** [comment]
> Hey @Don1250 That's most likely an issue with the browser you're using :S I can look into it but I don't have high hopes that this can be solved. What you can try however, is importing a working GoogleDrive profile from a different browser.

ok

**Comment by Don1250** [comment]
[marcelklehr](https://github.com/marcelklehr) nevermind import/Export work!!!
