### ISSUE TITLE
Android Bug Linkwarden Failed to map parentId: 0

### ISSUE THREAD

**Issue by Morethanevil** [floccusaddon/floccus#1738]
### Which version of floccus are you using?

5.3.0

### How many bookmarks do you have, roughly?

150

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 14 Oneplus 9 Pro

### Describe the Bug

First, Linkwarden can not be selected in this bugreport :)

After a few starts of Floccus on Android, I only get the error message `Failed to map parentId: 0` while syncing. Removing profile is impossible too, because the option menu is blank. 

I tried reinstalling the app and but the error remains. 

Sometimes it syncs just fine, I don't know why.

On Windows and Linux Floccus syncs fine with Linkwarden (Firefox and Brave)

![Screenshot_2024-10-04-21-12-05-91_b8d115ac496f4a57e482986381531d48](https://github.com/user-attachments/assets/ff5f13ab-dfd1-4b66-bff6-43a280a74d2a)
![Screenshot_2024-10-04-21-12-08-71_b8d115ac496f4a57e482986381531d48](https://github.com/user-attachments/assets/f5b96234-bcea-41d6-acec-e38a0650c543)

### Expected Behavior

It syncs everytime just fine

### To Reproduce

No specific way

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @ Morethanevil,

I've seen this error a few times already, but could not consistently reproduce it, sadly.

In the meantime you can try to trigger a sync from scratch in the settings of the profile that errored. Make sure you have a backup of your bookmarks before you do this, and check your bookmarks for deleted bookmarks that may have come back. You can be sure that nothing will be deleted in this step, though.

**Comment by Morethanevil** [comment]
Thanks for the answer, but the options of the profile are empty, as you can see in the second screenshot. This happens at the same time. I need to clear the app data and recreate the whole profile if I want to add bookmarks via Android. At least the error is known and it only affects the android app.

**Comment by marcelklehr** [comment]
Mh, then I'll need to fix the options first, of course, you're right!

**Comment by marcelklehr** [comment]
I was able to reproduce this.

**Comment by marcelklehr** [comment]
Fix is out now in F-Droid and in the Open Testing stage on Google Play, will move to production probably next week.

**Comment by githubkirk001** [comment]
@marcelklehr Hi Marcel, first of all thanks for the great work !!!
I have the same issue and it is not resolved with the new update. I am using it with Nextcloud and get the same error message on all my android devices. However the sync with the browser it working perfect (Firefox with the Floccus add-in).
When I am using a sync over webdav into a file i don't get any error messages. Any ideas ? 

Thanks in advance !

**Comment by marcelklehr** [comment]
Hey @githubkirk001 This is being tracked in #1749

**Comment by githubkirk001** [comment]
@marcelklehr : Thanks for the fast reply. I 'll keep waiting :-).
