### ISSUE TITLE
Profile name as git commit message

### ISSUE THREAD

**Issue by metal450** [floccusaddon/floccus#1739]
### Describe the feature you'd like to request

When using git as the backend, every commit message says "Floccus bookmarks update". It would be super helpful for the commit message to say the name of the profile that did the sync - then we could quickly differentiate where each update came from, just via git log.

Additionally including the OS & browser name would be even better. i.e. commit message "Firefox for Linux - Push Tabs" (where "Push Tabs" is the user-specified profile name)

### Describe the solution you'd like

Described above

### Describe alternatives you've considered

Described above

**Comment by marcelklehr** [comment]
Really good idea!

**Comment by elvisisvan** [comment]
i second this, even just iterations like 1, 2, 3, etc. would be enough for me can we just have that?! 
currently every commit by floccus has the same commit message, it's inconvenient to track changes by name

![floccus-commit-message](https://github.com/user-attachments/assets/7bae980f-0305-4dca-8a68-0c4a0e7ea983)


obsidian-git has a thing called placeholder so i can input custom properties like {{date}} for precise commit time and {{hostname}} for device name, i use "DESKTOP-1R97KDN" so i have this:
![image](https://github.com/user-attachments/assets/fea3873b-125a-4e79-a4c0-27bea05c4bef)
(look at the entire commit message in the 1st image above)

so...
# wen descriptive commit message?

**Comment by elvisisvan** [comment]
i second this, even just iterations like 1, 2, 3, etc. would be enough for me can we just have that?! 
currently every commit by floccus has the same commit message, it's inconvenient to track changes by only commit name

![floccus-commit-message](https://github.com/user-attachments/assets/7bae980f-0305-4dca-8a68-0c4a0e7ea983)


obsidian-git has a thing called placeholder so i can input custom properties like {{date}} for precise commit time and {{hostname}} for device name, i use "DESKTOP-1R97KDN" so i have this:
![image](https://github.com/user-attachments/assets/fea3873b-125a-4e79-a4c0-27bea05c4bef)
(look at the entire commit message in the 1st image above)

so...
# wen descriptive commit message?

**Comment by elvisisvan** [comment]
i second this, even just iterations like 1, 2, 3, etc. would be enough for me can we just have that?! 
currently every commit by floccus has the same commit message, it's inconvenient to track changes by only commit name

![floccus-commit-message](https://github.com/user-attachments/assets/7bae980f-0305-4dca-8a68-0c4a0e7ea983)


obsidian-git has a thing called placeholder so i can input custom properties like {{date}} for precise commit time and {{hostname}} for device name, i use "DESKTOP-1R97KDN" so i have this:
![image](https://github.com/user-attachments/assets/fea3873b-125a-4e79-a4c0-27bea05c4bef)
(look at the entire commit message in the 1st image above)

so...
# wen iterative commit message?
