### ISSUE TITLE
Linkwarden updating a URL not working

### ISSUE THREAD

**Issue by Morethanevil** [floccusaddon/floccus#1742]
### Which version of floccus are you using?

5.3.0

### How many bookmarks do you have, roughly?

150

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Linkwarden

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox latest stable

### Describe the Bug

If you create a bookmark and later update its URL, it is not updated in Linkwarden. It still refers to the old URL. Sometimes URLs gets updated like in GitHub when the repo changes from private to organization, or you remove unnecessary parts of it like trackers etc...

I know it is not possible to edit URLs in Linkwarden too, but maybe this is something to worked on.

### Expected Behavior

Update the URL or delete the old one and save the new one. Maybe moving the old one to an "archive" would be great.

### To Reproduce

Create a bookmark, wait for Linkwarden to finish. Update the URL :)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @Morethanevil 
In the upcoming Linkwarden release editing URLs will be supported

**Comment by Morethanevil** [comment]
Tried today with Linkwarden 2.8.0 and Floccus 5.3.3. Floccus syncs fine, but it does not update the URL in Linkwarden. No error message

Android app still gives me error message: "Failed to map parentid: 0" after a while

**Comment by marcelklehr** [comment]
Mmh, not even when you force a sync up?

The mapping failure on android is a known issue, which is likely unrelated.

**Comment by Morethanevil** [comment]
I changed an URL, then clicked on upload once, opened Linkwarden but still the old URL

**Comment by marcelklehr** [comment]
cc @daniel31x13 It seems that PUT to linkwarden with the new URL still doesn't work

**Comment by marcelklehr** [comment]
@187622085 Ah, you mean publish a linkwarden guide? Yep, good point!

**Comment by marcelklehr** [comment]
This is the code for floccus:

https://github.com/floccusaddon/floccus/blob/develop/src/lib/adapters/Linkwarden.ts#L110-L126

```

  async updateBookmark(bookmark: Bookmark<typeof ItemLocation.SERVER>): Promise<void> {
    Logger.log('(linkwarden)UPDATE', {bookmark})
    const {response: collection} = await this.sendRequest('GET', `/api/v1/collections/${bookmark.parentId}`)
    await this.sendRequest(
      'PUT', `/api/v1/links/${bookmark.id}`,
      'application/json',
      {
        url: bookmark.url,
        name: bookmark.title,
        tags: [],
        collection: {
          id: bookmark.parentId,
          name: collection.name,
          ownerId: collection.ownerId,
        },
      })
  }
```

It seems that I'm missing icon, iconWeight and color? Why doesn't it error though?

**Comment by marcelklehr** [comment]
But then what am I doing wrong?

**Comment by daniel31x13** [comment]
@marcelklehr hmm, could you log the response of the following request as well:

```js
await this.sendRequest(
      'PUT', `/api/v1/links/${bookmark.id}`,
      'application/json',
      {
        url: bookmark.url,
        name: bookmark.title,
        tags: [],
        collection: {
          id: bookmark.parentId,
          name: collection.name,
          ownerId: collection.ownerId,
        },
      })
```

It seems like link updates reflect correctly from the server to the browser but not vice versa. (It's not just the `url` field.)

**Comment by marcelklehr** [comment]
Ah, I'm missing the id

**Comment by marcelklehr** [comment]
Should be fixed in v5.3.4

**Comment by marcelklehr** [comment]
@Morethanevil Can you confirm?

**Comment by Morethanevil** [comment]
> @Morethanevil Can you confirm?

Yes works fine, tested with Linkwarden 2.8.3 and Floccus 5.3.4 

Thanks! :)
