### ISSUE TITLE
Firefox Windows 11 Git Sync Error

### ISSUE THREAD

**Issue by vincelawdev** [floccusaddon/floccus#1744]
### Which version of floccus are you using?

5.3.1

### How many bookmarks do you have, roughly?

5000

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 131.0.2

### Describe the Bug

2024-10-14T22:57:44.401Z Starting sync process for account Vince
2024-10-14T22:57:44.588Z onSyncStart: begin
2024-10-14T22:57:44.600Z (git) init
2024-10-14T22:57:44.601Z onSyncFail
2024-10-14T22:57:44.601Z Syncing failed with A mutation operation was attempted on a database that did not allow mutations.
2024-10-14T22:57:44.604Z onSyncFail

### Expected Behavior

Expect it to sync to my BitBucket repository I just created.

### To Reproduce

Set up new repository in BitBucket. Install Firefox on Windows 11. Install floccus addon for Firefox.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @vincelawdev 
Are you using Firefox' private browsing mode per chance? Firefox Private mode doesn't support IndexedDB it seems which is needed for Git sync to work.

**Comment by vincelawdev** [comment]
Yes. You were right. I am not sure how Firefox enabled private windows by default but I have disabled that and it now works fine.

**Comment by accforgithubtest** [comment]
Is firefox private windows not working a permanent expected behavior ? or is there any fixes planned ?
Are there any workarounds to get floccus working in firefox private windows ?

**Comment by marcelklehr** [comment]
@accforgithubtest floccus via Git not working in firefox private windows is permanent expected behavior, sadly.

**Comment by thinkingofmaud** [comment]
Had the same issue right now. I "hydrated" the git branch with bookmarks.xbel, now it works.

**Comment by accforgithubtest** [comment]
hi @thinkingofmaud - how to "hydrate" the git branch ? A bit more detailed steps wold be appreciated !
Cheers

**Comment by thinkingofmaud** [comment]
@accforgithubtest instead of trying to sing with a bare or nonexistent branch, i did a commit with the current copy of bookmarks.xbel.
