### ISSUE TITLE
Android App Open Bookmark in Private Tab

### ISSUE THREAD

**Issue by WizADSL** [floccusaddon/floccus#1747]
### Describe the feature you'd like to request

 Allow the Android app to open selected bookmarks in a private window.

### Describe the solution you'd like

I have a few ideas for implementation:

1) Add a global option where selecting a bookmark will ask whether it should be opened in a private window with a "remember" option (editing a bookmark would also allow changing the privacy setting).
2) Add a global setting to the application where all bookmarks are opened in a private window by default
3) Add an option to the 3-dot menu to open the bookmark is a private window

Ideally this would be implemented as #1 and #2. Would it be possible for this setting to carry over to desktop browsers?
#1 could be expanded to mark some bookmarks as "no sync".

### Describe alternatives you've considered

None

**Comment by marcelklehr** [comment]
I *think* this is not possible in android. All I can do is send a link open intend how android opens that is up to android and your android settings. I'm thus gonna have to close this. Sorry.
