### ISSUE TITLE
Android/iOS "Failed to map parentId: 0"

### ISSUE THREAD

**Issue by bege10** [floccusaddon/floccus#1749]
### Which version of floccus are you using?

Android app 5.3.1

### How many bookmarks do you have, roughly?

5

### Are you using other means to sync bookmarks in parallel to floccus?

Only for testing in this case: Nextcloud Bookmarks org.schabi.nxbookmarks

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

n/a

### Which version of Nextcloud? (if relevant)

? (managed Nextcloud at nextcloud.hosting.zone)

### Describe the Bug

Changing the folder structure on the server and therefor changing the root folder in the app throws the error `Failed to map parentId: 0`.
Clearing the cache allows to sync again - but of course reverts the changed folder structure - until the next change of the structure in the server. 
Nextcloud Bookmarks org.schabi.nxbookmarks works correct. 

### Expected Behavior

Update the structure in tbe app.

### To Reproduce

1. Change the folder structure on the server
2. Change the root folder in the app
3.  Sync in Floccus app
4. Error

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> Nextcloud Bookmarks org.schabi.nxbookmarks works correct.

Well schabi.nxbookmarks doesn't sync anything afaik; it has no offline storage.

> Changing the folder structure on the server and therefor changing the root folder in the app throws the error Failed to map parentId: 0.

Can you give a bit more details? So, you have set a subfolder on the server as the sync target and then move that folder on the server somewhere else?

**Comment by marcelklehr** [comment]
mh, I can't test with my Android device at the moment, but I couldn't reproduce this with the addon version for starters :/ That doesn't mean it's not a bug, though, of course :D

**Comment by marcelklehr** [comment]
Note to self: I think the main trigger for the error here may be changing the subfolder in the settings. Still have to think about what would be the most expected reaction in terms of resetting mappings and cache.

**Comment by devz3r0** [comment]
I have the exact same issue, with clearing the cache it works.
However I even removed the profile after I moved the Bookmarks Folder in a Subfolder, so I made it from scratch.
One downsync worked, then I got the error too.

**Comment by panamilonas** [comment]
> I have the exact same issue, with clearing the cache it works. However I even removed the profile after I moved the Bookmarks Folder in a Subfolder, so I made it from scratch. One downsync worked, then I got the error too.

Same behaviour by me

**Comment by marcelklehr** [comment]
Am I correct in saying that this is only a problem in the native app (Android app)?

**Comment by marcelklehr** [comment]
Do you all have multiple profiles or just one?

**Comment by marcelklehr** [comment]
I believe I've found the cause of this bug :tada:

**Comment by marcelklehr** [comment]
v5.3.4 will be out soon, please test

**Comment by bege10** [comment]
> v5.3.4 will be out soon, please test

It works here! Thank you very much!

**Comment by panamilonas** [comment]
It works also for me, Thank you for your quick response!!!
