### ISSUE TITLE
rsync

### ISSUE THREAD

**Issue by a1981611080** [floccusaddon/floccus#1751]
### Which version of floccus are you using?

latest

### How many bookmarks do you have, roughly?

300

### Are you using other means to sync bookmarks in parallel to floccus?

I also sync via Mozilla account

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

via

### Describe the Bug

when i use floccus to rsync my bookmark from edge to via, i found if the url include the # character,the rsync data will became & #38; ,when i use my phone to open some bookmark will open fail, when i open WeChat Official Account Post will alert me parameter error

such as 
https://mp.weixin.qq.com/s?__biz=MzkxMjQzMjA0OQ==&mid=2247484057&idx=1&sn=50e57108f736bc47137ac57dfb643893

become

https://mp.weixin.qq.com/s?__biz=MzkxMjQzMjA0OQ==&#38;mid=2247484057&#38;idx=1&#38;sn=50e57108f736bc47137ac57dfb643893

 

### Expected Behavior

i can open the website when i rsync data by via

### To Reproduce

![cf9a1addf00ae958b918034c7787a73](https://github.com/user-attachments/assets/e95a7133-add3-4e13-a4dc-091961a03978)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Which version of floccus is this, exactly, please?

**Comment by marcelklehr** [comment]
I cannot reproduce this, I'm afraid.

**Comment by a1981611080** [comment]
floccus version: 5.3.1
pc browser: edge
phone browser: via
