### ISSUE TITLE
Failed to map parentId: 0

### ISSUE THREAD

**Issue by trustno1foxm** [floccusaddon/floccus#1763]
### Which version of floccus are you using?

5.3.1

### How many bookmarks do you have, roughly?

2k

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 14

### Which version of Nextcloud Bookmarks are you using? (if relevant)

v14.2.6

### Which version of Nextcloud? (if relevant)

v29.0.8

### Describe the Bug

During the 1st synchronisation process everything works perfectly, but during a subsequent synchronisation the error "Failed to map parentId: 0" appears.
Only a reset of the app enables a successful 1st synchronisation. Also affects a 2nd Android device.
[floccus-5.3.1-2024-11-09-redacted.log](https://github.com/user-attachments/files/17688422/floccus-5.3.1-2024-11-09-redacted.log)

Thx in advance!

### Expected Behavior

Successful Synchronisation.

### To Reproduce

Open App and do a synchronisation.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
Seems like this has been reported two days prior already :)

#1749 Is this the same as your issue?

**Comment by marcelklehr** [comment]
(Shout if it isn't the same)
