### ISSUE TITLE
Feature: Allow user to manually clear lock

### ISSUE THREAD

**Issue by joshqou** [floccusaddon/floccus#1769]
### Describe the feature you'd like to request

Floccus currently doesn't have any self-contained way to clear any bugged out locks which can be created from network/server issues or other floccus agents misbehaving.

### Describe the solution you'd like

An additional button under dangerous actions, with a confirmation prompt before clearing the lock.

### Describe alternatives you've considered

_n/a;_ Floccus isn't able to determine if a lock being held improperly. Having floccus locks held for a set duration _could_ be used to prevent infinite locks however that could cause issues on it's own if two floccus agents have different system times.

**Comment by metal450** [comment]
Strongly agree here. I keep having this issue, & keep finding myself searching for how I fixed it :P I'm using git as the backend, most of the (many) issue reports related to this are about WebDAV. A way to force-clear the lock when I'm certain there are no other clients running would make life a lot easier.

**Comment by metal450** [comment]
Oh right, I remember how to release it. Have to go to the git repo & delete the `floccus-lock-xxx` tag.
