### ISSUE TITLE
Add disable/enable to profiles

### ISSUE THREAD

**Issue by cng10001** [floccusaddon/floccus#1770]
### Describe the feature you'd like to request

Hope to enable/disable configurations separately

### Describe the solution you'd like

![PixPin_2024-11-19_10-51-29](https://github.com/user-attachments/assets/1fe99ed2-b4af-419a-a226-e2a08ec34085)
Like this!

### Describe alternatives you've considered

None

**Comment by marcelklehr** [comment]
Hey @cng10001 
You can disable profiles in the profile settings, by disabling auto-sync.
