### ISSUE TITLE
Linkwarden - Failed to conenct to linkwarden server

### ISSUE THREAD

**Issue by JochenBN** [floccusaddon/floccus#1771]
### Which version of floccus are you using?

5.3.4

### How many bookmarks do you have, roughly?

~ 120

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Linkwarden

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

chrome and firefox

### Describe the Bug

I synch my bookmarks from android, Firefox and chrome with nextcloud successful. Everything works fine. Today i setup linkwarden server on docker behind nginx proxy manager. Access via Browser and alternate firefox extension works fine.
I decided to setup another floccus synch profile but it stops on step 2 . Setup the right URl in Linkwarden server it gives me an error "Failed to connect to your linkwarden server". I Tried this on chrome and firefox . Both with error. On both browsers i can the URl only i floccus no way to the server. 

Any ideas??
Cheers 
JK

### Expected Behavior

Works same as profile vor nextcloud

### To Reproduce

everytime i type the url,pw and username an klick next

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Make sure to use an access token instead of your password. Linkwarden restricts API use to access tokens only.

**Comment by JochenBN** [comment]
Ok, my mistake , i didnt read the text under the field. With open eyes it would be better . Thanks for your help. Work as expevted 

Cheers

**Comment by marcelklehr** [comment]
Awesome, I'm glad I could help :)
