### ISSUE TITLE
E019 with Linkwarden

### ISSUE THREAD

**Issue by physx2494** [floccusaddon/floccus#1773]
### Which version of floccus are you using?

5.3.4

### How many bookmarks do you have, roughly?

1.3k

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Linkwarden

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Version 128.0.6613.159 (Official Build, ungoogled-chromium) (64-bit)

### Describe the Bug

I'm getting `E019: HTTP status 409. Failed POST request. Check your server configuration and log.` after the initial sync of bookmarks with Linkwarden.

Deleting a bookmark from Chrome will unfortunately not merge with Linkwarden. The reverse will also not happen.

### Expected Behavior

No error should be thrown.

### To Reproduce

![image](https://github.com/user-attachments/assets/76eb0325-fe65-4ebb-8174-57a4508bd912)

[floccus-5.3.4-2024-11-23-redacted.log](https://github.com/user-attachments/files/17882129/floccus-5.3.4-2024-11-23-redacted.log)

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment]
You seem to have enabled "preventDuplicateLinks" in your user settings or somewhere in Linkwarden, which causes duplicate links in the same folder to fail to be created.

**Comment by physx2494** [comment]
Thanks, resolved!
