### ISSUE TITLE
Tab Synchronization overwriting changes

### ISSUE THREAD

**Issue by sascha-wi** [floccusaddon/floccus#1779]
### Which version of floccus are you using?

5.3.4

### How many bookmarks do you have, roughly?

20-30

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox

### Which version of Nextcloud? (if relevant)

28.0.7

### What kind of WebDAV server are you using? (if relevant)

Nextcloud

### Describe the Bug

I set up a sync profile on two devices to only sync all my tabs.

### Expected Behavior

That changes to my tabs are replicated on any device by modification date.

### To Reproduce

Not sure, I guess if I'd open my home device and press sync, some weird sychronization would happen, not taking into account changes I made on my current device.

I would add the log, but for gods sake why are the bookmarks in cleartext?

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
>  for gods sake why are the bookmarks in cleartext?

You can choose the redacted logs, where bookmarks are not in cleartext.

**Comment by marcelklehr** [comment]
>Describe the Bug
> I set up a sync profile on two devices to only sync all my tabs.

This doesn't sound like a bug?

**Comment by marcelklehr** [comment]
Maybe there's away to have a sane merge sync with tabs after all. I'm looking into this again. I'll keep you posted.
