### ISSUE TITLE
Synchronization no longer working fro mone day to other E018: Couldn't authenticate with the server.

### ISSUE THREAD

**Issue by kuhnino** [floccusaddon/floccus#1780]
### Which version of floccus are you using?

5.3.4 Android

### How many bookmarks do you have, roughly?

250

### Are you using other means to sync bookmarks in parallel to floccus?

Firefox plugin and Android app

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox

### Which version of Nextcloud Bookmarks are you using? (if relevant)

5.3.4 Firefox

### Which version of Nextcloud? (if relevant)

n/a

### What kind of WebDAV server are you using? (if relevant)

Docker Plugin on UNRAID server , https://github.com/mgutt/docker-apachewebdav

### Describe the Bug

I get the error message "E018: Couldn't authenticate with the server." on my Firefox plugin, the android app says Same, in German language "E018 Konnte nicht am Server authentifiziert werden"
I have not changed anything in my config nor update something

I can provide logs, but the upload server to cloud.marcelklehr no longer works

### Expected Behavior

sync without harm

### To Reproduce

no idea

### Debug log provided

- [X] I have provided a debug log file

**Comment by kuhnino** [comment]
Log file
2024-11-27T06:57:01.299Z Starting sync process for account xxxxxx
2024-11-27T06:57:01.412Z onSyncStart: begin
2024-11-27T06:57:01.414Z http://ip:port/bookmarks.xbel.lock
2024-11-27T06:57:01.426Z Setting lock: http://ip:port/bookmarks.xbel.lock
2024-11-27T06:57:01.434Z onSyncFail
2024-11-27T06:57:01.435Z Syncing failed with E018: Couldn't authenticate with the server.
2024-11-27T06:57:01.438Z onSyncFail

**Comment by marcelklehr** [comment]
that's strange. Can you try accessing the server with a different dav client?

**Comment by kuhnino** [comment]
Hi Marcel,
thanks for jumoing in sooooo fast, didin´t expected that at all.
Looks like my Server was running out of memory, 

- after restarting and 
- removing some files from CACHE drive, 
- re applying the users password in console

everything is running out of the scratch again

For now I´m fine closing this ticket and sorry for not doing my maintanentce in advance. But I was a bit curious.

**Comment by marcelklehr** [comment]
No problem :) Happy syncing!
