### ISSUE TITLE
Firefox: Trying to calculate hash of a folder that isn't loaded (2024 edition)

### ISSUE THREAD

**Issue by johanneskastl** [floccusaddon/floccus#1786]
### Which version of floccus are you using?

V5.3.4

### How many bookmarks do you have, roughly?

5000

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 133.0 

### Which version of Nextcloud Bookmarks are you using? (if relevant)

14.2.6

### Which version of Nextcloud? (if relevant)

v29.0.X

### Describe the Bug

After putting more and more bookmarks into the folder, that is being synced from Firefox to Nextcloud Bookmarks, I am now stuck with `Trying to calculate hash of a folder that isn't loaded`.

Apparently this was solved in 2021 in #873

### Expected Behavior

Sync should succeed.

### To Reproduce

No idea.

I have put more and more bookmarks into the synced folder and removed them again, if the sync failed. Then put some of them back in, until I find the culprit.

See https://github.com/floccusaddon/floccus/discussions/1760#discussioncomment-11237201

### Debug log provided

- [ ] I have provided a debug log file

**Comment by johanneskastl** [comment]
BTW: The URL to upload the debug.log was not reachable, is it in maintenance or is the URL outdated?

**Comment by johanneskastl** [comment]
OK, and after many many retries suddenly the sync is successful? Huh?

**Comment by marcelklehr** [comment]
> BTW: The URL to upload the debug.log was not reachable, is it in maintenance or is the URL outdated?

The URL is no longer in operation, I will remove it

**Comment by marcelklehr** [comment]
Mmmh, for some reason you seem to be plagued by many problems

**Comment by marcelklehr** [comment]
Can you post a redacted log here?

**Comment by johanneskastl** [comment]
> Can you post a redacted log here?

Sorry, while I was preparing the bug report the sync healed itself and I can no longer reproduce the problem.

As you mentioned the possibly outdated db schema, could this be related?

Otherwise, as I cannot reproduce, I propose to close this issue.

**Comment by marcelklehr** [comment]
huh. Alright, then let's close. We can always reopen if it comes back again.
