### ISSUE TITLE
Request to add safari can directly share the current web page to floccus.

### ISSUE THREAD

**Issue by bzmshang** [floccusaddon/floccus#1789]
### Describe the feature you'd like to request

Use the share button below safari to share the current web page to floccus to add favorites.

### Describe the solution you'd like

Use the share button below safari to share the current web page to floccus to add favorites.

### Describe alternatives you've considered

Use the share button below safari to share the current web page to floccus to add favorites.

**Comment by marcelklehr** [comment]
Hello @bzmshang 
This should already be possible. It was broken intermittently, but should now work again in the latest version. If it doesn't could you send a screencast that shows the issue, perhaps?

**Comment by marcelklehr** [comment]
You're welcome :)
