### ISSUE TITLE
Pressing "enter" when naming a profile has weird behaviour

### ISSUE THREAD

**Issue by jamie6king** [floccusaddon/floccus#1790]
### Which version of floccus are you using?

5.4.0

### How many bookmarks do you have, roughly?

0

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

LibreWolf 133

### Describe the Bug

When entering a name for a new profile, pressing the "enter" key refreshes the page. Going back (on the same tab) and repeating does nothing.

### Expected Behavior

After entering the profile name, pressing "enter" should move on to the next stage, just like the continue button.

### To Reproduce

1. Open Floccus
2. Create a new Profile
3. Select a service (I usually use WebDav).
4. Enter a name.
5. Press "enter". You should see the page refresh back to the begninning.
6. Repeat steps 3 & 4.
7. Press "enter". Nothing should happen.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Thanks for the feedback :blue_heart:
