### ISSUE TITLE
Can’t select folders when sharing from iOS share sheet

### ISSUE THREAD

**Issue by Fletch-99** [floccusaddon/floccus#1791]
### Which version of floccus are you using?

5.4.0

### How many bookmarks do you have, roughly?

330

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Describe the Bug

I can’t choose any of my Bookmark folders after adding link from iOS Share Sheet and selecting Floccus. It used to work fine but now there is a new window with ‘Untitled Folder’ and a plus sign for creating a new folder. 

### Expected Behavior

As it worked before, letting me choose in which folder I can save the bookmark. 

### To Reproduce

Open Safari (Same thing is happening on any iOS browser)
Click share icon to open the share sheet
Choose Floccus
Click on ‘root’ parent folder to select one of your folders
A windows appears with no option for selecting folder 
![IMG_6305](https://github.com/user-attachments/assets/6b2e9d0d-0510-4be6-a0da-6a574177835b)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Confirmed.
