### ISSUE TITLE
E029 Failsafe

### ISSUE THREAD

**Issue by sircode** [floccusaddon/floccus#1796]
### Which version of floccus are you using?

latest

### How many bookmarks do you have, roughly?

tested 20

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

WebDAV

### Describe the Bug

Added bookmarks to Android app. But Sync want to delete them although sync settings are set to "merge"
![Screenshot_2024-12-11-14-47-41](https://github.com/user-attachments/assets/90cb0e09-0203-4864-af81-763e6babe59d)

### Expected Behavior

Do not delete new bookmarks

### To Reproduce

as written

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
So this is the first sync ever? That's curious.

**Comment by sircode** [comment]
No, not the first sync.
Webserver and Android App were synced. Then I added entries in the app. After that the sync failed as described

**Comment by sircode** [comment]
This error may also be caused by testing sync with both version xbel and html. 
When editing with xbel settings, then switching to html, syncing html fails. 
When editing with html settings, then switching to xbel , syncing xbel fails.

**Comment by marcelklehr** [comment]
Aha, i see.

**Comment by marcelklehr** [comment]
> When editing with xbel settings, then switching to html, syncing html fails.

You shouldn't expect to be able to sync to a HTML file when XBEL is set in your profile, though. How should that work?

**Comment by sircode** [comment]
Not really. I was expecting sync as bookmarks.xbel only, when xbel is selected in settings.
Or sync of bookmarks.html when html is selected in settings. 
Both would we luxury ;)

General question. xbel and html seem to handle separate data in the app?

I thought the data are the same and one can just change the format. But that does not seem to be the case.

![Screenshot_2024-12-15-19-32-01.jpg](https://github.com/user-attachments/assets/fdb2be58-3309-492d-8f35-c1de0f555e30)

![Screenshot_2024-12-15-19-32-37.jpg](https://github.com/user-attachments/assets/fca64c94-15f6-494c-823d-660c2eb12588)

**Comment by marcelklehr** [comment]
The data is in the file that you specify, so when you change the file, the data changes as well.

**Comment by marcelklehr** [comment]
I'm closing this as this seems solved now that we've cleared this up :)
