### ISSUE TITLE
Unable to connect to NutCloud webdav

### ISSUE THREAD

**Issue by jiyi55** [floccusaddon/floccus#1798]
### Which version of floccus are you using?

5.4.0

### How many bookmarks do you have, roughly?

120

### Are you using other means to sync bookmarks in parallel to floccus?

否

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 86.0.424.198

### What kind of WebDAV server are you using? (if relevant)

坚果云的
地址是：https://dav.jianguoyun.com/dav/

### Describe the Bug

填写地址和密码后总提示 Failed to fetch

### Expected Behavior

能够正常链接使用

### To Reproduce

第二步

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi!

Did you create an application password for floccus at 第三方应用管理  https://www.jianguoyun.com/#/setting/ ?

**Comment by jiyi55** [comment]
已经创建了，有账号，也有第三方应用的密码

**Comment by jiyi55** [comment]
> 你好！
> 
> [您是否在第三方应用管理https://www.jianuoyun.com/#/setting/](https://www.jianguoyun.com/#/setting/)创建了絮凝的应用密码 ？ 使用普通的建国云密码与絮状体将不起作用。
> 
> 你好！
> 
> 您是否在第三方应用管理[https://www.jianuoyun.com/#/setting/](https://www.jianguoyun.com/#/setting/)上为floccers创建了应用密码？ 使用正常的建国云密码和flocus密码将失效。

已经创建了，有账号，也有第三方应用的密码

**Comment by jiyi55** [comment]
可以加您的别的联系方式吗？方便您给我指导一下？

**Comment by marcelklehr** [comment]
您是第一次尝试使用 floccus 吗？我以前用 floccus 设置过江鸥云，但几年前创建的第三方应用程序密码今天似乎失效了。不过创建一个新密码还是有效的。

**Comment by jiyi55** [comment]
> 您是第一次尝试使用絮状吗？我以前用絮状设置过江鸥云，但几年前创建的第三方应用程序密码今天似乎失效了。不过创建一个新密码还是有效的。

是第一次用，但是坚果云的第三方应用密码是昨天新创建的。

**Comment by marcelklehr** [comment]
对了，我觉得你需要同步到一个子目录。Floccus 似乎不允许在建国云的根目录下创建文件。

**Comment by jiyi55** [comment]
> 对了，我觉得你需要同步到一个子目录。Floccus 似乎不允许在建国云的根目录下创建文件。
有子目录，但是填写链接是无法链接，根本到不了后面选择子目录的步骤。

**Comment by marcelklehr** [comment]
嗯嗯。

**Comment by marcelklehr** [comment]
能不能把卡住的步骤截图发过来。

**Comment by jiyi55** [comment]
> 能不能把卡住的步骤截图发过来。

![截图20241214190900444](https://github.com/user-attachments/assets/1a3fa306-7d79-46c5-b55a-43ed7b093405)

**Comment by jiyi55** [comment]
> 不能把卡住的步骤截图发过来。

能看出来是哪里出问题了吗？

**Comment by marcelklehr** [comment]
这很奇怪。看起来是你的网络出了问题。您能用正常的浏览器标签页访问 dav.jianguoyun.com/dav/ 吗？

**Comment by jiyi55** [comment]
> 这很奇怪。看起来是你的网络出了问题。您能用正常的浏览器标签页访问 dav.jianguoyun.com/dav/ 吗？

是的，问题就在这，我浏览器别的网页都没问题，可以正常访问，坚果云链接也没问题，可目前就是不行唉。

**Comment by jiyi55** [comment]
> 这很奇怪。看起来是你的网络出了问题。您能用正常的浏览器标签页访问 dav.jianguoyun.com/dav/ 吗？

可以的。没问题。

**Comment by marcelklehr** [comment]
你能试试下面的方法吗？

#### Firefox
* Go to `about:debugging`
* go to "This firefox"
* click on `Inspect` button next to floccus entry
* go to the network tab in the inspector
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests

---

#### Firefox
* 转到 "关于：调试
* 转到 "此火狐”
* 点击 floccus 条目旁边的 “检查 ”按钮
* 进入 “检查器 ”中的 “网络 ”选项卡
* 检查失败的网络请求

#### Chrome 浏览器
* 转到 `chrome://extensions` 页面
* 启用 "开发者模式
* 点击 floccus “检查视图 ”旁边的 “dist/html/background.html ”按钮： ”
* 进入检查窗口中的 “网络 ”选项卡
* 检查失败的网络请求

**Comment by jiyi55** [comment]
> 你能尝试下面的方法吗？
> 
> #### 火狐浏览器
> * 前往`about:debugging`
> * 转到“这个火狐”
> * 单击`Inspect`絮状物条目旁边的按钮
> * 转到检查器中的网络选项卡
> * 检查失败的网络请求
> 
> #### 铬合金
> * 前往`chrome://extensions`
> * 使能够`Developer mode`
> * 单击`dist/html/background.html`絮状条目中“检查视图：”旁边的按钮
> * 转到检查器窗口中的网络选项卡
> * 检查失败的网络请求
> 
> #### 火狐浏览器
> * 转到`about:debugging`
> * 转到“此疑”
> * 点击絮状边境旁边的“检查”按钮
> * 进入“检查器”中的“网络”选项卡
> * 检查失败的网络请求
> 
> #### Chrome浏览器
> * 转到`chrome://extensions`页面
> * 启用“开发者模式
> * 点击絮状“查看视图”旁边的“dist/html/background.html”按钮： ”
> * 进入检查窗口中的“网络”选项卡
> * 检查失败的网络请求

提示这个
![20241214202828827](https://github.com/user-attachments/assets/2d989ad9-ec6a-4251-9d4b-f60875c9cdc3)

**Comment by jiyi55** [comment]
> > 你能尝试下面的方法吗？
> > #### 火狐浏览器
> > 
> > * 前往`about:debugging`
> > * 转到“这个火狐”
> > * 单击`Inspect`絮状物条目旁边的按钮
> > * 转到检查器中的网络选项卡
> > * 检查失败的网络请求
> > 
> > #### 铬合金
> > 
> > * 前往`chrome://extensions`
> > * 使能够`Developer mode`
> > * 单击`dist/html/background.html`絮状条目中“检查视图：”旁边的按钮
> > * 转到检查器窗口中的网络选项卡
> > * 检查失败的网络请求
> > 
> > #### 火狐浏览器
> > 
> > * 转到`about:debugging`
> > * 转到“此疑”
> > * 点击絮状边境旁边的“检查”按钮
> > * 进入“检查器”中的“网络”选项卡
> > * 检查失败的网络请求
> > 
> > #### Chrome浏览器
> > 
> > * 转到`chrome://extensions`页面
> > * 启用“开发者模式
> > * 点击絮状“查看视图”旁边的“dist/html/background.html”按钮： ”
> > * 进入检查窗口中的“网络”选项卡
> > * 检查失败的网络请求
> 
> 提示这个 ![20241214202828827](https://private-user-images.githubusercontent.com/50919921/395779213-2d989ad9-ec6a-4251-9d4b-f60875c9cdc3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNzk5OTgsIm5iZiI6MTczNDE3OTY5OCwicGF0aCI6Ii81MDkxOTkyMS8zOTU3NzkyMTMtMmQ5ODlhZDktZWM2YS00MjUxLTlkNGItZjYwODc1YzljZGMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDEyMzQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYWYyNjMwMGI3ZDQ3ZjY1MjIzY2U1YjNmYmJmZWQ3NjRlOGQ4MTgwM2MwYmQ3NGI3MjkwNzE0ZWRiZTNhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a_f3P2b2lpXUnMO5Csa9S1BHQfBpwbVzqsMAvSiNJf4)

我直接访问https://dav.jianguoyun.com/dav/得话，提示我输入账号密码，然后我按提示输入账号密码后，显示这样
![9](https://github.com/user-attachments/assets/3fe9b016-531a-4eb9-aebf-559c49c1b8bc)

**Comment by marcelklehr** [comment]
但您需要使用第三方应用程序密码

你能尝试创建一个新的第三方应用程序密码吗？

**Comment by jiyi55** [comment]
> 但您需要使用第三方应用程序密码
> 
> 你能尝试创建一个新的第三方应用程序密码吗？

有密码了，创建了，就是图中对应的应用密码，点显示密码后的那一长串字母。
![Screenshot_20241214_204200_com huawei photos](https://github.com/user-attachments/assets/65a7197e-3429-487d-ac24-3012f265630e)

**Comment by jiyi55** [comment]
> 我知道了。您还可以尝试生成一个新密码并用它试试吗？

刚才重新生成了，还是不行。
![1](https://github.com/user-attachments/assets/5086319b-94c2-4d01-900f-2fa87374b1b7)
![2](https://github.com/user-attachments/assets/43a3f1f0-3ec4-4f31-acb1-bca136c6698d)

**Comment by marcelklehr** [comment]
您可以尝试将浏览器更新到最新版本吗？

**Comment by jiyi55** [comment]
> 您可以尝试将浏览器更新到最新版本吗？

我用的是360企业浏览器，chrome的内核，已经是最新版了。

**Comment by marcelklehr** [comment]
你能用真正的谷歌浏览器试试吗？

**Comment by jiyi55** [comment]
> 你能用真正的谷歌浏览器试试吗？

真正的谷歌浏览器可以用，但是我不喜欢谷歌浏览器，所以我还是用xbrowersync吧。

**Comment by marcelklehr** [comment]
好的，很抱歉让您失望了。不管怎样，我认为这是 360 浏览器的一个错误。那我就把它关闭了。祝您愉快
