### ISSUE TITLE
[Android] Search does not match anymore on parts of the words in a bookmark's title

### ISSUE THREAD

**Issue by heapifyman** [floccusaddon/floccus#1801]
### Which version of floccus are you using?

v5.4.1

### How many bookmarks do you have, roughly?

2000

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

GrapheneOS Android 15, Dec. 2024, Google Pixel 6

### Describe the Bug

Given a bookmark with title "FRITZ!Box ZuHause" where the link is the box's IP address, floccus on android won't find the bookmark when only entering parts of the words in the title. E.g. entering only "fritz" (doesn't matter if you use lower or upper case) or onle "zuha" won'T find the bookmark. But entering the complete word "fritz!box" or "zuhause" will find it.

### Expected Behavior

Search should find the bookmark even when only parts of a word in the title are matched.

This was working before.

### To Reproduce

See above.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
You're right, I changed this, believing it would improve the experience because you'd get less false positives. Maybe I can reintroduce partial matches but with a lower rank than full matches.
