### ISSUE TITLE
Android app fails to install on Android 15

### ISSUE THREAD

**Issue by bhlevca** [floccusaddon/floccus#1802]
### Which version of floccus are you using?

5.4.1

### How many bookmarks do you have, roughly?

does not matter in this case

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 15 

### Which version of Nextcloud Bookmarks are you using? (if relevant)

n/a

### Which version of Nextcloud? (if relevant)

n/a

### What kind of WebDAV server are you using? (if relevant)

N/A

### Describe the Bug

Floccus fails to update on Android 15 

### Expected Behavior

Should install 

### To Reproduce

My last version that works is v4.19.1

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hi @bhlevca 

I have it working flawlessly here on Android 15 :/ Any other details?

**Comment by bhlevca** [comment]
Solved it by uninstalling the old one. Upgrading failed, installing from scratch worked fine.
