### ISSUE TITLE
Linkwarden: E019: HTTP status 500.

### ISSUE THREAD

**Issue by ElDubsNZ** [floccusaddon/floccus#1808]
### Which version of floccus are you using?

5.4.0

### How many bookmarks do you have, roughly?

2

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Linkwarden

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 133.0.3 (64-bit)

### Describe the Bug

The initial sync clearly worked, because it synced the only bookmark in Personal > Other Bookmarks to my browser.
But no further syncs work. I saved the reddit homepage as a bookmark, and it would not sync to LinkWarden.

[floccus-5.4.0-2024-12-26-full.log](https://github.com/user-attachments/files/18255183/floccus-5.4.0-2024-12-26-full.log)

### Expected Behavior

I'd expect it to sync.

### To Reproduce

1. Install LinkWarden.
2. Install Firefox, fresh with no bookmarks (delete mozilla default bookmarks)
3. Install floccus extension
4. Generate linkWarden access token, set to never expire
5. Setup Floccus with access token
6. Create a bookmark on test website (such as reddit home page) on bookmark bar.
7. Floccus will error.

### Debug log provided

- [X] I have provided a debug log file

**Comment by ElDubsNZ** [comment]
[floccus-5.4.0-2024-12-26-full (1).log](https://github.com/user-attachments/files/18255224/floccus-5.4.0-2024-12-26-full.1.log)

Log file from testing in Edge.

**Comment by marcelklehr** [comment]
Mmh. Can you check your linkwarden container for error entries in its log? HTTP 500 means the server encountered an error. Which version of linkwarden are you running?

**Comment by ElDubsNZ** [comment]
I've just discovered my linkwarden was severely out of date. After a reinstall to the latest version, the problem was resolved.

**Comment by marcelklehr** [comment]
I'm glad we figured it out :)
