### ISSUE TITLE
Separators

### ISSUE THREAD

**Issue by marcelklehr** [floccusaddon/floccus#186]
> Taken from @lightdot's comment over at #180

The separator situation in Chromium/Chrome is unfortunate. Users [have requested them](https://bugs.chromium.org/p/chromium/issues/detail?id=7789) on several occasions but apparently they won't be added.

There are how-to's online that suggest mitigating the lack of functionality by adding specially crafted bookmarks, using bookmarklets. [These](https://separator.mayastudios.com/?t=horz) seem to be very popular with Chromium/Chrome users.

Bookmark JSON for the horizontal "separator":
````
            {
               "date_added": "<TIMESTAMPINMS>",
               "id": "<ID>",
               "meta_info": {
                  "last_visited_desktop": "<TIMESTAMPINMS>"
               },
               "name": "───────────",
               "type": "url",
               "url": "https://separator.mayastudios.com/index.php?t=horz"
            }
````
generated XBEL:
````
<bookmark href="https://separator.mayastudios.com/index.php?t=horz" id="<FLCID>"><title>───────────</title></bookmark>
````

In Vivaldi, separators are supported by the browser. Unsurprisingly, their actual format is a hack, similar to the above. From Vivaldi's Bookmark file:
````
            {
               "date_added": "<TIMESTAMPINMS>",
               "id": "<ID>",
               "meta_info": {
                  "Description": "separator"
               },
               "name": "---",
               "type": "url",
               "url": "http://bookmark.placeholder.url"
            }
````
generated XBEL:
````
<bookmark href="http://bookmark.placeholder.url/" id="<FLCID>"><title>---</title></bookmark>
````

So we have those two, and from Firefox, JSON:
````
{"guid":"<GUID>","title":"","index":<INDEX>,"dateAdded":<UNIXTIMESTAMP>,"lastModified":<UNIXTIMESTAMP>,"id":<ID>,"typeCode":3,"type":"text/x-moz-place-separator"}
````
generated XBEL:
````
<bookmark href="data:" id="<FLCID>"><title/></bookmark>
````
Translating the above three hackish separators to XBEL's ```<separator>``` element and back would IMHO be safe and cover a lot of users.

**Comment by jantheodor** [comment]
I've been using https://separator.mayastudios.com/index.php to seperate my Bookmakr Folders. Floccus seems to missjudge them as duplicate entries, and therefore deletes them all the time. Any idea how to "fix" this?

**Comment by marcelklehr** [comment]
> Any ideas how I can fix this?

Until separators are supported there is no way for you to fix this, I'm afraid. I'll take a look at this when I'm done with my current project in August.

**Comment by jantheodor** [comment]
> Until separators are supported there is no way for you to fix this, I'm afraid. I'll take a look at this when I'm done with my current project in August.

As far as I understand it, the "seperators" I am using, are simply urls, I can bookmark, that have a "favicon" which gives the impression of an actual seperator, right? Floccus, for some reason, can't differ or doesn't allow, muitliple entries, with the same url? I guess it checks for possible duplicates and removes them (per entity or each layer so to say)?* 

*which maybe, makes sense for many users, and from a programmers perspective, but, in my case, needs to be an option I can choose from. Thanks.

**Comment by marcelklehr** [comment]
> Floccus, for some reason, can't differ or doesn't allow, muitliple entries, with the same url 

This is a limitation of the bookmarks app and does not apply when using WebDAV or GDrive for syncing.

**Comment by tessus** [comment]
> This is a limitation of the bookmarks app

Isn't there a way to workaround that, like adding a `?random_string`. Or maybe you can use a different primary key.

e.g. I might have bookmorks with the same URL but a different title on my system. Does this mean the sync will fail, or just not sync the duplicate? But I think this should be mentioned in the README either way.

**Comment by marcelklehr** [comment]
The next release will have support for Firefox separators by emulating them with http://separator.floccus.org bookmarks on other platforms. Syncing with Nextcloud Bookmarks will only support one separator per folder for now, but unsynced separators will stay where you left them.

**Comment by godfuture** [comment]
I am also interested in Nextcloud bookmarks app in combination with floccus, but this issue with separators holds me back.

Is there a ticket in the nc bookmarks app repository? 

Thanks for this nice piece of software.

**Comment by marcelklehr** [comment]
> Thanks for this nice piece of software.

You're welcome :)

> Is there a ticket in the nc bookmarks app repository?

There is not, I can reopen this ticket to track the remaining task of allowing multiple separators per folder with Nextcloud Bookmarks, there's a hack I have in mind to make this work, despite the Bookmarks app's limitations.

**Comment by godfuture** [comment]
Now that I have all separators in place, I replaced Fireofox sync for bookmarks with floccus. Currently working just fine.

Thanks a lot!
