### ISSUE TITLE
Option to accept Self Signed Certificates

### ISSUE THREAD

**Issue by Giom-fm** [floccusaddon/floccus#208]
### Software versions

- Browser: Firefox 63.0.3
- Nextcloud: 14.0.4.2
- Nextcloud Bookmarks app: 0.14.2
- Floccus: 3.1.14
- Floccus sync method: nextcloud-folders 

### Steps to reproduce

1. Open Firefox (Private Mode)
2. Sync by clicking on "Sync now"

### Expected outcome

Because Im in Private Mode, the self signed Certificates never gets saved.
A Dialog, that Im trying to connect to an "unsafe" webpage with an option to accept (Like Firefox normally does)

### Actual outcome

"Network Error: Check your Connection or your account details"

### Workaround
So as workaround I have to connect to my Server first, accept the untrusted Certificate and after that I can Sync via floccus

**Comment by marcelklehr** [comment]
Hey,

It should be possible to [store a permanent exception](https://www.attachmate.com/documentation/gateway-1-1/gateway-admin-guide/data/fxg_add_untrusted_cert.htm) for your self-signed certificate. This way you don't have to manually accept it every time. Let me know if that works.

**Comment by Giom24** [comment]
Hi,
as I mentioned, its not possible because I'm using Firefox in Private-mode. so no History neither Certificates are stored permanently. After every restart I have to accept it again.

**Comment by marcelklehr** [comment]
I see. Is it possible to disable private mode temporarily and then add the exception permanently?

**Comment by Giom24** [comment]
Yes that's possible.
But I would appreciate to have this feature.

**Comment by Giom24** [comment]
Ok I see,
Unfortunately, Im dealing with some kind of dyndns. so no Let's Encrypt for me...
Thank you anyway

**Comment by mnalis** [comment]
Just to note that Let's Encrypt works just fine with dynamic IPs (like  in dyndns) for me.

All it requires is that your hostname resolves to correct IP at the moment of renewal, so LE servers can connect to your LE script. So, if your machine HTTPS can be directly reached on the Internet (without using VPNs or similar hacks), you can use Let's Encrpyt to provide its certificates. 
Hopefully it helps the OP.

**Comment by bernd-wechner** [comment]
I can second mnalis, and state that I use letsencrypt to maintain certs for at least two servers behind a single router (gateway) that has a dynamic names (ddns). Yes, plural. Multiple domain names pointing to one dynamic IP address at which my gateway farms incoming traffic out to a machine on my LAN based on the domain name used. And the names are managed just fine with letsencrypt.

**Comment by Giom24** [comment]
Thanks,
I will give it a try

**Comment by marcelklehr** [comment]
Adding android user level certs does not seem to work for everyone.

**Comment by marcelklehr** [comment]
Oops, wrong issue. Sorry.
