### ISSUE TITLE
Digest Authentication Scheme?

### ISSUE THREAD

**Issue by Marenz** [floccusaddon/floccus#289]
My server allows only the digest authentication. Apparently that's not supported in the extension, the server logs say `"Client used wrong authentication scheme "basic"".`

Or maybe it is and I have to enable it somehow?

**Comment by marcelklehr** [comment]
Currently, only basic auth is supported with WebDAV sync

**Comment by clash82** [comment]
I would also love to see this implement.

**Comment by marcelklehr** [comment]
Closing this as it's my opinion digest auth gives a false sense of security. If you want secure auth, use basic auth + ssl.
