### ISSUE TITLE
Feature request: Please add Firefox HTML bookmark file format support

### ISSUE THREAD

**Issue by Chamomile11** [floccusaddon/floccus#616]
Please add an option to sync bookmarks into a Firefox HTML bookmark file (as you previously did for XBEL format). This format is supported by all major browser, human- and machine- readable, simple, and can be used either for browsing your freshly synced bookmarks from any other browser or device, or for transfers between browsers. Thank you.

**Comment by marcelklehr** [comment]
I previously dismissed the HTML format for syncing, but it might be possible to make it work using the HTML id attribute to keep track of the items. This is not a priority for me, but I'm happy to help anyone willing to assemble a pull request for this. The XEBL/WebDAV adapter code can be found here: https://github.com/marcelklehr/floccus/blob/develop/src/lib/adapters/WebDav.js

Anyone interested in taking this up, please comment here or reach out on gitter :heart:

**Comment by metbril** [comment]
Just out of curiousity @Chamomile11. Why would you need syncing this from floccus if the Bookmarks app itself can already export this if you only want to open it?

**Comment by Chamomile11** [comment]
> 
> 
> Just out of curiousity @Chamomile11. Why would you need syncing this from floccus if the Bookmarks app itself can already export this if you only want to open it?

This is because I like Floccus a lot but cannot use it (along with the Bookmarks app), because it is not compatible with OwnCloud (which I have to use because NextCloud cannot be installed on my box for some reason).

**Comment by GreenLunar** [comment]
You can use http://www.linkagogo.com/go/Convert to convert HTML bookmarks into XBEL.

[htmlToXBel](https://github.com/Arora/arora/tree/a2d19752759bfb183d983ee3a9d726a4b09375a9/tools/htmlToXBel) of Aurora project does just that.  See manpage at https://man.slitaz.org/?htmlToXBel.1

I think an addon for Firefox to export to XBEL is the best solution for Firefox users.
