### ISSUE TITLE
Firefox and private windows

### ISSUE THREAD

**Issue by delight** [floccusaddon/floccus#622]
It would be nice if floccus sync would also work in firefox private windows mode like it does for chrome in incognito mode

**Comment by marcelklehr** [comment]
Hey @delight 
What doesn't work specifically? You should be able to enable floccus to run in private mode in the addon settings, although I'm not sure what you'd gain from that except if your whole browser is always in private mode.

**Comment by delight** [comment]
Hello @marcelklehr 

indeed I start my browsers by default in private-window / incognito mode (Changed the default start parameters).
Unfortunately floccus won't sync with my webdav (I guess won't sync in general) if firefox is in private-window mode

Right now to let floccus / firefox sync I need to start a window in "standard" mode.

**Comment by marcelklehr** [comment]
In order to aid in debugging, you may provide client-side logs.

#### Firefox
* Go to `about:debugging`
* Click on 'This firefox'
* click on `inspect` button next to floccus entry
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice.
* go back to the inspector window and copy the logs

**Comment by delight** [comment]
I just tried it on firefox on a freshly installed kde neon system ... unfortunately it stops already when trying to add a "+ NEW ACCOUNT" I can't get over the account configuration dialog. This works in regular mode.
 
![grafik](https://user-images.githubusercontent.com/117198/89131600-4f9a6b80-d50e-11ea-8edc-28f9f05b4e44.png)

**Comment by delight** [comment]
TypeError: n is null
    create moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    CREATE_ACCOUNT moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    h moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:20
    dispatch moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:26
    dispatch moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:20
    onCreate moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:20
    Ut moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    a moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    Ut moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    $emit moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    click moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:20
    Ut moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    a moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    _wrapper moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    ue moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    oi moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    _e moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    x moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    m moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    ln moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    _update moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    e moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    get moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    ma moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    mount moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    $mount moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    init moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    m moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    m moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    g moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    m moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    g moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    m moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    g moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    m moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    ln moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    _update moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    e moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    get moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    ma moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    mount moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    $mount moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    init moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7
    m moz-extension://d72f8815-d578-4b3e-9184-df7da8730e83/dist/js/options.js:7

**Comment by marcelklehr** [comment]
I'm sorry for not getting back to you on this. I suspect this is due to Firefox' privacy settings and nothing I can fix. Sorry.

**Comment by srednax** [comment]
The issue with this is that some of us use private windows a lot. They protect your privacy because they prevent data like cookies to be shared between windows.
I can't open the floccus menu at all in private windows, it just shows an eternal spinner.

![Screenshot_20210713_095156](https://user-images.githubusercontent.com/3184467/125413272-0765a060-e7bc-47fb-9e06-2973486b89ff.png)

So pratcically I would have to open a normal firefox window once in a while *just* to sync floccus.

**Comment by hendrikreimers** [comment]
Still have the same issue as the last comment:
https://github.com/floccusaddon/floccus/issues/622#issuecomment-878862701

Please reopen and fix it. Thanks
