### ISSUE TITLE
Bookmarks added while sync is running are disappearing

### ISSUE THREAD

**Issue by smalchow** [floccusaddon/floccus#759]
Bookmarks added while a sync is in progress are deleted

**To Reproduce**
1. Manually start a sync
2. add a bookmark while the sync is running
3. verify whether the existence of the bookmark

Bookmarks should not be deleted when they are added while a sync is running

We verified this behaviour on this platform
 - MacOS 10.15
 - Firefox 
 - 84
 - Floccus version: 4.4.6
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: nextcloud-fpm docker image
 - Nextcloud version: 20.04
 - Bookmarks app version: 4.0.5

**Comment by marcelklehr** [comment]
Finally: Confirmed. They are deleted in the second sync run.

**Comment by marcelklehr** [comment]
Note to self: Fix is to filter tree to cache for items that have no mapping.
