### ISSUE TITLE
Sync fails with Firefox and Nextclout with SSL client certicate

### ISSUE THREAD

**Issue by yano0takashi** [floccusaddon/floccus#765]
**Describe the bug**
Sync fails with the following condition:
Browser: Firefox
Cloudnext: Require SSL client certificate

**To Reproduce**
1. Prepare Cloudnext with SSL client certificate
2. Prepare Firefox with floccus
3. Start sync
4. Sync fails with network error

**Expected behavior**
Sync finish with success

![image](https://user-images.githubusercontent.com/16567823/103469273-16f50b80-4da6-11eb-8a1d-db8aa6e79996.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser Firefox
 - Browser Version 84.0.1
 - Floccus version: 4.4.6
 - Floccus sync method: nextcloud

**Server (please complete the following information):**
 - OS: ubuntu 18.04.5
 - Nextcloud version: 20
 - Bookmarks app version: 4.0.5

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
2021-01-03T00:28:15.435Z Syncing failed with E017: Network error: Check your network connection and your account details

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [X] Debug log provided

**Additional context**
Workaround at nginx reverse proxy:
If at home, SSL client certificate is not required.
Bookmark sync is required only at home  becase all the browsers with floccus are only at home.
Cloudnext is required at any place.
        set $n "0";
        if ( $remote_addr !~ "^XXX\.XXX\.XXX\." ) {
            set $n "1";
        }
        if ($ssl_client_verify = SUCCESS) {
            set $n "0";
        }
        if ( $n = "1" ) {
            return 499;
        }
        add_header Content-Security-Policy "";
        proxy_pass http://XXX.XXX.XXX.XXX/mycloud/;
        proxy_connect_timeout 10;

**Comment by marcelklehr** [comment]
Confirmed.

Note to self: Apparently Firefox needs `credentials: true` in the call to fetch for it to send along the configured client cert. We'll prolly need a setting for this.
