### ISSUE TITLE
Interrupting sync causes duplicates?

### ISSUE THREAD

**Issue by marcelklehr** [floccusaddon/floccus#775]
> This extension, if the sync is ever interrupted for any reason, will create duplicates of all your bookmarks in a flattened structure of your original bookmarks you were syncing, which then synchronize, only to themselves be duplicated the next time sync is interrupted.  It is absolute trash.  I had to write a Python script to go through my bookmarks.html file and de-duplicate it.  Do not use this extension!!

From chrome webstore review

**Comment by daniu-de** [comment]
Hi,
unfortunately I also seem to have that issue with Firefox.
Please solve it soon ... it sounds really cool to be ably to sync my bookmarks with nextcloud
regards

**Comment by marcelklehr** [comment]
@daniu-de Thanks for your feedback! I'll try to investigate. By interrupting you mean closing the browser or clicking "cancel sync" in the ui? Or both?

**Comment by mikeperalta1** [comment]
I'm unaware of how I received my own duplicates. I just know last time I deleted a duplicate, it left zero copies in NextCloud.

I might have time to run tests somewhat soon if you have anything in mind.
