### ISSUE TITLE
Bookmarks order not kept for parent folder with excluded child folders

### ISSUE THREAD

**Issue by james-testified** [floccusaddon/floccus#787]
**Describe the bug**
I have a parent folder that contains several bookmarks and child folders. One of the child folders should be synced to a different account. The setting to exclude the child folder from sync is enabled. Yet, after syncing the parent folder, the bookmarks in the parent folder are out of order as the excluded child folder gets placed at the end. I’m using Floccus 4.4.7 with Nextcloud and Firefox.

Bookmarks order in parent folder before sync (example):
--- Bookmark A
--- Folder A (excluded child folder)
--- Bookmark B
--- Folder B

Bookmarks order in parent folder after sync (example):
--- Bookmark A
--- Bookmark B
--- Folder B
--- Folder A (excluded child folder)

**Expected behavior**
Excluded child folders should not be placed at the end if parent folder is synced. Bookmarks and child folders should stay in place in the parent folder.

Just let me know if you need additional information.

**Comment by marcelklehr** [comment]
Confirmed. This is currently by design, but I can see how that is undesirable.

**Comment by candrapersada** [comment]
And why does tab order change when I sync tabs from Firefox to Chromium?
- Floccus version: 4.6.0
