### ISSUE TITLE
Syncing failed with Invalid bookmark - Separators on waterfox

### ISSUE THREAD

**Issue by r4taw2mg** [floccusaddon/floccus#810]
**Describe the bug**
I cannot get sync to work after updating the local server software (Firefox based):

2021-01-28T21:00:38.025Z COMPARE { localItem: null,
cacheItem: null,
serverItem: - #354 parentId: 41 }
2021-01-28T21:00:38.026Z (local)CREATE - #undefined parentId: wElDPdrlxsGJ
2021-01-28T21:00:38.036Z Syncing failed with Invalid bookmark: {"title":"","type":1,"url":"data:","parentGuid":"wElDPdrlxsGJ"}
2021-01-28T21:00:38.040Z onSyncFail

**To Reproduce**
Setting up an account to sync XBEL file in WebDAV share, local server v1.1.2

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Waterfox
 - Browser Version 2020.10
 - Floccus version: 3.5.1
 - Floccus sync method: webdav

**Server (please complete the following information):**
 - OS: Win7
 - Nextcloud version: -
 - Bookmarks app version: 1.1.2

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ ] Debug log provided

**Additional context**

**Comment by marcelklehr** [comment]
You seem to be using Separators in your bookmarks. This does not seem to be supported in Waterfox for some reason.

**Comment by marcelklehr** [comment]
@r4taw2mg Were you able to resolve this? The solution should be as simple as removing the offending bookmark.

**Comment by r4taw2mg** [comment]
I remove the dividers from the local bookmarks and switched sync mode to overwrite remote changes. Still: Invalid bookmark: {"title":"","type":1,"url":"data:","parentGuid":"wElDPdrlxsGJ"}

**Comment by marcelklehr** [comment]
Separators should be ignored in recent versions of floccus. Your version of floccus has been over a year old at the time of your post. I suggest updating.
