### ISSUE TITLE
Built-in node"Mobile bookmarks" not syncing between Chrome and Firefox

### ISSUE THREAD

**Issue by lohfu** [floccusaddon/floccus#831]
### Describe the bug

If you set the local folder to the root folder, the "Mobile bookmarks" folder does not sync between Firefox and Chrome.

### To Reproduce

1. Add some mobile bookmarks to Firefox
2. Set up a new sync XBEL/WebDAV account with the local folder set to the root bookmark folder
3. Make a fresh sync some Firefox with the new account
4. Recreate the same account in Chrome
5. Restore the sync
6. Notice the "Mobile bookmarks" has not been synced into Chrome

### Expected behavior

The Mobile Bookmarks should be copied.

I know i could set this up via <https://github.com/marcelklehr/floccus#the-server-path-mapping-folders--profiles>, but would be nice if it worked syncing the root folder.

I presume some fiddling in https://github.com/marcelklehr/floccus/blob/c9d4d8fffc35204cda7162f143e266be638d8b14/src/lib/LocalTree.ts#L36-L49 would enable this feature.

### Desktop
(please complete the following information)
 - OS: Arch Linux
 - Browser Chromium , Firefox 
 - Browser Version 88.0.4324.150, 85.0.2
 - Floccus version: v.4.5.0
 - Floccus sync method: webdav

### Server
(please complete the following information)
 - OS: Arch Linux, rclone 1.54.0
 - Nextcloud version: Not applicable
 - Bookmarks app version: Not applicable

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Mmmh, does Chrome have a Mobile Bookmarks folder built-in?

**Comment by lohfu** [comment]
@marcelklehr yes, it works the same way as the firefox built-in folder. ie if you press the bookmark button in mobile chrome (both iOS and android), the bookmark is added to the "Mobile bookmarks" folder

**Comment by lohfu** [comment]
i forgot to mention in the bug report, it also appears if you create folders in your Firefox "Mobile bookmarks" floccus will error when syncing in Chrome saying the parent folder does not exist.

**Comment by lohfu** [comment]
@marcelklehr saw you reopened and closed one of my attempts at posting this issue that did not follow the issue template properly... did you mean to close this one?

**Comment by marcelklehr** [comment]
Nope, sorry, I thought there was no open version of this issue, but overlooked this one. :)

**Comment by marcelklehr** [comment]
@lohfu, the problem is that the mobile folder only exists when having used the built-in browser sync. In firefox it seems the mobile bookmarks folder has a constant ID, but in chrome the that doesn't seem to be the case :/

**Comment by lohfu** [comment]
ah. is the name "Mobile bookmarks" combined with the fact that the parent dir is the root not enough of an identifier?

**Comment by marcelklehr** [comment]
Probably not as the names of the built-in folders are localized :/

**Comment by lohfu** [comment]
well that's a bummer
