### ISSUE TITLE
Memory leak in floccus

### ISSUE THREAD

**Issue by Whissi** [floccusaddon/floccus#836]
### Describe the bug
I suspect there is a memory leak in floccus.

### To Reproduce
1. Start Microsoft Edge (I am using 89.0.774.27 at the moment)
2. Set up Nextcloud account
3. Sync
4. Open Browser Task Manager
5. Leave browser open for 24 hours

### Expected behavior
Memory usage of floccus add-on should stay the same (something between 20-40MB; it's higher during sync but should free up memory afterwards). But after some hours, floccus has reached 400MB. I accidentally left browser running during weekend and on Monday, Browser Task Manager showed more than 3GB RAM usage just for floccus extension. Whole browser was sluggish (not even another website was loaded). After disabling extension, browser recovered.

### Desktop
 - OS: Windows 10 20h@ 19042.804
 - Browser: Microsoft Edge
 - Browser Version: 89.0.774.27
 - Floccus version: 4.4.8
 - Floccus sync method: nextcloud folders

**Comment by marcelklehr** [comment]
Thanks for reporting, I'll look into this!

**Comment by marcelklehr** [comment]
This should be fixed in v4.4.9. Microsoft has been sitting on the latest release for 10 days now, hough :scream_cat:
