### ISSUE TITLE
Bookmark of "chrome://flags/" cannot be synced

### ISSUE THREAD

**Issue by gjf** [floccusaddon/floccus#838]
### Describe the bug
I have a bookmark for opening settings of Chromium browser:
chrome://flags/
It does not syncronize.

### To Reproduce
1. Open a webpage `chrome://flags/`
2. Add it to bookmarks
3. Synchronize bookmarks
4. Synchronize it on another device
5. The new created bookmark is absent

### Expected behavior
A bookmark should appear on all devices.

### Screenshots
N/A

### Desktop
(please complete the following information)
 - OS: Windows 10, Android 10
 - SRWare Iron 88.0.4500.0 (Chromium based) and Kiwi Browser (latest from Playmarket)
 - See above
 - Floccus version: 4.5.0
 - Floccus sync method: webdav

### Server
(please complete the following information)
 - Box.com

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
There is no any mention of "chrome://flags/" in neither PC log (which should upload it) nor Android one (which should download it).

### Additional context
N/A

**Comment by marcelklehr** [comment]
This is currently by design, as not all browsers support the `chrome://` URL scheme

**Comment by gjf** [comment]
But Chromium-based does!
Is it possible to remove this "design" in Chromium version of addon?

**Comment by marcelklehr** [comment]
Yes, it's possible. I'll look into this, but I can't promise anything.

**Comment by marcelklehr** [comment]
Fixed
