### ISSUE TITLE
Failed to map parentId: uw7U4EZOJHvn

### ISSUE THREAD

**Issue by LeSnake04** [floccusaddon/floccus#839]
### Describe the bug
I get this error, but I can't find the error or the ID 'uw7U4EZOJHvn' in the log at all. The log looks pretty normal

### Desktop
(please complete the following information)
 - Archlinux (EndeavorOS)
 - Firefox 86
 - Floccus 4.5.0
 - Nextcloud Bookmarks

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [x] Debug log provided (floccus-4.5.0-2021-02-25_lesnake04)

### Additional context
My other sync to the same cloud has no problem at all.

**Comment by marcelklehr** [comment]
hi @LeSnake04 

This would be a bug in the sync algorithm, likely in the "Sync down" strategy. A short-term fix might be to 1.) do a backup 2.) reset the cache to sync from scratch.

**Comment by LeSnake04** [comment]
> hi @LeSnake04
> 
> This would be a bug in the sync algorithm, likely in the "Sync down" strategy. A short-term fix might be to 1.) do a backup 2.) reset the cache to sync from scratch.

Yeah. This only happends when downloading bookmarks

**Comment by LeSnake04** [comment]
Updated to 4.6 
Now I get the mentioned error  when uploading and when downloading the plugin can't map the parentid 58 (discovered in my log this is the ID of my Folder "BackupKonferenzen")

**Comment by marcelklehr** [comment]
I'm working on a fix, I'll have a patch release ready soon :)

**Comment by x86dev** [comment]
Just upgraded to 4.6.1 on FF 86 here -- unfortunately did not fix my problem, same error. I also clicked on the "Trigger Sync from Scratch" button, but has the same effect.

Is there anything particular in the debug log I can send you to help debugging this?

**Comment by marcelklehr** [comment]
> Is there anything particular in the debug log I can send you to help debugging this?

I'd need more information on which way you're syncing, where the line that you pasted came from, i.e. what is written before the list that this line is part of. So far it seems that "Search-Engines" may have been removed, but only after Startpage was moved out of it. Now, Search-Engines is being recreated and Startpage moved back in, but as Search-Engines has been recreated it has a new ID now. It's just guesswork, though. It would help tremendously if you could upload the full log here: cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw The log will not be publicly accessible and I will destroy it once I've fixed this bug.

**Comment by x86dev** [comment]
Thanks for the offer -- right now I can't access the machine in question, but I'll upload the log as soon as I can!

**Comment by x86dev** [comment]
Sorry that it has been taken for so long -- was busy with other things unfortunately. I've just uploaded my anonymized log file "floccus-4.6.2-2021-04-08_anonymized.log" to your server. Hope that helps! Thank you!

**Comment by marcelklehr** [comment]
@x86dev Thanks! This was helpful indeed! I'll get on to fixing this soon.

Note to self: There's an UPDATE happening on an item in a newly created item, during a "merge default" sync. The UPDATE should probably have been a MOVE instead, to delay mapping until the new element is actually created.

**Comment by x86dev** [comment]
Nice, glad to hear that this has helped! I felt a bit uncomfortable to provide a non-anonymized log, but this was easy to cripple with a few regexes. This might be an idea for Floccus as well to have a checkbox (opt-in to *not* anonymize by default), so that users have a lower barrier of providing their (often work-critical / sensitive) bookmarks.

I'll try out the fix as soon as I've access to the new version. Thanks again!

**Comment by marcelklehr** [comment]
> I'll try out the fix as soon as I've access to the new version. Thanks again!

Any news on this front?

**Comment by x86dev** [comment]
I`d love to try a new version, but there is no update available, still on 4.6.2. Is there other, newer builds I can try?

**Comment by marcelklehr** [comment]
hah, don't mind me, I thought I'd created a release already :sweat_smile:

I'll get on this :dancing_men:

**Comment by x86dev** [comment]
Not a problem, cheers! 😃

**Comment by marcelklehr** [comment]
v4.6.4 is out now on firefox :D

**Comment by x86dev** [comment]
Just updated to 4.6.4 -- sync seems to be running fine now, thanks! I'll check a bit more in detail later on if all the stuff is there as it should be.
