### ISSUE TITLE
Tab Suspender for tab syncing

### ISSUE THREAD

**Issue by candrapersada** [floccusaddon/floccus#842]
### Is your feature request related to a problem? Please describe.
because to start sync tab Google Chrome to Mozilla Firefox and Mozilla Firefox to Google Chrome directly in Tab Suspender mode
### Describe the solution you'd like
Reduce the memory that your browser uses to keep your computer running quickly.
Suspended tabs look just like normal tabs, except they don't use memory.
### Describe alternatives you've considered
You can choose to suspend tabs automatically or on demand with one click. Either way, you’ll dramatically reduce your browser’s memory usage. Now you can keep all your tabs open without getting slowed down.

**Comment by marcelklehr** [comment]
Hi @candrapersada 

there's already addons out there that can suspend tabs, why do you feel like floccus should provide this feature rather than using a second addon for this?

**Comment by candrapersada** [comment]
because to start sync tab Google Chrome and Mozilla Firefox in Tab Suspender mode

**Comment by marcelklehr** [comment]
I've thought about this and tab suspending is not a priority for me at this time. Thank your for your suggestions, however. :heart:
