### ISSUE TITLE
fail init sync to webDAV@hosteurope.de webspace: error_log says "/dev/null doesn't point to a file or directory"

### ISSUE THREAD

**Issue by jgannn** [floccusaddon/floccus#843]
### Describe the bug
freshly installed and configured floccus plugin fails initial sync to webDAV account on dav://nteg.mywebdav.de (hosteurope.de webspace)
Thanks for taking a look. If desired I can send credentials to reproduce the problem. 

### Desktop
 - OS: windows 10
 - Browser Brave
 - Browser Version: Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
 - Floccus version: 4.5.0
 - Floccus sync method: webdav
 
### Server
 - OS: unknown 
 - webspace: hosteurope.de basic webpack
 - http-Server: apache

### Server error_log:
[Sun Feb 28 09:27:24 2021] [core:error] [pid 7376] [client 212.25.6.0] [host nteg.mywebdav.de] AH00038: Forbidden: /dev/null doesn't point to a file or directory
[Sun Feb 28 09:27:25 2021] [core:error] [pid 7377] [client 212.25.6.0] [host nteg.mywebdav.de] AH00038: Forbidden: /dev/null doesn't point to a file or directory

### Debug log
2021-02-28T08:27:25.773Z Starting sync process for account jg@nteg.mywebdav.de
2021-02-28T08:27:25.779Z onSyncStart: begin
2021-02-28T08:27:25.780Z https://nteg.mywebdav.de/bookmarks.xbel.lock
2021-02-28T08:27:25.897Z Syncing failed with E019: HTTP status 403. Failed GET request. Check your server configuration and log.
2021-02-28T08:27:25.904Z onSyncFail

### quick check with cgi script on webspace, albeit not executed by the webDAV user, but the "webpack user"
permissions of /dev/null:
crw-rw-rw- 1 0 root 1, 3 Oct 29 15:10 /dev/null

**Comment by marcelklehr** [comment]
Can you try to use a different webdav client and check if that works?

**Comment by jgannn** [comment]
- checked with cyberduck, same symptom and error_log entries....
- solved by appending directory to webDAV URL like https://nteg.mywebdav.de/<directory>
- no bug but incomplete configuration on my part and confusing error message on webDAV side. 
- Thanks for the fast response!
