### ISSUE TITLE
Can't sync via google drive

### ISSUE THREAD

**Issue by demogest** [floccusaddon/floccus#845]
### Describe the bug
cant login with my google account, returned error code 400.

### To Reproduce
just tap the 'LOGIN WITH GOOGLE'

### Expected behavior
connect to my google drive

### Screenshots
![image](https://user-images.githubusercontent.com/32982120/109812103-98fa9700-7c66-11eb-9808-f1d8004c1aa0.png)

### Desktop
 - OS: Windows 10 Pro 18363.1379
 - Browser Chrome
 - Browser Version 88.0.4324.190
 - Floccus version: 4.6.0
 - Floccus sync method: google drive

**Comment by marcelklehr** [comment]
Thanks for the heads up. The production id of the extension was not yet registered with google. Should be fixed now.

**Comment by candrapersada** [comment]
can't login with my google account from ungoogled-chromium?
![image](https://user-images.githubusercontent.com/36833664/110180995-6f479880-7e3d-11eb-83d4-0e1af43900f1.png)
