### ISSUE TITLE
Ungoogled Chromium: Can't sync via google drive

### ISSUE THREAD

**Issue by candrapersada** [floccusaddon/floccus#847]
### Describe the bug
cant login with my google account, error code 400
### To Reproduce
just tap the 'LOGIN WITH GOOGLE'
### Expected behavior
connect to my google drive

### Screenshots
![image](https://user-images.githubusercontent.com/36833664/110196580-11847200-7e78-11eb-8738-a37213e14fb6.png)
### Desktop
- OS: Windows 10 Home
 - Browser Ungoogled Chromium 
 - Browser Version 87.0.4280.88
 - Floccus version: 4.6.0
 - Floccus sync method: google drive

**Comment by marcelklehr** [comment]
That seems to be an issue with ungoogled chromium. It appears Google doesn't approve their redirect URI domain.

**Comment by candrapersada** [comment]
![image](https://user-images.githubusercontent.com/36833664/139638268-a5d7bf23-471a-4590-9aae-1945c8260806.png)

**Comment by marcelklehr** [comment]
Apparently the devs of ungoogled chromium will not try to fix this. See https://github.com/Eloston/ungoogled-chromium/issues/1437

**Comment by candrapersada** [comment]
add OneDrive or Dropbox for google drive alternative on Ungoogled Chromium #846

**Comment by marcelklehr** [comment]
@candrapersada OneDrive or Dropbox will likely have similar issues with ungoogled chromium

**Comment by candrapersada** [comment]
is there any other way to ungoogled chromium?

**Comment by mnalis** [comment]
@candrapersada  You could use other [storage method](https://floccus.org/start#3-choose-a-sync-method) than `Google drive` (`WebDAV` or `Nextcloud bookmarks`), I guess. It would require opening additional account on some server which offers [those services](https://floccus.org/start#0-prerequisites), though.

**Comment by PF4Public** [comment]
> is there any other way to ungoogled chromium?

One could rebuild ungoogled-chromium omitting the patches and substitutions that prevent the extension from functioning like I stated in the linked issue. It cannot be 'fixed' in ungoogled-chromium itself as it contradicts project goals.
