### ISSUE TITLE
sync tabs when browser start

### ISSUE THREAD

**Issue by candrapersada** [floccusaddon/floccus#850]
how to revert local changes and pull upstream remote changes at browser startup and Always revert upstream remote changes and push local changes every x minutes automatically for browser tabs?

**Comment by marcelklehr** [comment]
@candrapersada Currently you'll have to manually pull upon opening the browser and set the sync strategy to push.

**Comment by candrapersada** [comment]
what I mean is to use sync strategy automatically

**Comment by marcelklehr** [comment]
I could add an option to only sync on browser start. Then you could have one account that regularly pushes and one that pulls once on startup.

**Comment by candrapersada** [comment]
and i want to ask if the pull and push time can be adjusted so that there is no problem like [tabs I have recently closed reappear through the sync quite often](https://github.com/floccusaddon/floccus/issues/689#issuecomment-712039394)

**Comment by marcelklehr** [comment]
If you're talking about the sync frequency, you can definitely adjust that.

**Comment by candrapersada** [comment]
The time between two synchronizations runs in a few minutes. The default is 15 minutes. when the browser starts
for example when I start the browser after 1 day close the sync starts immediately before 15 minutes why this happens?

**Comment by marcelklehr** [comment]
> before 15 minutes why this happens?

This happens because the 15 minutes are calculated as the difference between current time and last sync time. If you haven't had the browser open for more than a day, that's more than 15min.

**Comment by marcelklehr** [comment]
Fixed by aca81a5065f80f6e38e1730fe469d125552eb790 -- now it will sync automatically within 7s of opening the browser.

**Comment by candrapersada** [comment]
Why is the tab sync problem still not resolved?

**Comment by marcelklehr** [comment]
> Why is the tab sync problem still not resolved?

Hey, I've been dealing with more pressing issues so far and was also not sure how to proceed as the requirement to be able to pull sync on browser start and push sync the rest of the time is radically different from the way bookmark sync is handled

**Comment by marcelklehr** [comment]
I think the underlying problem behind your request is that merge sync doesn't work well with tabs, which you would want to use all the time, be it at browser start or during a browsing session. I've recently drastically improved merge sync for tabs, which should hopefully obviate the need for your intricate "strategy switching" request. I'll let you know once the release is published. :)
