### ISSUE TITLE
Google Authorization Error in Edge

### ISSUE THREAD

**Issue by PaulGuijt** [floccusaddon/floccus#853]
### Describe the bug
In Edge I try to add a new account with Google Drive. Google comes back with: 

> Authorization Error
> Error 400: redirect_uri_mismatch
> The redirect URI in the request, https://gjkddcofhiifldbllobcamllmanombji.chromiumapp.org/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}

### Desktop
(please complete the following information)
 - OS: Win 10 64 
 - Browser Edge 
 - Browser Version 89.0.774.50 (Officiële build) (64-bits)
 - Floccus version: 4.6.0
 - Floccus sync method: [e.g. webdav, nextcloud legacy or nextcloud folders]

### Server
(please complete the following information)
 - OS: [e.g. centOS 7]
 - Nextcloud version: [if applicable]
 - Bookmarks app version: [if applicable]

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

**Comment by marcelklehr** [comment]
Hey @PaulGuijt 

Thanks for reporting this. I forgot that Edge uses different Addon IDs. I've added the ID for Edge to the Google OAuth registration. It should work with Edge as well now :)

Cheers!
