### ISSUE TITLE
sync root folder is not working properly

### ISSUE THREAD

**Issue by candrapersada** [floccusaddon/floccus#854]
why sync root folder doesn't work properly for all browsers. after importing and exporting settings and accounts to other browsers?
 - Floccus version: 4.6.0
 - Floccus sync method: google drive

**Comment by marcelklehr** [comment]
@candrapersada Can you please follow the issue template and give detailed information about what doesn't work as expected and how you expect it to work instead?

**Comment by candrapersada** [comment]
Export Floccus configuration from Chromium to Firefox But Sync Bookmark as a root folder is not working for Firefox.

**Comment by marcelklehr** [comment]
This is a general issue. When exporting an importing a config, you will have to set the synced folder anew. I agree that this is not apparent, yet, in the UI.

**Comment by candrapersada** [comment]
and add Trigger sync from scratch
When exporting importing configurations

**Comment by candrapersada** [comment]
Trigger sync from scratch
Tick this box to reset the cache so that the next synchronization run is guaranteed not to delete any data and merely merges server and local bookmarks together
When exporting importing configurations

**Comment by marcelklehr** [comment]
After import the state is the same as if you had selected sync from scratch.
