### ISSUE TITLE
Fixed. Will be released soon. Thanks for reporting :blush:

### ISSUE THREAD

**Issue by candrapersada** [floccusaddon/floccus#856]
Fixed. Will be released soon. Thanks for reporting :blush:

_Originally posted by @marcelklehr in https://github.com/floccusaddon/floccus/issues/848#issuecomment-792257425_
why is it still not fixed for Floccus version: 4.6.1?

**Comment by marcelklehr** [comment]
Hey! I'm sorry if this is still not fixed. Can we continue this in the old issue? I've reopened it in the meantime :) see https://github.com/floccusaddon/floccus/issues/848

**Comment by candrapersada** [comment]
- Browser Chromium

**Comment by marcelklehr** [comment]
Can we continue this in the old issue? I've reopened it in the meantime :) see #848
