### ISSUE TITLE
Separate and select which folders to pull in the root folder stored in bookmarks.xbel such as the Bookmarks bar, Bookmarks menu, and other Bookmarks.

### ISSUE THREAD

**Issue by candrapersada** [floccusaddon/floccus#857]
how to pull sync and separate Root folders stored in bookmarks.xbel such as the Bookmarks bar, Bookmarks menu, and other Bookmarks. without creating another account to sync from Firefox to Chromium?

**Comment by marcelklehr** [comment]
You can't currently. You have to create multiple accounts and files.
