### ISSUE TITLE
History Sync

### ISSUE THREAD

**Issue by NuraliMedeu** [floccusaddon/floccus#858]
### Is your feature request related to a problem? Please describe.
As of March-April 2021, there is no way to sync browser history across devices outside of the built-in sync of a browser. This prevents people from using their favorite browsers for specific platforms, e.g. MS Edge on Windows, Chromium on Linux and Kiwi on Android.

### Describe the solution you'd like
An option for syncing browser history inside the extension menus.

### Describe alternatives you've considered
History sync built into Firefox and MS Edge.

### Additional context
I might be wrong, but one way to implement this would be to periodically  read History.sqlite or places.sqlite (or any other similar history file) and sync its contents using the already implemented syncing algorithms.

**Comment by marcelklehr** [comment]
I'm closing this for now, as it's unlikely I will ever implement this.
