### ISSUE TITLE
No cloud passwords recorded?

### ISSUE THREAD

**Issue by martago54** [floccusaddon/floccus#859]
I hope no google or other cloud service password is ever recorded by your software.  Any web site, even the major ones, can be breached,

I prefer not to have a good bookmarks syncronation service as yours than have the possibility of important passwords, as those of google or other cloud service be compromised.

Solution: ask for the cloud service password everytime the syncronization service is requested, even at the discomfort of having to enter it many times, and DO NOT RECORD IT.  Thank you.

**Comment by marcelklehr** [comment]
Hello @martago54 

thank you for raising these excellent questions! I will extend the FAQ section on the website with more information on this.

As Floccus uses OAuth to connect to your Google Drive, it doesn't know and doesn't record your google password. Instead floccus stores an authentication token which can only be used to create new files and change the files created with the same token in your Google Drive. Not even floccus can access other data stored in your google services.

For Nextcloud you have the option to use your normal account password, or create a dedicated app token that you can revoke at any time.

For WebDAV, only a normal password can be used.

Floccus only stores the data you provide in your browser. The aforementioned access credentials are thus as secure as your browser, by default. If even that is not enough for you, you can encrypt your credentials entered into floccus with a passphrase that you will have to enter on every browser start.

Cheers,
Marcel
