### ISSUE TITLE
Unable to get working with IIS6.1

### ISSUE THREAD

**Issue by cbalbont** [floccusaddon/floccus#860]
### Describe the bug
WebDAV is configured and tested.  From the Internet, I can use Chrome to successfully browse to the URL where I want to store bookmarks, get a logon prompt, enter the username/pw, and view a text TXT file in that directory.  However, if I put this same server and logon information into Floccus, it won't work.  

### Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 91
 - Floccus version: 4.6.1
 - Floccus sync method: WebDAV

### Server
 - OS: Windows SBS 2011
 - IIS v6.1

### Debug log
2021-03-30T02:58:29.784Z Syncing failed with E019: HTTP status 405. Failed PUT request. Check your server configuration and log.

### Additional context
Is Floccus trying to use "Username@URL" as the username?  Because that would be the problem. Like many on-premises Windows servers, we have an Active Directory domain that is _different_ than the web server's external URL.   So if the WebDAV URL is "https://MyServer.com/bookmarks" and the domain is "local.net", then user JDOE needs to log in with one of the following for it to work:

Username:  jdoe
Password: *****
  
Username:  local.net\jdoe
Password: *****
  
Username:  jdoe@local.net
Password: *****

But, if user JDOE enters his username as "jdoe@myserver.com" then the server cannot authenticate him.

**Comment by marcelklehr** [comment]
Hi @cbalbont 
I'm sorry for your troubles.

> WebDAV is configured and tested.

Have you tested your setup with a different existing WebDAV client?

> HTTP status 405. Failed PUT request.

Does your server log any additional details?

> Is Floccus trying to use "Username@URL" as the username?

floccus uses the exact string you entered in the username field.

There have been reports about [problems with IIS](https://github.com/floccusaddon/floccus/issues/814), before but I'm not able to verify this. I'm happy to help troubleshoot in whatever way I can, though.

**Comment by cbalbont** [comment]
Hi Marcel,

Thank you for the response.

I’ve spent hours and hours trying to figure out what the magic settings are to get Floccus working with WebDAV on our IIS.  Today I tried changing things in Floccus again.  For the “WebDAV URL” field, I tried entering the full path to the directory.  I also tried putting in just the web server’s FQDM, and putting the rest of the path in the “Bookmarks file path” field, and also putting some of the path in one field and the rest in the other field.  None of those changes had any effect on the problem.

On the IIS server, I turned off all security for the folder.  Literally all permissions were set to “Everyone” with read/write/modify/delete, and I set WebDAV permissions to “All Users” with read/write/delete, and I enabled all authentication types including anonymous authentication.  I restarted the web server each time.  The folder was wide open, and even though other WebDAV utilities can connect, Floccus just gives the error error “E019: HTTP status 405. Failed PUT request” and no other information.

The log in the IIS server just says this:

2021-03-30 21:11:49 192.168.254.2 GET /Bookmarks/JDoe.lock - 443 floccus 192.168.254.10 Mozilla/5.0+(Windows+NT+6.1;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/80.0.3987.149+Safari/537.36 404 0 2 15

2021-03-30 21:11:49 192.168.254.2 PUT /Bookmarks/JDoe.lock - 443 floccus 192.168.254.10 Mozilla/5.0+(Windows+NT+6.1;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/80.0.3987.149+Safari/537.36 405 0 0 0

2021-03-30 21:11:49 192.168.254.2 DELETE /Bookmarks/JDoe.lock - 443 floccus 192.168.254.10 Mozilla/5.0+(Windows+NT+6.1;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/80.0.3987.149+Safari/537.36 405 0 0 0

After 35 hours trying different things, we are now forced to give up.  I don’t understand because the Floccus home page says it supports “all WebDAV servers”, and when we used the Firefox extension “Xmarks” 5 years ago, we used the same settings and it connected with no problem.  So I’ve no idea what else to do.

I am officially giving up.

Before I go, I have a change suggestion for the Floccus configuration page:

1.      Rename the WebDAV URL field to “WebDAV Server”.  Have users enter only the FQDN or the IP of the server.  (In fact, they shouldn’t need to enter “http” or “https” or even a trailing “/”).   So if the only thing that users should enter in that field is MyWebServer.com or the server IP address... then it’s obvious that only one type of information expected and nothing else.

Best Regards,
Chris

**Comment by marcelklehr** [comment]
Hi Chris,

I'm sorry you're giving up. Given that it seems to work with other clients, the problem my be in floccus. The WebDAV server expects the URL of the WebDAV root folder, while the second field expects the path to the file relative to that root folder. A problem that I know of is that floccus sends requests with `Origin: null`, which some servers trip over. If you like, you could give me a test account with your server and I can investigate. You may send me a mail in this regard (see my github profile).

Cheers
