### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by sotitrox** [floccusaddon/floccus#861]
### Is your feature request related to a problem? Please describe.
There are just the kiwi browser option for Android, but I like to use firefox or fennec, or any other browser.

### Describe the solution you'd like
I think that will be great have a front end app for view and manage the bookmarks, just clic and open in the default browser, and save new bookmarks with the share actions, I think that will be a nice option.
It's like an universal solution to the android issue.

### Describe alternatives you've considered
The add-on on specific browser I think that it's not necessary in a mobile app, I use the share action in other apps and it's confortable, an add-on just limit the spectrum of users and an app for one type of sync (nextcloud) it's the same problem.

### Additional context

PD= sorry my bad english

**Comment by marcelklehr** [comment]
I'm currently torn on how best to invest my time for mobile support.

The state at this time is:

* Kiwi + any floccus adapter
* Nextcloud Bookmarks app (only works when syncing via Nextcloud; the app is very limited)

Options for investing my time:

* Work on improving / creating a new Nextcloud Bookmarks app
* Work on implementing support for bookmarks extensions in Fenix (Firefox for Android)
* Work on creating a floccus mobile app that works with all floccus sync backends

If you have an opinion one way or another, have a vote (only once, please):

[![](https://api.gh-polls.com/poll/01F2BXKE0R0BVFSM04YXYE7RTM/Nextcloud%20Bookmarks%20Android%20App)](https://api.gh-polls.com/poll/01F2BXKE0R0BVFSM04YXYE7RTM/Nextcloud%20Bookmarks%20Android%20App/vote)
[![](https://api.gh-polls.com/poll/01F2BXKE0R0BVFSM04YXYE7RTM/Fenix%20support%20for%20bookmarks%20API)](https://api.gh-polls.com/poll/01F2BXKE0R0BVFSM04YXYE7RTM/Fenix%20support%20for%20bookmarks%20API/vote)
[![](https://api.gh-polls.com/poll/01F2BXKE0R0BVFSM04YXYE7RTM/Floccus%20Android%20app)](https://api.gh-polls.com/poll/01F2BXKE0R0BVFSM04YXYE7RTM/Floccus%20Android%20app/vote)

**Comment by mnalis** [comment]
@marcelklehr could you elaborate on `floccus mobile app` option? I understand it would work with all backends **on server-side** (eg. webDAV, nextcloud bookmarks), but what it would use as a **local side**? Internal bookmarks of some specific mobile browser (and if so, which one? Chrome? Fennec? jQuarks? Firefox Klar?). Or is there same magic bookmarks android API which works with all mobile browsers? Or something else?

**Comment by sotitrox** [comment]
With the share action can to interact with any app, just like "open with... (default browser can be anyone)", and to save the bookmark from any browser just "share -> floccus", open floccus "add bookmark" dialog, and that is basically.
the app can manage the bookmarks, and if share to local storage, can be sync with any program like rclone-explorer(many protocols), syncthing(p2p), or any program that can sync a local folder.
That would cover a lot of apps and types of sync, I think.

**Comment by mnalis** [comment]
@sotitrox but that would not be doing full sync as floccus does on desktop, would it? Sure, I can see how you could use android "share" functionality add current page from mobile browser to floccus app and vice versa, but:

- how would my mobile browser detect I added 5 new bookmarks on desktop and I want them to be synced to mobile browser?
- for that matter, when I get new phone with empty bookmarks, how would the mobile browser receive hundreds of bookmarks I want it to receive? I most definitely don't want to click several hundreds times to open each and every URL in order to "open in Klar" where I can bookmark it? 
- how would it detect deleted and changed bookmarks, etc. ?

**Comment by sotitrox** [comment]
Yes, that is, my idea its first support for android devices is the app, **only the app can handle and manage the bookmarks** in first instance, and **you open the links from the floccus app**.

Of course if your principal device is a web browser in android (where you have all your bookmarks and is not a firefox or chrome type of app) and this don't have the **"export bookmarks"** feature, yes, I think that can be a problem to share every single page to the floccus app, ordering them in the moment that you share to the floccus app, yes, that can be a problem, but **most of the web browser of any kind have the "export bookmarks" feature**, that can be import in another browser compatible with the floccus integration, and, of course, this app needs this feature of import a html's list of bookmarks (It's the most used format for bookmarks export I think).

This app detect, handle and manage every single change in another instances of your sync net of bookmarks.

**Even having that problem** of move all your bookmarks from and Android web browser app without "export bookmarks" feature to the floccus app, **it's better that have only one browser support**, because, in first instance this will cover a more number of users, I think.

I think **the first official support of floccus on android needs to be an independent app**, with time this app can have better handle of our data, and better integration with browsers.

Actually there are no independent app to sync and manage bookmarks that have support on different kind of devices in the open source spectrum of apps, and  floccus is the more relevant for that, an independent app will be really nice.

**Comment by sotitrox** [comment]
> Yes, that is, my idea its first support for android devices is the app, **only the app can handle and manage the bookmarks** in first instance, and **you open the links from the floccus app**.

And with this I don't say that the floccus app needs to be a browser, I don't try to say that (sorry for my bad english), just needs to show the bookmarks, with everything that mean manage bookmarks, when you clic on any link of your list, just it's open in your default app for that.

**Comment by marcelklehr** [comment]
I've decided to extend the floccus code base into a mobile app as suggested. Working on Fenix would have been nice as other extensions would have benefitted, but I have concluded that the Fenix code base is too unfamiliar to me to make substantial progress quickly. In addition to that I think it's strategically better for me to not focus on one particular browser.

**Comment by Manu99it** [comment]
xBrowserSync uses the suggested mobile app approach that i don't like so much. I've switched to floccus because of the integration with kiwi browser

**Comment by personager** [comment]
> I've decided to extend the floccus code base into a mobile app as suggested. Working on Fenix would have been nice as other extensions would have benefitted, but I have concluded that the Fenix code base is too unfamiliar to me to make substantial progress quickly. In addition to that I think it's strategically better for me to not focus on one particular browser.

Just started using Floccus, thank you for all your work on it, it works great! Is there any update or ETA on the mobile app?

**Comment by marcelklehr** [comment]
@Manu99it I know that a native app is not as great as full browser integration, but it's the best I can do for now. Kiwi integration will not go away if I can help it.

@personager I've had to focus on other things the last two months and so only had time to do some small improvements on the existing floccus code which I will release soon. I expect to resume work on the app code in a few weeks, so that I can publish an app hopefully still this year. (My dev time prediction formula is `expected time * PI`...)

**Comment by marcelklehr** [comment]
Please see https://github.com/floccusaddon/floccus/discussions/962 for news on this front.

**Comment by marcelklehr** [comment]
- [x] fix back button
- [x] fix Tree.vue updates
- [x] add i18n
- [ ] Add Nextcloud flow login
- [ ] fix WebDAV
- [ ] fix Google Drive

**Comment by personager** [comment]
> * [x]  fix back button
> * [x]  fix Tree.vue updates
> * [x]  add i18n
> * [ ]  Add Nextcloud flow login
> * [ ]  fix WebDAV
> * [ ]  fix Google Drive
> * [ ]  Implement moving items

Thanks so much for adding Android support. Any ETA on when you'll integrate WebDAV support in the app? Thanks!

**Comment by jknockaert** [comment]
What is actually the intended distribution channel for this Android add-on? Sideloading (not sure if possible at all on Andrdoi)? Or wait for it to be approved by Mozilla as a _recommended_ addon?

**Comment by marcelklehr** [comment]
> What is actually the intended distribution channel for this Android add-on? Sideloading (not sure if possible at all on Andrdoi)? Or wait for it to be approved by Mozilla as a recommended addon?

Once the android app is ready, you will be able to install it via Google Play and hopefully F-Droid. Firefox for Android does not support floccus (see #3 ).

**Comment by IzzySoft** [comment]
@marcelklehr inclusion with my repo [was just requested](https://gitlab.com/IzzyOnDroid/repo/-/issues/216). I happily take it until it's ready (or in your opinion stable enough) for the F-Droid.org repo – but could you please make sure the versioning matches with the tags? Currently, at tag v4.8.4, the app identifies as

    package: name='org.handmadeideas.floccus' versionCode='1' versionName='1.0'

While `versionCode='1'` might fit for the first Android release, `versionName` should rather be `4.8.4` at that tag. If you insist on a different versioning, we'd need separate tags (e.g. `android-1.0`). And with that I'm not only speaking for my repo, but also for F-Droid.org, as that's needed for automated update checks.

**Comment by marcelklehr** [comment]
> I happily take it

Yay :tada:  Thank you :hearts: 

> until it's ready (or in your opinion stable enough) for the F-Droid.org repo

The problem with inclusion in the F-Droid repo is that I'd rather not disclose my Google Drive API key :S Maybe you know a way around that or have advice on how to handle such situations.

> While versionCode='1' might fit for the first Android release, versionName should rather be 4.8.4 at that tag.

Ah, I wasn't aware of that. I'll update those and release a new version soon. Thanks! :)

**Comment by IzzySoft** [comment]
As for the API key, out of my head just 3 approaches:

* have a build flavor that comes without GDrive support. That would make the F-Droid version limited then, but accepted
* let users specify their own API keys, and have F-Droid build without an API key included (might also need a flavor). Full functionality then, with a little effort for those who want it.
* out-source GDrive support to an addon. That would mean the same (base) app for all places, and who wants GDrive can load the addon (from Play or my repo).

Looking forward to the fixed versioning then. Just give me a ping when it's ready, and I'll give it a go.

**Comment by marcelklehr** [comment]
@IzzySoft https://github.com/floccusaddon/floccus/releases/tag/v4.8.6

> out of my head just 3 approaches

I'll think about it, thanks! :)

**Comment by mnalis** [comment]
I think that having users provide their own API keys would be only real solution if @marcelklehr prefers his Google Drive API key to remain secret? I'm no expert on Google APIs by any means, but aren't such keys available inside `.apk` files and could thus be extracted?

**Comment by marcelklehr** [comment]
> I'm no expert on Google APIs by any means, but aren't such keys available inside .apk files and could thus be extracted?

That is probably true for APK files and already true for web extension bundles. I was mainly concerned by [F-Droid's inclusion info](https://f-droid.org/en/docs/Inclusion_Policy/), which states

> F-Droid does not sign up for any API keys. Even if provided by a third party, we include them in both, binary and sourcecode releases.

I have read up some more on OAuth security and realized that even Google themselves don't expect the OAuth client secrets they hand out to stay secret for too long -- at least as long as people use [PKCE](https://datatracker.ietf.org/doc/html/rfc7636), so that's what I will do, then. That means: Green light for F-Droid inclusion (at least on my part).

Thanks for weighing in @mnalis!

**Comment by IzzySoft** [comment]
Wow! So you'll go straight for an RFP or MR at F-Droid.org – or do you still want a listing with my repo until F-Droid is ready (remember the inclusion process can take between a week and a year+)?

**Comment by marcelklehr** [comment]
> do you still want a listing with my repo until F-Droid is ready

@IzzySoft Mh, that's quite a range. What's your recommendation?

**Comment by IzzySoft** [comment]
@marcelklehr both are extremes rarely reached, but it usually takes a couple of weeks until all is set and a new app first pops up at F-Droid. If that's OK with you, you can just start that process and see how it goes (the door to my repo is always open should you get stuck there).

Alternatively, you could have your app start in my repo. Here it usually takes less than 24h for a new app to show up. Side effect in case of Floccus could e.g. be that, after having it set here, I provide back [Fastlane structure](https://gitlab.com/snippets/1895688) which you will need for F-Droid anyway, having part of the scans already performed (so if e.g. something "slipped in" via a dependency, chances are it's detected beforehand), and you get a feeling how it might look like. Once inclusion with F-Droid is completed, I usually remove the app from my repo again – but if requested it can also stay, which some apps e.g. use to provide pre-releases via my repo and the stable ones via F-Droid.

Choice is entirely yours :smile:

**Comment by marcelklehr** [comment]
> Side effect in case of Floccus could e.g. be that, after having it set here, I provide back Fastlane structure which you will need for F-Droid anyway, having part of the scans already performed (so if e.g. something "slipped in" via a dependency, chances are it's detected beforehand), and you get a feeling how it might look like

Sounds good. I also don't know when I'll get to create an RFP, so I think until then, having the app in your repo already is a good thing. Thanks!

**Comment by IzzySoft** [comment]
OK, then welcome aboard! Floccus will [show up here](https://apt.izzysoft.de/fdroid/index/apk/org.handmadeideas.floccus) in about 5h from now (around 7pm UTC). Fastlane structures are on their way (see the link right above this comment). Once that's merged, I'll set up my updater to check that whenever there's a new release tagged and pulled (my updater checks once a day, starting around 6:30pm UTC). That way control over how floccus is presented lies with you; my updater will just take care to optimize graphics a bit, for bandwidth as well as small screens.

**Comment by marcelklehr** [comment]
For all lurkers: Floccus is now also available as an open beta in Google Play.

[<img alt="Google Play" src="https://play.google.com/intl/en_gb/badges/static/images/badges/en_badge_web_generic.png" height="70">](https://play.google.com/store/apps/details?id=org.handmadeideas.floccus)

I'm now closing this issue and will track progress on the remaining TODOs in separate issues.

Cheers :cloud:

**Comment by IzzySoft** [comment]
What is that game shop? <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.DP5biCYDFQQQhDNEflQ5NAHaEp%26pid%3DApi&f=1" width="40" alt="Drake dislikes"> Much better, the app is [available at IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/org.handmadeideas.floccus)! <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.WVouPWtTUmChKmQ35bWBFQHaHk%26pid%3DApi&f=1" width="40" alt="Drake likes">
