### ISSUE TITLE
Floccus extension offline in Chrome Web Store

### ISSUE THREAD

**Issue by ozboss** [floccusaddon/floccus#866]
### Describe the bug
Floccus is not available in the Chrome Web Store and the referenced [link](https://chrome.google.com/webstore/detail/floccus-nextcloud-sync/fnaicdffflnofjppbagibeoednhnbjhg) results in 404.

### To Reproduce
1. Go to https://chrome.google.com/webstore/detail/floccus-nextcloud-sync/fnaicdffflnofjppbagibeoednhnbjhg
2. See error

### Desktop
 - OS: Windows 10
 - Browser: Chrome, Brave

**Comment by marcelklehr** [comment]
Thanks for reporting :heart:. I'm [aware](https://twitter.com/floccusaddon) of this and am in contact with Google.

**Comment by VChernenkoRT** [comment]
Add some options for manual install maybe?

**Comment by ozboss** [comment]
Great, thank you for the fast response and the continued work on this awesome extension, much appreciated ❤️

**Comment by marcelklehr** [comment]
The web store entry has been reinstated.
