### ISSUE TITLE
UX: Sync bookmark root by default

### ISSUE THREAD

**Issue by marcelklehr** [floccusaddon/floccus#870]

**Comment by jantheodor** [comment]
I support this. I have started the syncing process with Brave bookmarks "/ ". Seems to work okay with Chrome. Doesn't work with Firefox tho. Instead of "/" it created a Floccus Subfolder which is suboptimal.

**Comment by marcelklehr** [comment]
@jantheodor resetting it to use the root folder should work.

**Comment by jantheodor** [comment]
> @jantheodor resetting it to use the root folder should work.

Sort of does. The / and sub order get's a bit messy. It seems the sorting algorhytms differ quite a bit. F.e. I use "★" as a prefix, to pull up certain entries within my bookmarks, which works perfectly fine for chrome-based browsers, but does the very opposite in firefox-based browsers. It sure sounds like a very individual issue, but also shows, how difficult it is, to create a 1:1 copy across all the browsers. (Offtopic) Plus: Browser specific bookmarks simply vansih. F.e. I have a bookmark that points towards "brave://bookmarks/?id=3916#1", it seems to get transformed correctly when I sync it with chrome "chrome://bookmarks/?id=6819#1" even so the id has changed for some reason. But it works, so I don't mind. Yet, when I try to receive the same bookmakrs on firefox, they simply vanish.

**Comment by marcelklehr** [comment]
> F.e. I have a bookmark that points towards "brave://bookmarks/?id=3916#1", it seems to get transformed correctly when I sync it with chrome "chrome://bookmarks/?id=6819#1" even so the id has changed for some reason. But it works, so I don't mind. Yet, when I try to receive the same bookmakrs on firefox, they simply vanish.

That's odd. It shouldn't get synced at all, to neither browser.
