### ISSUE TITLE
Top level non-folder bookmarks dont sync

### ISSUE THREAD

**Issue by agilob** [floccusaddon/floccus#871]
### Describe the bug
Bookmarks in firefox (source):
![image](https://user-images.githubusercontent.com/2544251/116530559-b26a3900-a8cd-11eb-81ba-e5374888cef6.png)

bookmarks in brave:
![image](https://user-images.githubusercontent.com/2544251/116530601-be55fb00-a8cd-11eb-97a0-149a4c96c305.png)

the top level bookmarks test | whitecircle | x | x | YT link

dont load in brave, they are present in nextcloud - > bookmarks

### To Reproduce
1. setup sync on firefox
2. push all bookmarks
3. all bookmarks appear in NC/Bookmarks
4. setup sync in Brave
5. top level non-folders aren't loaded

### Expected behavior
Top level non-folders should appear

### Desktop
(please complete the following information)
 - Browser firefox and brave
 - Floccus version: 4.6.4
 - Floccus sync method: nextcloud bookmarks addon

### Server
(please complete the following information)
 - Nextcloud version: 21.0.1
 - Bookmarks app version: 4.1.0

**Comment by marcelklehr** [comment]
Mh. Which local folder is your root folder for syncing in Brave?

**Comment by agilob** [comment]
![image](https://user-images.githubusercontent.com/2544251/116539885-f6af0680-a8d8-11eb-82eb-dca14db64e4b.png)

**Comment by agilob** [comment]
Ah crap, I had different `server directory there` it made folders sync but not direct links. my bad, sorry guys

**Comment by agilob** [comment]
Now order is not synced, there's an issue for it, and I can live with that.

**Comment by marcelklehr** [comment]
> Now order is not synced, there's an issue for it

Which issue is that?

**Comment by agilob** [comment]
https://github.com/floccusaddon/floccus/issues/787

**Comment by agilob** [comment]
Each browser i connected has different order of bookmarks

**Comment by marcelklehr** [comment]
> Each browser i connected has different order of bookmarks

Ah. #787 only applies if one of the child folders is excluded and should be synced to a different account. If your bookmarks are generally in the wrong order, that's a different more serious bug.

**Comment by agilob** [comment]
I'll keep observing it, but so far I have firefox on mac, brave on mac and same setup on linux, all bookmarks (as folders and top level links) are in different order on every browser. I reordered them to original state, but some folders changed order of inner bookmarks ~2 hours later.
