### ISSUE TITLE
Praise

### ISSUE THREAD

**Issue by dsiminiuk** [floccusaddon/floccus#874]
This plugin is performing well. I have over 1300 bookmarks and an update takes about 3 seconds. Amazing!

It is almost fast enough to do real time updates when any change is detected.

THANK YOU!

**Comment by marcelklehr** [comment]
Hi @dsiminiuk 

Thank you for the kind words! I'm glad you're still on board after 4 (sometimes difficult) years and are finally able to enjoy floccus :)

Stay safe in your personal stratosphere and: spread the word, share the love :hearts:

Cheers!
