### ISSUE TITLE
Seafile 

### ISSUE THREAD

**Issue by FlorianJSa** [floccusaddon/floccus#875]
### Is your feature request related to a problem? Please describe.
Hello, currently it is unfortunately not possible to synchronize the favorites with a Seafile cloud

### Describe the solution you'd like
Adding Seafile integration 

### Describe alternatives you've considered
An alternative would be to extract the favorites as e.g. Json or XML. To enable a manual synchronization 

### Additional context
If you are interested in an integration I would also be willing to deal with the feature and create an

**Comment by marcelklehr** [comment]
>  I would also be willing to deal with the feature and create an

...adapter? That would be cool!

Does seafile sync not work with WebDAV?

**Comment by FlorianJSa** [comment]
Thanks for your message, yes it also works with WebDav this was not aware of me. Sorry for the issue I think it can be closed
