### ISSUE TITLE
Firefox Sync not completing

### ISSUE THREAD

**Issue by xelcho** [floccusaddon/floccus#880]
### Describe the bug
Firefox sync is not completing, while chromium is just fine with the same settings.
When sync hangs it causes firefox to crawl... putting up warnings about a site slowing it down and such.

### To Reproduce
none

### Expected behavior
clean sync

### Desktop
(please complete the following information)
 Windows 10
 firefox
 - Browser Version [e.g. 22]
 - 88.01
 - Floccus version: [e.g. 3.2.2]
 - 4.6.4
 - Floccus sync method: [e.g. webdav, nextcloud legacy or nextcloud folders]
nexcloud - using - xbel file
### Server
(please complete the following information)
 - OS: [e.g. centOS 7]
 - ncp image (buster some such)
 - Nextcloud version: [if applicable]
 - 20.x
 - Bookmarks app version: [if applicable]
 - N/A

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
no log available.

- [ ] Debug log provided

**Comment by xelcho** [comment]
Here is a screen-shot of it hanging...
<img width="60" alt="Capture" src="https://user-images.githubusercontent.com/30007489/119659639-59be8b00-bdfc-11eb-95a0-d775f0cd3a64.PNG">

**Comment by marcelklehr** [comment]
Mmh, could you try to check the browser logs as follows:

#### Firefox
* Go to `about:debugging`
* Go to `This firefox`
* click on `debug` button next to floccus entry
* trigger a sync by clicking on `sync now` for the account of your choice.
* go back to the inspector window and copy the logs

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* trigger a sync by clicking on `sync now` for the account of your choice
* go back to the inspector window and copy the logs after waiting for the sync to finish

**Comment by xelcho** [comment]
@marcelklehr 

Thank you! for the noob instructions I will do so asap and post the response, here.

**Comment by xelcho** [comment]
The console reveled that it was hanging on the local removes. So I backed-up bookmarks and resynced and am checking for missing few.  There is a warning:

Reading manifest: Warning processing browser_action.chrome_style: An unexpected property was found in the WebExtension manifest.
occured during first sync... that went away after initial sync.

thoughts?

**Comment by marcelklehr** [comment]
> An unexpected property was found in the WebExtension manifest.

That's unrelated.

> The console reveled that it was hanging on the local removes.

mmmh, weird.

**Comment by Thaodan** [comment]
I have the same issue, same Firefox just on Arch while the server is Arch too and Nextcloud 21.

**Comment by marcelklehr** [comment]
Thank you for the feedback and sorry for the trouble, I'm a bit swamped at the moment, but will look into this soon-ish.

**Comment by marcelklehr** [comment]
Can you try with the latest release, maybe?
