### ISSUE TITLE
Bookmarks order not preserved on initial unidirectional sync

### ISSUE THREAD

**Issue by deragon** [floccusaddon/floccus#884]
### Describe the bug
Bookmarks order not preserved when syncing from Chrome to WebDAV to Firefox.

### To Reproduce
1. Go to Chrome
2. Sync bookmarks (All) with WebDAV Server
3. Go to Firefox
4. Delete all bookmarks under 'Bookmark toolbar'
5. Start sync one way, toward Firefox

### Expected behavior
Under Firefox, I expect that the bookmarks are set in the same order as in Chrome, but this is not the case.  The order seams random.

However, I do not believe any bookmark is missing.  The problem is only with the order not being respected.

### Desktop
 - OS: Ubuntu 20.04 LTS
 - Chrome 91.0.4472.77
 - Firefox 89.0
 - Floccus version: 4.6.4
 - Floccus sync method: webdav

### Server
 - OS: Ubuntu 20.04 LTS

**Comment by marcelklehr** [comment]
Thank you for the feedback and sorry for the trouble, I'm a bit swamped at the moment, but will look into this soon-ish.

**Comment by verglor** [comment]
Hi, I have the same problem with Chrome -> Google Drive -> Firefox sync.

**Comment by marcelklehr** [comment]
Confirmed. If you pull-sync a second time, the order is fixed. Note to self: This is a bug in the UnidirectionalMerge strategy.
