### ISSUE TITLE
Chrome can't map Firefox Bookmarks Menu (Failed to map parentId: xxxx)

### ISSUE THREAD

**Issue by Zottelchen** [floccusaddon/floccus#885]
### Describe the bug
When syncing data with Nextcloud, Chrome is unable to map the Bookmarks menu folder.

### To Reproduce
1. Push bookmarks up to Nextcloud with Firefox
2. Pull bookmarks with Chrome

### Expected behavior
Maybe create a new folder?

### Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 91.0.4472.77 
 - Floccus version: 4.6.4
 - Floccus sync method: Nextcloud Bookmarks App

### Server
 - OS: unknown (Linux 5.4.0-72-generic x86_64) / Hetzner Storageshare
 - Nextcloud version: 20.0.9
 - Bookmarks app version: 4.2.1

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
- [x] Debug log provided

**Comment by elearningdienst** [comment]
Same here on Ubuntu 20.04 with Chromium Version 91.0.4472.77 (Offizieller Build) snap (64-Bit) and Firefox 89 64-Bit. Floccus 4.6.4 from the Cromium/Firefox App Store and Nextcloud 21.0.2 / Nextcloud Bookmarks  4.2.1

**Comment by marcelklehr** [comment]
Thank you for the feedback and sorry for the trouble, I'm a bit swamped at the moment, but will look into this soon-ish.

**Comment by marcelklehr** [comment]
The latest release v4.7 is out now and has a lot of fixes, including a fix for an instance of this error. Please test and report back if this is fixed. Thank you :blue_heart:

**Comment by Zottelchen** [comment]
Hey, the problem seems to persist for me.

**Comment by marcelklehr** [comment]
Please try and reset the cache in the "dangerous actions" part of your account settings and try again.

**Comment by Zottelchen** [comment]
I've tried that and it didn't work. I've deleted all the bookmarks and tried again, now it doesn't show an error anymore, but it only syncs the bookmarks from the "Other Bookmarks" and the "Bookmarks Bar" folder, but misses the "Bookmarks Menu" folder.

**Comment by marcelklehr** [comment]
> misses the "Bookmarks Menu"

Chrome doesn't have a Bookmarks Menu, so you'll need to manually add a Bookmarks Menu folder somewhere, e.g. in your toolbar and then set up sync only for the Bookmarks Menu folder.

**Comment by Zottelchen** [comment]
Thank you, that works.
