### ISSUE TITLE
Unable to add account on Android

### ISSUE THREAD

**Issue by FlorianJSa** [floccusaddon/floccus#887]
### Describe the bug
On android the layout is cut off, also it is not possible to add an account

### To Reproduce
1. Go to Settings
2. Click on ADD ACCOUNT

### Screenshots
![photo_2021-06-14_22-21-49](https://user-images.githubusercontent.com/54689374/121954636-48afcc80-cd5f-11eb-8de5-4173a1da8d69.jpg)

### Mobile
(please complete the following information)
 - OS: [e.g. Android]
 - Browser Firefox
 - Browser Version 91.0
 - Floccus version: 4.6.4
 - Floccus sync method: WebDAV

**Comment by marcelklehr** [comment]
Hey @FlorianJSa 
This is a known problem: #3 
Thank you for your feedback nonetheless. :)
