### ISSUE TITLE
Unable to sync in Portable version of Chrome

### ISSUE THREAD

**Issue by v01ded** [floccusaddon/floccus#890]
Hi,

Thanks for the great software! 

I found that that floccus does work with Chrome Portable. The sync when through without error but the bookmarks never appear.

Chrome version: Version 91.0.4472.114 (Official Build) (32-bit)
SyncServer: NextCloud ver. 21 with Bookmark (v4.2.2)

I have attached my debug logs with private detail removed.
[floccus-4.6.4-2021-06-19.txt](https://github.com/floccusaddon/floccus/files/6679749/floccus-4.6.4-2021-06-19.txt)

Hope these information will make Floccus better!

**Comment by marcelklehr** [comment]
@v01ded You likely haven't select an existing folder to sync, so floccus creates a new empty one for you.

**Comment by v01ded** [comment]
![2021-06-19_192839](https://user-images.githubusercontent.com/10796960/122640923-9c8e2d00-d134-11eb-9ba7-afce03ef84c9.png)
Hi,

I did select the folder as highlighted in the screenshots. I remove the details logs about my bookmarks in the logs, that is why you dont see any entries of bookmarks from the sync servers.. The sync when through successfully but nothing happen on my Portable Chrome.. Cheers.

**Comment by marcelklehr** [comment]
> I remove the details logs about my bookmarks in the logs, that is why you dont see any entries of bookmarks from the sync servers..

Ah. Please, consider submitting the full log privately in such cases as it's rather confusing :D 

As it is, the log does not help much.

**Comment by marcelklehr** [comment]
Alright, thanks for the log. It appears, the server folder you selected is empty. You should be able to go to your nextcloud in the browser and enter `<your cloud URL>/apps/bookmarks/folders/165` to see the contents of the folder you selected.

**Comment by marcelklehr** [comment]
It may be a UX improvement to offer server folder selection with an actual folder picker UI.

**Comment by v01ded** [comment]
Thanks, thank seems to solve the issue. What happens is that initially created the folder on my server, delete it and then recreated it. Did not know that the Folder ID change that cause this issue. 

Apologies for the false alarm. Having the UI to choose the actual folder will be great.
