### ISSUE TITLE
Add account not response on iceraven brrowser

### ISSUE THREAD

**Issue by WqyJh** [floccusaddon/floccus#895]
### Describe the bug
Iceraven is a firefox based android browser, which support browser extensions.
This extension could successfully be installed on iceraven but do not perform any action when add account was touched.
However, it works fine on another android browser based on chromium called kiwi.

### To Reproduce
1. Install iceraven browser
2. Go to Add-ons Manager
3. Find floccus and install
4. Open Floccus options
5. Click new account
6. Select any one sync method and click add account, won't navigate to new page as expected

### Expected behavior

Navigate to new page to fill account info.

### Screenshots
![Uploading Screenshot_20210701_185549_io.github.forkmaintainers.iceraven.jpg…]()

### Desktop
 - OS: Android 10
 - Browser: Iceraven
 - Browser Version: iceraven-1.11.1
 - Floccus version: 4.6.4
 - Floccus sync method: webdav

### Server
(please complete the following information)
 - OS: [e.g. centOS 7]
 - Nextcloud version: [if applicable]
 - Bookmarks app version: [if applicable]

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

**Comment by WqyJh** [comment]
Also mentioned in https://github.com/fork-maintainers/iceraven-browser/issues/292

**Comment by marcelklehr** [comment]
> firefox based android browser

I don't know enough about iceraven, but even firefox for android itself doesn't support (and never has) the webextension bookmarks API, so this is an issue with iceraven.
