### ISSUE TITLE
why when use tab suspenders from other extensions can't sync use floccus

### ISSUE THREAD

**Issue by candrapersada** [floccusaddon/floccus#896]
why other Tab suspender extensions like The Marvelous Suspender that are stored in bookmarks can't sync and tabs without Tab Suspender can be synced?
and which extensions support sync in Suspender mode use floccus?

**Comment by marcelklehr** [comment]
@candrapersada What do these links look like?

**Comment by candrapersada** [comment]
extension://noogafoofpebimajpfpamcfhoaifemoa/suspended.html#ttl=Tartube%20-%20The%20Easy%20Way%20To%20Watch%20And%20Download%20Videos&pos=0&uri=https://tartube.sourceforge.io/

**Comment by marcelklehr** [comment]
Yep, floccus can only sync http(s) links at the moment. extension links are not cross- browser. Sorry.
