### ISSUE TITLE
Suggestion: User-Warning/Hint "Please do a full backup before using this extension!"

### ISSUE THREAD

**Issue by jantheodor** [floccusaddon/floccus#897]
Since the extension doesn't work flawlessly (yet), I think it's appropiate to add a user-warning: "Please do a full backup before using this extension!" At least before the inital sync. It's always a pain in the a** if you feel adventurous, try a fancy extension, and end up with a mess.

**Comment by marcelklehr** [comment]
That's a good point. When syncing things, doing a backup is always a good idea.
