### ISSUE TITLE
Improve wrong credential feedback

### ISSUE THREAD

**Issue by keponk** [floccusaddon/floccus#905]
I noticed this while installing on a new browser. When configuring a new folder and try to sync and the error message is:

```
{"status":"error", "data":"nextcloud API insufficient permissions"}
```

This clearly suggests a permission issue was at hand. After going through the extensions permissions and app permission on the nextcloud admin account, still the error continued. This took some time plus trying to find possible permission config setups online. All so that at the end the issue was wrong password was put in the extension settings.

A few possible solutions come to mind:
a) Update the error message to specifically inform "Wrong credentials"
a.1) Show error message in plaintext, not JSON. 
b) Use app auth method for nextcloud.

**Comment by marcelklehr** [comment]
Thanks for reporting this. It appears to be an upstream issue, that I'll happily work on: https://github.com/nextcloud/bookmarks/issues/1602
