### ISSUE TITLE
Tab sync documentation missing

### ISSUE THREAD

**Issue by acht** [floccusaddon/floccus#906]
Hi,

you have an tap-sync option (creating account), I have not found a documentation so my questions are:
- Is it useful as a backup in case Firefox is not able to restore a session?
- Is it possible to look into tabs of an other browser?
- Is a tab I open in one browser opened in an other browser when syncing (same for closing)?
- How is exclude/include of local folder handled?

Thank you very much for your help.

**Comment by marcelklehr** [comment]
Good point! I'll add docs for this

**Comment by marcelklehr** [comment]
See https://floccus.org/start#syncing-tabs

**Comment by PSeQXh** [comment]
[https://floccus.org/guides](https://floccus.org/guides) under "Sync tabs" might be the current place for this 
([https://floccus.org/start#syncing-tabs](https://floccus.org/start#syncing-tabs) results in 404/'File not found' for me)
