### ISSUE TITLE
Not syncing file on box.com via webdav

### ISSUE THREAD

**Issue by djlauria** [floccusaddon/floccus#909]
### Describe the bug
This worked until recently. File which is stored on box.com no longer syncs.

### To Reproduce
Attempt a normal sync with webdav file on Box

### Expected behavior
Should sync without issue. Last successful sync is dated July 8th

### Screenshots
Error text:
Parse Error: <html xmlns="http://www.w3.org/1999/xhtml"><body><parsererror style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black"><h3>This page contains the following errors:</h3><div style="font-family:monospace;font-size:12px">error on line 1 at column 1: Document is empty </div><h3>Below is a rendering of the page up to the first error.</h3></parsererror></body></html>

### Desktop
(please complete the following information)
 - OS: Windows 10
 - Browser: both Chrome and Edge
 - Browser Version 91 
 - Floccus version: 4.6.4
 - Floccus sync method: webdav

### Server
(please complete the following information)
Box.com

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

2021-07-13T00:50:39.226Z Starting sync process for account xxxxx@xxxxxx.com@dav.box.com
2021-07-13T00:50:39.234Z onSyncStart: begin
2021-07-13T00:50:39.234Z https://dav.box.com/dav/Bookmarks/BWRSD.xbel.lock
2021-07-13T00:50:39.568Z https://dav.box.com/dav/Bookmarks/BWRSD.xbel.lock
2021-07-13T00:50:40.991Z Syncing failed with Parse Error: <html xmlns="http://www.w3.org/1999/xhtml"><body><parsererror style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black"><h3>This page contains the following errors:</h3><div style="font-family:monospace;font-size:12px">error on line 1 at column 1: Document is empty
</div><h3>Below is a rendering of the page up to the first error.</h3></parsererror></body></html>
2021-07-13T00:50:40.996Z onSyncFail

**Comment by marcelklehr** [comment]
Does the sync file have any content in box.com's UI?

**Comment by djlauria** [comment]
Yes. Just downloaded it and can verify that it's not empty

**Comment by marcelklehr** [comment]
I cannot reproduce this with my own box.com account.
I suggest you 

1. Go to settings -> Dangerous actions -> Trigger sync from scratch
2. Delete your bookmarks file on box.com
3. Start a new sync run
