### ISSUE TITLE
Extension not usable with Google drive and Opera

### ISSUE THREAD

**Issue by mneiger** [floccusaddon/floccus#913]
### Describe the bug
Chrome extension can login with Google backend from Chromium but does not work from Opera 
The same account also work from Firefox.

### To Reproduce
Start Opera (Version:77.0.4054.254) with floccus extension for chrome (4.6.4)
Create a new floccus account 
select type Google
when clicking the "login with google" button it fails with the above message
![image](https://user-images.githubusercontent.com/3162934/125699132-5b99d7fd-b2ab-4435-a6ac-ddf0a3c4ce97.png)

google reports
Authorization Error
Error 400: redirect_uri_mismatch
The redirect URI in the request, https://djejpebekaoommcjfeaiipdikmdjkblg.chromiumapp.org/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/305459871054-4rr6n0jmsdvvprtjqbma5oeksshis2bn.apps.googleusercontent.com?project=305459871054

![image](https://user-images.githubusercontent.com/3162934/125699028-49a435db-8a57-438f-81e2-b199abfaeb2f.png)

### Expected behavior
it should offer to login with a google account 

### Desktop
 - OS: Linux Mint Xfce 20.2
 - Browser Opera
 - Browser Version 77.0.4054.254
 - Floccus version: 4.6.4
 - Floccus sync method: Google

- chromium : Version 91.0.4472.114 (Official Build) for Linux Mint (64-bit), Floccus 4.6.
- firefox : 90.0, Floccus 4.6.4

### Additional context
I suspect we've run into the following problem and do not request the appropriate redirect privileges from Google
https://stackoverflow.com/questions/50213150/chrome-extension-launchwebauthflow-error

As an aside, I decided to switch to use Google as a backend because the sync with the nextcloud bookmark app was putting too much load on my Nextcloud server with 1850 Bookmarks. (Huge Cpu load and lots of SQL writing, but this is another issue and likely already reported). beyond this, the extension used to work fine with Opera, Chromium and Firefox and Nextcloud 20-21 Bookmark app as backend.

Thanks a lot.

**Comment by marcelklehr** [comment]
Thanks for reporting. Google didn't have the redirect URI from Opera (I wasn't aware they're using a different one). Should be fixed now.
