### ISSUE TITLE
Cancel sync takes too long (at least minutes, likely forever?)

### ISSUE THREAD

**Issue by mnalis** [floccusaddon/floccus#916]
### Describe the bug
As mentioned in https://github.com/floccusaddon/floccus/issues/912#issuecomment-881408920, I'm syncing tabs in Firefox, and press `Cancel sync`. I'd expect it to cancel sync and indicate so immideately. Instead, after more than 40 minutes, it still says ` Synchronization in progress. ` and offers `Cancel sync` button. Or perhaps it is cancelled but information displayed to user is not updated?

### To Reproduce
1. Go to floccus menu
2. Toggle off syncing of that account
3. Click on `Cancel sync`
4. see button respond to click, but nothing happens
5. wait for 5 minutes, periodically checking, and see that still says ` Synchronization in progress. ` and offers `Cancel sync` button. I'm not sure if it will ever finish before I close firefox.
6. try clicking few more times on `Cancel sync` - it visually show it is pressed/depressed, but nothing else changes.

### Expected behavior
I expected that when I pressed `Cancel sync` it cancels sync immediately, or in at most few seconds, show status that sync was aborted, and removes `Cancel sync` button (replacing it with `Sync now` button)

### Desktop
 - OS: Debian Buster GNU/Linux
 - Browser:Firefox
 - Browser Version:78.11.0esr (64-bit)
 - Floccus version: 4.6.4
 - Floccus sync method: Nextcloud bookmarks

### Server
 - OS: Debian Buster GNU/Linux
 - Nextcloud version:  20.0.11
 - Bookmarks app version: 4.2.2

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [x] Debug log provided (yes, I'll anonymize and upload it shortly - it is the same debug log as for https://github.com/floccusaddon/floccus/issues/912#issuecomment-881408920)

### Additional context
I do have **a lot** of tabs open in firefox. By rough estimation, at least few hundreds, maybe near 1000.

**Comment by mnalis** [comment]
Is this supposed to be fixed in `floccus 4.7.0`? Because it still does not look like it works, I've waited few minutes after pressing `CANCEL SYNC` and it's still saying `Syncing` with rotating arrows...

(Firefox was upgraded to `78.12.0esr (64-bit)` and Floccus extension to `4.7.0` since this was initially reported)

**Comment by mnalis** [comment]
**Update**: ah, it does cancel now, but **does not show it** until the floccus window is **dismissed and opened again**, after which  it says in red `Error` / `E027: Sync process was interrupted`.

It would be nice if the correct status could be shown in the already opened floccus window, instead of requiring user to close and reopen window to see the updated status.

**Comment by marcelklehr** [comment]
The
