### ISSUE TITLE
Login with Google crashes Edge browser

### ISSUE THREAD

**Issue by AbraamNader** [floccusaddon/floccus#919]
### Describe the bug
Login with Google crashes Edge Browser when adding a new account.

### To Reproduce
1. Click new account
2. Choose Google Drive
2. Click Login with Google button

### Expected behavior
Should display the login page.

### Desktop
(please complete the following information)
 - OS: Windows 10
 - Browser: Edge
 - Browser Version:  91.0.864.71 (Latest)
 - Floccus version: 4.6.2
 - Floccus sync method: Google Drive

### Debug log
n/a

**Comment by marcelklehr** [comment]
Hey @AbraamNader!
I'm sorry for your troubles.
I cannot replicate this with Edge 93.0.957.0 on Linux. Please try again and report back :)

**Comment by fstaubach** [comment]
Hey,

I can confirm this behavior in Edge Version 92.0.902.73 (64bit) on Win10 21H1 with Floccus version 4.7.0.
After pressing the "Login with Google" Button during the initial account configuration process the whole Edge instance crashes. After restarting the browser the addon presents the debug log as follows:

### Debug Log

> 2021-08-15T20:54:47.431Z Starting sync process for account Google Drive: bookmarks.xbel
> 2021-08-15T20:54:47.474Z onSyncStart: begin
> 2021-08-15T20:54:47.613Z Syncing failed with E031: Could not authenticate with Google Drive. Please connect floccus with your google account again.
> 2021-08-15T20:54:47.622Z onSyncFail

**Comment by marcelklehr** [comment]
This appears to be a bug in Edge and will likely be fixed with the release of v93

**Comment by NuraliMedeu** [comment]
Hello! Is it possible to fix this on the user side without updating Edge or installing another browser?

**Comment by mnalis** [comment]
@NuraliMedeu You can use other [storage method](https://floccus.org/start#3-choose-a-sync-method) than `Google drive` (`WebDAV` or `Nextcloud bookmarks`), I guess. It would require opening additional account on some server which offers [those services](https://floccus.org/start#0-prerequisites), though.

**Comment by NuraliMedeu** [comment]
Thanks, @mnalis! I am currently trying to sync my bookmarks through Yandex Disk WebDAV.

**Comment by marcelklehr** [comment]
Still working for me with Edge 95.0.1000.0

**Comment by marcelklehr** [comment]
@kiwibrowser Do you maybe have a hint on what's going on here, as the same was/is happening on kiwi?

**Comment by TimKKLYT** [comment]
I met same issue on Microsoft Edge.

OS: [Win10 Pro, 21H1, x64]
Browser [Microsoft Edge]
Browser Version [94.0.992.31, x64]
Floccus version: [4.7.0. Direct installed from MicrosoftEdge store.]
Floccus sync method: [Googld Drive]

Situation:
Creat a new account. Choosed Google Drive for sync method.
Click on "Floccus icon"
Click on "Options"
Click on "Login with Google"
Screen freezed and then crashed.

I have another computer (also Win10 Pro, 21H1, x64), and Floccus works well on Edge and Chrome. Floccus still works well on that computer.

This is a new computer and just had clean installation. Floccus works well on Chrome but crash on Edge.
Seems it lost something on the new computer?

**Comment by fstaubach** [comment]
> This appears to be a bug in Edge and will likely be fixed with the release of v93

In the meantime I am already updated on Edge Version v94 and Floccus v4.8.2. The issue still persists. Any hope that this error will be fixed soon?
Please let me know, if you need more information.

**Comment by mnalis** [comment]
Perhaps it might it be useful if someone has access **both** to Edge instance that crashes, and to Edge instance that does not crash, and can see what are differences between them (version, settings, etc).

**Comment by Cyberavater** [comment]
> Great! Which version is that?

Microsoft Edge
Version 96.0.1032.0 (Official build) dev (64-bit)
