### ISSUE TITLE
Brave sync failing with parse error (Empty document)

### ISSUE THREAD

**Issue by Victor4X** [floccusaddon/floccus#922]
### Describe the bug
When trying to sync bookmarks from Brave to Google drive, it fails with a parse error (see debug log)

### To Reproduce
1. Add Google drive configuration (all default)
2. Start sync
3. See error

### Expected behavior
I expect my bookmarks to be synced to the bookmarks file on Google drive without an error

### Screenshots
Account configuration:
![image](https://user-images.githubusercontent.com/18222586/127283149-a34dedcd-7726-4769-a6e1-833bdfced2b8.png)

### Desktop
 - OS: Arch Linux
 - Browser: Brave
 - Browser Version: 1.26.77
 - Floccus version: 4.6.4
 - Floccus sync method: Google drive

### Server
Not applicable

### Debug log
```
2021-07-28T07:26:23.644Z Starting sync process for account Google Drive: bookmarks.xbel
2021-07-28T07:26:23.664Z onSyncStart: begin
2021-07-28T07:26:25.000Z Syncing failed with Parse Error: <html xmlns="http://www.w3.org/1999/xhtml"><body><parsererror style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black"><h3>This page contains the following errors:</h3><div style="font-family:monospace;font-size:12px">error on line 1 at column 1: Document is empty
</div><h3>Below is a rendering of the page up to the first error.</h3></parsererror></body></html>
2021-07-28T07:26:25.003Z onSyncFail
```

- [X] Debug log provided

### Additional context
I previously set up Floccus (with Google drive) on Firefox on a different machine running Fedora without problems. I have tried removing the bookmarks.xbel file from the Fedora sync, but that did not change the error, and the file is not recreated when syncing from Brave.

**Comment by marcelklehr** [comment]
Hey @Victor4X

I'm sorry for your trouble. I'll try to help troubleshoot.

Does the file exist in your GDrive? Did you enable encryption in firefox? Are there multiple bookmarks.xbel files in your GDrive (perhaps in your Trash even)?

> the file is not recreated when syncing from Brave.

This is likely because your local folder is empty (which is the default if you leave the default settings).

**Comment by Victor4X** [comment]
Hi!
After reading your reply, I tried deleting the file from Trash, and I successfully synced after that!  

I might have to tweak the firefox settings if I want to do cross-syncing, as the bookmarks.xbel that it generated seems to have been what caused the trouble.

Is there a way to look at the bookmarks.xbel file in a readable format, so I can try to spot the problem or upload them here?

**Comment by marcelklehr** [comment]
Feel free to upload the file to my file drop: https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

**Comment by Victor4X** [comment]
Done :)

**Comment by marcelklehr** [comment]
Yep, you set an encryption passphrase in Firefox but not in Brave.

**Comment by Victor4X** [comment]
Damn, I didn't remember doing that at all. Thank you! Maybe parsing errors should hint at this potentially being the problem? I don't think I would've thought about it myself :p

**Comment by marcelklehr** [comment]
> Maybe parsing errors should hint at this potentially being the problem?

Yeah, just thought the same thing. I'll change the error message :)

Cheers!
