### ISSUE TITLE
Always report E029 mistake

### ISSUE THREAD

**Issue by 94486** [floccusaddon/floccus#923]
E029: Failsafe: The current sync run would delete 67.17557251908397% of your bookmarks. Refusing to execute. Disable this failsafe in the account settings if you want to proceed anyway.

**Comment by 94486** [comment]
Always report E029 mistake E002

**Comment by Victor4X** [comment]
The error is saying that the sync would delete more than 50% of your bookmarks. If you think this is correct, go to the settings in your active account, and click the "Disabled" radio button here: 
![image](https://user-images.githubusercontent.com/18222586/127285275-255df803-997a-4432-a8e5-81251cffe33e.png)

**Comment by 94486** [comment]
No，I only deleted 1 bookmark，The mistake still happen.If I set enable as the picture，a new mistake happen:report E002 mistake.

**Comment by Victor4X** [comment]
Can you send the complete error for both Enabled and Disabled from the picture?

**Comment by 94486** [comment]
Thanks for your reply！The only reason is browser's problem.It should be 360 browser's problem.

**Comment by marcelklehr** [comment]
@94486 I can confirm other people have reported problems with that browser before.
