### ISSUE TITLE
upgrade to v.4.7.0 mangles "sync tabs" config?

### ISSUE THREAD

**Issue by mnalis** [floccusaddon/floccus#930]
### Describe the bug
I had 3 syncs enabled to same nextcloud account but different remote directories: `Bookmarks Toolbar`, `Bookmarks menu`, `sync tabs`. After upgrading to `4.7.0`, `sync tabs` have instead become  instead `Local folder` with literal value
`/Bookmarks Menu/Floccus (mnalis@owncloud.example.net)/`  - where `mnalis@owncloud.example.net` is my account/host name, and **was** non-existent as bookmark folder previously (not it has appeared as empty folder).

### To Reproduce
Can't really say. I upgraded from `4.6.4` to `4.7.0` as described in https://github.com/floccusaddon/floccus/issues/929, and several hours later I noticed "sync tabs" account had different name and looked at its config.

### Expected behavior
Config of all 3 floccus accounts staying the same after upgrade..

### Desktop
 - OS: Debian Buster GNU/Linux
 - Browser: Firefox
 - Browser Version: 78.12.0esr (64-bit)
 - Floccus version: 4.7.0
 - Floccus sync method: Nextcloud bookmarks

### Server
 - OS: Debian Buster GNU/Linux
 - Nextcloud version:  20.0.11
 - Bookmarks app version: 4.4.0

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

### Additional context
It is theoretically possible that it was some freakish copy/paste bug while I was clicking on hanged windows in https://github.com/floccusaddon/floccus/issues/929, but I don't think is is very likely. I certainly wasn't trying to change config consciously .

**Comment by mnalis** [comment]
Confirmed, it was floccus and not me. What I've done since:

- disabled auto-sync of that account
- edited that account so it is again `sync tabs`, and saved config
- removed local bookmarks folder `/Bookmarks Menu/Floccus (mnalis@owncloud.example.net)/` which was autocreated
- verified that account is still `sync tabs`
- doing other things in firefox
- clicking sync on that `sync tabs` account
- doing other things in firefox, including crashing it as it run out of memory (new bug coming up next for that :smile:)
- came back to see that `sync tabs` account is now again called `Floccus (mnalis@owncloud.example.net)/` and syncs the folder with same name instead of `sync tabs`

**Comment by candrapersada** [comment]
when will tabs sync problem be fixed?

**Comment by piddyt-fambyt** [comment]
I can confirm this exact bug still exists. At least with the chrome extension 4.8.2 (kiwi browser).
