### ISSUE TITLE
sync tabs create "blank" intermediary folder

### ISSUE THREAD

**Issue by mnalis** [floccusaddon/floccus#931]
### To Reproduce
1. Create an Nextcloud bookarms account for `Sync tabs` with `Server folder:`   `/tabs_leia`
2. Click `SYNC NOW` button on it
3. Open Nextcloud Bookmarks app and go in `tabs_leia` folder
4. Instead of seeing your tabs, there is first a folder with no name, and under it are all tabs (also [without names](https://github.com/floccusaddon/floccus/issues/928)).

### Expected behavior
I would expect my tabs would be directly under `tabs_leia` folder on server

### Screenshots
![Screenshot_2021-08-06 Bookmarks - Nextcloud](https://user-images.githubusercontent.com/156656/128558921-8b1c66a3-400a-4285-b2f2-1de8ae8a6745.png)

### Desktop
 - OS: Debian Buster GNU/Linux
 - Browser: Firefox
 - Browser Version: 78.12.0esr (64-bit)
 - Floccus version: 4.7.0
 - Floccus sync method: Nextcloud bookmarks

### Server
 - OS: Debian Buster GNU/Linux
 - Nextcloud version:  20.0.11
 - Bookmarks app version: 4.4.0

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

### Additional context
This is additionally the problem if that tabs is then synced elsewhere - while the bookmarks would be visible under bookmark manager in `Menu` / `Bookmarks` / `Show All Bookmarks`, if you instead go to `Menu` / `Bookmarks` / `your synced folder name` firefox would claim it is empty (presumably because it can't handle folders with no name)

**Comment by mnalis** [comment]
perhaps might be related (or not): I have `Enable Container Tabs` enabled in firefox preferences, although I do not use the functionality (but is required for other extension I use, `Cookie Quick Manager`)

**Comment by mnalis** [comment]
Whatever the cause, it should either not be there at all (if it is an error), or should have ***some*** name if it such folder must be there (for example, if  there could be multiple folders - eg. one for each `container`?) - at least unique numeric `id` (or whatever) should be used if real name cannot be known.

**Comment by marcelklehr** [comment]
The reason for this folder is that floccus supports syncing tabs for multiple open windows. There will be a folder for each window. I'll see what I can do.
