### ISSUE TITLE
Syncing tabs tries to reload all of them at once, which leads to browser overload/crash

### ISSUE THREAD

**Issue by mnalis** [floccusaddon/floccus#933]
### Describe the bug
I have setup `sync tabs` in Floccus. I have several hundred tabs (about thousand?) open at once. It work nicely in Firefox as it does not try to load them on (re)start (likely due to default `browser.sessionstore.restore_on_demand=true`, `browser.sessionstore.restore_tabs_lazily=true` Firefox settings?), but only when they're actually clicked on, so it starts up instantaneously.

Floccus however when syncing tabs tries to **reload all of them at once**, which causes huge problems with memory/cpu usage (even if none or just a few of the tabs changed since last sync).

### To Reproduce
0. have a lots of tabs open
1. Setup `Sync Tabs` account (in `Normal sync` mode)
2. Click on `SYNC NOW`
3. Wait 3-4 minutes
4. Floccus starts reloading all tabs (or closing/reopening them one by one, it's hard to say)
5. Memory consumption of Firefox start increasing by 300-1000MB per minute.
6. after dozen minutes all memory is consumed, and it leads to firefox crash or unstability of the system

### Expected behavior
I would expect that `tabs sync` would only close/open tabs **that actually changed** (eg. were added or removed since last sync), instead of all of them. Also I would expect (if possible) that the newly created tabs are also lazily loaded (eg. they do not start loading automatically when they are added, but only later if user clicks on them - same as firefox works by default when restarting from sessionstore).

### Screenshots
![reloading](https://user-images.githubusercontent.com/156656/128584635-fd063f17-29cb-424c-a2cf-1f5296902d0f.png)

### Desktop
 - OS: Debian Buster GNU/Linux
 - Browser: Firefox
 - Browser Version: 78.12.0esr (64-bit)
 - Floccus version: 4.7.0
 - Floccus sync method: Nextcloud bookmarks

### Server
 - OS: Debian Buster GNU/Linux
 - Nextcloud version:  20.0.11
 - Bookmarks app version: 4.4.0

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

### Additional context

Related to timeline in `additional context` in https://github.com/floccusaddon/floccus/issues/929.

**Comment by candrapersada** [comment]
[#689](https://github.com/floccusaddon/floccus/issues/689#issuecomment-712039394)

**Comment by marcelklehr** [comment]
@candrapersada Normal two-way sync is not recommended for tabs, as tab IDs are not stable and can thus not be tracked.

**Comment by candrapersada** [comment]
then how to pull sync once when starting browser and push sync every 15 minutes or auto diable sync only tab when starting browser [#850](https://github.com/floccusaddon/floccus/issues/850#issuecomment-879820198)

**Comment by mnalis** [comment]
@candrapersada if `IDs` are not stable between browsers, I would guess it could cause all kinds of strange behaviours on `pull` (automatic or manual) - eg. closing all tabs and reopening them, instead of leaving them alone? I haven't looked at the code, though... 

@marcelklehr  Perhaps for `sync tabs`, if firefox provided IDs are unstable, one might  instead use hash of tab URL as ID? That should fix problems related to unstable IDs (don't know how problematic it is to implement, though)
