### ISSUE TITLE
Moving a Bookmark From a Folder to Another Folder Leads to “E002: Bookmark to update doesn't exist anymore”

### ISSUE THREAD

**Issue by bianyukun1213** [floccusaddon/floccus#935]
### Describe the bug
After moving a bookmark from a folder to another folder, click “SYNC NOW”, it gives me error code E002.

### To Reproduce
1. Drag a bookmark out of folder A,
2. Drop it into folder B,
3. Click “SYNC NOW”,
4. See error.

### Expected behavior
Sync functions normally.

### Screenshots
![image](https://user-images.githubusercontent.com/24708556/128713610-f31f7458-7b4b-4fdc-b5be-001fa7d27bcf.png)

### Desktop
(please complete the following information)
 - OS: Windows 10
 - Browser: Microsoft Edge based on Chromium
 - Browser Version: 92.0.902.67
 - Floccus version: 4.6.2
 - Floccus sync method: WebDAV

### Server
(please complete the following information)
 - OS: [e.g. centOS 7]
 - Nextcloud version: [if applicable]
 - Bookmarks app version: [if applicable]

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [x] Debug log provided

### Additional context
Bookmarks contain Chinese characters.

**Comment by bianyukun1213** [comment]
Version 4.7.0 in the Chrome Web Store works well. Maybe it‘s time to upload a new version to the Microsoft Edge add-on store.

**Comment by marcelklehr** [comment]
![image](https://user-images.githubusercontent.com/986878/128725318-433a2b61-f0ec-4e9f-b36c-1fb379874593.png)
