### ISSUE TITLE
Use token to sync with GitHub (repo, gists, etc...)

### ISSUE THREAD

**Issue by reiuyfan** [floccusaddon/floccus#939]
### Is your feature request related to a problem? Please describe.

This is not a program problem.

### Describe the solution you'd like

Allow programs to use token to access GitHub repos, gists, etc... for synchronization.

### Describe alternatives you've considered

GitHub repos/gists/etc.

### Additional context

As a relatively free and stable option that does not require self-hosting.

**Comment by ashutoshsaboo** [comment]
+1, this would be useful! @marcelklehr any plans to add this to Floccus? For ex: having bookmarks pushed to private github repo as well as gdrive for backups.

**Comment by marcelklehr** [comment]
@ashutoshsaboo Mmh, I understand how that would be nice. It's not a priority for me. If someone implements it and maintains the code, that would be ideal.
