### ISSUE TITLE
label:question How specify the path to your bookmarks file in your Google Drive storage?

### ISSUE THREAD

**Issue by gmuller2** [floccusaddon/floccus#940]
Trying out Floccus as a replacement for Google Bookmarks, which will be killed off soon.

The Floccus documentation states:
"The next option allows you to specify the path to your bookmarks file in your Drive storage. By default floccus will place a file called bookmarks.xbel in your topmost folder."

However, I have not worked out how to specify the path to place the bookmarks file in a folder instead of the topmost folder.  I tried "/floccus/bookmarks.xbel", but his resulted in a file named exactly that in the topmost folder instead of placing bookmarks.xbel the folder /floccus, which I had pre-created.

What am I missing here?

**Comment by marcelklehr** [comment]
This is a known issue. For now you should be able to let it create a file and later sort it into a folder of your choosing via the Drive UI.
