### ISSUE TITLE
add a warning before push and pull sync message and backup remote file

### ISSUE THREAD

**Issue by test-0-zero** [floccusaddon/floccus#941]
### Is your feature request related to a problem? Please describe.
I use google drive to store the bookmark sync file.

if I forgot the pull sync setting and I lose all the work done before the last sync

### Describe the solution you'd like

- a warning message before **Pull** and **Push** synchronization
- a remote file backup (to be set separately the mode e.g. timestamp, name, location, etc.)

### Describe alternatives you've considered
remote backup is a good idea to limit the damage caused by errors, which are propagated to all profiles and shared folders.

**Comment by marcelklehr** [comment]
Hello @test-0-zero 
Sorry for the delay. I've thought about your request. It is understandable, but I have to limit my time spent on perfecting backup solutions for floccus when that's not what floccus is for. Floccus syncs. Sync is not backup. If you want backup, you need to backup the files that floccus syncs somehow.
