### ISSUE TITLE
Allow local file storage

### ISSUE THREAD

**Issue by DerDanilo** [floccusaddon/floccus#943]
### Is your feature request related to a problem? Please describe.
A user has other means to sync the bookmarks file or has a third party cloud provider tool that does not support webdav or is more efficient than webdav itself.
A user may also not wish to sync bookmarks between multiple devices but between different browsers on the same device.

### Describe the solution you'd like
Allow to select local file storage to store the bookmark files. The path should be selectable. Lock files can/should also be used with local storage to avoid sync issues with multiple browsers on the same device of between devices.

### Describe alternatives you've considered
The floccus local webdav server. But this has flaws and also requires the permission to install any software. Also this only allows to sync one bookmark location and not multiple. (saving them in different subfolders is not an option).

### Additional context
Sync issues with webdav (tool says it synced where it really did not do it, all available troubleshooting guides did not help!) and the lack of availability of webdav made me open this request. Webdav is also not the most efficient sync protocol for files, even with the bookmark files being small.

Thanks!

**Comment by marcelklehr** [comment]
Hey @DerDanilo 
This is a good idea, but not possible with web extensions, at least not without installing additional software, which LoFloccus already covers. I thus can't fulfill this request.

> Sync issues with webdav (tool says it synced where it really did not do it, all available troubleshooting guides did not help!)

If you like, feel free to open a new issue with your webdav problems.

**Comment by DerDanilo** [comment]
@marcelklehr Thanks for the fast reply.
Mh, that is sad. Could you extend your webdav server to support multiple folders, serving them on multiple subfolders instead of the root path? Then this could solve at least some of the problems. I understand that it's a complex undertaking to support more cloud providers to sync directly to.
In most projects I work we are using Seafile or Nextcloud for privacy reasons. Maybe you could add support to talk directly to the Seafile storage via API since you added Google Drive recently which seems more complex I guess. (I don't know)

WebDAV works but has issues from time to time and also floccus seems to sync fine but does not (which is frustrating since webdav on the server backend works fine when testing). This messed up all bookmarks over and over again over the course of more than a year now. If I haven't had versioning on my server thousand of bookmarks would be useless. :-/

**Comment by marcelklehr** [comment]
> Could you extend your webdav server to support multiple folders, serving them on multiple subfolders instead of the root path?

I don't offer any webdav server. If you use a webdav server software to sync to your local file system that is possible, but I'm most certainly not the author.

> Maybe you could add support to talk directly to the Seafile storage via API

Seafile supports WebDAV, too, according to my google skills.

> WebDAV works but has issues from time to time and also floccus seems to sync fine but does not (which is frustrating since webdav on the server backend works fine when testing).

In general, if you have sync issues with WebDAV, then the problem is most likely not WebDAV, but the sync algorithm (which is the same for all syncing methods). The way out of these issues is to report them as detailed as possible, so I can reproduce and fix them.

> This messed up all bookmarks over and over again over the course of more than a year now. If I haven't had versioning on my server thousand of bookmarks would be useless. :-/

Alas, I'm sorry for the frustration. I didn't set out to destroy people's bookmarks.

**Comment by DerDanilo** [comment]
I thought that you also made the local webdav server module. My mistake! :)
Seafile WebDAV works (that what we are using) but the webdav sync seems to have issues. 

What I know for is that floccus says it did sync after about 1 seconds but it didn't do anything and there is also no change on the the webdav storage, though it seems to be able to access the file. Maybe this gives already a hint.
I will try to document it the next time it happens and open a new issue for that then.

**Comment by marcelklehr** [comment]
> What I know for is that floccus says it did sync after about 1 seconds but it didn't do anything and there is also no change on the the webdav storage

That could mean you selected an empty local folder for sync.

**Comment by DerDanilo** [comment]
> That could mean you selected an empty local folder for sync.

It is not empty and I also checked that. The sync also works on other machines while it does (randomly) not work from others. If it has, for some reason, connection issues I would expect it to throw an error, but not say "everything is good" and nothing really happens.
Maybe it's possible to improve the sync algo to do more checks.

**Comment by marcelklehr** [comment]
@DerDanilo In that case, can you please open a new issue for this problem and add steps on how to reproduce? Thank you :heart:

**Comment by DerDanilo** [comment]
> @DerDanilo In that case, can you please open a new issue for this problem and add steps on how to reproduce? Thank you heart

https://github.com/floccusaddon/floccus/issues/956

here you go.

**Comment by TCB13** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> A user has other means to sync the bookmarks file or has a third party cloud provider tool that does not support webdav or is more efficient than webdav itself. A user may also not wish to sync bookmarks between multiple devices but between different browsers on the same device.
> ### Describe the solution you'd like
> 
> Allow to select local file storage to store the bookmark files. The path should be selectable. Lock files can/should also be used with local storage to avoid sync issues with multiple browsers on the same device of between devices.

@DerDanilo have a look at this: https://github.com/TCB13/LoFloccus it implements your use case.

Flloccus can't do it directly due to browser API restrictions and other policies.
