### ISSUE TITLE
Please add the backup function to file feature

### ISSUE THREAD

**Issue by baizhi1989** [floccusaddon/floccus#945]
### Describe the solution you'd like
For example, bookmarks are generated in the same forder folder_ history20200202.xbel, bookmarks_ history20200102.xbel,
When you use other bookmark de duplication plug-ins to synchronize on the mobile browser, there are many fewer bookmarks synchronized on the computer. The online disk does not have the function of restoring history. Can you add a function of restoring history bookmarks, merging history bookmarks between specified dates and merging all history bookmarks

**Comment by mnalis** [comment]
Related: https://github.com/floccusaddon/floccus/issues/858
