### ISSUE TITLE
Logo missing error on install of 4.8.0

### ISSUE THREAD

**Issue by dsiminiuk** [floccusaddon/floccus#963]
### Describe the bug
Error on installing 4.8.0 via Developer mode.

### To Reproduce
Download .crx
Open Extensions page
Enable Developer mode
Drop .crx file on page
See error attached.

### Expected behavior
No error is expected.

### Screenshots
![image](https://user-images.githubusercontent.com/5713547/134551333-14244baf-b3b1-4053-8e63-e1a5730ff9bf.png)

### Desktop
 - OS: Win 10 Pro
 - Browser Vivaldi
 - Browser Version 4.2
 - Floccus version: 4.7.0 at present
 - Floccus sync method: nextcloud bookmarks (legacy)

### Server
 - OS: Ubuntu 20....
 - Nextcloud version: 21.0.4
 - Bookmarks app version: 10.0.0

**Comment by marcelklehr** [comment]
oh, thanks for the heads up! I've fixed the build and update the release assets
