### ISSUE TITLE
Update causes account to be wiped - unable to import json file

### ISSUE THREAD

**Issue by dsiminiuk** [floccusaddon/floccus#970]
### Describe the bug
Updating from 4.8.0 to 4.8.1 via developer console drag and drop of the CRX file wipes out the config.

### To Reproduce
Open browser
Export account from floccus 4.8.0 to .json
CTRL+SHIFT+E to open plugins page
Enable Developer mode
Drag the new .crx package into the window
The account is removed.
Importing the .json file does not restore the settings.
Importing the .json file multiple times lists additional instances of the same account but none work.

### Expected behavior
Existing account should remain
Importing previous config from .json should work if needed

### Screenshots
![image](https://user-images.githubusercontent.com/5713547/134946474-6bea1cf7-16af-4bed-b0d5-b201641277dc.png)

**Comment by dsiminiuk** [comment]
I had to remove the extension completely to get rid of the extra accounts, installed 4.8.0 and all is good again. Imported the .json as well without a hitch.

**Comment by marcelklehr** [comment]
Did you set a password for floccus?

**Comment by dsiminiuk** [comment]
@marcelklehr I don't understand?

The username and password for user auth on the server is in the .json.
After importing the .json the details of the account shouldn't the account appear in the plugin when you left click on the icon?
The only thing that was displayed was "New Account" (none of the three listed above).
Am I missing something?

**Comment by marcelklehr** [comment]
I cannot reproduce this with Chromium 93.0.4577.82

1. I installed v4.7.0 (also tried with v4.8.0)
2. I created an account
3. I exported the account
4. I updated to v4.8.1
5. Everything is still there

> but none work

What does this mean? They don't sync? What are the (redacted) contents of the exported json file?

**Comment by marcelklehr** [comment]
> I don't understand.

It's possible to secure your credentials by setting a password for the whole extension, but I'm guessing from your reaction that you didn't do that.

**Comment by dsiminiuk** [comment]
```
[
  {
    "localRoot": "1",
    "strategy": "default",
    "syncInterval": 15,
    "nestedSync": false,
    "failsafe": true,
    "type": "nextcloud-bookmarks",
    "url": "https://cloud.domain.com",
    "username": "myuser",
    "password": "myhashedpassword",
    "serverRoot": "/floccus",
    "includeCredentials": false,
    "allowRedirects": false,
    "enabled": true,
    "syncing": false,
    "error": null,
    "lastSync": 1632758823071
  }
]
```

**Comment by dsiminiuk** [comment]
> > I don't understand.
> 
> It's possible to secure your credentials by setting a password for the whole extension, but I'm guessing from your reaction that you didn't do that.

Oh, I see, the "Set a pass phrase for floccus" option. No, not using that.

**Comment by dsiminiuk** [comment]
In the image above you see 3 accounts that can be exported.
They are all the same account having imported the same .json three times, so it appears there is an account provisioned.
However, clicking on the plugin's icon exposes "New Account" like none are not there.

**Comment by marcelklehr** [comment]
Mh, let's see if there are errors in the log:

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* copy the logs
* open the floccus settings
* Right click in the popup and select "Inspect"
* In the inspector switch to the Console tab and copy the logs

**Comment by dsiminiuk** [comment]
@marcelklehr Hahaha, you may as well ask me to give you a suitcase full of cash LOL

I got to the DevTools window but I have no idea where the logs are in that mess.

Let me try an update on a different machine (5 Windows, 1 Linux Mint using this plugin) and see if I can reproduce it. If not then I'll assume I had a problem in this particular browser.

I'll do it today.

**Comment by dsiminiuk** [comment]
@marcelklehr 

I was able to reproduce this on the same version of Vivaldi (4.2.2406.48) on a different machine.

I will PM you a link to the video capture.

**Comment by dsiminiuk** [comment]
The screen capture was so small I just attached it to an email at the address on your profile.

**Comment by dsiminiuk** [comment]
I removed the 4.8.1 plugin (not allowed to downgrade) and installed 4.8.0 and imported the .json and all that works perfectly and as expected.

**Comment by marcelklehr** [comment]
Can't reproduce with Vivaldi 4.1.2369.21

The screen capture indicates a bug in the overview panel, rather than the accounts being gone. Let me try to guide you through the process to get to the logs.

![Peek 2021-09-27 20-01](https://user-images.githubusercontent.com/986878/134961191-64913024-ab49-4daa-bf43-d0c92c4c3636.gif)

**Comment by marcelklehr** [comment]
Please try v4.8.2

**Comment by dsiminiuk** [comment]
@marcelklehr Thank you for the tutorial, I'll keep that email for later.

Also, thank you for v4.8.2, Upgrading was perfect. No loss of config.
