### ISSUE TITLE
floccus does not work properly in Firefox

### ISSUE THREAD

**Issue by enximi** [floccusaddon/floccus#974]
### Describe the bug

Add account. click sync, progress bar does not stop, but bookmarks are synced. When i exit floccus screen, my account disappeared but account remains in account import/export screen. Restarting browser does not work.

And I noticed that floccus is not displayed in Chinese in Firefox like it is in Chrome.

### To Reproduce

1. Installing floccus in Firefox.
2. Add the account in floccus and set it up as shown above.
3. Click to sync.
4. The progress bar does not stop and won't prompt with a successful bookmark sync. But the bookmarks are synced. when I exit the floccus interface, my account disappears and restarting the browser does not work.

### Expected behavior

When I click sync, floccus finishes its work and the progress bar stops and prompts me with success, just like it does in Chrome. And my account will not disappear.

### Screenshots

![account setting](https://user-images.githubusercontent.com/70036307/135018653-ec59fbe1-61e4-4596-b4c0-80e3e3baa23a.jpg)

![account disappered](https://user-images.githubusercontent.com/70036307/135019663-6595ad2f-fc76-48e9-95d8-d77b151f09df.png)

### Desktop

 - OS: Windows 10 Pro 21H1
 - Browser: Firefox
 - Browser Version: 92.0.1 x64
 - Floccus version: 4.8.1
 - Floccus sync method: webdav

### Server

webdav (https://www.jianguoyun.com/d/home#/)

### Debug log

- [ ] Debug log provided

.

**Comment by marcelklehr** [comment]
Confirmed. Will fix ASAP.

**Comment by marcelklehr** [comment]
Please try v4.8.2

**Comment by enximi** [comment]
Floccus v4.8.2 work fine. Thank you!
