### ISSUE TITLE
please make floccus work on the new firefox for android

### ISSUE THREAD

**Issue by gothmog123** [floccusaddon/floccus#975]
### Is your feature request related to a problem? Please describe.
no, currently most addons are disabled on the new firefox for android rewrite. however, addons can be force enabled and a lot of them do work but not floccus. after clicking on create new account with nextcloud, nothing happens.

### Describe the solution you'd like
please make it work

### Describe alternatives you've considered
using the nextcloud bookmarks app

**Comment by marcelklehr** [comment]
Hello @gothmog123 
Thank you for your feedback. This is not trivial as firefox for android does not support some of the APIs that floccus needs (as well as other extensions dealing with bookmarks), which make it work on dektop browsers. If the firefox team one day decides to implement these missing APIs, floccus will work automatically.

Also see #3, #861 and #962 for context.
