### ISSUE TITLE
Why does floccus's CPU usage jump to the top of Chrome's Task Manager list every 10 seconds? 

### ISSUE THREAD

**Issue by zylstra** [floccusaddon/floccus#980]
### Describe the bug
floccus's CPU usage jump to the top of Chrome's Task Manager list every 10 seconds.

### To Reproduce
1. Install floccus addon to Chrome.
2. View Chrome's Task Manager.
3. See CPU usage jump to top of the list every ten seconds.

### Expected behavior
I did not expect floccus to use CPU every ten seconds.

### Screenshots
[image upload not working.]

### Desktop
 - OS: Windows 10
 - Browser chrome
 - Browser Version 94.0.4606.61 (Official Build) (64-bit)
 - Floccus version: 4.8.2
 - Floccus sync method: Google Drive

### Server
N/A
 - OS: [e.g. centOS 7]
 - Nextcloud version: [if applicable]
 - Bookmarks app version: [if applicable]

### Debug log
TBD
[It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.  Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw ]

### Additional context
None.

**Comment by marcelklehr** [comment]
Hi @zylstra 

Sorry for the delay. The reason for the regular activity is a status poll that updates the floccus icon in your toolbar among other things. From what it does, it shouldn't be too heavy on the CPU, but it's still is probably a good idea to refactor this to only run when something has actually changed. Thanks for reporting this! :hearts:
