### ISSUE TITLE
v4.8.2: "E018: Couldn't authenticate with the server."

### ISSUE THREAD

**Issue by pjotrek-b** [floccusaddon/floccus#987]
### Describe the bug
Since updating from v4.7.0 to v4.8.2 I always get the error message when using a previously existing (working) profile:
> "E018: Couldn't authenticate with the server."

I'm connecting to my own Nextcloud server. Used to work flawlessly before. I've also checked the login credentials and also tried removing the password, then re-authenticating with Nextcloud.

Logfile says (replaced my email with "me@myserver.test.com"):

> 2021-10-17T19:41:30.130Z Starting sync process for account me@myserver.test.com
> 2021-10-17T19:41:31.060Z Syncing failed with E018: Couldn't authenticate with the server.

It's weird though that the timestamps are not correct, but off by 2 hours. I checked, and indeed: the server was in the wrong timezone (2h offset). I've fixed this now, so the time on the server is correct now. However, Floccus still displays the timestamps as 2h earlier.

### To Reproduce
1. Select *existing* Floccus account.
2. Click on 'Sync now'
3. Error message appears

### Expected behavior
Since the account was working properly with v4.7.0, I'd expect it to continue working.

### Screenshots
None

### Desktop
 - OS: Xubuntu 20.04.3 (64bit)
 - Browser Firefox
 - Browser Version 93.0
 - Floccus version: 4.8.2
 - Floccus sync method: nextcloud folders

### Server
 - OS: Ubuntu Server 18.04.5
 - Nextcloud version: 22.1.0
 - Bookmarks app version: 10.0.0

### Debug log
(Same as mentioned above):
> 2021-10-17T19:41:30.130Z Starting sync process for account me@myserver.test.com
> 2021-10-17T19:41:31.060Z Syncing failed with E018: Couldn't authenticate with the server.

- [x] Debug log provided

### Additional context
I've now tried adding a new account (in parallel) with the same server/credentials: Login and sync works!
It seems that only the account that was previously existing before the update (from v4.7.0 to v4.8.2). So my old account wasn't wiped by the update anymore (see #971), but maybe corrupted in another way?

**Comment by mnalis** [comment]
(don't know about "invalid password" bug, but to a comment about wrong time)

> 2021-10-17T19:41:30.130Z Starting sync process for account me@myserver.test.com

Note that [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) format used in this log contains `Z` at the end, which indicates times is logged in `UTC` (`GMT`), **_not_** in your local timezone. So if your local timezone is currently `UTC-02` or `UTC+02`, it is quite normal that it will be offset by two hours from `+00:00` (also known as its shorthand `Z`).

Same thing on server: `/etc/localtime`, `$TZ` environment variable, as well as local program configuration (like nextcloud or its plugin)  can override the timezone in which the server/application thinks it is located in. 

And depending on application, it can decide to log times:
- in local timezone (with or sometimes [horror!] even without specifying timezone!) - which is easier for the user, but contains nasty surprises (think DST time changes, time seeming to stop or even going backwards etc), or
- in `UTC` (which avoids those problems, but is harder for users to understand and convert)

**Comment by pjotrek-b** [comment]
Thanks about the info about time/timezones.
I thought I'd mention it, because I know that in some cases out-of-sync clocks may hinder authentication.

So it's something else causing the old account login to fail then.

**Comment by marcelklehr** [comment]
Sorry about the delay!

Does it help to create a new sync account in floccus?
Can you try the following:

1. export your acocunt
2. Open the exported JSON file
3. Run the following: `$ curl -u "username:passwordfromexportfile" https://your-nextcloud.com/index.php/apps/bookmarks/public/rest/v2/bookmark`

**Comment by Lishux** [comment]
got same error when i rename some folder, move some bookmarks into ithem. but after deleting all bookmarks on nextcloud and push local, everything just works.
