### ISSUE TITLE
Chrome Addin - Default Bob@Example.com account won't die.

### ISSUE THREAD

**Issue by thechickenmoo** [floccusaddon/floccus#988]
### Describe the bug
 I downloaded the floccus firefox addon to sync my bookmarks. I edited the main default account (The one using bob@example.com) and saved my changes. Everything appeared correct but nothing synced. I was looking at other things and just figured it was a delay. I later checked again and although I swear I had seen my username/password change and had saved changes, it had changed back to bob@example.com. 
I tried again to change the settings. Made sure everything took. Then closed and reopened the browser. It was back to bob@example.com with no syncing. 
I finally decided to just create a new account. I did so. Then after it synced correctly, I removed the Bob@example.com account. 
Next time I started my browser... the bob@example.com account was back and failing to sync (of course). 
I removed it again, saved changes. The icon went back it its normal "sync done" status icon. 
Next time I started the browser, again, Bob@Example.com was back and trying to continually sync. 

### To Reproduce
1. Click on Floccus Addon Icon
2. Click on "Down Arrow" under the bob@example.com account. 
3. Click Options.
4. Scroll Down to and click on "Remove Account". Then OK to Remove.
5. Click on the Addon Icon again to verify the account is now gone. 
6. Close the Browser.
7. Reopen the browser. 
8. Click the addon Icon again, and the account is back and trying (and eventually failing) to sync.

### Expected behavior
I expected the account to be removed and stay removed. 

### Desktop
 - OS: Windows 10, 20H2
 - Browser: Chrome
 - Browser Version: Version 95.0.4638.69 (Official Build) (64-bit)
 - Floccus version: Floccus 4.8.3
 - Floccus sync method: Nextcloud Bookmarks

### Server
 - OS: Docker Install on Ubuntu 18.04.6 LTS
 - Nextcloud version: 22.2.0
 - Bookmarks app version: 10.0.2

### Debug log
I couldn't find the debug log option in the browser floccus options. I'm probably just being blind. Let me know?

**Comment by marcelklehr** [comment]
This is such a weird bug. It has been reported similarly before, but I can't reproduce it :/
The debug logs are unfortunately only displayed if the addon detects an error, but in this case it thinks everything is fine.

**Comment by marcelklehr** [comment]
I can't reproduce this with Floccus 4.8.3, chromium 95.0.4638.69 (Official Build) (64-bit)

**Comment by marcelklehr** [comment]
> main default account

Did this account exist already after installing? There shouldn't exist any accounts immediately after installing.

**Comment by thechickenmoo** [comment]
I want to say that it didn't now that you ask. I am wondering now if I filled out the "New Account" info and somehow neglected to fill out that portion before saving and then on subsequent attempts tried to change it? 

Even more oddly, for whatever reason, the 15th time was the charm and now the phantom account hasn't returned? I guess I'll close this for now.
