### ISSUE TITLE
Sync Hangs, Slows Browser, Seemingly Uncancellable

### ISSUE THREAD

**Issue by DanielSherlock** [floccusaddon/floccus#995]
### Describe the bug
Sync hangs, seemingly having trouble with the lock file. In doing so, makes browser unusably slow. Perhaps related to #972 and #973.

### To Reproduce
Steps to reproduce the behaviour:
1. Start browser.
2. Extension icon will shortly show a sync has started. Browser becomes sluggish and unresponsive.
3. Clicking extension icon (eventually) brings up usual display of sync profiles. One is shown syncing. It never finishes.
4. Trying to click "Cancel Sync" does nothing.
5. To make browser usable, kill the extension's process (shown as using the CPU heavily).

### Expected behaviour
The sync should start and finish within a few minutes. If there is some problem with the lock file, it should give up and report an error, rather than continuously retrying and slowing the browser.

### Desktop
 - OS: Windows 10 (21H1)
 - Browser Vivaldi
 - Browser Version 4.3.2439.65
 - Floccus version: 4.8.3
 - Floccus sync method: webdav

### Server
 - LoFloccus running on same device
 - OS: As above
 - Nextcloud version: n/a
 - Bookmarks app version: n/a

### Debug log
Obtained not via "debug log" button, but via "dist/html/background.html" under "Inspect Views".

- [x] Debug log provided

```
background-script.js:3 initializing account [SOME_NUMBER].[SOME_OTHER_NUMBER]
background-script.js:1 2021-11-09T17:30:16.490Z Starting sync process for account [USERNAME]@127.0.0.1
background-script.js:1 2021-11-09T17:30:29.851Z onSyncStart: begin
background-script.js:1 2021-11-09T17:30:29.855Z http://127.0.0.1:[PORT]/bookmarks.xbel.lock
background-script.js:1 2021-11-09T17:30:41.732Z http://127.0.0.1:[PORT]/bookmarks.xbel.lock
background-script.js:1 2021-11-09T17:31:03.042Z http://127.0.0.1:[PORT]/bookmarks.xbel.lock
...
```

### Additional context
- The problem started some point last month; I don't recall when.
- I am using Vivaldi and no other browsers.
- The sync profile is set to sync every hour (not that that matters, as it hangs soon after the browser is opened, even after a few days, and the only way to get the browser back is to kill the process).
- There is no lock file visible in the folder on disk to which LoFloccus syncs.
- Trying to view the lock file via the browser's URL bar gives `Not Found` (in contrast, viewing the xbel file itself works fine).
- The lock file appears as a link in the debug log. Clicking here shows it as having the content `<html><body>I am a lock file</body></html>`.

**Comment by marcelklehr** [comment]
> There is no lock file visible in the folder on disk to which LoFloccus syncs.
> The lock file appears as a link in the debug log. Clicking here shows it as having the content <html><body>I am a lock file</body></html>.

This proves that the lock file exists after all. As such, this may be an issue with LoFloccus.

> Clicking extension icon (eventually) brings up usual display of sync profiles. One is shown syncing. It never finishes.

How long did you wait? Floccus should ignore an already existing lockfile after waiting for half an hour.

**Comment by marcelklehr** [comment]
It turns out floccus does end after half an hour but then encounters an error and restarts a minute later, so it seems like it's hanging, but the actual problem is the error.
