### ISSUE TITLE
Android WebDAV unable to connect E17 - Self Signed Cetificate

### ISSUE THREAD

**Issue by elmodor** [floccusaddon/floccus#997]
### Describe the bug
I'm unable to connect to my webdav on the android app. 
I believe the issue is that I use a self signed certificate on my webdav server for https. The certificate is installed as "user" certificate in my android system. However, the default setting for Android apps is to allow only "system" certificates. For "user" certificates to be accepted, this has to be stated in the AndroidManifest.xml. I recently found this out because I run into this issue in a different app.

### To Reproduce
1. Spin up a caddy server as reverse proxy and redirect to the webdav server
2. Spin up a webdav server
3. Install the root.crt form caddy in the android phone
4. Try to connect to the webdav server in the android app

### Expected behavior
Able to connect to the webdav server with a self signed certificate.

### Screenshots
-

### Desktop
-

### Android
 - Floccus 4.8.4

### Server
 - OS: Debian 10
 - Webdav Server

### Debug log
- [ ] Debug log provided

### Additional context
The "behavior" is described here:
https://developer.android.com/training/articles/security-config#base-config
https://developer.android.com/training/articles/security-config#certificates

A fix would be to add this to the AndroidManifest.xml:
```
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
           <certificates src="system" />
           <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
```
This is a MR that fixed this issue in a different app where I found the same problem:
https://github.com/advplyr/audiobookshelf-app/commit/44f535020d591ee56038c6d7ab9792ff29ce7445

This allows that certificates added by the user to the android system are allowed to be used to verify the https certificates.

**Comment by nagyrobi** [comment]
I have the same problem. Please add support for self signed certs.

**Comment by marcelklehr** [comment]
Can you confirm, whether this works in the latest version?

**Comment by elmodor** [comment]
I can confirm that it works now, thank you very much :heart:
Had to uninstall and install the app again for it to work.
