### ISSUE TITLE
Use different Oauth for Google login

### ISSUE THREAD

**Issue by Cyberavater** [floccusaddon/floccus#998]
When I log in using google login for other services, the page opens up on a new tab I can use many features (i.e Choose Gmail account or Gmail autocomplete, auto password fill-up (by password manager extension), and even no 2 fact verification if the account is already logged in on the same browser.)

I'm not sure how it's currently implemented in floccus but its functionality lacks in many ways that much I can tell.

**Comment by Cyberavater** [comment]
This also actually causes login issues (#919 and #921) on many browsers. If possible, please have a look at it.

**Comment by Cyberavater** [comment]
Hi, thanks for responding. Please check [Tampermonkey's](https://github.com/Tampermonkey/tampermonkey) way of Google Oauth implementation, it opens up the Oauth in a new tab that retains all functionality (mentioned above) and I've seen no browser crashed so far with that.

**Comment by marcelklehr** [comment]
> I'm not sure if Tampermonkey had this in the older version.

Yeah, I don't think it did, code search doesn't yield anything :/

**Comment by Cyberavater** [comment]
Okay, check this one, ([Violentmonkey](https://github.com/violentmonkey/violentmonkey)) it's full FOSS and its Google login also works ~~almost~~ nicely.

**Comment by marcelklehr** [comment]
Alright, their approach is a bit hacky but works

**Comment by marcelklehr** [comment]
aah. fml

**Comment by Cyberavater** [comment]
> Alright, their approach is a bit hacky but works

Nice, since you're interested in implementing it, I'll add this issue here for you to read, https://github.com/violentmonkey/violentmonkey/issues/1396

[You'll know I added almost, but you can also ignore this since it only happens on kiwi]

**Comment by marcelklehr** [comment]
*sigh*

That's the problem with hacks. They are often not officially supported :/

**Comment by Cyberavater** [comment]
But the Tempermoney implementation is just perfect, I haven't encountered any issues with that (but alas it's closed source).

**Comment by marcelklehr** [comment]
Sorry.
